### ISSUE TITLE
Keep the meeting banter going.

### ISSUE THREAD

**Issue by ledm** [ESMValGroup/ESMValCore#10]
Just wanted to say that it was great to meet everyone and finally be able to put faces to the names. We got so much accomplished this week; we should all feel proud of ourselves. 

One thing that really came across this week was how incredibly productive we are when we're all going in the same direction. I personally don't think that I get anywhere near as much done as an individual compared to working collectively. 

In addition to the long list of PR's completed and issues resolved, this week really helped me get a feel who was was working on what. I think this is crucial for teams to know what everyone is doing, as it lets everyone know who the best person to talk to for specific questions. The problem is that there are so many rapid developments happening in ESMValTool, we all move on to different subjects pretty quickly. It's hard to keep the mental map of who is doing what job up to date.

I'd like to propose that we start a monthly video conference for the core team with occasional contributions from diagnostics developers, senior scientists (@veyring), or external software developers (@bjlittle). I think that this would help address some of these issues, but keep our productivity high as well. 

This would also help with:
- Flagging important issues away from the firehose of github notification emails!
- Allow project managers to be a bit more specific in assigning tasks.
- Avoiding duplication of effort.
- Potentially reduce our carbon footprint through less air travel.
- Building the communication network and sense of community.
- Keep the meeting banter going.

I know that a lot of us are over subscribed to meetings, but a monthly 1 hour call wouldn't be so bad, I think. We've recently switched to [zoom](https://zoom.us/) at PML and I think it's not so bad. 

Lee

P.S. One minor point is that the github profile pictures really help too! If you haven't set one up yet, I'd strongly recommend doing so!

**Comment by ledm** [comment]
Does anyone still think that regular ESMValTool core developer teleconferences would be a good idea? 

I sure do! I've got myself painted into a corner and could use a 15 minute conversation to discuss how  `fx_files` work in the preprocessor.

**Comment by valeriupredoi** [comment]
am totally for regular calls! Having said that, got zero time today and tomorrow, but I can have a chat with you @ledm again on the phone if you need to talk about fx's. The fx files situation is murky to say the least because we need to accept #21 asap then convert it to #22 (but 22 needs a slight change to allow for more than a basic preprocessor for fx variables).

**Comment by bouweandela** [comment]
I would like to revive this old proposal and try to find a date and time for a first meeting that works for at least several of us. Participation is completely optional, it should be just intended for those who feel that more regular meetings would improve the way we collaborate. Topic of the meeting will the work that participants plan to do in the next 1 or 2 months.

How about a 1 hour meeting on Thursday April 2 at 14:00 CET? @ESMValGroup/esmvaltool-coreteam

**Comment by jvegasbsc** [comment]
Perfect for me

**Comment by valeriupredoi** [comment]
same here! if I am not in a hospital ward :grin:

**Comment by bouweandela** [comment]
Let's hope not!

**Comment by bouweandela** [comment]
Here is the link to the [zoom meeting](https://zoom.us/j/783495064) for joining. @ESMValGroup/esmvaltool-developmentteam

**Comment by valeriupredoi** [comment]
good stuff! when are we meeting? I was about to propse a onece a month telecon, how about we start with one next week? :beer:

**Comment by bouweandela** [comment]
Let's have it tomorrow at 2PM CET (1PM UK time), as proposed two weeks ago https://github.com/ESMValGroup/ESMValCore/issues/10#issuecomment-599593988.

**Comment by bouweandela** [comment]
I really enjoyed our first meeting and hope to see you all at the next (#1609) one!

**Comment by bascrezee** [comment]
Couldn't join today, but I will hopefully manage to join the next meeting!
