### ISSUE TITLE
Pre-commit hooks are a royal pain in the behind

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1001]
I just had a PR merged with no effect because the pre-commit hooks reverted my wanted change, and this is just one episode of major pains in the bottom, plus there's times when I find very old commits that have been reverted but they still persist as pre-commit hooks and they need to be removed manually - can we please get rid of these if we can't make them work optimally?

**Comment by stefsmeets** [comment]
Hi @valeriupredoi , can you give an example of what issues you are running into?

**Comment by valeriupredoi** [comment]
nevermind, I must have been doing something silly, am gonna assume that anyway :grin:
