### ISSUE TITLE
Unnecessary tags in repository?

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#1008]
We have many tags in the repository starting with `6.x.x`, see [here](https://github.com/ESMValGroup/ESMValCore/tags).

Are these there on purpose or have they been accidentally added and can be removed?

@ESMValGroup/esmvaltool-coreteam

**Comment by axel-lauer** [comment]
It seems most of them were created by @stefsmeets

**Comment by valeriupredoi** [comment]
yeah good eagle-eye spot @schlunma :eagle: -> @stefsmeets care to tell us why you are releasing version 6 already? :rofl: - think this is the automatic tag release from the esmvaltool-test data package

**Comment by stefsmeets** [comment]
Development is not going fast enough for me 😋

Actually, I have no idea how this happened 😅 I haven't set any tags on ESMValTool. Must be some automatic system at play. All the commits have messages like: `CMIP6_CVs-6.2.53.0/DREQ-01.00.32/CMOR-3.6.0`

**Comment by schlunma** [comment]
All right :laughing: So it is safe to remove them?

**Comment by valeriupredoi** [comment]
we need to understand what created them coz they sure look dodgy AF - it looks like the CMOR tables ctag hashes got picked up by the our tagging, @jvegasbsc got any idea - possibly after updating the CMOR tables?

**Comment by valeriupredoi** [comment]
right - those tags appear in `esmvalcore/cmor/tables/cmip6/scripts/cleanupTags.py` - and that executes a bunch of git processes that assign new tags and clean older ones - that is what created them - Javi, care to tell us what's that all about? :beer:

**Comment by stefsmeets** [comment]
Does this mean I'm not guilty? 😁

**Comment by stefsmeets** [comment]
The tags are also present on my system, out of pre-caution I removed them using `git tag -d 6.2.24 6.3.27 6.3.27-fixed 6.4.28 6.5.29 6.6.30 6.7.31 6.8.31 6.9.32`, because I think they would be re-added the next time I push a commit.

**Comment by valeriupredoi** [comment]
you should be clean @stefsmeets - unless further evidence points to you :laughing: I don't know whay that script gets executed since it doesn't look to be our script - it looks like Javi just plopped it in [there](https://github.com/ESMValGroup/ESMValCore/blob/master/esmvalcore/cmor/tables/cmip6/scripts/cleanupTags.py) from the CMOR folks

**Comment by bouweandela** [comment]
The CMOR tables are just copies of whatever [PCMDI](https://github.com/PCMDI) has, that's how the script ended up there. It looks like @stefsmeets accidentally ran the script and pushed his tags to the repo. I'll delete the offending tags and make a pull request to remove the scripts to prevent this from happening again.

**Comment by bouweandela** [comment]
If anyone wants to get rid of these tags in their local copy of the ESMValCore repository: you can list tags in your local repository with:
```bash
git tag -l
```
and to delete a tag locally, run e.g.
```bash
git tag -d 6.9.32
```

Be careful to only remove tags starting with a `6`.

**Comment by stefsmeets** [comment]
> The CMOR tables are just copies of whatever [PCMDI](https://github.com/PCMDI) has, that's how the script ended up there. It looks like @stefsmeets accidentally ran the script and pushed his tags to the repo. I'll delete the offending tags and make a pull request to remove the scripts to prevent this from happening again.

@bouweandela , it is not helpful if you start pointing fingers. I have never seen this script and I have never run this script (also not accidentally).

**Comment by bouweandela** [comment]
Sorry @stefsmeets, my apologies. I did not mean to blame you or anyone else for it, I just repeated what was said in https://github.com/ESMValGroup/ESMValCore/issues/1008#issuecomment-781314690.

Running
```
git show 5c2e1cd3c2bcac26dc953fd80d6a39160ab3e8c2
```
does give me
```
tag 6.4.28
Tagger: Stef Smeets <s.smeets@esciencecenter.nl>
Date:   Fri Feb 5 09:19:19 2021 +0100

CMIP6_CVs-6.2.15.0/DREQ-01.00.28/CMOR-3.3.3
```
but I'm no expert on git, so I have no idea if you actually created the tag and even if you did it's not a problem at all.

**Comment by valeriupredoi** [comment]
we need to remove that script that creates the tags via running the git calls asap, since I am fairly sure Stef didn't run it manually so I *think* there is an automated process that runs it. No blames, good that we figured out what causes the crazy tags to be created :+1:

**Comment by stefsmeets** [comment]
Furthermore, to *push* tags, you actually have to run `git push --tags`. Afaik, you cannot accidentally push tags.

**Comment by valeriupredoi** [comment]
> Furthermore, to _push_ tags, you actually have to run `git push --tags`. Afaik, you cannot accidentally push tags.

that's what `subprocess.call(['git','push','origin',''.join([':refs/tags/',tag])])` does in that piratical script :pirate_flag:

**Comment by valeriupredoi** [comment]
OK thanks @bouweandela for being our French maid and cleaning up for us :grin: This is closed now but peeps should be careful not to commit those scripts anymore since those may come back with an unaware commit+push
