### ISSUE TITLE
Use standard names for fix modules and classes

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#101]
At the moment, many of the Python modules and classes in `esmvalcore.cmor._fixes` have names that do not conform to PEP8. Would it be possible to change that? I would be happy to do it if everyone agrees that it's a good idea.

The advantage of using the PEP8 standard in this part of the code too is that:
1) we no longer get unnessary linter errors, which are confusing to new contributors
2) we do not run the risk of creating files with names that only differ in upper/lower case (we have a unit test to check this too, so we're not allowing it anyway), as this causes problems for people that use filesystems that are not case sensitive, see https://github.com/ESMValGroup/ESMValTool/issues/12

**Comment by bouweandela** [comment]
@jvegasbsc Would this be OK with you? Does anyone else object?

**Comment by jvegasbsc** [comment]
I have no trouble with that if we make it clear how we construct the names. We are already changing `-` for `_` in model names

- For models and we can just use lower() after the change I mentioned before. It will be quite straightforward
  
- For variables I see it more difficult, but as short names are always lowercase, I think we can let the fixes be capitalized in any way: (Tos, TOS, AllVars, Allvars) and just complicate a bit the code to get the class so it is case insensitive
