### ISSUE TITLE
Git operations change to token-based

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1012]
[This](https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/) urges git users to switch their auth to token-based and every user will have to enable token-based authentication by **August 13, 2021**. This is here to remind @ESMValGroup/esmvaltool-developmentteam that sooner or later they'll have to do this (including myself, and I really dislike tokens :grin: ) and maybe we should add a warning in our documentation as well? :beer:

**Comment by bouweandela** [comment]
Good idea to update the documentation, it looks like ssh access will continue to work as usual and that's already well documented, but the https method may need to be removed or is it still possible to use https for cloning with some other authentication mechanism?

Our documentation on the topic lives here:
https://docs.esmvaltool.org/en/latest/quickstart/installation.html#install-from-source

**Comment by SarahAlidoost** [comment]
> Good idea to update the documentation, it looks like ssh access will continue to work as usual and that's already well documented, but the https method may need to be removed or is it still possible to use https for cloning with some other authentication mechanism?
> 
> Our documentation on the topic lives here:
> https://docs.esmvaltool.org/en/latest/quickstart/installation.html#install-from-source

What I understood from [this guide](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) is that `https clone` works, but instead of the GitHub password, users should use a personal token for authentication. This is the example on that page:

```
$ git clone https://github.com/username/repo.git
Username: your_username
Password: your_token
```

**Comment by valeriupredoi** [comment]
cheers @SarahAlidoost - a nice overview, that's what I took home we have to do too

**Comment by valeriupredoi** [comment]
here's a handy set of instructions, do we want these in the docs here or we just close and forget about it? https://github.com/ESMValGroup/ESMValTool/issues/2265

**Comment by valeriupredoi** [comment]
this is a bit historical now...
