### ISSUE TITLE
extract_season is broken

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1013]
PR https://github.com/ESMValGroup/ESMValCore/pull/247 broke the basic functionality of `extract_season()` - it may have introduced the functionality for custom seasons but it broke the basic functionality for extracting a simple meteorological season like `"MAM"`; the problem is reported in this [comment](https://github.com/ESMValGroup/ESMValTool/issues/2028#issuecomment-783246327) and my investigations show that by running a simple functional extraction with:
```python
    seasons = ['DJF', 'MAM', 'JJA', 'SON']
    season_cubes = [extract_season(data_cube, season) for season in seasons]
```
the code returns only the `DJF` cube and `None` for the others because the `clim_season` coord looks malformed:
```
AuxCoord(array(['DJF', 'DJF', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON',
       'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON',
       'DJF', 'DJF', 'DJF', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON',
       'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON',
       'MAMJJASON', 'DJF', 'DJF', 'DJF', 'MAMJJASON', 'MAMJJASON',
       'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON',
       'MAMJJASON', 'MAMJJASON', 'DJF', 'DJF', 'DJF', 'MAMJJASON',
       'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON',
       'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'DJF', 'DJF', 'DJF',
       'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON',
       'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'DJF'],
      dtype='<U64'), standard_name=None, units=Unit('no_unit'), long_name='clim_season')
```

I unfortunately don't know what you want to achieve with the custom seasons functional integration so I can't fix the code myself, but please fix it **asap** and add a test for the basic seasonal extraction too please.
Cheers :beer:

**Comment by schlunma** [comment]
Can you try adding a simple `cube = cube.copy()` at the beginning of the `extract_season` function? `iris.coord_categorisation.add_season` changes the source cube in-place, which would explain why the problem is picked up by your list comprehension but not by the unit tests.

**Comment by valeriupredoi** [comment]
nay, the problem is the malformed aux coordinate because of the way the function got rewritten:
```python
    sstart = allmonths.index(season)
    res_season = allmonths[sstart + len(season):sstart + 12]
    seasons = [season, res_season]
```
generates seasons that look like `['DJF', 'MAMJJASON']` which have no meaning if passed as `season` argument to the iris function

**Comment by schlunma** [comment]
I'm pretty sure [`iris.coord_categorisation.add_season`](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris/coord_categorisation.html#iris.coord_categorisation.add_season) can handle seasons like that (I tested that when I tested that PR). Anyway, the second season here `res_season` gets thrown away at the end of the function:

```py
return cube.extract(iris.Constraint(clim_season=season))
```

However, the `clim_season` coordinate is permanently saved to the the input cube, which lets the second call of `extract_season` with `MMA` fail (the first with `DJF` works fine). For me, running the recipe with `cube = cube.copy()` at the beginning of `extract_seasons` solves that issue. Also, try your function with `seasons = ['MAM', 'JJA', 'SON']`, then you'll see that suddenly `MAM` works just fine and `JJA` fails.

**Comment by valeriupredoi** [comment]
yes exactly! it's lazy coding - the season gets extracted correctly first time, but the other time points get garbage seasons and next time you want to extract a decent season, without prior copying the cube and using the pristine cope, you end up with garbage in the already added AuxCoord(clim_season) - I don't like this and I don't want to make useless copies and hog memory :+1:

**Comment by valeriupredoi** [comment]
and the tests work simply because the operation is done once for every season tested, we should avoid this type of Kinder Suprprise type of output - you only find out about garbage introduced in the output only when you try to reuse it

**Comment by valeriupredoi** [comment]
my solution (more elegant than simply copying the cube) is to recreate the clim_season aux coord everytime one needs to run the preprocessor step - that ensures clean output and customizable output also, depending on what sort of seasons one wants to extract - definitely remove the garbage added as "seasons" other the ones that is specified as functional argument

**Comment by valeriupredoi** [comment]
we should make a rule for ourselves everyime we add an iris Coord or AuxCoord it should be correct in its entirety and not cut corners and create only partially correct coordinates that suit our local needs - this type of philosophy prevents data reusability and leads to unnecessary operations and/or extra memory usage. @mwjury and @jvegasbsc please fix this according to this rule and make the clim_season a fully correct coordinate. And I will be happy and won't pester you with more posts on this issue :grin:
