### ISSUE TITLE
Multimodel statistics regression tests using sample data fail

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#1028]
Since #1021 was merged, the multimodel statistics tests using sample data are failing on CircleCI:
https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore/4362/workflows/599dc369-ac7a-4822-b159-d3e1d9b5146a/jobs/20368

This happens because the intermediate results are stored in the pytest cache. The test computation was changed, but the cache key was not updated in the same pull request, resulting in re-using the wrong cache. The problem can be solved by running `pytest --cache-clear`, but it's a bit unfriendly to other developers to expect everyone to do that and there's no way to do that on CircleCI.

**Comment by stefsmeets** [comment]
Is this the notorious cache invalidation problem? 😂

**Comment by bouweandela** [comment]
Guess so, found some nice quotes about it: https://martinfowler.com/bliki/TwoHardThings.html
