### ISSUE TITLE
Increase flexibility of CMOR checks for datasets with generic alevel coordinates

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#1029]
Background
---

Some 4D atmospheric variables are defined with a `alevel` instead of a `plev` Z dimension. Example: [`cl`](https://github.com/ESMValGroup/ESMValCore/blob/2966f5448a7aa9e3cc53058b6e2bbe69256c9296/esmvalcore/cmor/tables/cmip6/Tables/CMIP6_Amon.json#L206).

In these datasets, the Z coordinate is time, lat and lon-dependent and can be calcualted from 1D and 3D arrays (see [here](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#_atmosphere_hybrid_sigma_pressure_coordinate)). Saving these 1D and 3D arrays takes much less memory than saving a 4D array. When loading these datasets, `iris` automatically transforms these generic level coordinates into `air_pressure` or `altitude` (depends on the exact type of level coordinate that is used) coordinates via [`iris.aux_factories`](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris/aux_factory.html). Thus, something like

```py
cube = iris.load_cube('path/to/data_with_alevel_coordinate.nc')
air_pressure_coord = cube.coord('air_pressure')
```

even thought the original netCDF does **NOT** have an `air_pressure` coordinate is totally viable. Cubes like these behave exactly like cubes with an `air_pressure` coordinate defined. Moreover, diagnostic scripts can assume that these datasets have these derived coordinate, which is also vertical coordinate that is most relevant from a scientific point of view.

For some observational dataset, e.g. ERA5, it is be the case that these 4D variables are defined with a default (1D) `air_pressure` coordinate ( `plev`). This causes datasets like this to fail during our CMOR checks, since the tool expects a generic level coordinate. While this makes sense from a technical point of view, it does not make sense from a scientific point of view. After loading both cubes will have `air_pressure` coordinates, with the only exception that in the first case this coordinate is 4D and in the second case it is 1D. One obvious solution would be to create a generic level coordinate in the CMORizer, but this is not reasonable and unnecessary work.

Feature request
---

Would it be possible to let datasets with "non-generic" level coordinates pass our CMOR checks if the original variable is defined with a generic level coordinate? As I explained above, the generic level coordinates are actually only an intermediate step in the creation of a "non-generic" coordinate. This would only affect few predefined combinations, e.g. for the generic level coordinate `alevel`, the coordinates `air_pressure` (`plev`) or `altitude` (`alt`) would be allowed alternatives. This probably also applies to ocean coordinates, but I don't know the details here.

This feature would simplify the handling of these datasets a lot!

**Comment by schlunma** [comment]
I just found a CMIP6 model that suffers from this issue (i.e., that has a simple 1D `plev` coordinate): `CMIP/UA/MCM-UA-1-0/historical/r1i1p1f1/Amon/cl/gn/v20190731/cl_Amon_MCM-UA-1-0_historical_r1i1p1f1_gn_185001-201412.nc`

```
netcdf cl_Amon_MCM-UA-1-0_historical_r1i1p1f1_gn_185001-201412 {                                                                                                                                                                                                      [56/396]
dimensions:
        bnds = 2 ;
        longitude = 96 ;
        latitude = 80 ;
        plev = 19 ;
        time = UNLIMITED ; // (1980 currently)
variables:
        double bnds(bnds) ;
                bnds:long_name = "vertex number         " ;
        double longitude(longitude) ;
                longitude:long_name = "longitude" ;
                longitude:units = "degrees_east" ;
                longitude:axis = "X" ;
                longitude:bounds = "lon_bnds" ;
                longitude:standard_name = "longitude   " ;
        double latitude(latitude) ;
                latitude:long_name = "latitude" ;
                latitude:units = "degrees_north" ;
                latitude:axis = "Y" ;
                latitude:bounds = "lat_bnds" ;
                latitude:standard_name = "latitude    " ;
        double plev(plev) ;
                plev:long_name = "pressure" ;
                plev:units = "Pa" ;
                plev:axis = "Z" ;
                plev:positive = "down" ;
                plev:standard_name = "air_pressure" ;
        double lat_bnds(latitude, bnds) ;
                lat_bnds:long_name = "latitude bounds       " ;
                lat_bnds:units = "degrees_north" ;
                lat_bnds:axis = "Y" ;
        double lon_bnds(longitude, bnds) ;
                lon_bnds:long_name = "longitude bounds      " ;
                lon_bnds:units = "degrees_east" ;
                lon_bnds:axis = "X" ;
        double areacella(latitude, longitude) ;
                areacella:long_name = "area of grid cell atm " ;
                areacella:units = "m**2                  " ;
        float cl(time, plev, latitude, longitude) ;
                cl:units = "%" ;
                cl:missing_value = 1.e+20f ;
                cl:long_name = "Percentage Cloud Cover                                " ;
                cl:cell_methods = "area: time: mean" ;
                cl:cell_measures = "area: areacella" ;
                cl:_FillValue = 1.e+20f ;
                cl:table_id = "Amon" ;
                cl:standard_name = "cloud_area_fraction_in_atmosphere_layer" ;
        double time(time) ;
                time:units = "days since 0001-01-01 00:00:00" ;
                time:calendar = "noleap" ;
                time:long_name = "time" ;
                time:axis = "T" ;
                time:calendar_type = "noleap" ;
                time:bounds = "time_bnds" ;
                time:description = "for time-mean fields" ;
                time:standard_name = "time" ;
        double time_bnds(time, bnds) ;
                time_bnds:units = "days since 0001-01-01 00:00:00" ;
                time_bnds:calendar = "noleap" ;
                time_bnds:long_name = "time axis boundaries" ;
                time_bnds:missing_value = 1.e+20f ;
                time_bnds:FillValue = 1.e+20f ;
```

**Comment by sloosvel** [comment]
Well if you want to accept another definition of the level coordinate for this types of variables, I think that at least the requested values for the new 1D coordinated should be checked. I had a look at your approach and it seems like you are changing the definition coordinate and skipping everything that comes after. You risk having a 1D coordinate with wrong values, which could be a problem.

**Comment by schlunma** [comment]
Yes, I fully agree! The code I proposed was just a first approach which could be used as a starting point but which is definitely not complete.

Do you have any suggestions on how to approach this? Which checks do we have that you think are necessary?

**Comment by sloosvel** [comment]
I think it's a bit complicated because this would require making the checker not only check against the definition, but also guess which definition you are using. Especially when working with multiple datasets, which will be a mix of cubes with `alevel` and cubes with `plev`. 

But maybe something like calling the checks on the alternative coordinate (`self._check_coord_values`, `self._check_coord_bounds` and `self._check_coord_monotonicity_and_direction`) right after guessing the alternative name would work? This would not affect the rest of the run, nor mess with the dictionary with the original cmor info.

I still have to try it though.

**Comment by schlunma** [comment]
> But maybe something like calling the checks on the alternative coordinate (`self._check_coord_values`, `self._check_coord_bounds` and `self._check_coord_monotonicity_and_direction`) right after guessing the alternative name would work? This would not affect the rest of the run, nor mess with the dictionary with the original cmor info.

Sounds great! I guess this is probably by far the least invasive option!
