### ISSUE TITLE
Switch main branch from "master" to "main"

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1031]
...as per new Github be-nice norms https://github.com/github/renaming

**Comment by bouweandela** [comment]
@ESMValGroup/esmvaltool-coreteam Could someone with appropriate permissions please take care of doing this, both here and in the ESMValTool repository? I am not allowed to do this. The instructions for renaming the `master` branch to `main` are [here](https://github.com/github/renaming#renaming-existing-branches).

**Comment by axel-lauer** [comment]
I am fine with that change bit this also requires the documention and all other references to "master" e.g. in README.md or PKG-INFO to be updated. I created 2 draft pull requests addressing these changes. @valeriupredoi @bouweandela @zklaus could one of you please take a look whether the changes look fine?

* https://github.com/ESMValGroup/ESMValCore/pull/1132
* https://github.com/ESMValGroup/ESMValTool/pull/2172

Ideally, updating the documentation would be done shortly after renaming master to main. Also, I guess we would need to inform all developers about this? Any opinions?

**Comment by valeriupredoi** [comment]
cheers @axel-lauer for the good work! I am going to email the devvs right now, one more thing left to do - delete `master` once and for all or keep it as legacy (I am fine with either, but think that we might want to rename it to something like `master-legacy`) @bouweandela

**Comment by zklaus** [comment]
Let's kill it. It will only cause confusion.

**Comment by valeriupredoi** [comment]
OK, sounds good, will you do the service and execute the poor fella, Klaus? :gun:

**Comment by zklaus** [comment]
I'm gonna wait a bit to give others a chance to weigh in; otherwise, I will do the deed next Monday.

**Comment by valeriupredoi** [comment]
yeah good call dude! One thing I remembered is whoever is doing the automatic pull in the private project needs to switch from pulling `master` nightly - is it you @axel-lauer or @remi-kazeroni ?

**Comment by remi-kazeroni** [comment]
> yeah good call dude! One thing I remembered is whoever is doing the automatic pull in the private project needs to switch from pulling `master` nightly - is it you @axel-lauer or @remi-kazeroni ?

Yes I will start pulling from `main` once it has become the default branch. Who is going to rename the default `master` branches of ESMValTool and ESMValCore to `main`? @axel-lauer?

**Comment by valeriupredoi** [comment]
they are already renamed and pushed, man :baby:

**Comment by zklaus** [comment]
@valeriupredoi, hmm. https://github.com/ESMValGroup/ESMValTool/branches still shows master as the default. So does https://github.com/ESMValGroup/ESMValCore/branches

**Comment by valeriupredoi** [comment]
very good observation @zklaus - I forgot to check - unfortunately I am not powerful enough to change it, could @remi-kazeroni or @axel-lauer please follow these [instructions](https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/changing-the-default-branch) to change the Default branch on both Core and Tool please :beer:

**Comment by bouweandela** [comment]
The idea is to **rename** `master` to `main`, not delete it and also not change the default branch (though renaming will effectively do that of course). Please use the renaming instructions from the [renaming](https://github.com/github/renaming) repository. See [here](https://github.com/github/renaming#renaming-existing-branches) for instructions and information. Indeed this would need to be done by someone with administrator rights.

**Comment by axel-lauer** [comment]
@ESMValGroup/esmvaltool-developmentteam 

### Important information

Following the (new) GitHub standards, we renamed the "master" branch in ESMValTool and ESMValCore as well as in ESMValTool-private to "main". Open pull requests have been automatically redirected to main, so nothing to do from your side here.

### Please note

In case you are working with local copies of the repositories ESMValTool (ESMValTool-private) or ESMValCore, please rename the master branches in all of those to main using the following commands:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by valeriupredoi** [comment]
@bouweandela could you also pls update Codacy to run on `main` as the main branch in Pull Requests, I just tried to do that and it didn't allow me to - see eg [this message](https://app.codacy.com/gh/ESMValGroup/ESMValCore/pullRequest?prid=7398606)

**Comment by bouweandela** [comment]
I can't, I'm not administrator either. @axel-lauer Could you please have a look?
https://app.codacy.com/gh/ESMValGroup/ESMValCore/settings/branches
https://app.codacy.com/gh/ESMValGroup/ESMValTool/settings/branches

**Comment by valeriupredoi** [comment]
cheers for the renaming clarification @bouweandela - @axel-lauer has done this and now I see `main` is boss, no more `master` in the branches list either, nice one guys! Just the Codacy bit left to do. I did have a look on PyPi and conda and there is no mention of default branches there

**Comment by axel-lauer** [comment]
@bouweandela @valeriupredoi Just changed main branch in Codacy to "main" for ESMValTool and ESMValCore. Hope that does the job.

**Comment by bouweandela** [comment]
I just updated dockerhub. Readthedocs picks up the default branch.

**Comment by bouweandela** [comment]
Can we close the issue? I believe we have now updated everything everywhere.

**Comment by valeriupredoi** [comment]
I thinks so yes
