### ISSUE TITLE
Variable derivation fails due to inconsistend metadata

### ISSUE THREAD

**Issue by lukasbrunner** [ESMValGroup/ESMValCore#1054]
**Describe the bug**

In #1053 (discussed in #1050) we aim to implement a derived variable for ERA5. This currently fails due to inconsistent metadata in the two variables used for calculation. 

https://github.com/ESMValGroup/ESMValCore/blob/241c59bbb44026f694a2fce09c7ff017f03939f7/esmvalcore/preprocessor/_derive/rsus.py#L36

`*** ValueError: Insufficient matching coordinate metadata to resolve cubes, cannot map dimensions (1, 2) of the RHS cube 'surface_net_downward_shortwave_flux' to the LHS cube 'surface_downwelling_shortwave_flux_in_air'.`

My best guess is that this due to different capitalization of the `long_name` attributes of the longitude and latitude dimensions. 
```python
ipdb> rsds_cube.coords()[1].long_name
'Latitude'
ipdb> rsns_cube.coords()[1].long_name
'latitude'
```
Here is the rsns CMOR file

https://github.com/ESMValGroup/ESMValCore/blob/241c59bbb44026f694a2fce09c7ff017f03939f7/esmvalcore/cmor/tables/custom/CMOR_rsns.dat#L18

Not sure where exactly the information for rsds comes from? Maybe here:

https://github.com/ESMValGroup/ESMValCore/blob/241c59bbb44026f694a2fce09c7ff017f03939f7/esmvalcore/cmor/tables/obs4mips/Tables/obs4MIPs_coordinate.json#L875

[main_log_debug.txt](https://github.com/ESMValGroup/ESMValCore/files/6162537/main_log_debug.txt)
[recipe_climwip_brunner2019_eur.yml.txt](https://github.com/ESMValGroup/ESMValCore/files/6162539/recipe_climwip_brunner2019_eur.yml.txt)

**Comment by valeriupredoi** [comment]
if you just do a `for cube in (rsds, rsns): print(cube.coords())` and attach the output, we could probably identify the offending metadata elements that differ from one to another, you guess might be the answer actually - coords (1, 2) are indeed lat and lon

**Comment by lukasbrunner** [comment]
[derive_rsus.txt](https://github.com/ESMValGroup/ESMValCore/files/6169767/derive_rsus.txt)

**Comment by valeriupredoi** [comment]
cheers, looks like indeed just that `latitude -> `Latitude` `var_name` differs, beats me if I can see anything else different :+1:

**Comment by lukasbrunner** [comment]
:+1:  so which one is the correct one?

I guess taking the capitalized one is easier to fix? Then we need to change `latitude` -> `Latitude` and `longitude` -> `Longitude` in ESMValCore/esmvalcore/cmor/tables/custom?

Although naively it seems inconsistent to me to have `time` but `Latitude`...
If we want the non-capitalized one I think I would ask you to fix it @valeriupredoi if that is okay? Seems to be a potentially larger effort and I don't want to break anything...

**Comment by valeriupredoi** [comment]
`var_name` is not strictly reinforced by CF conventions (iris' policeman) neither it is a cause of fail for our most restrictive CMOR checks against the CMOR tables ( @sloosvel correct me if I'm wrong pls) and the equivalent in the CMOR table is `long_name` which is `Latitude` for CMIP6 and `latitude coordinate` for CMIP5 so I don't think we should implement a fix per se but rather a check in the derivation script, and a harmonization of the coordinates' metadata there - I can do this right now if you agree with this? :+1:

**Comment by lukasbrunner** [comment]
Definitely fine with me I don't have a strong opinion on this :)

**Comment by bouweandela** [comment]
> Not sure where exactly the information for rsds comes from? 

The `native6` project uses the CMIP6 table. I think the problem is that the custom variables follow the CMIP5 CMOR table, but are still added as extra variables to the CMIP6 CMOR table, so you end up trying to mix variables with coordinates from different tables.
