### ISSUE TITLE
Should we test every PR with Python 3.6?

### ISSUE THREAD

**Issue by stefsmeets** [ESMValGroup/ESMValCore#1055]
**Is your feature request related to a problem? Please describe.**
The installation guide mentions that we support Python 3.6 and up (https://docs.esmvaltool.org/en/latest/quickstart/installation.html). However, CircleCI runs the test on every commit with a higher version. Actually I'm not sure which version, because it just pulls the docker container (but it's not 3.6). 

In my opinion, if we are supporting Python 3.6, we should make sure that we test against 3.6 as the lowest version. This to make sure that we do not 'accidentally' add code or features that are not supported by 3.6, for example in #1042, where this came up.

Note that Python 3.6 support will be dropped later this year (https://endoflife.date/python).

**Comment by bouweandela** [comment]
If the (very small) changes in ce46fc686d1e830fb0e088e0dcfa353a1a40c38b were all that was needed to make the package work with Python 3.6, there is probably no need to run these tests on every commit and just a nightly run is sufficient.

**Comment by valeriupredoi** [comment]
github actions [runs](https://github.com/ESMValGroup/ESMValCore/actions/runs/674399495) the tests nightly with Python 3.6 too :+1:

**Comment by stefsmeets** [comment]
Considering that #1042 just got merged, the nightly github actions test Python 3.6, *and* that Python 3.6 will be eol later this year, this does not seem like it is needed right now 👍
