### ISSUE TITLE
Reversing coordinates using iris.util.reverse flips the bounds incorrectly

### ISSUE THREAD

**Issue by sloosvel** [ESMValGroup/ESMValCore#1060]
**Describe the bug**
During the checks for monotonicity and direction, if a coordinate has the wrong direction it gets flipped using `iris.util.reverse`. However, this also flips the bounds and makes them non-contigous. This can cause issues in later preprocessing steps, for instance, when computing area weighted operations.

**Comment by bouweandela** [comment]
Is this a bug in iris? If so, it would be good to report it there too.
