### ISSUE TITLE
Slow `_get_response` in `citation.py` 

### ISSUE THREAD

**Issue by sloosvel** [ESMValGroup/ESMValCore#1088]
**Is your feature request related to a problem? Please describe.**

The machine we use at BSC does not allow outgoing connections due to security reasons. This makes some recipes hang for some time after they finish computing diagnostics and they get to the citation module:

````
2021-04-27 10:10:45,598 UTC [14045] INFO    No network connection, unable to retrieve CMIP6 citation information
2021-04-27 10:13:55,038 UTC [14045] INFO    No network connection, unable to retrieve CMIP6 citation information
2021-04-27 10:17:05,502 UTC [14045] INFO    No network connection, unable to retrieve CMIP6 citation information
````

Would there be any way to get a quicker response?

**Comment by SarahAlidoost** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> The machine we use at BSC does not allow outgoing connections due to security reasons. This makes some recipes hang for some time after they finish computing diagnostics and they get to the citation module:
> 
> ```
> 2021-04-27 10:10:45,598 UTC [14045] INFO    No network connection, unable to retrieve CMIP6 citation information
> 2021-04-27 10:13:55,038 UTC [14045] INFO    No network connection, unable to retrieve CMIP6 citation information
> 2021-04-27 10:17:05,502 UTC [14045] INFO    No network connection, unable to retrieve CMIP6 citation information
> ```
> 
> Would there be any way to get a quicker response?

Thank you for reporting this. I think we can add `timeout=1` to `requests.get(url)` in [that function](https://github.com/ESMValGroup/ESMValCore/blob/622366123bc57df1796a558dec7b24316c113041/esmvalcore/_citation.py#L149) as: 
```python 
requests.get(url, timeout=1)
```
However, I amnot sure if `timeout=1 sec` is practical. @stefsmeets  what do you think? I made the draft PR #1091 to add this.

**Comment by stefsmeets** [comment]
Hi @SarahAlidoost , I think this is the only solution that is practical. Maybe put it to 5 or 10 seconds to allow for somewhat longer response times.

The alternative (and what is done by the OS) is to first ping some server or website (i.e. www.google.com) to see if there is a connection at all, but that will also have to have a timeout.

**Comment by stefsmeets** [comment]
I also like the suggestion from @zklaus to make it a configurable parameter (i.e. it can be put to 0 at BSC).

**Comment by sloosvel** [comment]
Thanks!
