### ISSUE TITLE
Dataset problem: Issues with latitude and longitude for sos and siconc of BCCs CMIP6 models

### ISSUE THREAD

**Issue by remi-kazeroni** [ESMValGroup/ESMValCore#1089]
**Describe the dataset issue**
This is the same as #537 or #748 but for the variables `sos` and `siconc` (model `BCC-ESM1` for the latter only).

- Pointer to existing copy of data on ESGF node (it would be very useful if you could provide a physical
fullpath to the file(s) that are causing the problem, e.g. on CEDA Jasmin or DKRZ):
/mnt/lustre02/work/ik1017/CMIP6/data/CMIP6/CMIP/BCC/BCC-CSM2-MR/historical/r1i1p1f1/Omon/sos/gn/v20181126/sos_Omon_BCC-CSM2-MR_historical_r1i1p1f1_gn_185001-201412.nc
/mnt/lustre02/work/ik1017/CMIP6/data/CMIP6/CMIP/BCC/BCC-CSM2-MR/historical/r1i1p1f1/SImon/siconc/gn/v20200218/siconc_SImon_BCC-CSM2-MR_historical_r1i1p1f1_gn_185001-201412.nc
/mnt/lustre02/work/ik1017/CMIP6/data/CMIP6/CMIP/BCC/BCC-ESM1/historical/r1i1p1f1/Omon/sos/gn/v20181129/sos_Omon_BCC-ESM1_historical_r1i1p1f1_gn_185001-201412.nc
/mnt/lustre02/work/ik1017/CMIP6/data/CMIP6/CMIP/BCC/BCC-ESM1/historical/r1i1p1f1/SImon/siconc/gn/v20200218/siconc_SImon_BCC-ESM1_historical_r1i1p1f1_gn_185001-201412.nc

**Comment by zklaus** [comment]
This should also be addressed with #1092
