### ISSUE TITLE
conda_build test is running out of time (again) on Circle

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1121]
[nightly](https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore/4741/workflows/8ebd4853-d7ec-4071-a2da-b73ab9b2b75b/jobs/22382) and lots in commits. Do we want to fix it or remove conda build test from the CI altogether, given the new conda forge deployment? @zklaus @bouweandela

**Comment by zklaus** [comment]
Sorry I've been slacking the rest of the conda-forges. Will get back to it soon.

**Comment by valeriupredoi** [comment]
it's been behaving lately, it dies but that's coz the tests die, and for that we have a fix
