### ISSUE TITLE
In filenames, experiments names which include a date do mislead recognizing file time period 

### ISSUE THREAD

**Issue by senesis** [ESMValGroup/ESMValCore#1127]
Assume your DRS file pattern is :
```
input_file : '{simulation}_*_{freq}_{file_var_name}.nc'
```
and your simulation name has a year suffx , i.e. the filename is :
```
CM61-LR-hist-03.1950_18500101_19491231_1M_concbc.nc
```
then, the date range found by _data_finder is 
```
n="CM61-LR-hist-03.1950_18500101_19491231_1M_concbc.nc"
re.findall(r'([0-9]{4,12}[-_][0-9]{4,12})',n)
['1950_18500101']
```
which is a wrong choice
Using  the so-called "non-capturing version of regular parentheses" with **(?: ....)** can help finding the right pair of dates :
```
 re.findall(r'(?:[-_])([0-9]{4,12}[-_][0-9]{4,12})(?:[-_.])',n)
['18500101_19491231']
```

This is a real use case for my preferred model. If there is no concern with the choice of characters that must surround the date range, I would be glad to use this modest change as my first try at proposing a PR

**Comment by bouweandela** [comment]
Related to #1078

**Comment by bouweandela** [comment]
I think the 'problem' here may be that there is an `_` between the two dates instead of a `-`. For CMIP data, facets are separated by an underscore and the date is a single facet. I have a slight preference for the solution proposed in #1078 because configuring things is usually less error-prone than programming them.

**Comment by senesis** [comment]
I agree that #1078 proposes a more general solution. And that the issue here is caused by the fact that, for now, the underline character is allowed as separating dates in date ranges, while this is not in line with e.g. CMIP6 DRS (but I assumed that some pre-existing use case lead to allow for that)
However, until the handling of #1078 is developed and tested, I will use the solution above. And I recommend that the use of "non-capturing version of regular parentheses"  is used in #1078 because it allows to enforce that facet separators actually occurs at both end of the date ranges
