### ISSUE TITLE
Replace synda download with esgf-pyclient download?

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#1130]
Because synda is very difficult to install and configure, while esgf-pyclient is easy to install and easier to configure than synda.

**Comment by zklaus** [comment]
@ESMValGroup/technical-lead-development-team how do we feel about this? Do we want to replace synda? Or only offer pyesgf-client as an alternative? If we decide to remove synda, do we need a deprecation phase first?
