### ISSUE TITLE
Stop creating plots of provenance?

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#1135]
Recently a problem was reported by a user (see #1126) because of the provenance plots. Maybe we could stop creating those plots, because they are hardly readable anyway and if needed they can easily be created afterwards. Is anyone using them for anything? @ESMValGroup/esmvaltool-developmentteam

**Comment by Emmadd** [comment]
Can you post a provenance plot so people can have an idea of what they would be missing please?

**Comment by schlunma** [comment]
Never used them and also had problems with it (with complex recipes), so I'm happy with removing them. Especially when the recipe is complex, the amount of information they provide is really overwhelming and not readable at all.

**Comment by bouweandela** [comment]
They are only created for small recipes (less than 100 provenance entries) because that was too slow.

Here is an example for a plot with just a single input file:
![tas_global_CMIP5_CanESM2_Amon_historical_r1i1p1_tas_1850-2000_provenance](https://user-images.githubusercontent.com/5430937/118614735-599d0a80-b7c0-11eb-990b-1b68d6d4ea16.png)
That looks still fine, but as the number of input files increases the plots very rapidly become useless.

**Comment by zklaus** [comment]
I too struggle to use them. However, I have gotten a lot of questions about the provenance. That certainly seems to be one of the most attractive features of ESMValTool, so maybe we should think a bit more about how to make this information more useable?

I think the generation of the plots in its current form can be deactivated.

**Comment by Emmadd** [comment]
Wow! That is a lot of information. I can imagine that in my case with 70 files which were in some cases merged from 5 year datafiles the amount of information is overwhelming and leads to problems. 

Nice to see/good to know that the CheckLevels values is stored here as well as I've been playing around with them a bit (was not useful thus far) and was wondering if/where this information was stored.

**Comment by fserva** [comment]
Would it be reasonable to make this optional, for example with a `make_provenance` flag controlled from the config file?

**Comment by earnone** [comment]
I agree this could be produced on request. With large processing they are
not produced anyway.

**Comment by lukasbrunner** [comment]
Maybe related: I recently also had problems with the provenance in the output files (for a large number of models):
https://github.com/ESMValGroup/ESMValTool/pull/1859#issuecomment-827573581

I think it is good to have but in this case (>99% of file size only for provenance) it seems that another solution would be preferable.

**Comment by bouweandela** [comment]
That's a different problem, but thanks for reporting it. I created a new issue here: #1148.
