### ISSUE TITLE
Handle IPSLCM native formats  

### ISSUE THREAD

**Issue by senesis** [ESMValGroup/ESMValCore#1143]
This **Handle IPSLCM native formats** feature is related to IS-ENES3 WP9.5 "_Enhancing the use of the ESMValTool for model development_" and more precisely its subtask "_Incorporation of ESMValTool into modelling or stand-alone workflow_" , and to IS-ENES3 deliverable D9.2 "_ESMValTool version enabling model development usage_" 

The intent is to add this feature for [release 2.3.0](https://github.com/ESMValGroup/ESMValCore/milestone/6), for which PR's are due for June, 7 (so, yet in two weeks time)

Handling IPSLCM requires :

1. to find datafiles by translating variable names to native variable names
2. to handle filenames where experiment name may include a date (independently of the CMIP sub-experiment concept), and this experiment name can be a neighbour of the dates range in the filename
3. to develop specific fixes for that model's data
4. to get an acceptable performance when using the IPSLCM data format which include multiple variables in a single NetCDF file (called 'Output')

The current status is : 
1. Item 1 is covered by #1124, but that PR is not related to [milestone 2.3.0](https://github.com/ESMValGroup/ESMValCore/milestone/6)
2. Item 2 is explained in #1127, which proposes a bugfix. Because it is related to #1078 which proposes a more generic solution, it has been closed. However, #1078 is not related to  [milestone 2.3.0](https://github.com/ESMValGroup/ESMValCore)
3. Item 3 is OK. However, until #494 is developed and merged, handling the two flavors of IPSLCM data format implies to create two projects, and thus two fixes directories (which share a single fix module)
4. Item 4 is addressed in an [ESMValCore issue](https://github.com/ESMValGroup/ESMValTool/issues/2141), and solved by a [feature of the developed fixes](https://github.com/ESMValGroup/ESMValTool/issues/2141#issuecomment-845927522) 

So, the open questions are: 
- Is it the intent that PR #1124 be merged for [milestone 2.3.0](https://github.com/ESMValGroup/ESMValCore/milestone/6)? Note that I already tested IPSLCM fixes using corresponding @zklaus repository's branch 
- Should issue #1127 be re-opened (beyond @bouweandela comment) and turned into a PR marked for [milestone 2.3.0](https://github.com/ESMValGroup/ESMValCore/milestone/6) ? (I would elaborate it)
- Is anybody committed to handle #494 in time for [milestone 2.3.0](https://github.com/ESMValGroup/ESMValCore/milestone/6), and is it the right way to go, with respect to the proposal in #795 ? in that context, what about choosing the solution to populate the _fixes directory with  2 directories?

(@jservonnat and @alistairsellar may wish to be mentioned here)

**Comment by senesis** [comment]
Further questions :
- documentation : apart from the ChangeLog, I see no other place in the on-line documentation for reporting about such a feature, and to provide users with some explanations and examples; any direction here, @ESMValGroup/tech-reviewers  ? 
- tests : the tests directory apparently does not include any test directed at checking that each data source can be read; should I nevertheless build such a test for that IPSLCM data (and so add data in the ESMValTool_sample_data repository), @ESMValGroup/tech-reviewers ?

**Comment by zklaus** [comment]
I have marked #1124 with milestone 2.3.0 and I have no problem with anything else being marked as such. After all, these markings are rather indicative. If the PRs are not integrated by June 7, they will be bumped to 2.4.0.

The other things you mention are only issues at the moment. They can also be assigned to the milestone, please feel free to do so, but right now as far as I can see there is nobody committed to working on them.

**Comment by zklaus** [comment]
As for the other questions:

documentation: Since this is an aggregate issue, I am not completely sure which feature you have in mind, so I see two possibilities. Either we discuss this in the individual issues, or/and we add a new section to the documentation dealing with native model data. That is appealing also as a place to put generic instructions on how to add new models. I see two candidate places for it, one under "ESMValTool"->"Obtaining input data" and the other under "ESMValCore"->"The recipe format". Reading through the documentation it might also be worthwhile to have a new section that better describes all the possible data sources, perhaps in parts rewriting "ESMValTool"->"Obtaining input data"?

tests: I think we try to avoid data-heavy tests, @valeriupredoi, do you have more insights here? Or perhaps @jvegasbsc from the CMIP inputs?

**Comment by senesis** [comment]
> The other things you mention are only issues at the moment. They can also be assigned to the milestone, please feel free to do so, but right now as far as I can see there is nobody committed to working on them.

I would be glad to work on both, i.e. : 
- turn #1127 to a PR which will only change the regexp pattern for date ranges, thus forgetting about #1078 proposal, 
- and try to turn  #494 in a PR that would go along [my suggestion](https://github.com/ESMValGroup/ESMValCore/issues/494#issuecomment-845808725), 

but my request here was rather to reach an agreement than to head toward developing a solution which wouldn't last for long.

**Comment by senesis** [comment]
> I have marked #1124 with milestone 2.3.0 and I have no problem with anything else being marked as such. 

Thanks. I would be glad to build a draft PR (in ESMValTool repository), at least for benefit of automated tests, but I do not know how I could issue it (in ESMValTool repository) based on your branch for the draft PR #1124  (which is in your private repository).

**Comment by zklaus** [comment]
- I agree that addressing the issue of the regex for dates in a slimmer version that hinted at in #1078 is reasonable. I would suggest going with your suggestion in #1078 to enforce date pairs having the same length. I think this is a simple and clear improvement of the regex with minimal impact. At the same time we can move from accepting any length between 4 and 12 to exactly the right ones, i.e. 4, 6, 8, 10, 12.

- Addressing #494 also sounds good. I suggest trying to reach an agreement on the format in the issue first. I think the main difference between your and @bsolino's suggestion is at which level to put the model in the configuration hierarchy.

**Comment by senesis** [comment]
> Reading through the documentation it might also be worthwhile to have a new section that better describes all the possible data sources, perhaps in parts rewriting "ESMValTool"->"Obtaining input data"?

@zklaus This solution is my preferred one. What about such a structure : 

```
Input data (was: Obtaining input data)
  Known data types
    Model data
    Observations and reanalyses
  Adding a data type
    Offline reformating data (was : cmorizer scripts)
    On-the-fly reformating (was : cmorization as a fix)
  Obtaining input data
    Data centers
    Downloading ESGF data with Synda

```
and who should be pinged here ?

**Comment by zklaus** [comment]
Good question. Perhaps @ESMValGroup/userengagementteam ?

**Comment by senesis** [comment]
@zklaus @bouweandela I am going to update this PR. What is your prefered case : that I keep IPSL-CM6 in project native6 , or that I create a new project (thus allowing to use e.g. simultaneousy e.g. native6/ERA5 and ISPL-CM6).

**Comment by zklaus** [comment]
My feeling is that things work out better when every model is its own project. Consider whether it makes sense to have a project IPSL-CM instead with different iterations distinguished by different datasets. I really cannot judge if that makes sense based on how the data format has changed between different generations of the model.

**Comment by zklaus** [comment]
@senesis, what do you think, is this issue addressed by now? If not, what are the points that you would still like to see handled?
