### ISSUE TITLE
Embedding provenance in diagnostic results may crash ESMValCore or a Jupyter notebook using the files

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#1148]
Another question: I started looking at the `weights.nc` output file. For about 130 models it has about 10MB. Almost all of this (>99%) is due to the provenance global attribute. This seems a bit excessive. I could not quite figure out where this is added to the file (and it is not really connected to this PR, I assume it was always there just not so large with less models). I think @Peter9192 and @stefsmeets implemented that. Is that really necessary or is there another way of storing this? As it is the single 10MB string is quite efficient in killing my Jupyter notebook when I try to open the file...

_Originally posted by @lukasbrunner in https://github.com/ESMValGroup/ESMValTool/pull/1859#issuecomment-827573581_

**Comment by bouweandela** [comment]
@ESMValGroup/esmvaltool-coreteam Should we continue embedding the provenance information as a global attribute in the output NetCDF files? Appently this makes it impossible to use them in some cases.

**Comment by schlunma** [comment]
The provenance output makes it really hard to read the files with `ncdump`, since there is important information above that (coordinates, variable metadata, etc.) and below it (data). In my opinion we could get rid of it (or replace it with some basic information (e.g. ESMValTool version, diagnostic name, etc.).

**Comment by bouweandela** [comment]
Discussed this with @nielsdrost and he suggested trying to store the provenance in an additional variable instead of in the header. If that doesn't work, the best option is probably to only store it in a separate file.

For reference here is a [document with some background information on provenance storage for climate data](http://cfconventions.org/Meetings/2020-workshop/Metadata-handling-provenance-discussion-notes.pdf).

**Comment by bouweandela** [comment]
It looks like embedding provenance in .png files is also not that ideal, it crashes the tool if the provenance is too large (see linked issue).

**Comment by bouweandela** [comment]
> Discussed this with @nielsdrost and he suggested trying to store the provenance in an additional variable instead of in the header. 

I tried this, but iris will interpret this as a second cube and that will break many diagnostics, so this does not look like a viable option:
```python
from netCDF4 import Dataset
import numpy as np
import iris

def write_prov():
    with Dataset("test.nc", "a") as rootgrp:
        prov = rootgrp.createDimension("prov", 10000)
    
        provenance = rootgrp.createVariable("provenance","S1",("prov",))

if __name__ == '__main__':
    cube = iris.cube.Cube(np.arange(73*144*2, dtype=np.float32).reshape(2, 73, 144))
    cube.add_dim_coord(iris.coords.DimCoord(np.arange(2, dtype=np.float64), var_name='time'), 0)
    cube.add_dim_coord(iris.coords.DimCoord(np.arange(73, dtype=np.float64), var_name='latitude'), 1)
    cube.add_dim_coord(iris.coords.DimCoord(np.arange(144, dtype=np.float64), var_name='longitude'), 2)
    iris.save(cube, target='test.nc')
    write_prov()
    cubes = iris.load('test.nc')
    print(cubes)
```
prints
```
0: unknown / (unknown)                 (time: 2; latitude: 73; longitude: 144)
1: provenance / (unknown)              (-- : 10000)
```

**Comment by valeriupredoi** [comment]
unknown provenance - a bit of a misnomer :laughing: - why not store it as an attribute in `cube.metadata()`?

**Comment by bouweandela** [comment]
That is what we are currently doing, see the top post for why this is a problem

**Comment by valeriupredoi** [comment]
:man_facepalming: indeed! I am being silly, I thought I have just discovered hot water :grin: How about an sql db then?
