### ISSUE TITLE
Simplify branches

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#115]
Currently we have two branches

`development` -> this is where we work
`master` -> we never use this, it is identical to the latest tagged version

I would propose to start working in the `master` branch instead and remove the `development` branch, because we never use the current `master` branch. This is what most open source projects do.

If you want to see the code of the released version, you can just get the tag, i.e. `git checkout v2.0.0a1`, or download the zipped source code from the [releases page](https://github.com/ESMValGroup/ESMValCore/releases).

**Comment by bouweandela** [comment]
@mattiarighi Could you remove the protected status and delete the `development` branch from GitHub?

**Comment by mattiarighi** [comment]
Done.
