### ISSUE TITLE
cf-units=2.1.5 for OSX still preserves older version behaviour (<2.1.4)

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1158]
`cf-units=2.1.5` installed in the esmvaltool conda env on OSX as seen from the [GA test](https://github.com/ESMValGroup/ESMValCore/runs/2759882084?check_suite_focus=true) preserves the behavior of `num2date` from an older version, <2.1.4. We need to raise this with the `cf-units` develsm @bjlittle this is a SciTools package, would you be able to look into it maybe? :beer: 

Results for `cf_units.num2date(time.points, time.units.name, time.units.calendar)[0].strftime('%Y%m%d%H%M')` for Linux:
- Behavior for 2.1.4:  "  30001161200"
- Behavior for 2.1.5:  "30001161200"

I remember that "030001161200" result was when we were using 2.1.2 or something similar.

**Comment by zklaus** [comment]
C.f. (haha): SciTools/cf-units#170 It seems @trexfeathers is on it as of 3 hr ago.

**Comment by valeriupredoi** [comment]
cheers man! I thought I'm losing my beans with this again :rofl:

**Comment by trexfeathers** [comment]
Note that there is already [API to access the new behaviour](https://github.com/SciTools/cf-units/blob/855077c68d39be652a6dac560d1eaf71af515f36/cf_units/__init__.py#L497):

```python
num2date(only_use_cftime_datetimes=True)
```

**Comment by zklaus** [comment]
@valeriupredoi, why are we even doing the conversion to string here? Wouldn't it make more sense to compare the datetime objects themselves?

**Comment by valeriupredoi** [comment]
that is a very good point indeed @zklaus - let me try set that up! :beer:

**Comment by valeriupredoi** [comment]
> Note that there is already [API to access the new behaviour](https://github.com/SciTools/cf-units/blob/855077c68d39be652a6dac560d1eaf71af515f36/cf_units/__init__.py#L497):
> 
> ```python
> num2date(only_use_cftime_datetimes=True)
> ```

cheers @trexfeathers - I'll have a look into fixing it either as Klaus or as you point out :beer:
