### ISSUE TITLE
Load and use fx variable even if not broadcastable onto model cube data

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1160]
Thanks to @sloosvel we now have a nice integration of anciliary vars for fx vars, including CMOR checks and all that fancy jazz. There is, however, room for improvement, as I see it: there is a hard [cut-off](https://github.com/ESMValGroup/ESMValCore/blob/fc87d72c3fce12a2117b4b4e42a4857045c4d404/esmvalcore/preprocessor/_ancillary_vars.py#L34) that stops the process of using a certain fx var if its data array is not broadcastable onto the model data array: I think we can relax this a bit:

- if the fx data is time-invariant, and the model data is not, we can still use the fx data by propagating the fx data at every time point of the model data
- if the fx data is on a finer/coarser time axis than the model data, we can perform a time regridding and still use the fx data (and it'd even be broadcastable onto model data this time around)

These are statistical massages of the fx data that **may** not be sound, so please correct me here if you see any issues with these approaches :beer:

**Comment by schlunma** [comment]
Hi V.,

1. If the data is time-invariant (and time is the first dimension, which it usually is), then we can already handle this due to the way broadcasting [works](https://numpy.org/doc/stable/user/basics.broadcasting.html#general-broadcasting-rules).
2. If the fx files have a time dependence, I think we need to be really careful when regridding them. Apart from that, I haven't encountered this case once, so would it make sense to leave it like that and re-open this issue if necessary?

**Comment by zklaus** [comment]
I tend to agree with @schlunma, but let's keep the issue open for a bit of discussion. I have assigned the next milestone (2.4.0) and I think we should by then decide

1. What exactly is the issue? Use-cases, examples, past occurrences of the problem.
2. How do we want to address it? Just close the issue? Improve documentation before?

**Comment by valeriupredoi** [comment]
cool, let's come back to this - I intent to do that after I've done fixing a number of test nuisances, next week - cheers for the input @schlunma and @zklaus

**Comment by valeriupredoi** [comment]
am closing this for now since I've run a bunch of tests and am yet to find a case that needs implementation/attention - I'll reopen if need be but for now it looks bright :+1:
