### ISSUE TITLE
Nightly tests on CircleCI are failing

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#1166]
The `install`, `develop`, and `conda_build` test [failed on CircleCI last night](https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore/4985/workflows/92577489-0597-4286-9bc7-3e6a0637ebbf). There appear to be two problems:
1) timeouts when creating the conda environment
2) Newer version of mypy with extra dependencies

**Comment by valeriupredoi** [comment]
second issue is not only for Circle but also GA, `mypy>=0.900` needs the stubs, am opening a separate issue for that, see [here](https://mypy.readthedocs.io/en/latest/getting_started.html) and already detected by the conda-lock install tests [here](https://github.com/ESMValGroup/ESMValCore/pull/1164/checks?check_run_id=2781895221)

**Comment by valeriupredoi** [comment]
incidentally, conda build complains about our license `/tmp/tmp2wnrfrma/esmvalcore-2.2.0-py_0.tar.bz2: C1115 Found invalid license "Apache License, Version 2.0" in info/index.json` - you guys know if that's something we're doing wrong?

**Comment by bouweandela** [comment]
The easiest solution would probably be to not run the mypy tests when building the conda package, I'm not sure if they bring any added value at that stage.

The alternative is to add the stubs to the test dependencies in meta.yaml, provided that they are available on conda-forge.

**Comment by valeriupredoi** [comment]
I agree @bouweandela - let's not run the mypy tests, I too have no knowledge of any added verification from them in conda build. Good weekend, man :beer:
