### ISSUE TITLE
mypy>=0.900 needs stubs installed as separate packages

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1168]
on Circle but also GA tests are failing, `mypy>=0.900` needs the stubs, see [here](https://mypy.readthedocs.io/en/latest/getting_started.html) and already detected by the conda-lock install tests [here](https://github.com/ESMValGroup/ESMValCore/pull/1164/checks?check_run_id=2781895221) - do we want these as regular dependencies or together with the mypy installation?

**Comment by valeriupredoi** [comment]
we kinda need this sorted asap otherwise @zklaus will breathe fire on us. I am very much OK with pinning `mypy<0.900` for now

**Comment by bouweandela** [comment]
Fixed in #1167

**Comment by valeriupredoi** [comment]
yup, added it there to be closed when that gets merged :+1:

**Comment by valeriupredoi** [comment]
#1167
