### ISSUE TITLE
Naming of `extract_levels` schemes

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#1170]
General question about the naming of the schemes we support for `extract_levels` (i.e., the vertical regridding):

Why are the extrapolating versions of the schemes called `nearest_horizontal_extrapolate_vertical` and `linear_horizontal_extrapolate_vertical`? Do they really consider the horizontal dimensions in some way? I have the feeling they don't...The documentation of [`stratify.interpolate`](https://github.com/SciTools-incubator/python-stratify) is really sparse, but I made some tests and I don't think that horizontal neighbors are taken into account, especially since `stratify.interpolate` doesn't take horizontal dimensions into account but works on pure `numpy` arrays.

I think I could trace back the renaming to [this](https://github.com/ESMValGroup/ESMValTool/pull/438#discussion_r199433771) comment, I hope that's the correct commit :sweat_smile: @ledm Is there any particular reason you included `horizontal` into the name?

As alternatives, I suggest `linear_extrapolate` and `nearest_extrapolate` (similar to the horizontal regridding schemes). What do you think @ESMValGroup/esmvaltool-coreteam?

**Comment by bouweandela** [comment]
> Do they really consider the horizontal dimensions in some way?

`python-stratify` is able to handle multidimensional vertical coordinates if they are present in the input data, but indeed it only looks at the vertical coordinate (that may vary horizontally)

**Comment by schlunma** [comment]
Sorry, could have expressed myself better: I know that `python-stratify` handles multidimensional coordinates, but my question was if it really considers horizontal neighbors when extrapolating. I'm pretty sure it does not.

**Comment by schlunma** [comment]
Anymore opinions on this? I'd like to open a PR for this to get this into v2.4.

**Comment by valeriupredoi** [comment]
I reckon best bet would be to target ask @bjlittle and/or @zklaus dude :beer:
