### ISSUE TITLE
Masked values when regridding datasets with coord `circular=False`

### ISSUE THREAD

**Issue by sloosvel** [ESMValGroup/ESMValCore#1175]
**Describe the bug**
At the BSC, it was reported that when regridding dataset MCM-UA-1-0, a white line with masked values appeared for lon > 355. 
After some debugging it turns out that when the longitudes are not circular and do not span fully from [0,360], those masked values can appear after regridding. 

This dataset got fixed in #1098, because (among other issues) the last bound in atmospheric coordinates was not set properly. That issue makes iris set the `circular` attribute to `False`, and makes the dataset come out of the regridding with masked values. Once the bounds are fixed, a quick solution would be to set the circular attribute to `True` in the same fix, since the condition that iris imposes to set this attribute checks for the fixed bound.

But I was wondering  if it would be ok to check for this attribute, either during the cmor checks or during the regridding,  to make a more general fix.

**Comment by zklaus** [comment]
We do need the ability to deal with non-circular datasets, e.g. regional data from CORDEX, subset data after another preprocessor, etc., so I think the easiest approach to this is really to make sure that the datasets are correctly labeled circular if that applies.
