### ISSUE TITLE
Fix bullet list formatting on readthedocs

### ISSUE THREAD

**Issue by zklaus** [ESMValGroup/ESMValCore#1179]
The list of changelog entries, which seems to be correct in the rst file, is not formatted as a bullet list. This should be fixed.

**Comment by bouweandela** [comment]
This problem appears to affect all lists in the documentation, maybe it's a sphinx issue?

**Comment by zklaus** [comment]
Maybe. [The Sphinx docu](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#lists-and-quote-like-blocks) seems to consistently use `*` for lists, though I did not expect our use of `-` to be a problem.

**Comment by bouweandela** [comment]
I suspect it's something to do with a new version of some package, it used to work fine before.

**Comment by zklaus** [comment]
Seems the culprit is an incompatible version of docutils. For details see https://stackoverflow.com/a/68008428
