### ISSUE TITLE
Dataset problem: invalid time bounds of `gpp_Lmon_MIROC-ESM_esmFixClim1_r1i1p1_000101-014012.nc`

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#1187]
**Describe the dataset issue**

The first time bound of `gpp_Lmon_MIROC-ESM_esmFixClim1_r1i1p1_000101-014012.nc` is below `datetime.MINYEAR`, which causes trouble when `unit.num2date` is used.

**Comment by zklaus** [comment]
Since the file is no longer available from ESGF, could you make it available somehow? Alternatively, you could post `ncdump -h` + `ncdump -v time_bounds` here.

**Comment by schlunma** [comment]
https://swift.dkrz.de/v1/dkrz_4eefb34f-8803-415a-bd70-9c455db9a403/CMIP/gpp_Lmon_MIROC-ESM_esmFixClim1_r1i1p1_000101-014012.nc?temp_url_sig=1096d53ba8cbb460f802c17f0897b565625c9cb1&temp_url_expires=2021-07-17T12:24:07Z
