### ISSUE TITLE
Anomaly/Bias/Error preprocessor

### ISSUE THREAD

**Issue by zklaus** [ESMValGroup/ESMValCore#119]
What do you guys think about a preprocessor for anomaly calculation?

It seems a rather common task to calculate anomalies or errors against either

- reference dataset
- climatology over certain period
- a fixed point in time

What do you think?

**Comment by valeriupredoi** [comment]
good call! and I know the right person to implement it, his name is Klaus :grin: We should, however, keep the dev work low until the release, but this seems a rather useful feature :beer:

**Comment by mattiarighi** [comment]
Agree with @valeriupredoi, it is definitely an interesting and useful feature, but as agreed upon at the workshop, we should focus on the high priority issues until the papers are out.

**Comment by ledm** [comment]
A climatology function by itself was requested today at the NCEO tutorial. TBH, I'm surprised it wasn't there already!

**Comment by zklaus** [comment]
Good idea @ledm! Is there an issue for that already?

**Comment by ledm** [comment]
Not only is there an issue for it, #221, there's already a solution for it! See @jvegasbsc's [comment](https://github.com/ESMValGroup/ESMValCore/issues/221#issuecomment-527548317).

**Comment by zklaus** [comment]
Great! I was always a bit afraid of the complexities imposed on climatological time axes by CF. Glad to hear it being addressed. :+1:

**Comment by jvegasbsc** [comment]
One comment: for now the anomalies are computed using as a reference the whole period of the dataset. it is impossible to choose another period or dataset as the reference.

Adding the option to choose the reference period is trivial (and by extension the fixed point). Using another dataset climatology as a reference is not.

By the way, we can complicate this as much as we want. A user requested to me:
- Compute anomalies for each dataset (full period as a reference)
- Reconstruct the field by adding the *reference_dataset* climatology

> complexities imposed on climatological time axes by CF.

Working only with projections and observations / reconstructions is not to bad. It gets far worse when working with (sub)seasonal predictions

**Comment by zklaus** [comment]
I was mostly thinking of [CF Section 7.4](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#climatological-statistics), that is climatological bounds on the time axis and extended `cell_methods`.

**Comment by schlunma** [comment]
To resurrect this very old issue:

To facilitate native model evaluation I think it might be helpful to implement a `bias` preprocessor, i.e. a simple subtraction of a reference dataset from other datasets. This would allow to plot bias plots with the generic output plotter from ESMValGroup/ESMValTool#2184.

Here are my thoughts on the implementation:

- Implement the preprocessor as new [`MULTI_MODEL_FUNCTION`](https://github.com/ESMValGroup/ESMValCore/blob/e4d61adfb14e3a3995abe2eb869d5f1781053416/esmvalcore/preprocessor/__init__.py#L193-L197) to ensure that the entire preprocessing chain is applied to all datasets before calculating the bias.
- Use the facet `reference_for_bias: true` for a given dataset to specify the reference dataset in the recipe. This needs to be given for exactly one dataset of the input products.
- Implement an absolute and a relative bias (using the keyword `bias_type`).

Any further thoughts on this @ESMValGroup/esmvaltool-coreteam before I start the implementation?

**Comment by axel-lauer** [comment]
> To facilitate native model evaluation I think it might be helpful to implement a `bias` preprocessor, i.e. a simple subtraction of a reference dataset from other datasets. This would allow to plot bias plots with the generic output plotter from [ESMValGroup/ESMValTool#2184](https://github.com/ESMValGroup/ESMValTool/pull/2184).

I am not sure I fully understand the additional benefit of implementing this in a preprocessor rather than having this done by a simple diagnostic (since this only works if both datasets are on the same grid anyways). I would think that handling this in a diagnostic might allow for greater flexibility (thinking e.g. about thresholds for minimum values for which calculation of a relative bias starts making sense, handling of zeros, etc.).

But that's just a thought. If you think such a new preprocessor is needed, then please go ahead.

**Comment by schlunma** [comment]
I also thought about simply using a diagnostic (actually I already implemented this, not only once), but I think adding this to the preprocessor is the cleaner way to do it and might be also interesting for new users (I remember that a user already asked for this functionality, can't remember the issue though). Ensuring that all datasets are on the same grid shouldn't be a problem with the `regrid` preprocessor (similar to `multi_model_statistics`).

Thresholds for minimum values can be added with the existing masking preprocessors, and the handling of zeros can be configured with an optional argument that I will add. How does that sound @axel-lauer ?

**Comment by axel-lauer** [comment]
Sounds good, I just wasn't completely sure this would be worth the effort. But as I said, please go for it.
