### ISSUE TITLE
Test multimodel for sample data fails with Runtime error

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1203]
see [test](https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore/5161/workflows/4a7017f9-56a6-4e11-bb83-9c5b16491112/jobs/24577) - the problem is that re-adding the files is barred by `.gitignore` since that ignores any `.nc` files, one can always force that but I reckon this is not quite an elegant implement

**Comment by stefsmeets** [comment]
Why am I assigned to this?

**Comment by stefsmeets** [comment]
Seems to me like you deleted the old reference data, committed the deletion, and then didn't re-add the files. Since the files are already tracked in git, they should show up as changed.

+1 for assigning @Peter9192 😅

**Comment by valeriupredoi** [comment]
I did exactly that but still we should be able to recreate those without stepping on git toes and don't have the CI belching Runtime errors, anyways problem solved now, but I'd replace that Runtime error with a warning, what say you @Peter9192 :beer:

**Comment by stefsmeets** [comment]
It seems to me that the runtime error is doing it's job, it's letting you know that the reference data are missing (and thus newly generated). Do you think you would been clearer if a warning was raised instead?

**Comment by valeriupredoi** [comment]
I just don't think raising an error (of any type) is useful, if those files get (re-)created anyway why break a test for it?

**Comment by stefsmeets** [comment]
The tests are broken by deleting the reference data. By just issuing a warning, the tests would always pass (whether the reference data are there or not). That's why the tests require a double pass to ensure that the tests pass with the newly generated data.

**Comment by Peter9192** [comment]
Hmm I see how the error is confusing, but I also agree with Stef that it doesn't make sense for the tests to pass if they just regenerate the data (but not actually test anything). Maybe a clearer error message would help?

**Comment by stefsmeets** [comment]
> Maybe a clearer error message would help?

When I wrote these tests, I added some info about how it works in the docstring for the test (this seemed like the most appropriate place to me):
https://github.com/ESMValGroup/ESMValCore/blob/e573b5d93dc350afd7f36264fd1e6026b349e65f/tests/sample_data/multimodel_statistics/test_multimodel.py#L190

Would it help if that was moved or copied to the error message?

**Comment by Peter9192** [comment]
I like that! Would that be clear for you as well @valeriupredoi ?

**Comment by valeriupredoi** [comment]
not quite - I want something like this https://github.com/ESMValGroup/ESMValCore/pull/1205 - don't throw any exceptions, just run seamlessly and create the files if they're not there. This is good for the automated testing environment, as we re-activate tests we will re-add the reference data files. Regression tests should test validity of results only and not file existence I know I'm being nit picky but I am trying to avoid any automated testing possible fails

**Comment by valeriupredoi** [comment]
another thing I noticed is that the reference data, if not existent in the form of the netCDF files, is constructed using the current version of the MM module - this is a bit of a chicken and egg problem, ideally we'd want to test against a reference dataset constructed with the latest stable release, so really - create those files once per release

**Comment by stefsmeets** [comment]
@valeriupredoi I don't understand anymore what you are trying to achieve. The fact that the reference data cannot be found should always result in a fail. 

The tests try help you by generating data that you may possibly want to use for the reference data, so that they can easily be added if you wanted. You are, of course, free to generate/add your own reference data if you prefer. You could argue that it is not better to have a separate script for this. It still remains that the fact that this caused a fail in the test, shows exactly why the mechanic that is in place works. The test could not find the reference data, and therefore it crashed the test.

**Comment by valeriupredoi** [comment]
yeah agreed - am thinking a little too much ahead and am not doing it proper in code (at the moment) - just gonna close this and revisit at some point, there's a few other things that are more stringent now - this is a bit of an egg deodorant case I am yapping about :grin:
