### ISSUE TITLE
Readthedocs webhook not working

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#121]
The documentation on readthedocs is not building automatically when we change things here. @mattiarighi can you please have a look at it? Because I don't have the required permissions on the GitHub repository. Instructions can be found here: https://docs.readthedocs.io/en/stable/webhooks.html

If everything works as expected, updating the `development` or `docu_join` branches should automatically trigger a build of the documentation on readthedocs, you can see current and past builds here: https://readthedocs.org/projects/esmvalcore/builds/

**Comment by mattiarighi** [comment]
Can you try now?

**Comment by bouweandela** [comment]
I just pushed a commit to the `docu_join` branch, but see no build appearing here: https://readthedocs.org/projects/esmvalcore/builds/

The last build is more than an hour ago..

**Comment by mattiarighi** [comment]
Now should be correct. This is how the Webhooks section on the GitHub settings of the project looks like:

https://github.com/organizations/ESMValGroup/settings/hooks

**Comment by bouweandela** [comment]
Yes, it works! Thanks.
