### ISSUE TITLE
Problem with new multi-model statistics and variables on hybrid levels

### ISSUE THREAD

**Issue by axel-lauer** [ESMValGroup/ESMValCore#1222]
Variables on hybrid vertical levels (e.g. clw) have to be converted to pressure or height levels to be able to be processed by some diagnostics and to be able to calculate meaningful multi-model statistics across different models. For this conversion, some models provide an auxiliary coordinate 'p0'. Calculating the multi-model mean over such datasets converted to pressure or height levels fails because 'p0' is kept after converting the vertical levels but (as expected) not identical in all models:

```
iris.exceptions.MergeError: failed to merge into a single cube.
  Coordinates in cube.aux_coords (scalar) differ: p0.
```

p0 contains no useful information any more after vertical coordinate transformation has been done. Yet, this results in a failure to calculate the multi-model mean over such 3-dim variables (e.g. 3-dim cloud variables).

This issue has been introduced with the new multi-model statistics (https://github.com/ESMValGroup/ESMValCore/pull/1150) and can be reproduced with the following example recipe: [recipe_testp0.yml.txt](https://github.com/ESMValGroup/ESMValTool/files/6807388/recipe_testp0.yml.txt)

**Comment by zklaus** [comment]
Thanks for reporting this issue, @axel-lauer. Is there a recipe in ESMValTool that is impacted by this?

**Comment by axel-lauer** [comment]
As far as I know, this issue affects recipes under development only.

**Comment by zklaus** [comment]
Ok, in that case I will target 2.4.0 here.

**Comment by valeriupredoi** [comment]
do we have any recipes that have made it to `main` @axel-lauer - if not, we can bump this to 2.5.0 :grin:

**Comment by axel-lauer** [comment]
I don't think we have anything in main yet, so postponing this until v2.5 is fine but we shouldn't forget about it.

**Comment by axel-lauer** [comment]
Further investigation of this problem showed that in addition to auxiliary coordinate `p0`, also presence of `ptop` can cause the same problems and needs to be removed in order to be able to calculate multi-model statistics (again). A fix in `_combine` (esmvalcore/preprocessor/_multimodel.py) could look like this:

```
        for auxcoord in cube.aux_coords:
            if (auxcoord.var_name == 'p0' or auxcoord.var_name == 'ptop'):
                cube.remove_coord(auxcoord)
```

In addition to this, `add_plev_from_altitude` and `add_altitude_from_plev` in esmvalcore/cmor/_fixes/shared.py need to be modified in order to work properly by removing definition of `var_name` and of `long_name`, e.g. https://github.com/ESMValGroup/ESMValCore/commit/38c1c01033359a6f3d795f2d2b529f63ba6abef6

**Comment by schlunma** [comment]
Moving this to v2.6 since there is not open PR yet.
