### ISSUE TITLE
Link historical-ssp scenarios with different ensemble tags

### ISSUE THREAD

**Issue by ledm** [ESMValGroup/ESMValCore#1226]
Hi,

so I've just discovered (with @valeriupredoi) that UKESM has published linked historical-ssp??? scenarios where the historical and the ssp run have different ensemble numbers.

ie, the two datasets are linked:

```
- {dataset: UKESM1-0-LL, project: CMIP6, mip: Omon, exp: historical,     ensemble: r5i1p1f3, start_year: 1990, end_year: 2014, grid: gn}
- - {dataset: UKESM1-0-LL, project: CMIP6, mip: Omon, exp: ssp126,     ensemble:  r5i1p1f2, start_year: 2015, end_year: 2100, grid: gn}
```
(note  ensemble: **r5i1p1f3** and **r5i1p1f2**.)

So, we should be able to combine them into a single recipe dataset entry:
```
- {dataset: UKESM1-0-LL, project: CMIP6, mip: Omon, exp: [historical, ssp126],     ensemble: [r5i1p1f3, r5i1p1f2], start_year: 1990, end_year: 2100, grid: gn}
```
Is that possible somehow?

**Comment by valeriupredoi** [comment]
yes, see the [doc entry](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/recipe/overview.html) :grin:

**Comment by zklaus** [comment]
Seems this is already in. Closing for now, @ledm, if this does not work for you, please reopen and describe what goes wrong.
