### ISSUE TITLE
New regional regrid option fails with float inputs for target grid

### ISSUE THREAD

**Issue by Peter9192** [ESMValGroup/ESMValCore#1230]
Trying to use the new regional regrid option from #1034 with the following spec

```yaml
    regrid:
      scheme: linear
      lon_offset: true
      lat_offset: true
      target_grid:
          start_longitude: 3.75
          end_longitude: 11.75
          start_latitude: 46.25
          end_latitude: 52.25
          step_longitude: 0.5
          step_latitude: 0.5
```
fails for me with 

```
  File "/home/peter/ESMValCore/esmvalcore/preprocessor/_regrid.py", line 257, in get_points
    num = int((stop - start) // Decimal(str(step)))
TypeError: unsupported operand type(s) for //: 'float' and 'decimal.Decimal'
```

Initial discussion in https://github.com/ESMValGroup/ESMValCore/pull/1034

**Comment by stefsmeets** [comment]
Reason the decimal conversion is needed:
https://github.com/ESMValGroup/ESMValCore/pull/1034#issuecomment-796650877

**Comment by stefsmeets** [comment]
I wonder if this works:

`num = int(decimal.Decimal(stop - start) // Decimal(str(step)))`

instead of:

https://github.com/ESMValGroup/ESMValCore/blob/2a0bb11cb52df3ec4a485a16bf92356e04617b52/esmvalcore/preprocessor/_regrid.py#L257

**Comment by Peter9192** [comment]
seems it does

**Comment by Peter9192** [comment]
Although the resulting grid values are now: 

```
lat = 53.001, 52.501, 52.001, 51.501, 51.001, 50.501, 50.001, 49.501,
    49.001, 48.501, 48.001, 47.501, 47.001, 46.501, 46.001
```

not sure if that's what we want

**Comment by zklaus** [comment]
This might need more discussion to determine what is the desired behavior.

**Comment by stefsmeets** [comment]
@zklaus No further discussion is needed, see this comment from @Peter9192: https://github.com/ESMValGroup/ESMValCore/pull/1231#issuecomment-881286124
