### ISSUE TITLE
Running a recipe through the python API fails because of missing `extra_facets_dir`

### ISSUE THREAD

**Issue by Peter9192** [ESMValGroup/ESMValCore#1232]
```python
from esmvalcore.experimental import get_recipe
recipe = get_recipe('examples/recipe_python.yml')
recipe.run()
```

fails with

```
~/ESMValCore/esmvalcore/_recipe.py in _initialize_variables(self, raw_variable, raw_datasets)
   1154             required_keys.update({'start_year', 'end_year'})
   1155         for variable in variables:
-> 1156             _add_extra_facets(variable, self._cfg['extra_facets_dir'])
   1157             if 'institute' not in variable:
   1158                 institute = get_institutes(variable)

KeyError: 'extra_facets_dir'
```

Running the same recipe from the command line works fine.

**Comment by valeriupredoi** [comment]
that dir needs to be set in the config file, from the doc:
```markdown
Location of the extra facets files
----------------------------------
Extra facets files can be placed in several different places. When we use them
to support a particular use-case within the ESMValTool project, they will be
provided in the sub-folder `extra_facets` inside the package
`esmvalcore._config`. If they are used from the user side, they can be either
placed in `~/.esmvaltool/extra_facets` or in any other directory of the users
choosing. In that case this directory must be added to the `config-user.yml`
file under the `extra_facets_dir` setting, which can take a single directory or
a list of directories.
```

**Comment by zklaus** [comment]
Yes, so the issue, if I recall correctly, is that the Python API (i.e. the experimental future config API) uses the example config_user.yml as the repository of default values, whereas the current config system has a separate place for default values. It was decided to leave the `extra_facets_dir` out of the example `config_user.yml` so as not to confuse users unnecessarily.

Overall, I think it is a good idea to have a way of setting defaults that is not the example configuration for new users. With that in place, we could set the correct default and thus make the Python API working, while still keeping the example configuration lean for unsuspecting users.

One simple way to achieve this might be to just have a copy of the example config that only serves as defaults.

**Comment by stefsmeets** [comment]
> One simple way to achieve this might be to just have a copy of the example config that only serves as defaults.

I proposed this a while back while I was working on the experimental config, because I was worried the two implementations would diverge at some point. In anticipation of a default config file, it can be set here: https://github.com/ESMValGroup/ESMValCore/blob/2a0bb11cb52df3ec4a485a16bf92356e04617b52/esmvalcore/experimental/config/_config_object.py#L239

**Comment by zklaus** [comment]
Nice. So should we just duplicate the existing example in a new location and add the new key there? I think this would be sensible, and to be honest I was thinking about collecting all internal configuration files in one place like `esmvalcore/etc` or similar anyway.

But it would also be a somewhat big change with some chance of confusion in the future if we have to maintain two different `config-user.yml` files, so at a minimum I think we need to get the rest of the core devs on-board about this.
This means delays, so I wonder how critical you see this change for the release? An alternative fix would be to add the key to the current file for now and do the separation of default config and user example in the next release.

@bouweandela, how would you feel about having the `extra_facets` key in the `esmvalcore/config-user.yml` file in light of this?

**Comment by stefsmeets** [comment]
> But it would also be a somewhat big change with some chance of confusion in the future if we have to maintain two different `config-user.yml` files, so at a minimum I think we need to get the rest of the core devs on-board about this.

In my view it's far simpler to maintain two config files than two implementations. One will be a subset of the other, so you could add a test to ensure that the keys in `config-user.yml` are equivalent to what is in `config-default.yml`. The latter can serve as the `master` in this case. The config validators can be used to ensure that the input is valid.

The idea was that the experimental config will replace the current config at some point. So see this as a step to bring them closer together.

**Comment by zklaus** [comment]
Oh, I am absolutely in favour of having the two files. I just want to make sure that everyone who might add/remove/change an option in the future is aware of where that has to happen, and I think there are some questions that need to be addressed like:
- What should be names and locations of the two files? I always thought it would be good to name the example as such, i.e. `config-user.yml.example` or similar. I also think it could be good to collect all configuration files in one place.
- Where does the documentation need updating? Do we need to have a section in the developer docs that clearly states that for now you need to update defaults in two places?

Perhaps there are more questions. Hence, the need to have a bit of discussion and time for this.

**Comment by stefsmeets** [comment]
It's also an opportunity to pick up on some 'hidden defaults' set by the CLI: https://github.com/ESMValGroup/ESMValCore/blob/2a0bb11cb52df3ec4a485a16bf92356e04617b52/esmvalcore/_main.py#L307

**Comment by bouweandela** [comment]
> @bouweandela, how would you feel about having the extra_facets key in the esmvalcore/config-user.yml file in light of this?

Sure, that's fine.

> What should be names and locations of the two files? I always thought it would be good to name the example as such, i.e. config-user.yml.example or similar. I also think it could be good to collect all configuration files in one place.

They should probably be placed in [`esmvalcore/_config`](https://github.com/ESMValGroup/ESMValCore/tree/main/esmvalcore/_config) (at some point to be moved to `esmvalcore/config` when we integrate the experimental module into the main esmvalcore). We left config-developer.yml and config-user.yml one level up because we thought they might be easier to find there for users, but moving them to the _config subdirectory is probably fine if we make sure we update all documentation.

> Where does the documentation need updating? Do we need to have a section in the developer docs that clearly states that for now you need to update defaults in two places?

If a unit test is implemented that ensures the settings in the example are a subset of the default, as suggested by @stefsmeets above, I think there may be no need for further documentation.
