### ISSUE TITLE
CMIP3 uses "." as a separator for the time range part of the filename

### ISSUE THREAD

**Issue by zklaus** [ESMValGroup/ESMValCore#1245]
**Describe the bug**
CMIP3 doesn't follow the usual approach of separating components of the filename with `_` or `-`, but additionally uses also `.`, particularly for the time range part of the filename. This is no longer detected correctly since the update of the time range regex.

I think we can simply add `.` to the list of allowed characters for the `context` in https://github.com/ESMValGroup/ESMValCore/blob/d87679baa79de416b6e0c521f21be414fc1d936d/esmvalcore/_data_finder.py#L64.

@senesis, what do you think? @jvegasbsc, @bouweandela, do you have an opinion on the matter?

**Comment by valeriupredoi** [comment]
yup, sorry @zklaus am a bit late to the show, I was just worried that if we use `os.path.splitext` (and we do in `_io.py`) that'll be dumb and confuse the extension, but that's fine, I checked that and it's all good :+1:
