### ISSUE TITLE
Add link to figures and work directory on index.html

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#1254]
Hi! I recently used the bot for the first time and needed some help finding the output figures. Is the link to the figures something you could add to the output page? The output page looks really pretty btw.
"The figures are there: https://esmvaltool.cloud.dkrz.de/shared/esmvaltool/esmvalbot-output/pvcf_gmddraft-kr0c7llt/recipe_pv_capacity_factor_20210712_081803/plots/capacity_factor/main/
This really should be improved that this link is not given on the esmvalbot output page but one needs to put it together from its link and the main_log.txt"

_Originally posted by @Emmadd in https://github.com/ESMValGroup/ESMValTool/issues/1882#issuecomment-881294985_

**Comment by stefsmeets** [comment]
It should link the images if they are provided in the provenance. Could this be an issue with the recipe? Did the authors declare the path to the output png as part of the provenance?

**Comment by bouweandela** [comment]
Indeed this is only useful if the provenance is not quite right yet. Or maybe if you would want to download all figures?

**Comment by stefsmeets** [comment]
Made a small pr with what this could look like. I don't have much time to test/debug it, so feel free to hi-jack in case this is useful, or otherwise close 😁

**Comment by Emmadd** [comment]
I think the png path was included in the provenance. @katjaweigel should know for sure

  # Set provenance for output files
   xprov <- list(
     ancestors = list(
       fullpath_filenames[i]
     ),
     authors = list(
       "cionni_irene"
     ),
     projects = list("crescendo"),
     caption = title,
     statistics = list("other"),
     realms = list("atmos"),
     themes = list("phys"),
     plot_file = filepng
   )

   provenance[[filencdf]] <- xprov

**Comment by bouweandela** [comment]
Ok, if that is the problem, this is partly my fault. Recording provenance for figures like this never quite worked as it should and we intend to completely drop support for it (it is already buggy). The correct way to do it would be
```R
xprov <- list(
    ancestors = list(
        fullpath_filenames[i]
    ),
    authors = list(
        "cionni_irene"
    ),
    projects = list("crescendo"),
    caption = title,
    statistics = list("other"),
    realms = list("atmos"),
    themes = list("phys"),
)
provenance[[filepng]] <- xprov
provenance[[filencdf]] <- xprov
```

**Comment by katjaweigel** [comment]
Ok, good to know, then I'll change that in the PR #2153 (when Mistral is working again)
