### ISSUE TITLE
Case to fully replace CircleCI tests with Github Actions (and retire CircleCI tests)

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1285]
This is a very tentative issue - I am not saying we should do that, but I reckon there are a few solid reasons why we should:

- Circle doesn't offer support for multiple OS's and Python versions (unless you pay)
- Circle has a max resident memory per process per machine of 4GB vs 8GB for GA
- I have noticed a **lot** more segfaults (our famous unexplained segfaluts even for single-thread runs) on Circle than on GA - possible Red Hat (Circle) vs Ubuntu (GA)
- There is serious overlap between the Circle and GA tests we have - redundancy is good but maybe we can just retire bits that are well tested on one CI platform
- Circle is slow at times, loading and navigating through test results/artifacts etc needs login and is sluggish (noticed this only recently)
- Runtime limit is 1h for Circle, 5h for GA (this is not to say that we should be happy with a test that takes 3-5h to run, though!)

@bouweandela @zklaus @jvegasbsc what say you fellas?

**Comment by jvegasbsc** [comment]
I prefer to have everything in one platform if possible. Redundancy is nice, but a simplified workflow will be easier to maintain and more of us will be able to fix whatever is needed.

**Comment by bouweandela** [comment]
My take on this would be don't fix it if it ain't broken, there is enough broken stuff that needs fixing. I agree that it's kind of nice to have everything in once place though.

Some of the reasons for changing listed above are not quite true:
- Indeed CircleCI doesn't offer free support for MacOS and Windows, but you can run any Docker container on it, something I believe you cannot do on GitHub Actions, so it does support all Linux and Python versions.
- A limit of 4 GB and 1 hour should be sufficient for running unit tests. Only conda is extremely compute hungry, but I believe we're planning to retire that anyway in favour of mamba and builds on conda-forge?
- GitHub can also be very slow and unresponsive and also requires a login

**Comment by valeriupredoi** [comment]
good points all round, gents! I propose we discuss this at the (hopefully) upcoming workshop on ESMVal testing that @zklaus was proposing and I was supporting; in fact, I am going to create a label for this and start labelling issues relevant to that wkshop :hammer_and_wrench:

**Comment by valeriupredoi** [comment]
this has been discussed-ish as far as I remember, and the conclusion was "horses run fast", am closing since there are no immediate plans to retire/replace Circle just yet
