### ISSUE TITLE
Should we list all found input files?

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#1287]
When running a recipe with a relatively large number of models such as [recipe_impact.yml](https://github.com/ESMValGroup/ESMValTool/blob/1fff5e4178f0c7ebc8d3fc2e224a027741ee0c1b/esmvaltool/recipes/recipe_impact.yml), the number of log messages printed to the screen becomes very large (over 25000 lines of log messages in this case). Do we really want to print the names of all input files to the screen?

@ESMValGroup/esmvaltool-developmentteam Anyone an opinion? Are these log messages helpful or is the tool making too much noise?

**Comment by Peter9192** [comment]
I'd prefer less noise 👍

**Comment by valeriupredoi** [comment]
good question - who reads that? It'd be good for debugging though, but only for debugging, I'd still list them if eg the number of models is <10 - this comes in handy when people are new to the tool and just want to see what it's doing and how it's doing without running in debug mode

**Comment by jvegasbsc** [comment]
Is not only a matter of the number of models. I have been using ERA5 native on Jasmin, and some variables are stored in hourly files. The log becomes so large that is nearly impossible to browse

**Comment by valeriupredoi** [comment]
> Is not only a matter of the number of models. I have been using ERA5 native on Jasmin, and some variables are stored in hourly files. The log becomes so large that is nearly impossible to browse

very good point! Even the daily data is like the end credits from Avatar

**Comment by malininae** [comment]
Just a piece of mind, for AR6 figures, I used these log files and the provided there information on all the input files to create the requested by IPCC metadata files, and I found it extra handy, in particular on Jasmin, where the versions are noted a bit odd and provenance is not of a big help. That being said, it's a very unique task, but answering the question from @valeriupredoi , I read and actively used them. Though I'm not sure what would be the best move going forward, for me just the log file was enough, since I needed only the path. Maybe, as a though, you can write them out only in debug or something?

**Comment by bouweandela** [comment]
The proposal here would be to change the log level of these messages from INFO to DEBUG, so the tool would still save the filenames of all the input files in the file run/main_log_debug.txt, but no longer display them on the screen or save them in run/main_log.txt.

> provenance is not of a big help. ..  since I needed only the path.

Actually, the provenance is much more suitable for finding out which files were used to create which figure, because it is saved per output file instead of everything bunched together in one file. However, I can imagine that it might not be easy to use because of the format. Maybe we could add a small helper tool to extract just the names of the input files from the *_provenance.xml files.

**Comment by valeriupredoi** [comment]
> Maybe we could add a small helper tool to extract just the names of the input files from the *_provenance.xml files.

yesh, I likes that! Or, we can write a separate log file with only the files used from the data finder stdout?

**Comment by jvegasbsc** [comment]
> yesh, I likes that! Or, we can write a separate log file with only the files used from the data finder stdout?

No more files with duplicated info, please! The output structure is complex enough to leave new users guessing already.

The helper tool for the provenance is a good idea, my only doubt if it should be part of ESMValTool or a contribution to the provenance framework (I don't know enough about the technical implementation of the provenance to have an opinion on this)

**Comment by valeriupredoi** [comment]
I like me log files, man, have you seen Apollo 13? - log files and socks saved those three astronauts :laughing: No but yeah, I agree, too much stuff for users

**Comment by bouweandela** [comment]
> The helper tool for the provenance is a good idea, my only doubt if it should be part of ESMValTool or a contribution to the provenance framework (I don't know enough about the technical implementation of the provenance to have an opinion on this)

This would be a tiny script that makes use of the [`prov`](https://prov.readthedocs.io/en/latest/) library. We could keep it in [esmvaltool/utils](https://github.com/ESMValGroup/ESMValTool/tree/main/esmvaltool/utils)

**Comment by bouweandela** [comment]
I have created a pull request to reduce the number of log messages shown on the screen here: #1296, please try it out if you're interested.
