### ISSUE TITLE
additional_datasets - Obs4MIPS `day of year` failure

### ISSUE THREAD

**Issue by ledm** [ESMValGroup/ESMValCore#131]
Hi,

I'm evaluating the CMIP5 sea surface temperature field, tos, using the Obs4MIPs dataset, `tos_ATSR_L3_ARC-v1.1.1_199701-201112.nc`. This dataset can be obtained [here](http://gws-access.ceda.ac.uk/public/esacci-sst/ARC-obs4mips/).

For an unknown reason, the preprocessor fails to calculate the `day_of_year` value and instead sets all values to `1`. Ie:
```
In [2]: nc01 = ncdfView('01_fix_metadata.nc')
In [3]: nc01('day_of_year')
Out[3]: 
array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
```

This occurs in the early stages of the preprocessor, between `00_load_cubes.nc` (which does not include the `day_of_year` field) and `01_fix_metadata.nc`, where it is broken. 

I can assume that might be fixable by setting a fix_metadata function for the additional dataset. How do I do that?

Thanks,

Lee

**Comment by bouweandela** [comment]
@ledm @valeriupredoi Any news on this?

**Comment by valeriupredoi** [comment]
`cf_units` is now at `2.1.1` so I think we good to close this

**Comment by mattiarighi** [comment]
@ledm ok to close?
