### ISSUE TITLE
Error "Requested fx variable 'areacello' not available" introduced by 2.3 update

### ISSUE THREAD

**Issue by Jon-Lillis** [ESMValGroup/ESMValCore#1312]
@Ehogan and I have been converting AutoAssess radiation budget scripts into an ESMValTool diagnostic, the branch for which can be found [here](https://github.com/ESMValGroup/ESMValTool/tree/radiation_budget_new_diagnostic). We’ve been developing against ESMValtool v2.2, but recently upgraded to v2.3 and are now encountering the following issue. 

Our radiation budget diagnostic runs correctly under ESMValTool 2.2, producing the output we expect, but fails under 2.3 with four instances of the error `Requested fx variable 'areacello' not available in any CMOR table for 'obs4mips'`, correlating to our use of four variables from the CERES-EBAF dataset which can be seen in the recipe linked below.

Is this expected behaviour? If so, is there a way to stop ESMValTool from looking for the fx variable since we've proved it isn't required by running the diagnostic under 2.2, or is this configuration option yet to be implemented?

We have reverted to 2.2 to finish development of the diagnostic, but we'll need to have it running in 2.3 before we submit a pull request. Any comments/feedback here would be greatly appreciated.

- [Radiation budget recipe](https://github.com/ESMValGroup/ESMValTool/blob/56d58e3689580677802065282ec86f7b1606c478/esmvaltool/recipes/recipe_radiation_budget.yml)
- [main_log_debug.txt](https://github.com/ESMValGroup/ESMValTool/files/7149546/main_log_debug.txt) for run under ESMValTool 2.2.
- [main_log_debug.txt](https://github.com/ESMValGroup/ESMValTool/files/7149547/main_log_debug.txt) for run under ESMValTool 2.3.

**Comment by valeriupredoi** [comment]
thanks @schlunma - was just about to transfer it, but I got distracted :beer:
