### ISSUE TITLE
Filepath of default config file is printed as 'None' in main_log

### ISSUE THREAD

**Issue by Jon-Lillis** [ESMValGroup/ESMValCore#1313]
When launching ESMValTool with a config file specified as an argument, the line 'Using config file path/to/config-user.yml' is printed correctly in the logs. When launching ESMValTool without specifying a config file (using the default file in ~/.esmvaltool/), the line 'Using config file None' is printed instead. 

When debugging during development, it would be useful to see at a glance exactly which config file is being used, even if it is in the default location.

[Link to Radiation Budget branch](https://github.com/ESMValGroup/ESMValTool/tree/radiation_budget_new_diagnostic)

- [Radiation Budget Recipe (in development)](https://github.com/ESMValGroup/ESMValTool/blob/56d58e3689580677802065282ec86f7b1606c478/esmvaltool/recipes/recipe_radiation_budget.yml)
- [main_log_debug.txt from run with default config location](https://github.com/ESMValGroup/ESMValTool/files/7149484/main_log_debug.txt)
- [main_log_debug.txt from run using the config argument](https://github.com/ESMValGroup/ESMValTool/files/7149483/main_log_debug.txt)

**Comment by valeriupredoi** [comment]
I think it's ok to close this since the feature is in the `main` development branch, @Jon-Lillis please reopen if need be :+1:
