### ISSUE TITLE
Add option to stop if cell area files are missing

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#1315]
_Originally posted by @ledm in https://github.com/ESMValGroup/ESMValCore/pull/1296#discussion_r707159092_

> I don't think we're calculating areas any more, but I would still argue that we shouldn't calculate it at all for CMIP6 models (Observations is a different and messier story).
> 
> Basically, because the Earth isn't perfectly round, an iris-calculated area in a regular grid may not match what was used at the model runtime. Different models can use represent the Earth using spherical or non-spherical globes, and that can make (albeit small) differences in area, even in the regular grid area.
> 
> I'm just arguing that I want the option for ESMValTool to stop if FX files are absent, and not to find out about their absence in an obscure error message after half an hour of preprocessing.

**Comment by bouweandela** [comment]
Note that there is a WARNING message that the fx files are missing already issued when parsing the recipe, there is no need to do half an hour of preprocessing before hearing about this from the tool. Currently, the message looks like this:
> WARNING [19025] Missing data for fx variable areacella of dataset FGOALS-s2

**Comment by valeriupredoi** [comment]
bit of a duplicate of https://github.com/ESMValGroup/ESMValCore/issues/1282 so I guess we can close either one

**Comment by bouweandela** [comment]
Let's close this one
