### ISSUE TITLE
Replace requests with httpx

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1317]
This https://github.com/encode/httpx looks very solid. I think we can probably look at its use by us too, replacing `requests` - am not sure how much we'd gain terms of performance/extended functionality since I'm not all too familiar with the bits that use `requests` but am putting this forward for boffin discussion :grin: @bouweandela @jvegasbsc @zklaus are the boffins in this case :nerd_face:

**Comment by zklaus** [comment]
What problem with `requests` is this solving?

**Comment by valeriupredoi** [comment]
like I said, this issue is for those who know if/what problems are with `requests` and see if those will be solved/improved by using `httpx` - I don't know much about either, but it seems `httpx` is the bee's knees these days

**Comment by zklaus** [comment]
Sure, but as long as we don't have any problems with `requests`, it seems a waste of resources to look at it. Resources that could be spent on closing 2.4.0 PRs instead. See also https://www.confessionsofadataguy.com/httpx-vs-requests-in-python-performance-and-other-musings/ for a comparison of the packages. This guys conclusion:

> After reading the rest of the httpx documentation I didn’t really see the point of doing more work exploring it’s features. I mentioned above the only “nice” feature I can appreciate about this new http package is the sync and async support in one. Calling WSGI apps directly seems like something I will never care about.
>
> It does seem like someone took their time to create this package, the documentation is nice, but I just don’t really see the point of switching. One could always test the async performance of httpx vs aiohttp, but I think I will just stick with the tried and true requests.

I'll close this for now; if we need to revisit `requests` we'll know to look at httpx.

**Comment by valeriupredoi** [comment]
good find @zklaus :+1: I think it's fine to close. Yes, let's focus on 2.4.0 - plenty of guff there :grin:
