### ISSUE TITLE
Add a title to recipes and maybe for diagnostics

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#1319]
For generating the output html page of a recipe, it would be nice to have titles for the recipe and for the diagnostics. At the moment we use the name of the recipe file for the recipe title and the name of the task for the diagnostic output, but this does not look very nice. See for example [this](https://esmvaltool.cloud.dkrz.de/shared/esmvaltool/v2.3.0-test/recipe_carvalhais14nat_20210701_161251/) run. The title of the page there is "Recipe carvalhais14nat" and the title of the first diagnostic is "diag_land_carbon_turnover/global_turnover_time", both not very human readable.

@ESMValGroup/esmvaltool-coreteam Anyone an opinion on whether or not this would be a desirable feature?

**Comment by zklaus** [comment]
Sounds good to me. This can be an additional key in the recipe. Or rather two: One for the recipe as a whole and one for the diagnostic.

**Comment by axel-lauer** [comment]
Just as an idea, for the recipes we could use the same titles used in the documentation of the recipe (from the user's guide) or alternatively the global key "documentation:description". For individual diagnostics, we could simply use the filename of the diagnostic script + the info from the key "description" (from the recipe). This way, all we need would be there already.

**Comment by valeriupredoi** [comment]
I like it! Given my tendency to write long and arduous GH issue titles and posts, I shall proceed to writing three- or four-liner titles for recipes and diags. Just kidding :laughing: How do you want to approach this - we do it or we ask the diag devs to add them to their recipes?

**Comment by zklaus** [comment]
First, we need the facilities, i.e. decide on the keys and implement some functionality for their interpretation and linting.
Then we should ask the recipe maintainers to update their respective recipes. It would be good to strengthen that role anyways.

**Comment by jvegasbsc** [comment]
In fact, for diagnostics we are only showing them at the script level. We may want to show the diagnostic title and the description before, at least for those that have more than one script

**Comment by bouweandela** [comment]
I'll try to come up with some infrastructure for this, because we have a task for this in IS-ENES3.

**Comment by bouweandela** [comment]
The pull request linked above is now ready for review, if anyone would like to give it a try?
