### ISSUE TITLE
Tests failing on Circle CI and Github Actions

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1322]
A number of tests fail - Circle is using iris 3.1.0 and is failing the tests that use `iris.fileformats` and GA tests fail with:
```
ERROR: Could not find a version that satisfies the requirement esmpy!=8.1.0 (from esmvalcore[develop]) (from versions: none)
ERROR: No matching distribution found for esmpy!=8.1.0
```

**Comment by valeriupredoi** [comment]
@zklaus I'll fix those now, no worries for you, just heads up for release coz we'll need whatever fixes I cook up :hamburger:

**Comment by zklaus** [comment]
Cheers, @valeriupredoi. I think you are aware that there is already a fix for the iris.fileformats thing in ESMValGroup/ESMValCore#1217.

If you do attack them here specifically, I would probably prefer a solution along the lines of my comment https://github.com/ESMValGroup/ESMValCore/pull/1217#discussion_r711982570

**Comment by zklaus** [comment]
Sure. Should we just take it with #1217 then? Perhaps we can push that through and get all its goodness, including the fileformat fix.

**Comment by valeriupredoi** [comment]
there are a lot of other test files that need the explicit import of `iris.fileformats` than in #1217 sadly

**Comment by zklaus** [comment]
Ah, gotcha. I only saw 4 tests failing in not so many files and assumed #1217 would take care of them. Go ahead.

**Comment by valeriupredoi** [comment]
this served its puprose so it's gonna go in the shadows, cheers @zklaus and @bouweandela - but we have a new one :grin: https://github.com/ESMValGroup/ESMValCore/issues/1329
