### ISSUE TITLE
Highlights for v2.4.0 release

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1342]
I propose we highlight two of the many changes we include in v2.4.0 (when we write the Changelog, we include these two in the Highlights section, like we did before):
 - https://github.com/ESMValGroup/ESMValCore/pull/1217
 - https://github.com/ESMValGroup/ESMValCore/pull/1321
These are two awesome functionalities that more than deserve a Highlight status, well done @bouweandela - you almost won an Oscar :medal_military: :grin:

**Comment by zklaus** [comment]
I really like the idea and those two are good candidates. There might be others, for example #1133 ? Other ideas, opinions, @ESMValGroup/esmvaltool-coreteam ?

**Comment by valeriupredoi** [comment]
good call, Tina! :beer:
