### ISSUE TITLE
Availability of CMOR tables

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#135]
In PR #195 the option to define custom CMOR tables in the `config-developer.yml` file was introduced. This raises the question of how to retrieve such tables and what happens if you try to run the tool but do not have the CMOR tables matching your data. It would be best to install such tables as dependencies, or include them with the tool, or add some other automatic mechanism for retrieving them.

**Comment by valeriupredoi** [comment]
ideally this should be talked with the CMOR folks, I agree with Javi we shouldn't include all those tables, our tool is **not** a CMORization tool :beer:
