### ISSUE TITLE
Add more tests to test DRS paths in `config-developer.yml`

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1353]
I just merged https://github.com/ESMValGroup/ESMValCore/pull/1304 because it was ready bar a test for its specific DRS implementation, before merging it I had realized that that PR is just a drop in an ocean of missing tests for DRS variations (no native6, EMAC, obs4MIPs etc etc), so we have to add tests to cover those. Yeah, a drop in an ocean of missing tests, deal with it :grin: :ocean:

**Comment by schlunma** [comment]
Moving this to v2.6 since there is not open PR yet.

**Comment by valeriupredoi** [comment]
Thanks to #1490 we now have IPSLCM tested, but we are still missing a few others, so keeping this for 2.6 is a good idea :+1:
