### ISSUE TITLE
Remove our own-grown conda package

### ISSUE THREAD

**Issue by zklaus** [ESMValGroup/ESMValCore#1362]
With conda packaging on conda-forge, we can probably remove `package` from our repo.

**Comment by valeriupredoi** [comment]
how about we use it as a backup of the conda forge recipe just in case things go south badly there?

**Comment by zklaus** [comment]
Well, in that case, we have to maintain and test it continuously. And it would still rely on conda-forge working in general since that's needed for all the dependencies. In my book, the cost-benefit analysis tips to removing it.

But I am happy to put it to a vote?
