### ISSUE TITLE
Change to release procedure: version number in main

### ISSUE THREAD

**Issue by zklaus** [ESMValGroup/ESMValCore#1364]
I'd like to propose that we handle the version number separately in the main and release branches, respectively.
More specifically, my idea is to set the version number in `main` to `...dev` for the next planned release at the time we do the release branch.

For example, now we create the release branch `v2.4.x` and that should get the version number `2.4.0rc1` for the first release candidate. At the same time the `main` branch would get `2.5.dev1`. Note that this perhaps slightly awkward format for the version is carefully chosen to be compatible with both [PEP440](https://www.python.org/dev/peps/pep-0440/#developmental-releases) and [conda](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/pkg-specs.html#supported-version-strings).

Any thoughts, @ESMValGroup/technical-lead-development-team ?

**Comment by bouweandela** [comment]
It could be interesting to look at automating this a bit, see discussion in https://github.com/ESMValGroup/ESMValTool/discussions/2299
