### ISSUE TITLE
test_get_input_filelist() doesn't handle extra_facets

### ISSUE THREAD

**Issue by senesis** [ESMValGroup/ESMValCore#1377]
While designing a new entry in [data_finder.yml](https://github.com/ESMValGroup/ESMValCore/blob/main/tests/integration/data_finder.yml) for testing access to IPSL-CM native format data files (which is called for by #1353), I realized that the (quite new) 'extra_facets' feature is not yet handled by test_get_input_filelist() in [test_data_finder.py](https://github.com/ESMValGroup/ESMValCore/blob/main/tests/integration/test_data_finder.py). 

Here is a proposal for a changed code (which I tested) :

```
def test_get_input_filelist(root, cfg):
    """Test retrieving input filelist."""
    create_tree(root, cfg.get('available_files'),
                cfg.get('available_symlinks'))

    # Find files
    variable = cfg['variable']
    rootpath = {variable['project']: [root]}
    drs = {variable['project']: cfg['drs']}
    extra_facets = get_extra_facets(variable["project"], variable["dataset"],
                                    variable["mip"], variable["short_name"],
                                    tuple())
    variable.update(extra_facets)
    (input_filelist, dirnames,
     filenames) = get_input_filelist(variable, rootpath, drs)
     ........

```

I refrained from turning that proposal to a PR in order to favor the discussion on alternate solutions.

I do no think that bypassing the extra_facet feature in this test routine (which would be quite easy by populating the variable entry in data_finder.yml with the values for extra_facets) is a better way.

**Comment by senesis** [comment]
@ESMValGroup/esmvaltool-coreteam : any interest for this topic ?

**Comment by zklaus** [comment]
@senesis, thanks for this. Would you mind turning it into a PR at this point? I appreciate the openness to other solutions, but it will be much easier to see the differences. Also, so far, this looks good to me.

**Comment by bouweandela** [comment]
The test was designed to check that given the available facets, the function `get_input_filelist` is able to find the files. You can just specify the required (extra) facets in `variable` data_finder.yml. I think that adding a call to `get_extra_facets` breaks the modularity of the code: we do not try to reproduce the entire process of going from the facets as defined in the recipe to the facets required to find the files here. There are other tests for that, e.g. those in tests/integration/test_recipe.py.

**Comment by schlunma** [comment]
@senesis Do you think you can turn this into a pull request soon? If it doesn't involve a lot of changes I think we can still get this into v2.5.

**Comment by senesis** [comment]
It depends what soon means.

Le 4 février 2022 12:27:53 GMT+01:00, Manuel Schlund ***@***.***> a écrit :
***@***.*** Do you think you can turn this into a pull request soon? If it doesn't involve a lot of changes I think we can still get this into v2.5.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ESMValGroup/ESMValCore/issues/1377#issuecomment-1029902345
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
--
Stéphane Sénési

**Comment by schlunma** [comment]
The release is scheduled for 14 February, so next week would be great.

**Comment by zklaus** [comment]
Well, if we follow @bouweandela's reasoning, we don't need to do these changes. So @senesis, what do you think about that? If you agree that this test tests what it tests and any further tests should be done separately or are already covered, we can just close this issue. If not, you might want to elaborate why *this* test must test the extra_facets.

**Comment by senesis** [comment]
I agree that, if one agree with the point of view of @bouweandela , providing extra facets in data_finder.yml is the right way. This may however seems tricky, but I am not the expert here.
