### ISSUE TITLE
Provenance files do not have the default file permissions

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#1378]
The provenance files are created with a read/write for the user only mask instead of with default permissions, for example:
```
$ ll ~/esmvaltool_output/recipe_python_20211022_150442/plots/map/script1/png/
total 100
-rw-rw-r-- 1 bandela bandela   798 Oct 22 17:04 CMIP5_CanESM2_Amon_historical_r1i1p1_tas_2000-2000_citation.bibtex
-rw-rw-r-- 1 bandela bandela   135 Oct 22 17:04 CMIP5_CanESM2_Amon_historical_r1i1p1_tas_2000-2000_data_citation_info.txt
-rw-rw-r-- 1 bandela bandela 25359 Oct 22 17:04 CMIP5_CanESM2_Amon_historical_r1i1p1_tas_2000-2000.png
-rw------- 1 bandela bandela 14012 Oct 22 17:04 CMIP5_CanESM2_Amon_historical_r1i1p1_tas_2000-2000_provenance.xml
```
where the user mask is set as:
```
$ umask -S
u=rwx,g=rwx,o=rx
```

This may lead to problems. For example, at the moment the provenance files in ESMValBot output cannot be read.

**Comment by valeriupredoi** [comment]
can this cause this https://github.com/ESMValGroup/ESMValCore/issues/1383 too? Problem is, the issue with permissions doesn't happen all the time in the case of @ledm - it's frequent, but not 100% reproducible

**Comment by zklaus** [comment]
No. Completely unrelated.
