### ISSUE TITLE
Case sensitivity in data finder?

### ISSUE THREAD

**Issue by bettina-gier** [ESMValGroup/ESMValCore#1379]
Just came across this issue when testing recipe_gier2020bg.yml:

The data finder doesn't find the co2 esmrcp85 data on mistral for FIO-ESM, although it is available. This is due to there being uppercase and lowercase folders for this CMIP5 model on mistral containing different data

esmhistorical co2:
/mnt/lustre01/work/kd0956/CMIP5/data/cmip5/output1/FIO/FIO-ESM/esmHistorical/mon/atmos/Amon/r1i1p1/v20130424/co2/co2_Amon_FIO-ESM_esmHistorical_r1i1p1_185001-200512.nc
esmrcp85 co2:
/mnt/lustre01/work/kd0956/CMIP5/data/cmip5/output1/FIO/fio-esm/esmrcp85/mon/atmos/Amon/r1i1p1/v20130424/co2/co2_Amon_FIO-ESM_esmrcp85_r1i1p1_200601-210012.nc

Now I don't know if this issue occurs in other models (I only recall finding it weird that the CMIP5 inmcm4 model was always used with lower letters while everything else is written in caps). Do we want to support case insensitive searching in these cases or just ignore and do workarounds like symbolic links since these seem to be outliers?

**Comment by valeriupredoi** [comment]
@bettina-gier I don't understand why you are thinking this is a char case issue - if it's not finding `esmrcp85` data it means it either doesn't know it needs that data or there is a problem with the path it's searching in, does it look for eg `esmRCP85` or smth like this to indicate it's changing the case? Can you pls run in `debug` and see where it's actually looking for the data before calling it quits and saying it can't find it? :beer:

**Comment by bettina-gier** [comment]
If you look closely it's because the esmrcp85 co2 data is in the "fio-esm" folder instead of the "FIO-ESM" folder, it's a mistral problem that there are two model folders under the institute folder for the same model - one uppercase as it should be and one lowercase and they have different data inside. bold italiced the path
esmhistorical co2:
/mnt/lustre01/work/kd0956/CMIP5/data/cmip5/output1/FIO/_**FIO-ESM**_/esmHistorical/mon/atmos/Amon/r1i1p1/v20130424/co2/co2_Amon_FIO-ESM_esmHistorical_r1i1p1_185001-200512.nc
esmrcp85 co2:
/mnt/lustre01/work/kd0956/CMIP5/data/cmip5/output1/FIO/_**fio-esm**_/esmrcp85/mon/atmos/Amon/r1i1p1/v20130424/co2/co2_Amon_FIO-ESM_esmrcp85_r1i1p1_200601-210012.nc

**Comment by zklaus** [comment]
I think this is a problem on mistral. I would let them know and I don't think we should introduce a work-around in our code.

**Comment by valeriupredoi** [comment]
@bettina-gier cheers, am blind :eyeglasses: Right! so Klaus is right, this is a non-standard issue (it should actually be reported to the Mistral guys) :beer:

**Comment by bettina-gier** [comment]
Alright!
