### ISSUE TITLE
[CEDA/JASMIN] Curious netCDF4/HDF5 (Python backends) errors on certain files

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1383]
Here's a curious case that we've seen before: some netCDF file gets written to disk but for some reason netCDF4/hdf5 has issues opening it; you move this file to a different location, and voila all works well. We thought this was more of a curiosity, but @ledm  has been seeing this more and more frequently as of late. Here's a toy example you can run:

```python
from netCDF4 import Dataset

lee_filename = "/gws/nopw/j04/ukesm/ldemora/ESMValTool_output/recipe_ocean_ai_mpa_mld_20211102_142314/preproc/diag_timeseries_3/mlotst_map_hist/CMIP6_HadGEM3-GC31-MM_Omon_historical_r4i1p1f3_mlotst_gn_2000-2010.nc"

v_filename = "CMIP6_HadGEM3-GC31-MM_Omon_historical_r4i1p1f3_mlotst_gn_2000-2010.nc"

with Dataset(v_filename, 'a') as dataset:
    print("location in /home/users/valeriu: \n", dataset)

print("location in /gws/nopw/j04/ukesm/ldemora: \n")
with Dataset(lee_filename, 'a') as dataset:
    print(dataset)
```

The file in my `$HOME` (which is a mere copy that I got via "cp" of the original file in the `ukesm` gws) works perfectly fine, the file in `ukesm` GWS in ldemora throws an HDF exception:

```
Traceback (most recent call last):
  File "/home/users/valeriu/prov_lee_hdf.py", line 11, in <module>
    with Dataset(lee_filename, 'a') as dataset:
  File "src/netCDF4/_netCDF4.pyx", line 2307, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1925, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -101] NetCDF: HDF error: b'/gws/nopw/j04/ukesm/ldemora/ESMValTool_output/recipe_ocean_ai_mpa_mld_20211102_142314/preproc/diag_timeseries_3/mlotst_map_hist/CMIP6_HadGEM3-GC31-MM_Omon_historical_r4i1p1f3_mlotst_gn_2000-2010.nc'
```

And this happens always, there is no fluctuation!

I have the following versions of netcdf4/hdf5:

```
(esmvaltool-stock-latest) [valeriu@sci2 ~]$ conda list netcdf4
# packages in environment at /home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock-latest:
#
# Name                    Version                   Build  Channel
netcdf4                   1.5.7           nompi_py39h64b754b_103    conda-forge
(esmvaltool-stock-latest) [valeriu@sci2 ~]$ conda list hdf5
# packages in environment at /home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock-latest:
#
# Name                    Version                   Build  Channel
hdf5                      1.12.1          mpi_mpich_h9c45103_0    conda-forge
```

I am not sure about Lee's versions but they don't really matter since the file itself is not corrupt (note that access via a C backend like `ncdump` or `ncdump -h` works fine on the file on `ukesm` GWS too), it's the Python library that has issues with the ukesm GWS location. Any clues what might trigger this?

**Comment by valeriupredoi** [comment]
another clue is that error doesn't happen when one tries to open the file in `r` (read only mode)

**Comment by zklaus** [comment]
Hm hm. This *might* be a hairy one. Similar problems have surfaced on their tracker at https://github.com/Unidata/netcdf4-python/issues?q=is%3Aissue+is%3Aopen+_ensure_nc_success.

However, I can reproduce the problem also with the copy, by removing write permissions.
@ledm, would you mind giving write permissions to the group (`chmod g+w`) just to test this?

Also, looking at the output of `stat` is interesting:

#### Lee file
```
   Size: 297524          Blocks: 144        IO Block: 65536  regular file
Device: 62h/98d Inode: 10993391    Links: 1
Access: (0644/-rw-r--r--)  Uid: (29791/ ldemora)   Gid: (26126/gws_ukesm)
Access: 2021-11-03 14:35:10.000000000 +0000
Modify: 2021-11-02 16:28:04.000000000 +0000
Change: 2021-11-02 16:28:04.000000000 +0000
 Birth: -
```

#### V file
```
  Size: 297524          Blocks: 582        IO Block: 524288 regular file
Device: 29h/41d Inode: 27021597778064031  Links: 1
Access: (0644/-rw-r--r--)  Uid: (7051091/ valeriu)   Gid: (26030/   users)
Access: 2021-11-03 14:34:16.000000000 +0000
Modify: 2021-11-03 14:34:15.773656000 +0000
Change: 2021-11-03 14:34:15.774000000 +0000
 Birth: -
```

Look particularly to Blocks and IO Blocks.

**Comment by valeriupredoi** [comment]
yeah man, strange size differences can be seen from a simple `du -h`:
```bash
(esmvaltool-stock-latest) [valeriu@sci2 ~]$ du -h /gws/nopw/j04/ukesm/ldemora/ESMValTool_output/recipe_ocean_ai_mpa_mld_20211102_142314/preproc/diag_timeseries_3/mlotst_map_hist/CMIP6_HadGEM3-GC31-MM_Omon_historical_r4i1p1f3_mlotst_gn_2000-2010.nc
72K	/gws/nopw/j04/ukesm/ldemora/ESMValTool_output/recipe_ocean_ai_mpa_mld_20211102_142314/preproc/diag_timeseries_3/mlotst_map_hist/CMIP6_HadGEM3-GC31-MM_Omon_historical_r4i1p1f3_mlotst_gn_2000-2010.nc
(esmvaltool-stock-latest) [valeriu@sci2 ~]$ du -h CMIP6_HadGEM3-GC31-MM_Omon_historical_r4i1p1f3_mlotst_gn_2000-2010.nc 
291K	CMIP6_HadGEM3-GC31-MM_Omon_historical_r4i1p1f3_mlotst_gn_2000-2010.nc
```

**Comment by valeriupredoi** [comment]
@zklaus you are correct, I get exactly the same error when I remove my own `write` rights off a copy of that file that I moved to another `nopw` partition (`chmod u-w`_:
```
location in /nopw/esmeval: 

Traceback (most recent call last):
  File "/home/users/valeriu/prov_lee_hdf.py", line 14, in <module>
    with Dataset(esmeval_filename, 'a') as dataset:
  File "src/netCDF4/_netCDF4.pyx", line 2307, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1925, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -101] NetCDF: HDF error: b'/gws/nopw/j04/esmeval/CMIP6_HadGEM3-GC31-MM_Omon_historical_r4i1p1f3_mlotst_gn_2000-2010.nc'
```

size on disk changes too:
```
(esmvaltool-stock-latest) [valeriu@sci2 ~]$ du -h /gws/nopw/j04/esmeval/CMIP6_HadGEM3-GC31-MM_Omon_historical_r4i1p1f3_mlotst_gn_2000-2010.nc 
355K	/gws/nopw/j04/esmeval/CMIP6_HadGEM3-GC31-MM_Omon_historical_r4i1p1f3_mlotst_gn_2000-2010.nc
```

and doesn't change back when I re-add own `w` rights. Anyway, could it be that @ledm loses `w` permissions to his own dir from time to time while running the code that appends to that file? Also, it'd be nice if hdf5 would tell us "Permission to write denied" etc not throw an errcode -101 at them

**Comment by ledm** [comment]
I've added group write permissions to that file now. Just to be explicit, this file: `/gws/nopw/j04/ukesm/ldemora/ESMValTool_output/recipe_ocean_ai_mpa_mld_20211102_142314/preproc/diag_timeseries_3/mlotst_map_hist/CMIP6_HadGEM3-GC31-MM_Omon_historical_r4i1p1f3_mlotst_gn_2000-2010.nc`

**Comment by valeriupredoi** [comment]
cheers @ledm - I can't see the error anymore. OK so things are starting to clear up: it seems that you are losing `w` permissions periodically (or better said, the process you are running is) - and this could be related to https://github.com/ESMValGroup/ESMValCore/issues/1378

There is still the dodgy difference in disk space though:
```
(esmvaltool-stock-latest) [valeriu@sci2 ~]$ du -h /gws/nopw/j04/ukesm/ldemora/ESMValTool_output/recipe_ocean_ai_mpa_mld_20211102_142314/preproc/diag_timeseries_3/mlotst_map_hist/CMIP6_HadGEM3-GC31-MM_Omon_historical_r4i1p1f3_mlotst_gn_2000-2010.nc
99K	/gws/nopw/j04/ukesm/ldemora/ESMValTool_output/recipe_ocean_ai_mpa_mld_20211102_142314/preproc/diag_timeseries_3/mlotst_map_hist/CMIP6_HadGEM3-GC31-MM_Omon_historical_r4i1p1f3_mlotst_gn_2000-2010.nc
(esmvaltool-stock-latest) [valeriu@sci2 ~]$ du -h CMIP6_HadGEM3-GC31-MM_Omon_historical_r4i1p1f3_mlotst_gn_2000-2010.nc 
291K	CMIP6_HadGEM3-GC31-MM_Omon_historical_r4i1p1f3_mlotst_gn_2000-2010.nc
```
but this may be explained by the difference between the two different File Systems: `/home` and `nopw`?

**Comment by mjpritchard** [comment]
@valeriupredoi make sure you're using `du -h --apparent-size` for more reliable result on that filesystem.

**Comment by valeriupredoi** [comment]
@mjpritchard cheers! That does the trick:
```
(esmvaltool-stock-latest) [valeriu@sci2 ~]$ du -h --apparent-size /gws/nopw/j04/ukesm/ldemora/ESMValTool_output/recipe_ocean_ai_mpa_mld_20211102_142314/preproc/diag_timeseries_3/mlotst_map_hist/CMIP6_HadGEM3-GC31-MM_Omon_historical_r4i1p1f3_mlotst_gn_2000-2010.nc
291K	/gws/nopw/j04/ukesm/ldemora/ESMValTool_output/recipe_ocean_ai_mpa_mld_20211102_142314/preproc/diag_timeseries_3/mlotst_map_hist/CMIP6_HadGEM3-GC31-MM_Omon_historical_r4i1p1f3_mlotst_gn_2000-2010.nc
(esmvaltool-stock-latest) [valeriu@sci2 ~]$ du -h CMIP6_HadGEM3-GC31-MM_Omon_historical_r4i1p1f3_mlotst_gn_2000-2010.nc 
291K	CMIP6_HadGEM3-GC31-MM_Omon_historical_r4i1p1f3_mlotst_gn_2000-2010.nc
```

**Comment by zklaus** [comment]
Well, `du --apparent-size` certainly does some trick. Namely, it gives us back the information of the `Size: ` entry of the `stat` output, equivalently the size reported by `ls`. But it doesn't tell us the actual space occupied on the filesystem, in other words, the sparseness, that we were trying to use to determine whether the original file might be corrupted as indicated by the presence of a large number of zeros.

But if @ledm, can reproduce somehow the problem and figure out if he might be blocked from writing at the time of its occurrence, that could be useful.

**Comment by valeriupredoi** [comment]
I think that's the way around this - figuring out if the Python process opening the nc file to append is losing write permissions to it from time to time - as you say, Klaus - but how to check this in a systematic way? This could actually happen at netcdf4-python level hdf5 level

**Comment by agstephens** [comment]
@valeriupredoi @zklaus Do you know if the `netCDF4` library is doing parallel-writes behind the scenes.

**Comment by zklaus** [comment]
@agstephens, I believe that is not the case.

**Comment by valeriupredoi** [comment]
@agstephens I don't think so since the build version we have is done without `mpi` (`nompi_py39h64b754b_103`)

**Comment by ledm** [comment]
Here's what I don't understand. This error is happening a lot for me, in almost every run now. If it were just a read/write error it would happen at all the places that the netcdf is written. However, it only ever happens at the `_include_provenance` stage in the `_include_provenance_nc` function. What is so special about this function?

**Comment by valeriupredoi** [comment]
@alaniwi from CEDA was kind enough to have a look into this, I am reposting his email from Friday, cheers, Alan!

I've experimented a little, and this seems to be entirely related to write permission. I cannot reproduce the errors when opening the files in "r" mode, but see the same behaviour as you in "a" mode. Equally, if I have a file that I own but chmod it to 400, then I will also get the error when using "a" mode.

It also seems that the error is happening during the attempt to open the file, before any data is read, so can also be seen if you have "pass" instead of "print(dataset)" in your example. At a low level (as seen by the "strace" utility), I see that if you open in "a" mode, then each file is opened initially read only (O_RDONLY), then some header data is read, and then it is closed and reopened read-write (O_RDWR). This second (read-write) open attempt fails (with low-level error EACCS) if there is not write permission on the file, and evidently this propagates to the application level as an HDF error. In the case where the file is opened in "r" mode at the application level, something similar happens except that both of the low-level open calls are in O_RDONLY mode (perhaps not surprisingly).

If there is a file on which you do not even have read permission, then the first low-level open will fail, and this will give a different error in Python (permission denied). Arguably the "HDF error" message that is obtained in the case where you have read-only permission but attempt to use append mode is a bit misleading, and maybe you could create a bug report to suggest that this should instead be reported to the user as "permission denied", but I'm afraid I don't know for sure whether this would be an issue for the netCDF4 package or the hdf5 library maintainers.

I also tried the commands under your username via sudo, and could not reproduce any problem. This seems to be because the file has group-write permission and you are a member of the gws_ukesm group but I am not. Equally, I see that the file has a recent change time, so presumably it did not have the group-write permission at the time when you first reported this.

If files are starting with group-write permission but then losing that permission bit, then I could not tell you what is causing this to happen, but if you look at the change times of the files ("ls -l --time=ctime") this may give a clue as to when it is happening (as a "chmod" should update the change time although not the modification time), and this may help identify what process is responsible. It would have to be something running as the username which owns the files (or as the root user, but this seems unlikely).

If the software had reported the error message as "permission denied" in the first place, then I believe that you would not have perceived the files to be corrupted.

Also, I believe that this problem is unrelated to previous problems with "HDF error" from some netCDF files on JASMIN, which seemed to be related to file locking, and to work around this we set an enviroment variable for users to tell the HDF5 libraries to ignore the (advisory) file locks. I think that issue may now be fixed. Again, the files in question were not actually corrupted.

**Comment by ledm** [comment]
At @valeriupredoi's suggestion, I moved my output directory to my home directory, instead of the `/gws/nopw/j04/ukesm` and this exact same recipe with no changes worked fine (or at least ran until it hit a different error). We have a feeling the issue is with the jasmin file system, not netcdf4, iris or esmvaltool.

**Comment by valeriupredoi** [comment]
OK so I think I finally got to the bottom of this, and now I can reproduce the issue 100% cases, and with everything belonging to me (as user, as it's the case for @ledm - no secondary users file access etc). I wrote a test file like this:
```python
from netCDF4 import Dataset


nopw_filename = "/gws/nopw/j04/ukesm/valeriu/CMIP6_HadGEM3-GC31-MM_Omon_historical_r4i1p1f3_mlotst_gn_2000-2010.nc"
home_filename = "/home/users/valeriu/CMIP6_HadGEM3-GC31-MM_Omon_historical_r4i1p1f3_mlotst_gn_2000-2010.nc"


class FileTest():
    @staticmethod
    def _test_open(filename, type_of_file):
        with Dataset(filename, 'a') as dataset:
            print(type_of_file)


def test_main_1():
    ft = FileTest()
    file_dict = {"home": home_filename, "nopw": nopw_filename}
    for k, v in file_dict.items():
        ft._test_open(v, k)
        assert True


def test_main_2():
    ft = FileTest()
    file_dict = {"home": home_filename, "nopw": nopw_filename}
    for k, v in file_dict.items():
        ft._test_open(v, k)
        assert True
```

It mimics the actual functional behavior of that bit of code: a class that uses a static method that accesses the file and appends to it, what's extra in the test is that the test runs in parallel and both tests try to execute the same operation on the same file:

```
pytest -n 2 tests/test_file_permissions.py
```

this leads to a fail of one of the two tests at any one time:
```
tests/test_file_permissions.py:29: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/test_file_permissions.py:11: in _test_open
    with Dataset(filename, 'a') as dataset:
src/netCDF4/_netCDF4.pyx:2307: in netCDF4._netCDF4.Dataset.__init__
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   OSError: [Errno -101] NetCDF: HDF error: b'/home/users/valeriu/CMIP6_HadGEM3-GC31-MM_Omon_historical_r4i1p1f3_mlotst_gn_2000-2010.nc'

src/netCDF4/_netCDF4.pyx:1925: OSError
```
which is the rather cryptic error that Lee has been seeing. Now, this is a bit like pulling the pin of a greneade and not expecting an explosion - this type of test run with `-n 2` will always offer us a failure simple because the file is still open in append mode from the other test that goes to completion, what I wanted to get out of this was the actual trace that is given to the user when this is happening. So Lee has no issues with changeable permissions, it's simply a case of the file is still open while another process is trying to access it and append to it, and this shouldn't matter if on a `/nopw` or PW partition - it's just bad coding on our part, well @bouweandela part since he wrote the provenance code :grin: Sorry Bouwe, there's a reason why I tagged you here, not because I am tossing blames, but rather, do you think this could be fixed - my take on why this is happening only at certain times, and only on `nopw` (as Lee tested on `home` all fine) is that the `nopw` FS is really really slow, and this open/append/close operation is a very quick one, but on a slow FS it gets in the way of the next process trying to perform it. What do you guys think?

**Comment by valeriupredoi** [comment]
here is a fix that ensures file handling done correctly by the two racing processes:

```python
import time
from netCDF4 import Dataset


nopw_filename = "/gws/nopw/j04/ukesm/valeriu/CMIP6_HadGEM3-GC31-MM_Omon_historical_r4i1p1f3_mlotst_gn_2000-2010.nc"
home_filename = "/home/users/valeriu/CMIP6_HadGEM3-GC31-MM_Omon_historical_r4i1p1f3_mlotst_gn_2000-2010.nc"


class FileTest():
    @staticmethod
    def _test_open(filename, type_of_file):
        with Dataset(filename, 'a') as dataset:
            print(type_of_file)

def test_main_1():
    ft = FileTest()
    #file_dict = {"home": home_filename, "nopw": nopw_filename}
    file_dict = {"nopw": nopw_filename}
    for k, v in file_dict.items():
        try:
            ft._test_open(v, k)
        except OSError as err:
            if err.errno == -101:
                time.sleep(5)
                ft._test_open(v, k)
            else:
                raise err
        assert True


def test_main_2():
    ft = FileTest()
    # file_dict = {"home": home_filename, "nopw": nopw_filename}
    file_dict = {"nopw": nopw_filename}
    for k, v in file_dict.items():
        try:
            ft._test_open(v, k)
        except OSError as err:
            if err.errno == -101:
                time.sleep(5)
                ft._test_open(v, k)
            else:
                raise err
        assert True
```

I reckon we should put this in the provenance code, inside that static method to avoid such issues, what you reckon @bouweandela ?

**Comment by valeriupredoi** [comment]
that was just an idea - I don't like sleeps either, no need to artificially slow down the code, but this is the only solution I found that averts the race situation; I'll leave it to @bouweandela to decide how to best avoid the race, but am afraid this will bite again in certain conditions

**Comment by bouweandela** [comment]
@valeriupredoi I don't see how the code you produced resembles what happens in the ESMValCore. When saving a NetCDF file, first the iris cube is stored in the file (either by the preprocessor or the diagnostic) and then we add some global attributes (caption, text that says file was created by ESMValTool, no provenance anymore since #1306). See for example this code for preprocessor files:
https://github.com/ESMValGroup/ESMValCore/blob/4b8bf66ce6ef51cc6814b5d18357ae91684eb0b7/esmvalcore/preprocessor/__init__.py#L452-L454

The code on line 452 calls `iris.save`, while the code on line 454 opens the file again and adds the extra global attributes. So unless `iris.save` does not close the file after writing to it, I do not see how this is related to the code you provided.

**Comment by valeriupredoi** [comment]
`save` takes too long on a slow file system while `save_provenance` catches up with it and tries to append to a file that's still open?

**Comment by ledm** [comment]
Can't we just do all the writing to disk sequentially instead of in parallel?

**Comment by zklaus** [comment]
@bouweandela's comment is clarifying that indeed already with the current code all writing should happen sequentially. If you,@ledm or @valeriupredoi, still think there is something happening in parallel, you should clarify how and where.

**Comment by schlunma** [comment]
Moving this to v2.6 since there is not open PR yet.

**Comment by valeriupredoi** [comment]
yeah this is a Loch Ness monster kind of issue, I am actually going to close it, and will reopen if the behaviour resurfaces :sauropod:
