### ISSUE TITLE
Variable information from recipes overwritten by cmor table info when deriving custom variables

### ISSUE THREAD

**Issue by remi-kazeroni** [ESMValGroup/ESMValCore#1388]
**Describe the bug**
In [#2396](https://github.com/ESMValGroup/ESMValTool/issues/2396), it was found out that variable information (e.g. frequency) specified in a recipe to derive a custom variable can be overwritten by reading cmor tables and this can lead to inconsistencies like in the case of ERA5 hourly data. It is not clear if this issue only affects ERA5 variable derivation for hourly data or other datasets/variable derivations as well.

Below is an example where the `1hr` frequency used for ERA5 hourly variable is overwritten to `1hrPt` when deriving custom variables. Consequently, input variables needed for the derivation are not found and the recipe fails.

**Please attach**
  - The recipe that you are trying to run, you can find a copy in the `run` directory in the output directory:
 [recipe_check_era5_hourly_derive.yml.txt](https://github.com/ESMValGroup/ESMValCore/files/7487251/recipe_check_era5_hourly_derive.yml.txt)
  - The `main_log_debug.txt` file, this can also be found in the `run` directory in the output directory
[main_log_debug.txt](https://github.com/ESMValGroup/ESMValCore/files/7487252/main_log_debug.txt)

**Comment by schlunma** [comment]
Moving this to v2.6 since there is not open PR yet.

**Comment by bouweandela** [comment]
Background information: the recipes fails for variables:
- rlus: derived from rlds (surface_thermal_radiation_downwards) and rlns (surface_net_thermal_radiation)
- rsus: derived from rsds (surface_solar_radiation_downwards) and rsns (surface_net_solar_radiation)

All of these from **Table 3: surface and single level parameters: [accumulations](https://confluence.ecmwf.int/display/CKB/ERA5%3A+data+documentation#ERA5:datadocumentation-Meanrates/fluxesandaccumulations)** shown [here](https://confluence.ecmwf.int/display/CKB/ERA5%3A+data+documentation) so have frequency `1hr`.
