### ISSUE TITLE
Error when running variable `toz` derivation

### ISSUE THREAD

**Issue by hahsan1** [ESMValGroup/ESMValCore#1396]
I am trying to generate the variable `toz` which is the total column ozone by following the instructions from the [guide](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/recipe/preprocessor.html#variable-derivation), but I get an error. It's not clear to me from the error log what the problem is. Any insight would be greatly appreciated!

Here are the recipe and error log from the run.
[global_reference.txt](https://github.com/ESMValGroup/ESMValTool/files/7550545/global_reference.txt)
[main_log_debug.txt](https://github.com/ESMValGroup/ESMValTool/files/7550546/main_log_debug.txt)

**Comment by valeriupredoi** [comment]
hi @hahsan1 I have transferred the issue to the ESMValCore since it deals with derivation which is a preprocessing functionality. `toz` takes `[{'short_name': 'o3'}, {'short_name': 'ps'}]` as input variables, do you have GISS data for those variables and corresponding mip end exp?

**Comment by schlunma** [comment]
Hi @hahsan1, based on your error it looks like your dataset uses a `atmosphere_hybrid_sigma_pressure_coordinate`, which is not currently supported for deriving `toz`. I actually implemented this is an the branch `ozone` and hopefully will get this into the `main` branch, soon!

https://github.com/ESMValGroup/ESMValCore/blob/7509434392601b5e477ec9ee5b29a641b6bf901b/esmvalcore/preprocessor/_derive/toz.py#L59-L86

**Comment by valeriupredoi** [comment]
cheers Manu :beer:

**Comment by hahsan1** [comment]
I managed to get this working by adapting your code, thank you!

**Comment by hahsan1** [comment]
I realized that the derived file `toz` has yearly timesteps, but the input model files (i.e., `o3` and `ps`) have monthly timesteps. Is there a way to generate `toz` with monthly timesteps too? The reason is, I use `toz` for subsequent processing through ESMValTool and it is giving me this error: `time: Frequency mon does not match input data`, since `toz` has yearly timesteps.

**Comment by schlunma** [comment]
`toz` should have the exact same coordinat as `o3`. Can you please make sure that `o3` is really truly monthly data and if yes, post `ncdump`s of the input and output files as well as the recipe and debug log you are using?

**Comment by hahsan1** [comment]
I realized my error now, I simply needed to specify `monthly_statistics` in the preprocessors section, rather than `annual_statistics`.
