### ISSUE TITLE
Our pandas left us: test failures due to missing module `pandas` since latest `iris` doesn't need any more `pandas`

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1401]
[test fails eg](https://github.com/ESMValGroup/ESMValCore/runs/4348196555?check_suite_focus=true) - I am investigating

**CAUSE FOUND**: latest iris build:
```
(esmvalcore-stock-conda) valeriu@valeriu-PORTEGE-Z30-C:~/ESMValCore$ conda list iris
# packages in environment at /home/valeriu/miniconda3/envs/esmvalcore-stock-conda:
#
# Name                    Version                   Build  Channel
iris                      3.1.0              pyhd8ed1ab_3    conda-forge
```
does not include `pandas` as dependency anymore - I opened an issue https://github.com/SciTools/iris/issues/4442 and asked, if they don't need it anymore we either include it ourselves or see about not using it anymore :+1:

**Comment by zklaus** [comment]
I think we should probably include it ourselves, no matter what Iris does. Similar to the discussion we had about the `import` stuff, I tend to think that we should name everything we ourselves are using, even if it would also be pulled by a dependency.

**Comment by valeriupredoi** [comment]
yeah man that was my ontention as well, I'm gonna get a qwik PR out with :panda_face: in now
