### ISSUE TITLE
Pin `flake8<4` - running `pytest` tests with `--flake8` turned on may mask print statements that are necessary if test fails

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1405]
A bunch of native Python errors - like undefined name/variable - are now picked up by Flake8 when running a pytest test - if those errors can be debugged via print statements that the test developer has purposefully put in the test for debugging, those print statements don't get flushed to stdout even if you change the `--capture` value when running pytest, because flake8 runs right at the very beginning and once it fails it discards every other call that follows in the test. I'd like to change this somehow, without having to turn off the `--flake8` flag, but I don't know how - any ideas?

**Comment by valeriupredoi** [comment]
also, flake8 errors are now starting to be darn opaque, have a look at [this](https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore/6018/workflows/f1bc0ab9-9492-4449-810f-548dbb04e089/jobs/28922)

**Comment by bouweandela** [comment]
See https://github.com/tholo/pytest-flake8/issues/81

**Comment by bouweandela** [comment]
Yes, that would make sense. The issue with the flake8 plugin looks quite old and nothing seems to be happening there.

**Comment by valeriupredoi** [comment]
pin it is then...I'll do it soon :hourglass:

**Comment by valeriupredoi** [comment]
opening a PR with the pin now!
