### ISSUE TITLE
`unstructured_nearest` regridding does not return masked arrays

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#1413]
The `unstructured_nearest` regridding scheme does not return masked arrays (only regular `dask`/`numpy` arrays with explicit values of `1e20`). This can lead to problems further down the preprocessing chain and gets only fixed in the `save` step.

This is actually a problem of `iris`, but since they will improve their support for unstructured grids soon and we will also probably adapt the regridding preprocessor I don't think it is worth to report this upstream.

This can be solved with a single line, I will open a quick PR for that!

**Comment by valeriupredoi** [comment]
eagle eyed Many :eagle: I reckon it's best you raised this with Iris in the form of an issue (if there isn't one already) :+1:

**Comment by schlunma** [comment]
Opening an issue right now

**Comment by valeriupredoi** [comment]
eagle eyed Manu not Many :laughing: Cheers, maybe they are not aware of this, what do you know?

**Comment by schlunma** [comment]
See SciTools/iris#4463 :+1:
