### ISSUE TITLE
Improve documentation on how to deprecate features

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#1421]
In #1416 an optional argument of a preprocessor function was deprecated. There we realized that the [existing documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#backward-compatibility) does not describe the procedure in full detail.

#1416 introduced a [custom](https://github.com/ESMValGroup/ESMValCore/blob/4b8bf66ce6ef51cc6814b5d18357ae91684eb0b7/esmvalcore/exceptions.py#L21-L22) deprecation warning that can be [called](https://github.com/ESMValGroup/ESMValCore/blob/4b8bf66ce6ef51cc6814b5d18357ae91684eb0b7/esmvalcore/preprocessor/_mask.py#L153) using the default python warning framework. The existing documentation needs to be updated to reflect these changes.

**Comment by valeriupredoi** [comment]
I think a good inspirational case is Numpy's [NEP 23](https://numpy.org/neps/nep-0023-backwards-compatibility.html) - pinging @alistairsellar too since he is well interested in making sure these things are done in a standardized and documented manner :+1:

**Comment by valeriupredoi** [comment]
also I'd remove the `deprecated feature` label - yes that thing is discussed here but the discussion will not lead to a deprecated feature, but rather to an enhancement :hammer_and_wrench:

**Comment by zklaus** [comment]
Pinging @ESMValGroup/esmvaltool-coreteam. Let's bring it up at the monthly meeting as well.

**Comment by bouweandela** [comment]
There is documentation on this topic: https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#backward-compatibility

**Comment by bouweandela** [comment]
If you would like to add additional documentation, that might be a good place? Or link from there?

**Comment by schlunma** [comment]
Somehow I overlooked this, I think this is actually a good place for it! Will update the information now.

**Comment by zklaus** [comment]
I updated the title, but @schlunma, could you have a look at the description as well?
