### ISSUE TITLE
Adapt `annual_statistics` to DCPP data

### ISSUE THREAD

**Issue by sloosvel** [ESMValGroup/ESMValCore#1422]
**Is your feature request related to a problem? Please describe.**
As mentioned in https://github.com/ESMValGroup/ESMValCore/issues/1120#issuecomment-843030860, a year in DCPP datasets spans 12 months but not necessarily starting in January. For this reason, aggregating these datasets by `year` number in `annual_statistics` is not very convenient, as a dataset with 12 months of data spanning from Nov 1960 to Oct 1961 would result in a cube with two time steps. It would be convenient to be able to compute annual statistics defining the year span as 12 months from the origin. In that way, the resulting cube for this example would have one timestep, as expected.

As for the implementation, maybe `annual_statistics` could have a `from_origin=False/True` parameter, with default value set to `False`:

```python

def annual_statistics(operator, from_origin=False):
   if from_origin:
       #Aggregate considering a year is 12 months of data
       return cube
   # continue with annual_statistics aggregating by year number

``` 
But suggestions are very much welcome.

**Would you be able to help out?**
Yes

**Comment by zklaus** [comment]
Just a thought: Would it be possible to do this with seasonal statistics and a season of "NDJFMAMJJASO"?

**Comment by sloosvel** [comment]
Yes, but in the case of having a recipe with datasets that start in different months I feel like it's more flexible to adapt `annual_statistics`. Otherwise you would need to create separate preprocessors for each one of the datasets.

**Comment by sloosvel** [comment]
Anyway, I gave it a go and it's something not that tedious to implement. It is also much more useful to our applications to have a result cube with a `year` coordinate computed with `annual_statistics`, rather than the result you obtain with seasonal statistics. So if you don't mind, I will open a pull request.

**Comment by zklaus** [comment]
Don't mind at all. Just thought there might be a way to achieve what you need without any work :wink:

**Comment by zklaus** [comment]
I suggest discussing a bit more though:
- If it is always the 12 months from the start of the file, what happens when the file has weird alignment (it is quite common that output files have a single day of the previous or next year)?
- What about sub-daily output? 
- If the "year" goes from September 2010 to August 2011, is that year 2010 or year 2011?

**Comment by sloosvel** [comment]
> If it is always the 12 months from the start of the file, what happens when the file has weird alignment (it is quite common that output files have a single day of the previous or next year)?

You can take that point out with the timerange tag, the clipping happens before the time statistics.

>What about sub-daily output?

I dont' get what you mean. But you can set a suitable origin with the timerange tag as well.

>If the "year" goes from September 2010 to August 2011, is that year 2010 or year 2011?

The aggregation sets the time to the middle of the interval, so March 2011.

**Comment by sloosvel** [comment]
Nevermind, as you said the seasonal statistics can already do this. I will close this issue.
