### ISSUE TITLE
`esmvaltool run --help` does not show all possible command line options

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#1433]
Currently, `esmvaltool run --help` returns

```
> esmvaltool run --help
...

FLAGS
    --config_file=CONFIG_FILE
        Type: Optional[]
        Default: None
        Configuration file to use. If not provided the file ${HOME}/.esmvaltool/config-user.yml will be used.
    --resume_from=RESUME_FROM
        Type: Optional[]
        Default: None
        Resume one or more previous runs by using preprocessor output files from these output directories.
    --max_datasets=MAX_DATASETS
        Type: Optional[]
        Default: None
        Maximum number of datasets to use.
    --max_years=MAX_YEARS
        Type: Optional[]
        Default: None
        Maximum number of years to use.
    --skip_nonexistent=SKIP_NONEXISTENT
        Default: False
        If True, the run will not fail if some datasets are not available.
    --offline=OFFLINE
        Type: Optional[]
        Default: None
        If True, the tool will not download missing data from ESGF.
    --diagnostics=DIAGNOSTICS
        Type: Optional[]
        Default: None
        Only run the selected diagnostics from the recipe. To provide more than one diagnostic to filter use the syntax 'diag1 diag2/script1' or '("diag1", "diag2/script1")' and pay attention to the quotes.
    --check_level=CHECK_LEVEL
        Default: 'default'
        Configure the sensitivity of the CMOR check. Possible values are: `ignore` (all errors will be reported as warnings), `relaxed` (only fail if there are critical errors), default (fail if there are any errors), strict (fail if there are any warnings).
    Additional flags are accepted.

```

These are clearly not all possible arguments, see for example here:

https://github.com/ESMValGroup/ESMValCore/blob/4b8bf66ce6ef51cc6814b5d18357ae91684eb0b7/esmvalcore/experimental/config/_config_validators.py#L254-L289

@ESMValGroup/esmvaltool-coreteam  Is there a certain strategy which options are shows in the help and which not? I think it would definitely make sense to show additional options (not all of them!), like `run_diagnostic` which even [appears in the documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/quickstart/run.html#running).

**Comment by valeriupredoi** [comment]
related to this https://github.com/ESMValGroup/ESMValCore/issues/936 - we really need to fix the command helper and run

**Comment by zklaus** [comment]
Can we single-source this? Eg  embed the output of `esmvaltool --help` in the documentation or perhaps a version of `esmvalcore._main.ESMValTool.run.__doc__` or similar?

**Comment by schlunma** [comment]
Yes, I agree with that!

As far as I can tell `Fire` uses the docstrings of the corresponding classes and functions (e.g., [this one](https://github.com/ESMValGroup/ESMValCore/blob/a1bd01e8356923914b9fcac3d1e7c3e96750def6/esmvalcore/_main.py#L334-L369) for the `run` subcommand) to create the `--help` output, so using `esmvalcore._main.ESMValTool.run.__doc__` as single source would definitely make sense!

Adding additional optional arguments for the `--help` command can probably be implemented by explicitly adding optional arguments to `run` (right now, many of them are passed in the `kwargs`).

**Comment by bouweandela** [comment]
>  Is there a certain strategy which options are shows in the help and which not?

Historically some options are command-line options and others are configuration file options. At some point, it became possible to specify most (all?) options either on the command line or in the configuration file and the distinction got a bit lost. The best solution seems to be have a look at all available options and think about which options make sense as a command line option and document those with the `--help` flag.

**Comment by valeriupredoi** [comment]
fire has a PR improving this https://github.com/google/python-fire/pull/364 - seems like their dev process is somewhat slower though wrt PR acceptance. I am also wondering if we should ask them about the issue with command line args integrity ir `--config_user` vs `--config-user`

**Comment by schlunma** [comment]
I think the problem here is not fire, but rather that we do not explicitly list all possible options in the main function but use `**kwargs` instead:

https://github.com/ESMValGroup/ESMValCore/blob/54385ac7bf490f6f823cc99fe1f9786065318ab1/esmvalcore/_main.py#L325-L335
