### ISSUE TITLE
Configuration file issues

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#1456]
My apologies for being a bit late to the party, but please see my comments on https://github.com/ESMValGroup/ESMValCore/pull/1453.

**Comment by schlunma** [comment]
Sorry, nobody commented on my issue and we want to do the feature freeze for v2.5, so I wanted to get this in rather quickly.

I still think we have time to fix the issues you raised, I will open a draft PR for that. I also left some comments in the old PR (#1453).

**Comment by bouweandela** [comment]
Thanks @schlunma!
