### ISSUE TITLE
CMIP6 tables are out of sync

### ISSUE THREAD

**Issue by zklaus** [ESMValGroup/ESMValCore#150]
There is something going on with the CMIP6 tables. The `esmvalcore/cmor/tables/CMIP6/README.md` file claims that it is version 01.00.30, but the actual tables are version 01.00.10, ie quite old and are indeed not suitable for current cmorized data.

For instance, the `standard_name` of (Amon, psl) is still `air_pressure_at_sea_level` where the correct one now is `air_pressure_at_mean_sea_level`.

**Comment by jvegasbsc** [comment]
I will update to latest version
