### ISSUE TITLE
Running with CMIP6 data and OBS data fails if using mip: AERmonZ

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#152]
mirroring https://github.com/ESMValGroup/ESMValTool/issues/1208 for ESMValCore

**Comment by bouweandela** [comment]
Duplicate of #160

**Comment by valeriupredoi** [comment]
in case of issues that pertain to both Tool and Core we should make good practice to have both issues open/closed at the same time, no such thing as duplicates when dealing with two different projects

**Comment by bouweandela** [comment]
Yes, but in this case it's an issue with the core only, as it's the preprocessor that fails.
