### ISSUE TITLE
Remove `package/meta.yml` files in ESMValCore and ESMValTool

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#1522]
Since our conda packages are built on conda-forge (e.g., https://github.com/conda-forge/esmvalcore-feedstock) the `package/meta.yml` files are not necessary anymore.

See discussions: #1521 https://github.com/conda-forge/esmvalcore-feedstock/pull/33

**Comment by bouweandela** [comment]
Don't forget to update the related documentation: https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#create-and-upload-the-conda-package
