### ISSUE TITLE
Dataset problem: ocean variables for multiple CMIP6 datasets

### ISSUE THREAD

**Issue by tomaslovato** [ESMValGroup/ESMValCore#1539]
**Describe the dataset issue**

A number of CMIP6 datasets requires fixes for different ocean variables to correct coordinates metadata and fix issues with depth definition.

Along with the dataset initially spotted in this issue (`cesm2_waccm`, `gfdl_cm4`, `gfdl_esm4`), it was decided to integrate and verify the changes reported in the sloppy PR #1395

Some of these fixes can be easily inherited from the models of the same family, where they have already been implemented.

**Comment by tomaslovato** [comment]
if @zklaus @valeriupredoi agrees, I can open a PR and apply the above fixes so you only need revise the code changes ...

**Comment by zklaus** [comment]
Go ahead. Thanks, @tomaslovato!

**Comment by tomaslovato** [comment]
as agreed with @zklaus,  the present issue will be extended to include the applicable ocean variables fixes repored in PR #1395
