### ISSUE TITLE
Install all dependecies from conda-forge

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#1541]
Copy all dependencies from `setup.py` to `environment.yml` so that all packages are installed from conda-forge.

All dependencies: https://github.com/conda-forge/esmvalcore-feedstock/blob/main/recipe/meta.yaml

@ESMValGroup/esmvaltool-coreteam I'm pretty sure we discussed that somewhere, but I didn't find an issue to this. Please correct me if I'm wrong, then we can close this.

**Comment by bouweandela** [comment]
I missed that discussion, but maybe this could be something for the next @ESMValGroup/technical-lead-development-team meeting?

**Comment by valeriupredoi** [comment]
the DPR associated with this got bumped to M2.8 so am bumping its issue as well, boos all over (directed to me)
