### ISSUE TITLE
`start_year` and `end_year` attributes for derived variables can be missing

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#1546]
If only a `timerange` is specified in the recipe for a derived variable, the attributes `start_year` and `end_year` are missing for that variable.

Related to #1485.

I will open a PR with a fix soon.

**Comment by zklaus** [comment]
This is a candidate for a v2.5.1 bugfix release imho. I have set up a milestone for that and assigned this issue. That doesn't mean that we have to do it that way or that a v2.5.1 has to happen, but let's keep track of some issues and if things accumulate to a degree that makes it useful, we can consider it.

**Comment by schlunma** [comment]
> That doesn't mean that we have to do it that way or that a v2.5.1 has to happen, but let's keep track of some issues and if things accumulate to a degree that makes it useful, we can consider it.

Sounds good! I don't think that this single issue justifies a bugfix, but if we find more similar small issue we should certainly think about it.
