### ISSUE TITLE
Use CMIP6 tables for OBS

### ISSUE THREAD

**Issue by jvegasbsc** [ESMValGroup/ESMValCore#157]
We are using CMIP5 tables for obs. This implies that we are missing many variables that were introduced in CMIP6 and that we need to add those manually to the custom tables when adding observations from them

The obvious solution is to use CMIP6 tables as a reference for observations, but I don't know how much work this will imply

**Comment by bouweandela** [comment]
I've made a pull request https://github.com/ESMValGroup/ESMValCore/pull/111 for adding ERA5 support. It also contains a new OBS6 project, that is CMIP6 + custom tables. I guess we can encourage new CMORizers to be written for OBS6 instead of OBS and gradually replace the old OBS by OBS6.

**Comment by bouweandela** [comment]
Closing this as the OBS6 project is now available.
