### ISSUE TITLE
Adding more operators to `depth_integration`

### ISSUE THREAD

**Issue by sloosvel** [ESMValGroup/ESMValCore#1583]
**Is your feature request related to a problem? Please describe.**
A while back, Javi worked on generalising the `depth_integration` preprocessor to accept other operators. It would be useful to have this changes officially in the core. 

Additionally, it could be an opportunity to improve some lines to make the preprocessor lazy, namely:

```python
            if depth.ndim == 1:
                slices = [None for i in cube.shape]
                coord_dim = cube.coord_dims(cube.coord(axis='z'))[0]
                slices[coord_dim] = slice(None)
                thickness = np.abs(thickness[tuple(slices)])
            ones = np.ones_like(cube.data)


```

**Would you be able to help out?**
yes

**Comment by sloosvel** [comment]
As a clarification, what I mean by adding more operators is to add an `operator` argument to the preprocessor that defaults to `sum` but that allows other iris operators when collapsing the coordinate. So something along the lines of:

```python
def depth_integration(cube, operator='sum'):
....
    operation = get_iris_analysis_operation(operator)
    weights = None
    if operator_accept_weights(operator):
        thickness = np.abs(depth.bounds[..., 1] - depth.bounds[..., 0])
        coord_dim = cube.coord_dims(cube.coord(axis='z'))[0]
        axes = list(range(cube.ndim))
        axes.remove(coord_dim)
        weights = np.expand_dims(thickness, axes)
        weights = da.broadcast_to(weights, cube.shape)
        result = cube.collapsed(cube.coord(axis='z'),
                                operation,
                                weights=weights)
    else:
        result = cube.collapsed(cube.coord(axis='z'), operation)
```

**Comment by zklaus** [comment]
Thanks for this clarification, @sloosvel. I like the idea of generalizing this preprocessor. The name part `integration` would not be appropriate for most operators though, and it would be nice to allow their application to arbitrary axis, so I would suggest to implement this generalized preprocessor separately and then change the implementation of the special case of `depth_integration` into a call to the more general version.

**Comment by sloosvel** [comment]
Does the name `axis_statistics` work for you? It would take the direction and the operator as arguments and depth_integration would call it as `axis_statistics(cube, axis='z', operator='sum').
