### ISSUE TITLE
Specify encoding when reading YAML and other text files

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#1585]
When reading a YAML or other text file, it would be best if we specify the encoding, for example:
```python
with open('/path/to/file.yml', encoding='utf-8') as file:
    content = yaml.safe_load(file)
```

this prevents problems such as https://github.com/ESMValGroup/ESMValTool/issues/973 and https://github.com/ESMValGroup/ESMValTool/issues/2652.

**Comment by zklaus** [comment]
Second that. Noteworthy also [Yaml Specification Section 5.2](https://yaml.org/spec/1.2.2/#chapter-5-character-productions) that only seems to allow variations of UTF as encoding, with UTF-8 being the default.

**Comment by valeriupredoi** [comment]
yes, we may have to offer a possibility to set the `locale` variables too if the user runs on a machine/docker where the encoding is eg ANSI crappe

**Comment by zklaus** [comment]
In an email exchange, a similar issue surfaced. @ledm, you mentioned a PR, but none exists so far, right?

**Comment by remi-kazeroni** [comment]
Hi @valeriupredoi, do you still have this in your radar? Would it be possible for you to take a look at this issue this week so that it could go into the release? If not, please assign it to the next milestone. Thanks a lot 🍺

**Comment by valeriupredoi** [comment]
this is M2.9 material 120%

**Comment by valeriupredoi** [comment]
sorry @bouweandela - I'll change it to 2.9 and promise I'll have a good stab at it in the first weeks after 2.8 release :+1:

**Comment by bouweandela** [comment]
@valeriupredoi Any appetite to fix this before the feature freeze of v2.9 on Monday?

**Comment by valeriupredoi** [comment]
> sorry @bouweandela - I'll change it to 2.9 and promise I'll have a good stab at it in the first weeks after 2.8 release +1

V from the Past: you fool! :rofl:

**Comment by valeriupredoi** [comment]
so March 31st is just around the corner so I'll start this early :rofl:  *ie* now :+1:
