### ISSUE TITLE
Only display warning about needing an ESGF account when downloading CORDEX

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#1590]
At the moment, users are always warned that they need to set up an ESGF account when they use the download feature. However, this is only needed for downloading CORDEX data. It would be better to only display this message when it is actually useful.

**Comment by zklaus** [comment]
Rather than hard-coding this to CORDEX, it would be good to get the information from the server on whether there is an authentication restriction. This may be tied to the new search functionality. In any case, we might want to confer with @agstephens or Phil Kershaw.
