### ISSUE TITLE
Docker image can't write temp fille in /opt/conda/envs/esmvaltool

### ISSUE THREAD

**Issue by senesis** [ESMValGroup/ESMValCore#1591]
**Describe the bug**
Trying to launch the docker stable image on TGCC using [pcocc](https://pcocc.readthedocs.io/), I get an error :
>     OSError: [Errno 30] Read-only file system: '/opt/conda/envs/esmvaltool/.tmph8wij1lp'

I have no way to grant root privilege to my instance for writing there.  Is there a way to configure conda (e.g. through ~/.condarc) for using an alternate location ? 

Here is the full error report

>  ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
> 
>     Traceback (most recent call last):
>       File "/opt/conda/lib/python3.9/site-packages/conda/exceptions.py", line 1080, in __call__
>         return func(*args, **kwargs)
>       File "/opt/conda/lib/python3.9/site-packages/conda/cli/main.py", line 84, in _main
>         exit_code = do_call(args, p)
>       File "/opt/conda/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
>         return getattr(module, func_name)(args, parser)
>       File "/opt/conda/lib/python3.9/site-packages/conda/cli/main_run.py", line 25, in execute
>         script_caller, command_args = wrap_subprocess_call(on_win, context.root_prefix, prefix,
>       File "/opt/conda/lib/python3.9/site-packages/conda/utils.py", line 403, in wrap_subprocess_call
>         with Utf8NamedTemporaryFile(mode='w', prefix=tmp_prefix, delete=False) as fh:
>       File "/opt/conda/lib/python3.9/site-packages/conda/auxlib/compat.py", line 88, in Utf8NamedTemporaryFile
>         return NamedTemporaryFile(
>       File "/opt/conda/lib/python3.9/tempfile.py", line 541, in NamedTemporaryFile
>         (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
>       File "/opt/conda/lib/python3.9/tempfile.py", line 251, in _mkstemp_inner
>         fd = _os.open(file, flags, 0o600)
>     OSError: [Errno 30] Read-only file system: '/opt/conda/envs/esmvaltool/.tmpyh7ykxho'
> 
> `$ /opt/conda/bin/conda run --name esmvaltool esmvaltool`
> 
>   environment variables:
>                  CIO_TEST=<not set>
>                CONDA_ROOT=/opt/conda
>            CURL_CA_BUNDLE=<not set>
>                      PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin
>                           :/bin
>        REQUESTS_CA_BUNDLE=<not set>
>             SSL_CERT_FILE=<not set>
> 
>      active environment : None
>        user config file : /src/ESMValCore/~/.condarc
>  populated config files : 
>           conda version : 4.11.0
>     conda-build version : not installed
>          python version : 3.9.5.final.0
>        virtual packages : __linux=3.10.0=0
>                           __glibc=2.31=0
>                           __unix=0=0
>                           __archspec=1=x86_64
>        base environment : /opt/conda  (read only)
>       conda av data dir : /opt/conda/etc/conda
>   conda av metadata url : None
>            channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
>                           https://repo.anaconda.com/pkgs/main/noarch
>                           https://repo.anaconda.com/pkgs/r/linux-64
>                           https://repo.anaconda.com/pkgs/r/noarch
>           package cache : /opt/conda/pkgs
>                           /src/ESMValCore/~/.conda/pkgs
>        envs directories : /src/ESMValCore/~/.conda/envs
>                           /opt/conda/envs
>                platform : linux-64
>              user-agent : conda/4.11.0 requests/2.27.1 CPython/3.9.5 Linux/3.10.0-1160.59.1.el7.x86_64 debian/11 glibc/2.31
>                 UID:GID : 38578:33263
>              netrc file : None
>            offline mode : False
> 
> 
>

**Comment by zklaus** [comment]
Thanks @senesis for pointing this out. I think you may have run into the same problem described in ESMValGroup/ESMValTool#2575. This will be fixed by updating the conda version in the container and we hope to have a new, functioning container soon.
