### ISSUE TITLE
Smarter area weighted sum

### ISSUE THREAD

**Issue by znicholls** [ESMValGroup/ESMValCore#1613]
Follows comment made [here](https://github.com/ESMValGroup/ESMValCore/pull/1574#issuecomment-1123428679) (other issues could also be spun out of that comment). 

**Is your feature request related to a problem? Please describe.**

Currently, when doing an area-weighted sum, the units are not changed. They should be multiplied with area ** 2.

**Would you be able to help out?**

Yes, but this would not be a backwards compatible change so I would need guidance.

**Comment by znicholls** [comment]
Was some discussion in https://github.com/ESMValGroup/ESMValCore/pull/418 already

**Comment by bouweandela** [comment]
Maybe it would be good to raise this issue with the iris developers too. We're using iris to compute area statistics and iris is supposed to handle metadata correctly for you (this is one of the big advantages of using iris over xarray), but apparently it doesn't.

**Comment by zklaus** [comment]
With regards to Iris, the thing is that the function takes the weights as an array, not as a cube or similar (coordinate, cell measure, ancillary variable), so they don't come with units and indeed Iris has no way of knowing that these particular weights happen to be areas. Of course, that could (and perhaps should?) be changed. Why not accept all those things I mentioned above and integrate proper unit handling?

**Comment by bouweandela** [comment]
Or maybe it could even be just a string: if the cube has a `'cell area'` cell measure attached and I ask for
```python
cube.collapsed(['latitude', 'longitude'], iris.analysis.SUM, weights='cell_area')
```
shouldn't that just work? Instead of having to do:
```python
cube.collapsed(['latitude', 'longitude'], iris.analysis.SUM, weights=cube.cell_measures('cell area').core_data())
```

**Comment by schlunma** [comment]
I opened an issue in iris about this, already have a working solution :+1: 

https://github.com/SciTools/iris/issues/5082
