### ISSUE TITLE
Custom user-defined location for custom CMOR tables

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#1623]
Currently, the location of custom CMOR tables is [hardcoded](https://github.com/ESMValGroup/ESMValCore/blob/933b37b225a89aeed84029d8c83105407ed7ae5f/esmvalcore/cmor/table.py#L820).

To facilitate the evaluation of new variables coming from native model output or new model components (e.g., ESM2025 project) that are not yet avaialble in the official CMOR tables, I think it would be good to allow the user the definition of a custom location for these custom CMOR tables in the `config-developer-yml` file. This can be implemented very easily [here](https://github.com/ESMValGroup/ESMValCore/blob/933b37b225a89aeed84029d8c83105407ed7ae5f/esmvalcore/cmor/table.py#L58).

The ultimate goal is of course to extend the CF standard names and/or CMOR tables, but since this process can take quite a while I think this feature would be great for users who want to have a quick look of newly defined variables. @zklaus what do you think? Would be great to get this into v2.6, I could open a PR today.

**Comment by sloosvel** [comment]
> Would be great to get this into v2.6, I could open a PR today.

I closed the milestone this morning since yesterday was the due date for the feature freeze. Do you need it reopened?

**Comment by schlunma** [comment]
No, I don't think that's necessary. Would it be okay to include this in v2.6 nevertheless? I think it's only a minimal change to the code base, and we haven't performed any tests yet. I will take care that this gets merged quickly in case we agree to include it. Thanks!!
