### ISSUE TITLE
[EMAC] Quicklook quality control

### ISSUE THREAD

**Issue by axel-lauer** [ESMValGroup/ESMValCore#163]
*Task*

- [x] run quicklook system on EMAC historical run
- [x] check results

**Comment by LisaBock** [comment]
Tasks after first quality control (2-years data):

- [ ] sithick: averaging without zero values?
- [ ] prl, pr, prsn, prc, evspsbl: change plot_units to mm/Tag
- [ ] clt: values to high - multiplied twice by 100
- [ ] TN_GHG_CO2: 1e-6 to small
- [ ] SHIP_SO2, SHIP_NO, ROAD_NO, BB_SO2, BB_NO, BB_CO, ANTHNT_SO2, ANTHNT_NO, ANTHNT_CO given in molecules: update conversion
- [ ] BB_SO2, ANTHNT_SO2, ANTHNT_NO, ANTHNT_CO, ANTHNT_AER: changing custom CMOR table
- [ ] Sea salt: all modes are considered?
- [ ] MP_S = 0: controlling EMAC output

- [ ] headings overlap in some cases with "1e..." specification
