### ISSUE TITLE
Test fail if CEDA ESGF archive is down

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1637]
See [test fails](https://github.com/ESMValGroup/ESMValCore/actions/runs/2522354760) - all of them and their dog have died when CEDA archive was down a couple days ago - I thought we fixed this behaviour and got the rerouting done if one ESGF archive was down, I might be slightly out the loop if this was done, but clearly is still causing total test failures. @bouweandela what you reckon? :beer:

**Comment by zklaus** [comment]
To be clear, in this case this was a planned maintenance at CEDA. I saw the fails and double-checked this. It did make me wonder: Should we have some kind of status page or log of past CI failures?

**Comment by valeriupredoi** [comment]
> > Should we have some kind of status page or log of past CI failures?
> 
> It is available here: https://app.circleci.com/insights/github/ESMValGroup/ESMValCore/workflows/nightly/overview?branch=main&reporting-window=last-90-days

thanks, Bouwe! That is returning a Server Error for me at the mo, but also I'd be looking into a log of the GA tests - those are a bit harder to track after they've failed since one needs to scroll through a lot more test results (since they are 8-10x more numerous)

**Comment by bouweandela** [comment]
Maybe you need to sign in on CircleCI to see the test results? You can sign in with your GitHub account.

**Comment by valeriupredoi** [comment]
so I've set this up https://meercode.io with ESMValCore's Github Actions as Integration (it has many more CI integrations available) - it's pretty nifty - see attached example screenshot - but this is set up as a user so I am not sure how we can integrate it inside our organization. Just a pointer if you guys want to have a look at it
![GA-Dashboard](https://user-images.githubusercontent.com/28983971/174783631-67c35112-94c2-4437-8d1c-a3af6f7e7b57.png)
