### ISSUE TITLE
Test failure due to change in cf-units

### ISSUE THREAD

**Issue by zklaus** [ESMValGroup/ESMValCore#1655]
For a couple of days now, we have seen our tests fail. The problem stems from a change in the latest cf-units release where the handling of the `gregorian` and `standard` calendars was changed, namely SciTools/cf-units#205. This creates the failure in our tests where they find now the calendar to be `standard` instead of `gregorian`. The quick fix is to just change the tests to expect `standard`, but I have a lingering concern that other places like diag scripts may be surprised to find `standard` now.

This is similar to ESMValGroup/ESMValTool#2705.

**Comment by bouweandela** [comment]
For the upcoming release and to avoid a lot of last-minute work, would it be an option to just pin cf-units to the version that we know works and that @sloosvel already ran all the tests with for now?

**Comment by zklaus** [comment]
I think pinning would be ok. For completeness' sake, the release notes for cf-units 3.1.0 are [here](https://github.com/SciTools/cf-units/releases/tag/v3.1.0). Hopefully, it will help us deal with calendar issues in the future.

**Comment by valeriupredoi** [comment]
shall we resurrect this now that all release chores are done?
