### ISSUE TITLE
Running sum as a preprocessor function

### ISSUE THREAD

**Issue by malininae** [ESMValGroup/ESMValCore#1663]
Hi, 

I want to volunteer to write a new preprocessor function something like running sum/mean/max/min etc for the 'time' coordinate based on the 'iris.rolling_window' function.  I needed it to calculate Rx2day and TX3x ETCCDI indices. So far I have done it in the diagnostic, but I think the community would  profit from it as a preprocessor function. If people are interested, I will create a pull request.

**Comment by schlunma** [comment]
Hi @malininae, that sounds great! I started developing something like this some time ago but that never made it into the `main` branch. Feel free to re-use anything from this: https://gist.github.com/schlunma/efd574e5e5217d601d83b1bf0bae3e8d

Please open a pull request and ping me, I am happy to review it. Thanks!!

**Comment by valeriupredoi** [comment]
@malininae that's awesome, many thanks! You can ask me give you a hand with writing the tests, so we don't overload Manuel :grin:

**Comment by malininae** [comment]
> Hi @malininae, that sounds great! I started developing something like this some time ago but that never made it into the `main` branch. Feel free to re-use anything from this: https://gist.github.com/schlunma/efd574e5e5217d601d83b1bf0bae3e8d
> 
> Please open a pull request and ping me, I am happy to review it. Thanks!!

@schlunma, @valeriupredoi  I was thinking about creating a function something like 'time_convolution' and it would be similar to 'timeseries_filter', but would it be better to be 'coordinate_convolution' to make it broader?  Or should I expand 
 the 'timeseries_filter' but with different options?

**Comment by schlunma** [comment]
I think that depends on what you want to do...If you just want to run a running sum on the time coordinate, I think it would be nice to write this preprocessor as general as possible with arbitrary `coordinate`, `operation`, and `window_length` (see the code I posted).

If you want a more specific version with special weights that make only sense for the time axis then probably an extension of `timeseries_filter` or a new `timeseries_convolution` make more sense.
