### ISSUE TITLE
Add conda-forge-feedstock-pr-action to gh actions?

### ISSUE THREAD

**Issue by zklaus** [ESMValGroup/ESMValCore#1665]
More of an idea rather than a fixed suggestion. There is now [a github action](https://github.com/joezuntz/conda-forge-feedstock-pr-action) that can automatically open a PR on the feedstock. This could potentially replace the bot opening a PR for the update. I see two main advantages: It could be quicker than waiting for the bot, and we might be able to add it for the pre-release as well. This would further cut down on the load for the release manager.

@ESMValGroup/esmvaltool-coreteam, thoughts?

**Comment by zklaus** [comment]
> I guess we would create a fork of the feedstocks from `ESMValGroup` in this case?

Yes, that sounds right.

> And can we disable the bot opening PRs?

Probably. In any case, I think the bot will compare version numbers, so if we are faster, it will just not spring into action.

**Comment by valeriupredoi** [comment]
that looks good - all we have to do is to add the `Make PR on conda forge feedstock` step to our existing `build-and-deploy-on-pypi` workflow - but can we deactivate the feedstock bot?

**Comment by valeriupredoi** [comment]
OK I completely forgot about this - guess it's the next RM that'll test it :rofl:

**Comment by remi-kazeroni** [comment]
Hi @valeriupredoi, I see this issue is in the v2.8 milestone but the corresponding PR has v2.9 instead. Could you please let us know if that is still plan for v2.8 or not and put both issue and PR in the same milestone? Thanks a lot 🍺

**Comment by valeriupredoi** [comment]
uff I'd really like to test this during a live release but never have the chance to since it's too much else to do for the actual release; I'll move this to 2.9 - we got too much to do for 2.8 already
