### ISSUE TITLE
Consider dropping `pytest-flake8` plugin

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1699]
It seems there's not much love between `flake8` and `pytest-flake8` (see eg https://github.com/tholo/pytest-flake8/issues/87#issuecomment-1216704377 ) and if you look up that issue there are people saying `pytest-flake8` is going its own way proper, and it's not condoned by the Pytest community - we've already had issues before and even now, and asking the `flake8` devs to fix stuff only worsens the situation, since they are not communicating with the plugin devs. Can we suggest alternatives for the plugin plss @ESMValGroup/technical-lead-development-team

**Comment by bouweandela** [comment]
Maybe it's best to drop it, we also had issues when the previous version of flake8 was released (#1405). We could just use flake8 without the plugin and run it before running the unit tests with pytest.

**Comment by valeriupredoi** [comment]
sorry @bouweandela - this went off the radar screen faster than an F-117A Nighthawk, could you pls give me an example of the workflow that does that? I am struggling to think of an example other than the pre-commit shambles in https://github.com/ESMValGroup/ESMValCore/pull/1701 that neither me nor you are fans of :beer:

**Comment by bouweandela** [comment]
Remove the pytest-flake8 dependency from setup.py and replace every call to pytest by two separate calls, one to `flake8` and one to `pytest`, e.g.
https://github.com/ESMValGroup/ESMValCore/blob/4bb30611615bad43fe872e4ad7d03dc3aa140802/.circleci/config.yml#L30-L31
would need to be replaced by
```bash
             flake8 -j 4
             pytest -n 4 -m "not sequential" --junitxml=report-1.xml 
             pytest -n 0 -m "sequential" --cov-append --junitxml=report-2.xml 
```
and the configuration
https://github.com/ESMValGroup/ESMValCore/blob/4bb30611615bad43fe872e4ad7d03dc3aa140802/setup.cfg#L13-L14
would need to be moved to a section called `[flake8]`, as described [here](https://flake8.pycqa.org/en/latest/user/configuration.html).

**Comment by valeriupredoi** [comment]
thanks @bouweandela - most useful! I'll do this then, bit of a PITA but heyho
