### ISSUE TITLE
Codacy issue `Django was not configured` keeps popping up in pull requests

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#1703]
Recently, we saw the Codacy issue

```
Django was not configured. For more information run pylint --load-plugins=pylint_django --help-msg=django-not-configured 
```

popping up in some PRs (e.g., [here](https://app.codacy.com/gh/ESMValGroup/ESMValCore/pullRequest?prid=10002238&bid=30646651)).

@ESMValGroup/esmvaltool-coreteam do we use Django anywhere in the code? I couldn't find a reference to it. Running the suggested command above gives

```bash
$ pylint --load-plugins=pylint_django --help-msg=django-not-configured
:django-not-configured (E5110): *Django was not configured. For more information run pylint --load-plugins=pylint_django --help-msg=django-not-configured*
  Finding foreign-key relationships from strings in pylint-django requires
  configuring Django. This can be done via the DJANGO_SETTINGS_MODULE
  environment variable or the pylint option django-settings-module, eg: `pylint
  --load-plugins=pylint_django --django-settings-module=myproject.settings` .
  This can also be set as an option in a .pylintrc configuration file. Some
  basic default settings were used, however this will lead to less accurate
  linting. Consider passing in an explicit Django configuration file to match
  your project to improve accuracy. This message belongs to the django foreign
  keys referenced by strings checker.
```

So I guess we are using the `pylint-django` plugin? Could we disable this?

**Comment by valeriupredoi** [comment]
`django=4.1` is inside the Core environment via `pylint-django=2.0.11`  - I scanned the issues at PyCQA/pylint here https://github.com/PyCQA/pylint/issues but couldn't see anything obvious, and given that I had a rather nasty back and forth with one of the PyCQA/flake8 devs last time around (an absolute gammon), I'd rather not go and open another issue where that individual might snoop around :grin:

**Comment by zklaus** [comment]
Curious indeed. The Codacy configuration says it uses our config file, which does not contain the Django plugin, so I think it should not be run. Does this happen for all PRs? Can we keep an eye on it to see if it was a fluke?

**Comment by zklaus** [comment]
One last comment: python-django seems to be pulled in by prospector. Of course, just because it's installed shouldn't mean that it gets run, but I am not quite sure why it should be installed in the first place, particularly if it pulls in a heavy package like Django itself.

**Comment by valeriupredoi** [comment]
and in ESMValTool `django` tags along from the get-going from `esmvalcore`

**Comment by schlunma** [comment]
> Curious indeed. The Codacy configuration says it uses our config file, which does not contain the Django plugin, so I think it should not be run. Does this happen for all PRs? Can we keep an eye on it to see if it was a fluke?

I saw it in multiple PRs

**Comment by bouweandela** [comment]
Maybe this could be a solution? https://prospector.landscape.io/en/master/profiles.html#libraries-used-and-autodetect

I'll make a pull request.

**Comment by schlunma** [comment]
A recent example: https://app.codacy.com/gh/ESMValGroup/ESMValCore/pullRequest?prid=9879541&bid=30334383

**Comment by schlunma** [comment]
I haven't see this is an a long time, closing for now.
