### ISSUE TITLE
Add Met Office-specific paths to the ESMValTool user configuration file

### ISSUE THREAD

**Issue by mo-tgeddes** [ESMValGroup/ESMValCore#1708]
Add Met Office-specific paths to the ESMValTool user configuration file, e.g. like JASMIN.

**Comment by valeriupredoi** [comment]
cheers for opening this @mo-tgeddes - could you also please add concise information on how to obtain a login and access to the MO machine (in the documentation) in the PR that closes this? :beer: Note that it would be nice to have info on how to access the cluster-wide installation of esmvaltool at the Met Office too (if there's one), but prob best not in the PR that fixes this :+1:
