### ISSUE TITLE
Using CMORCheck directly on an Iris cube results in errors about lon and lat units for valid units

### ISSUE THREAD

**Issue by evertrol** [ESMValGroup/ESMValCore#172]
When I read a netCDF file with Iris, and then proceed to use the resulting cube with `CMORCheck`, the metadata checker throws errors about the longitude and latitude units: "lon: units should be degrees_east, not degrees" and similar for latitude / degrees_north.
The file itself is correct, as `ncdump` or using the `netCDF4` package show.

The reason appears because Iris reduces the units to purely degrees, since that is what the unit actually is: direction is set by the coordinate system. Details and discussion in [this closed Iris issue](https://github.com/SciTools/iris/issues/148) from October 2012.
As a result, the Iris cube has units "degrees" for longitude and latitude, and `CMORCheck(...).check_metadata()` compares these units with those defined in, in my case, the CMIP5 tables.

I've briefly spoken with @bouweandela , and he mentioned that normally, this is avoided, since the netCDF file is usually loaded in the `preprocessor._io` module, which uses [the callback option to `iris.load_raw()`](https://github.com/ESMValGroup/ESMValCore/blob/development/esmvalcore/preprocessor/_io.py#L38) to adjust the unit names.

Since the `CMORCheck` class is a documented core API, I figured I'd leave a note about this behaviour. I can't really judge whether this should be considered a bug.

Below is a short script to reproduce, its result and a CDL file to create a near-minimal netCDF file to use as input.

---

Python code:
```python
import sys
import iris
import netCDF4 as nc
from esmvalcore.cmor.check import CMORCheck
from esmvalcore.cmor.table import CMIP5Info

info = CMIP5Info('cmip5-cmor-tables')
varinfo = info.get_variable('Amon', 'tas')
ds = nc.Dataset(sys.argv[1])
print('> netCDF4:', ds.variables['lon'].units)
cube = iris.load(sys.argv[1])[0]
print('> Iris:', cube.coord('longitude').units)
checker = CMORCheck(cube, varinfo,  fail_on_error=False, automatic_fixes=False)
checker.check_metadata()
```

Output:
```text
> netCDF4: degrees_east
> Iris: degrees
Traceback (most recent call last):
  File "testcase.py", line 14, in <module>
    checker.check_metadata()
  File "/usr/local/lib/python3.7/site-packages/esmvalcore/cmor/check.py", line 104, in check_metadata
    self.report_errors()
  File "/usr/local/lib/python3.7/site-packages/esmvalcore/cmor/check.py", line 122, in report_errors
    raise CMORCheckError(msg)
esmvalcore.cmor.check.CMORCheckError: There were errors in variable tas:
lon: units should be degrees_east, not degrees
 lat: units should be degrees_north, not degrees
in cube:
air_temperature / (K)               (time: 12; latitude: 2; longitude: 3)
     Dimension coordinates:
          time                           x             -             -
          latitude                       -             x             -
          longitude                      -             -             x
     Scalar coordinates:
          height: 2.0 m
     Attributes:
          original_name: 2T
     Cell methods:
          mean: time (3 hours)
```

Input CDL file:
```text
netcdf bad_coordinate_units {
dimensions:
	time = UNLIMITED ;
	lat = 2 ;
	lon = 3 ;
	bnds = 2 ;
variables:
	double time(time) ;
		time:bounds = "time_bnds" ;
		time:units = "days since 2005-1-1" ;
		time:calendar = "gregorian" ;
		time:axis = "T" ;
		time:long_name = "time" ;
		time:standard_name = "time" ;
	double time_bnds(time, bnds) ;
	double lat(lat) ;
		lat:bounds = "lat_bnds" ;
		lat:units = "degrees_north" ;
		lat:axis = "Y" ;
		lat:long_name = "latitude" ;
		lat:standard_name = "latitude" ;
	double lat_bnds(lat, bnds) ;
	double lon(lon) ;
		lon:bounds = "lon_bnds" ;
		lon:units = "degrees_east" ;
		lon:axis = "X" ;
		lon:long_name = "longitude" ;
		lon:standard_name = "longitude" ;
	double lon_bnds(lon, bnds) ;
	double height ;
		height:units = "m" ;
		height:axis = "Z" ;
		height:positive = "up" ;
		height:long_name = "height" ;
		height:standard_name = "height" ;
	float tas(time, lat, lon) ;
		tas:standard_name = "air_temperature" ;
		tas:long_name = "Near-Surface Air Temperature" ;
		tas:units = "K" ;
		tas:original_name = "2T" ;
		tas:cell_methods = "time: mean (interval: 3 hours)" ;
		tas:coordinates = "height" ;
		tas:missing_value = 1.e+20f ;
		tas:_FillValue = 1.e+20f ;

data:
  lat = -15, 15 ;
  lat_bnds = -45, 0, 0, 45 ;
  lon = 30, 60, 90;
  lon_bnds = 15, 45, 45, 75, 75, 105 ;
  time = 15.5, 45, 74.5, 105, 135.5, 166, 196.5, 227.5, 258, 288.5, 319, 349.5 ;

  time_bnds = 0, 31, 31, 60, 60, 91, 91, 121, 121, 152, 152, 182, 182, 213,
    213, 244, 244, 274, 274, 305, 305, 335, 335, 365 ;
  height = 2 ;
  tas = 240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240,
    240, 240, 240, 240, 240, 240, 240, 240 ;
}
```

**Comment by valeriupredoi** [comment]
the entry in the `CMIP5_grids` CMOR table for `longitude` is:
```
!============
variable_entry: longitude
!============
!----------------------------------
standard_name:    longitude
units:            degrees_east
long_name:        longitude coordinate
dimensions:       longitude latitude
!----------------------------------
!
! Additional axis information:
!----------------------------------
out_name:         lon
valid_min:        0.           ! CMOR will add n*360 to input values
                               ! (where n is an integer) to ensure
                               !  longitudes are in proper range.
valid_max:        360.         !  see above comment.
!----------------------------------
```
so the checker is merely comparing the cube units with the entry in the CMOR table and raises the error if automatic fixes are turned off. If you turn those on (as is the default in the tool's run) you won't run into this non-existent issue :beer:

**Comment by evertrol** [comment]
Do you mean turning on the automatic fixes?

I just like to verify whether a file is correct, not fix it if it's incorrect. So that I can compile a list of invalid files, and decide (manually) whether I need to remove or fix them, or leave them as is. 
Which is also why I prefer to have `fail_on_error` turned off, so I can obtain a list of all errors in the file.

**Comment by valeriupredoi** [comment]
the best, safest and most hassle-free way to do that is not to use the checker as a stand alone function but to run the tool (`esmvaltool`) on a batch of data for a number of variables of interest - that way you replicate the actual behavior of the data ingestion together with the associated concatenations, checks and their errors, just as @bouweandela has told you there are a bunch of callback funcs and fixes that are applied and you shouldn't be concerned unless you get a real checker error from running `esmvaltool`. I suggest a very simple recipe with just the default preprocessor (ie no preprocessor specified in any of your variables).

**Comment by valeriupredoi** [comment]
also, our resident CMOR specialist is @jvegasbsc so he can tell you lots of stories, way more than myself :grin:

**Comment by bouweandela** [comment]
From my point of view this is an iris issue.

> I've briefly spoken with @bouweandela , and he mentioned that normally, this is avoided, since the netCDF file is usually loaded in the preprocessor._io module, which uses the callback option to iris.load_raw() to adjust the unit names.

You can use [`esmvalcore.preprocessor.load`](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/api/esmvalcore.preprocessor.html#esmvalcore.preprocessor.load) instead of `iris.load` to avoid the problem altogether.

**Comment by jvegasbsc** [comment]
This a known "issue" of Iris: it simplifies the degrees units. The checker is working as expected, as we don't want it to fix anything if automatic fixes are not applied
