### ISSUE TITLE
Dataset problem: siconc variable in EC-Earth3-Veg and EC-Earth3-Veg-LR models

### ISSUE THREAD

**Issue by egalytska** [ESMValGroup/ESMValCore#1731]
**Describe the dataset issue**
A clear and concise description of what the problem with the data is is. Here are some guidelines that you can use
right out the box by filling in the blanks (note that, if needed we will assist you with writing a fix; also note that
if the problem is with a CMIP6 dataset, we will alert the ESGF and/or the model developers for them to fix the problem
in the long run; fixes for CMIP5 by the model developers are no longer possible):

- Data file has been changed by you in any way (if you answer yes the issue will be void and closed, we are not
supporting custom-made datasets that present problems, it is your resposability to fix those problems): NO

- Project: CMIP6
- Full dataset description (fill out as many as you know, please):
  - dataset:EC-Earth3-Veg and EC-Earth3-Veg-LR
  - experiment:historical;ssp585
  - ensemble: r1i1p1f1
  - mip:SImon
  - grid:gn
  - ~~type~~:
  - ~~version~~: 
  - ~~tier~~:
  - variable used: siconc
  - data version: latest
- Problems encountered (please describe what the actual problems are: e.g. wrong standard name, issue with dimensions):

For both models **siconc** variable from historical and ssp585 experiments can not be concatenated. 

- Pointer to existing copy of data on ESGF node (it would be very useful if you could provide a physical
fullpath to the file(s) that are causing the problem, e.g. on CEDA Jasmin or DKRZ):

DKRZ: 
EC-Earth3-Veg
/work/ik1017/CMIP6/data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg/historical/r1i1p1f1/SImon/siconc/gn/v20200919
/work/ik1017/CMIP6/data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp585/r1i1p1f1/SImon/siconc/gn/v20200919
EC-Earth3-Veg-LR
/work/ik1017/CMIP6/data/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/SImon/siconc/gn/v20200919
/work/ik1017/CMIP6/data/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/ssp585/r1i1p1f1/SImon/siconc/gn/v20201201

- Other notes and mentions:
I have tried some fixes in a local branch and they seemed to fix these issues.

**Assign the right people**
If you are already a member of the ESMValTool GitHub project, please assign Valeriu Predoi (valeriupredoi) and
Klaus Zimmermann (zklaus) to the issue. They will then check the issue raised and propagate it further to the
data model developers.

**Please attach**
  - The recipe that you are trying to run, you can find a copy in the `run` directory in the output directory [recipe_seaice_tests.yml.txt](https://github.com/ESMValGroup/ESMValCore/files/9664503/recipe_seaice_tests.yml.txt)

  - The `main_log_debug.txt` file, this can also be found in the `run` directory in the output directory
  - [main_log_debug_EC-Earth3-Veg.txt](https://github.com/ESMValGroup/ESMValCore/files/9664522/main_log_debug_EC-Earth3-Veg.txt)
  - [main_log_debug_EC-Earth3-Veg-LR.txt](https://github.com/ESMValGroup/ESMValCore/files/9664536/main_log_debug_EC-Earth3-Veg-LR.txt)

  - Attach a text file with the output of `ncdump -h /path/to/file.nc`
[ncdump_EC-Earth3-Veg-LR_ssp585.txt](https://github.com/ESMValGroup/ESMValCore/files/9664623/ncdump_EC-Earth3-Veg-LR_ssp585.txt)
[ncdump_EC-Earth3-Veg-LR_historical.txt](https://github.com/ESMValGroup/ESMValCore/files/9664624/ncdump_EC-Earth3-Veg-LR_historical.txt)
[ncdump_EC-Earth3-Veg_ssp585.txt](https://github.com/ESMValGroup/ESMValCore/files/9664625/ncdump_EC-Earth3-Veg_ssp585.txt)
[ncdump_EC-Earth3-Veg_historical.txt](https://github.com/ESMValGroup/ESMValCore/files/9664626/ncdump_EC-Earth3-Veg_historical.txt)

Cheers :beer:

**Comment by malininae** [comment]
I think I also had that issue with these models, but concatenating historical and ssp245.

**Comment by egalytska** [comment]
> I think I also had that issue with these models, but concatenating historical and ssp245.

Hi Lisa. The same (siconc) or other variables as well?

**Comment by malininae** [comment]
> > I think I also had that issue with these models, but concatenating historical and ssp245.
> 
> Hi Lisa. The same (siconc) or other variables as well?

So far I got issues with `siconc` in `SImon`. Otherwise I use `tasmax` and `pr` in `day` and at least `EC-Earth3-Veg` `r1i1p1f1` seemed to work. I'd need to look at `EC-Earth3-Veg-LR`

**Comment by egalytska** [comment]
@remi-kazeroni and @bsolino, I have the fixes for this issue. I can open a pull request, right?

**Comment by remi-kazeroni** [comment]
> > > I think I also had that issue with these models, but concatenating historical and ssp245.
> > 
> > 
> > Hi Lisa. The same (siconc) or other variables as well?
> 
> So far I got issues with `siconc` in `SImon`. Otherwise I use `tasmax` and `pr` in `day` and at least `EC-Earth3-Veg` `r1i1p1f1` seemed to work. I'd need to look at `EC-Earth3-Veg-LR`

From what I could see, this problem only affects the `siconc` variable among commonly used variables.

**Comment by bouweandela** [comment]
I'm running into the same issues with `tos`.

**Comment by bouweandela** [comment]
```
ncdump -h /work/bd0854/DATA/ESMValTool2/download/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp126/r1i1p1f1/Omon/tos/gn/v20221112/tos_Omon_EC-Earth3-Veg_ssp126_r1i1p1f1_gn_210001-210012.nc
netcdf tos_Omon_EC-Earth3-Veg_ssp126_r1i1p1f1_gn_210001-210012 {
dimensions:
	time = UNLIMITED ; // (12 currently)
	j = 292 ;
	i = 362 ;
	bnds = 2 ;
	vertices = 4 ;
variables:
	double time(time) ;
		time:bounds = "time_bnds" ;
		time:units = "days since 1850-01-01 00:00:00" ;
		time:calendar = "proleptic_gregorian" ;
...
```
and
```
ncdump -h /work/bd0854/DATA/ESMValTool2/download/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg/historical/r1i1p1f1/Omon/tos/gn/v20211207/tos_Omon_EC-Earth3-Veg_historical_r1i1p1f1_gn_185001-185012.nc
netcdf tos_Omon_EC-Earth3-Veg_historical_r1i1p1f1_gn_185001-185012 {
dimensions:
	time = UNLIMITED ; // (12 currently)
	j = 292 ;
	i = 362 ;
	bnds = 2 ;
	vertices = 4 ;
variables:
	double time(time) ;
		time:bounds = "time_bnds" ;
		time:units = "days since 1850-01-01 00:00:00" ;
		time:calendar = "gregorian" ;

```

**Comment by bouweandela** [comment]
@egalytska Any reason you picked the proleptic_gregorian calendar instead of the standard/gregorian calendar? Neither the historical nor the future experiment crosses the [1582 date](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#calendar), so for me the standard/gregorian calendar would seem a more logical choice.

**Comment by egalytska** [comment]
Hi @bouweandela, no, no specific reason. I just used/adopted the existing fixes, and they worked for the siconc datasets...
The examples what I did are here: https://github.com/ESMValGroup/ESMValCore/pull/1771/files
