### ISSUE TITLE
Release v2.7.0 code freeze and Highlights

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1740]
@ESMValGroup/esmvaltool-developmentteam heads up the Core release v2.7.0 code freeze is happening today, and I need to ask you for two things (do either or both, please, but I need some input for the second point):

- if you have a **very strong** intention to have any of your Pull Requests merged and featured in 2.7 please let me know today - and I need that PR to be shipshape - reviewed and approved, tests passing (bar the odd Codacy/Django-related thingie that we still ought to solve), labels added, description in - all that jazz;
- propose **one highlight** that we will feature in the Highlights section of the Changelog/release notes: just as Sean Connery says in The Hunt for Red October - one ping, Vasili, just one ping! One highlight per dev team member, please :beer: Have a look at the closed and merged PRs [here](https://github.com/ESMValGroup/ESMValCore/pulls?q=is%3Apr+is%3Aclosed) and the ones that are still open and marked with [Milestone 2.7](https://github.com/ESMValGroup/ESMValCore/pulls?q=is%3Aopen+is%3Apr+milestone%3Av2.7.0); include your preference in a comment to this issue, please :beer: 

Muchos cheers :beer:

**Comment by valeriupredoi** [comment]
@valeriupredoi chosen highlight https://github.com/ESMValGroup/ESMValCore/pull/1702

**Comment by schlunma** [comment]
I couldn't find another highlight, so also voting for #1702 :smile:

**Comment by remi-kazeroni** [comment]
In case we could have more than one highlight in the Highlights section of the Changelog, I'd propose #1678

**Comment by valeriupredoi** [comment]
cheers, guys! Yes, I was planning on 2-3 highlights, depending what we consider worth a highlight (ie not gonna add the bot's conda-lock PR as highlight obviously, even though we should probably start making friends with the bots, Skynet may be upon us soon :grin: )

**Comment by bettina-gier** [comment]
Yeah seems quite bare in terms of new features or notable fixes, think unless anything else comes in the two you guys proposed are probs best.

**Comment by valeriupredoi** [comment]
Tina, low chances anything extraordinaire will pop up, I already froze the thing :grin:

**Comment by valeriupredoi** [comment]
PS - pro tip - if you want to be the release manager and not work your butt off (like poor @sloosvel had to), be an RM for the October release, after dead months like July and August :grin:

**Comment by bouweandela** [comment]
Instead of the single pull request https://github.com/ESMValGroup/ESMValCore/pull/1678, we could maybe highlight the improved support for native models? By the looks of it, this was very nicely done in a series of pull requests: #1678, #1694, #1705, #1718.

**Comment by valeriupredoi** [comment]
OK guys we have us a v2.7.0 release, currently just on PyPi https://pypi.org/project/ESMValCore/ - all Circle, readthedocs and GA tests passed fine, currently waiting on the DockerHub to build us the new release. For the record, we have tested (most all) Tool recipes with the RC2 of this stable release here https://github.com/ESMValGroup/ESMValTool/issues/2833 - I will update you once we have it all spiffy on conda-forge and close this issue, provided all goes well. Many thanks for your patience and support so far :beer:

**Comment by valeriupredoi** [comment]
OK update: Docker builds :green_circle: - episode 2 is Operation Conda Forge, this stuff's better than Netflix :laughing:

**Comment by valeriupredoi** [comment]
OK guys, ta to @zklaus who pointed me to here https://gitter.im/conda-forge/conda-forge.github.io where I found out the regro bot is sick, but currently being tendered for so one of the guys fixing it recommended I should wait until tomorrow, and (hopefully) it'll be back to functional and pick up our 2.7.0 PR :+1:

**Comment by valeriupredoi** [comment]
bot was nice enough to come back to life so we have us a release PR that just got merged, yay https://github.com/conda-forge/esmvalcore-feedstock/pull/50
