### ISSUE TITLE
Tests failing for Python<3.10 - error stemming from PR 1713

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1747]
@bouweandela please see [fails](https://github.com/ESMValGroup/ESMValCore/actions/runs/3189986408/jobs/5204475390) - could you plese fix this asap, bud? I always turn on GA tests on feature branches to catch exactly these sort of issues (and yes, I should have turned them on in yer branch before merging #1713 but heyho). @schlunma if you are around before Bouwe sees this and know a qwikfix, then please jump in :ocean:

**Comment by schlunma** [comment]
Yeah, I think this should be simple, let me open a fix for that

**Comment by valeriupredoi** [comment]
absolute legend, Manu :medal_military:

**Comment by bouweandela** [comment]
Sorry about the mess, thanks guys!
