### ISSUE TITLE
Improve instructions on ESGF credentials

### ISSUE THREAD

**Issue by nhsavage** [ESMValGroup/ESMValCore#1766]
**Is your feature request related to a problem? Please describe.**
When using data from ESGF the instructions on how to set up credentials in esmvalcore/_config/_esgf_pyclient.py could be clearer.

specifically:
 * make it clear that the keyring will probably only work on desktop systems and not clusters and why
 * make it easier to work out what hostname is

**Would you be able to help out?**
Yes, I will attempt to do a PR for this soon

**Comment by bouweandela** [comment]
@nhsavage You mentioned at the workshop that you were having some issues getting login to work. Did you manage in the end?

**Comment by nhsavage** [comment]
I did get it work, but only by using a different login - something seems wrong with my CEDA login even just dropping down to the pyesgf module at the command line I couldn't authenticate but this seems to be specific to me (other people can).

**Comment by dhohn** [comment]
Could be a particular character in your password. I had that here too: https://github.com/Prodiguer/synda/issues/197

**Comment by nhsavage** [comment]
I have checked that and it's not that (was suggested by CEDA support)

**Comment by nhsavage** [comment]
thanks for the offer but I've concluded it's not worth chasing as it seems to be a very minor edge case
