### ISSUE TITLE
Version number on `main` branch is stuck at v2.7.0rc3

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#1773]
The version number on the `main` branch appears to be stuck on v2.7.0rc3 instead of v2.7.0:
```
$ esmvaltool version
ESMValCore: 2.7.0rc3.dev10+g3149d07eb
ESMValTool: 2.6.1.dev48+gd3ef603b4.d20221027
```

I'm not sure I quite understand how the release happened, but I suspect that this happened because the release was made off of another branch than `main`. That branch was subsequently merged into `main` in #1756, but because it was squash merged `main` still does not contain the same commits as the `v2.7.0` tag and that causes the `main` branch to show the previous version number.

I tried, and merging the `v2.7.0` tag into `main` and re-installing the ESMValCore package from source does seem to solve the problem.

**Comment by valeriupredoi** [comment]
there was no `rc3` so this is even weirder

**Comment by valeriupredoi** [comment]
@bouweandela do you think a merge of the release branch into `main` (direct, no PR hence no squash) would fix that?

**Comment by bouweandela** [comment]
Yes

**Comment by bouweandela** [comment]
Or a pull request which is not squash merged but merged normally, that would be even better because more clear to everyone.
