### ISSUE TITLE
When using multiple experiments for a single dataset (e.g., `exp: [historical, ssp585]`), the resulting attributes in the cubes can change from run to run, depending on the order in which the files have been read.

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#1779]
When using multiple experiments for a single dataset (e.g., `exp: [historical, ssp585]`), the resulting attributes in the cubes can change from run to run, depending on the order in which the files have been read.

Example:

```
:experiment = "ESM RCP8.5;ESM historical" ;
:experiment_id = "esmrcp85;esmHistorical" ;
```

vs.

```
:experiment = "ESM historical;ESM RCP8.5" ;
:experiment_id = "esmHistorical;esmrcp85" ;
```

Relevant code: https://github.com/ESMValGroup/ESMValCore/blob/354ee551db9bde9c5fe202f72d26388cd950dc98/esmvalcore/preprocessor/_io.py#L228

_Originally posted by @schlunma in https://github.com/ESMValGroup/ESMValTool/discussions/2901#discussioncomment-4020154_

**Comment by schlunma** [comment]
Looking into this right now
