### ISSUE TITLE
Doc build failing

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1780]
[fail](https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore/7739/workflows/c9adb4a3-d511-4fd7-a0df-de1c2529d09d/jobs/35598) - am very bemused, since that scipy inv file exists - I don't really understand what the problem is, @bouweandela any clue? :beer: Seems Nov 1st is the day of the dead docs :skull:

**Comment by zklaus** [comment]
It seems docs.scipy.org really was down for some time. This problem is solved now and the builds are fine again.

**Comment by valeriupredoi** [comment]
thanks @zklaus :beer:
