### ISSUE TITLE
Problem reading files with start year 0001 and calendar 'noleap'

### ISSUE THREAD

**Issue by npgillett** [ESMValGroup/ESMValCore#1782]
When I try to read in data from files with start date '0001' and calendar 'noleap', some of the years are not read in. If I request years from 1 to 150, I get a file with only 104 years in it. esmvalcore does not give an error message, but it returns a file with the wrong number of years. The input NetCDF files contain data for all the years requested. 

This applies for example to all the abrupt 4xCO2 simulations from CESM2, CESM2-WACCM, CESM2-WCCCM-FV2, NorESM2-LM, NorESM2-MM.

@malininae suggests that this may be connected with cftime having problems handling a 365-day calendar.

In the example below, you can see that despite the fact that I requested 0001 to 0150 for NorESM2-LM, the preprocessor returns files for years 0001 - 0104. (Note that this does not directly throw up an error, but I get an error when the files are passed to my diagnostic script, because the files are not the length I expect). This error is not specific to one file or variable, and appears for all the models above not just this one.

Thanks for the help!

[recipe_proportionality.yml.txt](https://github.com/ESMValGroup/ESMValCore/files/9933789/recipe_proportionality.yml.txt)
[main_log_debug.txt](https://github.com/ESMValGroup/ESMValCore/files/9933785/main_log_debug.txt)

**Comment by schlunma** [comment]
Hi @npgillett, YAML [treats numbers starting with a `0` as octal numbers](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/recipe/overview.html#recipe-section-datasets). Try using `150` instead of `0150` in your recipe (and similar for all other numbers), this should do the trick!

**Comment by npgillett** [comment]
Thanks very much! Yes, omitting the leading zeroes in the years fixed the problem..
