### ISSUE TITLE
Tests failing left, right, and centre on Circle and Github Actions

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1788]
The new pytest-mypy is causing phenomenal test fails - frankly I've no idea why, I can't understand the standards complaints, if anyone more literate in PEP can, please explain @ESMValGroup/technical-lead-development-team - this PR https://github.com/ESMValGroup/ESMValCore/pull/1787 uses the pin on pytest-mypy (at 0.10.0, 0.10.1 is causing the whole hubbub)

**Comment by schlunma** [comment]
Some of this is changed in https://github.com/ESMValGroup/ESMValCore/pull/1769.

I think we should pin `mypy` now, then merge https://github.com/ESMValGroup/ESMValCore/pull/1769, and then fix the remaining issues. They should be fairly simply to solve.

**Comment by valeriupredoi** [comment]
d3eal, lemme RfR that PR, add a bit of description, then call you up for review :+1:
