### ISSUE TITLE
Issues from PR 1769 for older Pythons and OSX

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1793]
We get a number of fails for tests other than Python=3.10 and/or Linux64 https://github.com/ESMValGroup/ESMValCore/actions/runs/3461961077 - @bouweandela could you have a looksee please

- Python 3.8 Linux64 typing error (fixed in https://github.com/ESMValGroup/ESMValCore/pull/1795)
- OSX (and Linux64) - seems to be random - sample data missing when it's cloudy outside (fixed in https://github.com/ESMValGroup/ESMValCore/pull/1797)

**Comment by bouweandela** [comment]
I'm not sure what's causing the problem with the sample data not being found occasionally. Maybe it's some race condition with the configuration since multiple tests might be modifying it in parallel..
