### ISSUE TITLE
Installing `iris-esmf-regrid` as a dependency

### ISSUE THREAD

**Issue by sloosvel** [ESMValGroup/ESMValCore#1794]
**Is your feature request related to a problem? Please describe.**
As mentioned in https://github.com/ESMValGroup/Community/discussions/56#discussioncomment-3981066 , `iris-esmf-regrid` should be added as a dependency in ESMValCore in order to ease its installation process. 

For the moment it would be best to keep both the "regular" regridding and the iris-esmf ones, as even though iris-esmf performs better, there are functionalities that are missing from the package. 

Tests should also be added.

**Would you be able to help out?**
Yes

**Comment by sloosvel** [comment]
I think it would be good to take care of #1542 before adding new dependencies though. @ESMValGroup/esmvaltool-coreteam If no one is working on that already I can give it a try as well, it was already done for the tool

**Comment by schlunma** [comment]
I think V is already taking care of that in #1786 :+1:

**Comment by sloosvel** [comment]
Ah right sorry, I got lost in all the issues :sweat_smile:

**Comment by sloosvel** [comment]
Regarding the tests, there are some differences between the usual regridding and the iris-esmf one. The current area_weighted scheme, tested as:

```
    def test_regrid__area_weighted(self):
        data = np.empty((1, 1))
        lons = iris.coords.DimCoord([1.6],
                                    standard_name='longitude',
                                    bounds=[[1, 2]],
                                    units='degrees_east',
                                    coord_system=self.cs)
        lats = iris.coords.DimCoord([1.6],
                                    standard_name='latitude',
                                    bounds=[[1, 2]],
                                    units='degrees_north',
                                    coord_system=self.cs)
        coords_spec = [(lats, 0), (lons, 1)]
        grid = iris.cube.Cube(data, dim_coords_and_dims=coords_spec)
        result = regrid(self.cube, grid, 'area_weighted')
        expected = np.array([1.499886, 5.499886, 9.499886])
        np.testing.assert_array_almost_equal(result.data, expected, decimal=6)
```

Returns an array of (3,), whereas the same call with iris-esmf returns an array of (3, 1, 1). Is that a big deal? It would be no problem to squeeze the cube if so.

Also the call to `esmf_regrid.schemes.regrid_rectilinear_to_rectilinear` is failing for some reason. I guess all schemes should be supported, so I need to look into it

**Comment by schlunma** [comment]
I think `(3, 1, 1)` is the "more" correct shape since the grid is a `(1, 1)` cube, so I guess this is fine. I don't think the old regridding schemes should drop the dimensions here.

**Comment by valeriupredoi** [comment]
> I think V is already taking care of that in #1786 +1

that's done now, guys :ok:
