### ISSUE TITLE
Proposal to deprecate the `callback` argument from `esmvalcore.preprocessor.load` in v2.8 and remove it in v2.10.

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#1800]
I would like to deprecate the `callback` argument from the [`esmvalcore.preprocessor.load`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/api/esmvalcore.preprocessor.html#esmvalcore.preprocessor.load) function because it

1) does not seem likely that anyone uses this as it cannot be meaningfully set from the recipe
2) prevents implementation of a simple `Dataset.load` function in #1609. See the [example notebook](https://github.com/ESMValGroup/ESMValCore/blob/split-recipe/notebooks/Dataset.ipynb) for the intended use of `Dataset.load`. This function would do everything related to loading the data: fixes, cmor checks, concatenation, and attaching ancillary variables.

@ESMValGroup/esmvaltool-coreteam Would this change cause problems for your work?

**Comment by schlunma** [comment]
Sounds good to me!

**Comment by valeriupredoi** [comment]
can we maybe convert it to a different load engine eg an xarray dataset or a GRIB file? I am starting to think how to support other formats, like GRIB

**Comment by zklaus** [comment]
> can we maybe convert it to a different load engine eg an xarray dataset or a GRIB file? I am starting to think how to support other formats, like GRIB

Iris supports Grib perfectly fine; no change needed.

I am ok with removing the callback as-is. Mid- to long-term, we might want to use the (extended?) Iris callback functionality for some of the fixing. That should help avoid most `fix_file` fixes.

**Comment by valeriupredoi** [comment]
@bouweandela I started working on this here https://github.com/ESMValGroup/ESMValCore/pull/1901

**Comment by bouweandela** [comment]
Thanks V! I did the same thing in https://github.com/ESMValGroup/ESMValCore/pull/1801, but then I realized that this change was backward incompatible, even if nobody might be using the feature, so I thought it might be better to deprecate it instead and add some workarounds so it keeps working even with the new `esmvalcore.dataset.Dataset.load` function.

**Comment by valeriupredoi** [comment]
we could just remove it and not deprecate it since only two cmorizers use the load callback, apart from that no recipe afaik - we can just fix those cmorizers?

**Comment by valeriupredoi** [comment]
> I did the same thing in https://github.com/ESMValGroup/ESMValCore/pull/1801

Sorry for starting a new PR, bud - I completely missed the linked PR upstream - my old Firefox has lost the ability to remove floating temporary popping windows so I might have missed that hidden behind one of those (need to upgrade, yes, I know :grin: )

**Comment by remi-kazeroni** [comment]
Hi @valeriupredoi and @bouweandela, shall we move this to v2.9 since the corresponding PR was shifted to v2.9? Or do you think you would have time to address this issue during this week? Thanks 👍

**Comment by valeriupredoi** [comment]
@remi-kazeroni I think @bouweandela is rather under a lot of snow with 1609 and the other baby PRs belonging to it - maybe we can push this to 2.9 since it's not a history-defining change anyways?

**Comment by bouweandela** [comment]
In #1609, I deprecated the feature and set the version for removing it to v2.10. I'll bump this issue to v2.10 too then.
