### ISSUE TITLE
Problems with the ESMF shared library and setuptools>65.5.0

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1824]
We have started seeing [test fails](https://github.com/ESMValGroup/ESMValCore/actions/runs/3523909643/jobs/5910336042) that are currently localized and env solving-dependent ie they occur only when the solver picks up setuptools>65.5 and @bouweandela found the actual root of the problem that is described in this issue https://github.com/numpy/numpy/issues/22623 with a TL;DR that ESMF uses numpy's distutils that is not supporting setuptools>65.5 - the question here is what to do avoid these fails (that will creep up even more in the future):

- we pin setuptools
- we pin setuptools in esmf conda package
- anything else?

Ping @ESMValGroup/technical-lead-development-team

**Comment by valeriupredoi** [comment]
what's wrong with this one? https://github.com/esmf-org/esmf

**Comment by valeriupredoi** [comment]
> Does anyone have access to the ESMF issue tracker? The best approach would be to check if there is already an issue there and if not report it.

there isn't on the GH Issues tracker, and if there is elsewhere the good folk at ESMF will point us to that one :grin:

**Comment by bouweandela** [comment]
Great to see that they moved to GitHub! When I tried to find it last time, I ended up on SourceForge and needed to create an account. Once I had done that, I still couldn't see the issue tracker, and then I gave up.

**Comment by valeriupredoi** [comment]
I vaguely remember doing the same, for ESMF actually, some 2-3 years ago

**Comment by valeriupredoi** [comment]
we are not seeing any more issues as of late (the test fail log is so old that I can't even access it anymore) with setuptools=67.7 and esmf=8.4 (current), so am gonna close this (will reopen if needed)
