### ISSUE TITLE
Add data finder to the public API

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#1825]
It would be nice to add some of the functionality in `esmvalcore/_data_finder.py` to the public API. An example of what the public API could look like is available [here](https://esmvaltool--1609.org.readthedocs.build/projects/ESMValCore/en/1609/api/esmvalcore.local.html). I used the module name `esmvalcore.local` because we also have `esmvalcore.esgf` which provides similar functions for files on ESGF. Opinions anyone? @ESMValGroup/esmvaltool-coreteam

**Comment by valeriupredoi** [comment]
completely agreed! But there are quite a few specialized (private or not) funcs in that module that will be hard for users to understand and use, we should probably get out to public just a subset of its methods - like `_find_input_files` that is private now

**Comment by bouweandela** [comment]
Yes, my proposal would be to keep all of those private for now and only expose a single function for finding files called [`find_files`](https://esmvaltool--1609.org.readthedocs.build/projects/ESMValCore/en/1609/api/esmvalcore.local.html#esmvalcore.local.find_files), similar to how it's named in the [`esmvalcore.esgf`](https://esmvaltool--1609.org.readthedocs.build/projects/ESMValCore/en/1609/api/esmvalcore.local.html#esmvalcore.local.find_files) module, and a single [`LocalFile`](https://esmvaltool--1609.org.readthedocs.build/projects/ESMValCore/en/1609/api/esmvalcore.local.html#esmvalcore.local.find_files) class for representing the files that have been found (basically just `pathlib.Path`, but with an extra `facets` property).
