### ISSUE TITLE
Allow arbitrary kwargs for preprocessors that use `iris.cube.Cube.collapsed` or `iris.cube.Cube.aggregated_by`

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#1851]
**Is your feature request related to a problem? Please describe.**

Many iris operators used for collapsing/aggregating allow arbitrary kwargs (see [example](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris/analysis.html#iris.analysis.PERCENTILE)). We use `iris.cube.Cube.collapsed`/ `iris.cube.Cube.aggregated_by` in many preprocessors, so it might make sense to allow arbitrary kwargs in the recipes.

Affected preprocessors:

- `multi_model_statistics`
- `ensemble_statistics`
- `climate_statistics`
- `area_statistics`
- `zonal_statistics`
- `meridional_statistics`
- `volume_statistics`
- `axis_statistics`
- `hourly_statistics`
- `daily_statistics`
- `monthly_statistics`
- `seasonal_statistics`
- `annual_statistics`
- `decadal_statistics`

**Comment by valeriupredoi** [comment]
good idea! Do we know which of those are lazy? Also, do we know which are slower/faster? Do we care about performance - well, indirect performance, via iris using internal or external methods, but directly affecting our resources.

**Comment by schlunma** [comment]
Since basically all of them use iris, I guess that all of them are lazy. There's a list [here](https://github.com/ESMValGroup/ESMValCore/issues/674), but not sure how up-to-date that is.

Regarding performance, I'm not quite sure how that is relevant to this issue, it's just about allowing additional options (which as far as I can tell are not about performance) :smile:
