### ISSUE TITLE
Update esmpy dependency

### ISSUE THREAD

**Issue by zklaus** [ESMValGroup/ESMValCore#1870]
With version `8.4.0`, the esmpy package changed a couple of things. Most importantly, the main package name changed from `ESMF` to `esmpy`, but possibly more names changed internally.

I think we should:
1. pin `esmpy <8.4` https://github.com/ESMValGroup/ESMValCore/pull/1871
2. add a repodata patch to conda-forge to apply the same pinning for older versions of ESMValTool
3. update our code so it works with both versions #1876
4. update iris-esmf-regrid (and iris itself?) so it works with both versions and make a new release https://github.com/SciTools-incubator/iris-esmf-regrid/issues/227
5. unpin esmpy

**Comment by valeriupredoi** [comment]
indeed tests are failing on both CI's, see eg [GA test fail](https://github.com/ESMValGroup/ESMValCore/actions/runs/3681260173/jobs/6227759758). I have pinned `esmpy <8.4.0` in the 2.7.1 autotick PR https://github.com/conda-forge/esmvalcore-feedstock/pull/52 just now. I think we should first release that then apply the repo patch, what do you think @zklaus ?
