### ISSUE TITLE
Issue loading some `OBS` data with the latest installation containing `iris3.4.0`

### ISSUE THREAD

**Issue by remi-kazeroni** [ESMValGroup/ESMValCore#1875]
**Describe the bug**
I recently (yesterday) made a new installation of the Tool, that is:
```bash
$ esmvaltool version

ESMValCore: 2.7.1
ESMValTool: 2.7.1.dev31+g68c73b288

$ mamba list iris
iris                      3.4.0              pyhd8ed1ab_0    conda-forge

```

and noticed that the recipe of the PR I was reviewing was no longer running successfully. I then tested quite a few recipes with this new installation, all running fine, except the [recipe_ecs_scatter.yml](https://github.com/ESMValGroup/ESMValTool/blob/main/esmvaltool/recipes/recipe_ecs_scatter.yml) which fails with:

```bash
esmvalcore.preprocessor:338 Failed to run preprocessor function 'load' on the data
['/work/bd0854/DATA/ESMValTool2/OBS/Tier2/HadISST/OBS_HadISST_reanaly_1_Amon_ts_187001-201712.nc']
```

<details><summary>see details</summary>
ERROR 1: PROJ: proj_create_from_database: Open of /work/bd0854/b309192/soft/mambaforge/envs/tool/share/proj failed

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[2], line 1
----> 1 cube = iris.load_raw('/work/bd0854/DATA/ESMValTool2/OBS/Tier2/HadISST/OBS_HadISST_reanaly_1_Amon_ts_187001-201712.nc')

File /work/bd0854/b309192/soft/mambaforge/envs/tool/lib/python3.10/site-packages/iris/__init__.py:434, in load_raw(uris, constraints, callback)
    431 from iris.fileformats.um._fast_load import _raw_structured_loading
    433 with _raw_structured_loading():
--> 434     return _load_collection(uris, constraints, callback).cubes()

File /work/bd0854/b309192/soft/mambaforge/envs/tool/lib/python3.10/site-packages/iris/__init__.py:284, in _load_collection(uris, constraints, callback)
    282 try:
    283     cubes = _generate_cubes(uris, callback, constraints)
--> 284     result = _CubeFilterCollection.from_cubes(cubes, constraints)
    285 except EOFError as e:
    286     raise iris.exceptions.TranslationError(
    287         "The file appears empty or incomplete: {!r}".format(str(e))
    288     )

File /work/bd0854/b309192/soft/mambaforge/envs/tool/lib/python3.10/site-packages/iris/cube.py:104, in _CubeFilterCollection.from_cubes(cubes, constraints)
    102 pairs = [_CubeFilter(constraint) for constraint in constraints]
    103 collection = _CubeFilterCollection(pairs)
--> 104 for cube in cubes:
    105     collection.add_cube(cube)
    106 return collection

File /work/bd0854/b309192/soft/mambaforge/envs/tool/lib/python3.10/site-packages/iris/__init__.py:269, in _generate_cubes(uris, callback, constraints)
    267 if scheme == "file":
    268     part_names = [x[1] for x in groups]
--> 269     for cube in iris.io.load_files(part_names, callback, constraints):
    270         yield cube
    271 elif scheme in ["http", "https"]:

File /work/bd0854/b309192/soft/mambaforge/envs/tool/lib/python3.10/site-packages/iris/io/__init__.py:223, in load_files(filenames, callback, constraints)
    221 fnames = handler_map[handling_format_spec]
    222 if handling_format_spec.constraint_aware_handler:
--> 223     for cube in handling_format_spec.handler(
    224         fnames, callback, constraints
    225     ):
    226         yield cube
    227 else:

File /work/bd0854/b309192/soft/mambaforge/envs/tool/lib/python3.10/site-packages/iris/fileformats/netcdf/loader.py:574, in load_cubes(filenames, callback, constraints)
    571 if mesh is not None:
    572     mesh_coords, mesh_dim = _build_mesh_coords(mesh, cf_var)
--> 574 cube = _load_cube(engine, cf, cf_var, filename)
    576 # Attach the mesh (if present) to the cube.
    577 for mesh_coord in mesh_coords:

File /work/bd0854/b309192/soft/mambaforge/envs/tool/lib/python3.10/site-packages/iris/fileformats/netcdf/loader.py:287, in _load_cube(engine, cf, cf_var, filename)
    282 _assert_case_specific_facts(engine, cf, cf_var.cf_group)
    284 # Run the actions engine.
    285 # This creates various cube elements and attaches them to the cube.
    286 # It also records various other info on the engine, to be processed later.
--> 287 engine.activate()
    289 # Having run the rules, now add the "unused" attributes to each cf element.
    290 def fix_attributes_all_elements(role_name):

File /work/bd0854/b309192/soft/mambaforge/envs/tool/lib/python3.10/site-packages/iris/fileformats/_nc_load_rules/engine.py:97, in Engine.activate(self)
     86 def activate(self):
     87     """
     88     Run all the translation rules to produce a single output cube.
     89 
   (...)
     95 
     96     """
---> 97     run_actions(self)

File /work/bd0854/b309192/soft/mambaforge/envs/tool/lib/python3.10/site-packages/iris/fileformats/_nc_load_rules/actions.py:521, in run_actions(engine)
    510 """
    511 Run all actions for a cube.
    512 
   (...)
    517 
    518 """
    520 # default (all cubes) action, always runs
--> 521 action_default(engine)  # This should run the default rules.
    523 # deal with grid-mappings
    524 grid_mapping_facts = engine.fact_list("grid_mapping")

File /work/bd0854/b309192/soft/mambaforge/envs/tool/lib/python3.10/site-packages/iris/fileformats/_nc_load_rules/actions.py:74, in action_function.<locals>.inner(engine, *args, **kwargs)
     71 @wraps(func)
     72 def inner(engine, *args, **kwargs):
     73     # Call the original rules-func
---> 74     rule_name = func(engine, *args, **kwargs)
     75     if rule_name is None:
     76         # Work out the corresponding rule name, and log it.
     77         # Note: an action returns a name string, which identifies it,
     78         # but also may vary depending on whether it successfully
     79         # triggered, and if so what it matched.
     80         rule_name = _default_rulenamesfunc(func.__name__)

File /work/bd0854/b309192/soft/mambaforge/envs/tool/lib/python3.10/site-packages/iris/fileformats/_nc_load_rules/actions.py:90, in action_default(engine)
     87 @action_function
     88 def action_default(engine):
     89     """Standard operations for every cube."""
---> 90     hh.build_cube_metadata(engine)

File /work/bd0854/b309192/soft/mambaforge/envs/tool/lib/python3.10/site-packages/iris/fileformats/_nc_load_rules/helpers.py:216, in build_cube_metadata(engine)
    214 nc_att_cell_methods = getattr(cf_var, CF_ATTR_CELL_METHODS, None)
    215 with warnings.catch_warnings(record=True) as warning_records:
--> 216     cube.cell_methods = parse_cell_methods(nc_att_cell_methods)
    217 # Filter to get the warning we are interested in.
    218 warning_records = [
    219     record
    220     for record in warning_records
    221     if issubclass(record.category, UnknownCellMethodWarning)
    222 ]

File /work/bd0854/b309192/soft/mambaforge/envs/tool/lib/python3.10/site-packages/iris/fileformats/netcdf/saver.py:283, in parse_cell_methods(nc_cell_methods)
    281 cell_methods = []
    282 if nc_cell_methods is not None:
--> 283     for m in _split_cell_methods(nc_cell_methods):
    284         d = m.groupdict()
    285         method = d[_CM_METHOD]

File /work/bd0854/b309192/soft/mambaforge/envs/tool/lib/python3.10/site-packages/iris/fileformats/netcdf/saver.py:242, in _split_cell_methods(nc_cell_methods)
    240 for ii in range(len(name_start_inds) - 1):
    241     method_indices.append((name_start_inds[ii], name_start_inds[ii + 1]))
--> 242 method_indices.append((name_start_inds[-1], len(nc_cell_methods)))
    244 # Index the string and match against each substring
    245 nc_cell_methods_matches = []

IndexError: list index out of range
</details>

So I tried to load files directly and it seems that some `OBS` files can't be loaded, I'm not sure I understand why. I couldn't reproduce this issue with data from other projects like `OBS6` so far. Any idea @ESMValGroup/technical-lead-development-team? 

**Please attach**
Path to a troublesome file:
- DKRZ: `/work/bd0854/DATA/ESMValTool2/OBS/Tier2/HadISST/OBS_HadISST_reanaly_1_Amon_ts_187001-201712.nc`
- Jasmin `/gws/nopw/j04/esmeval/obsdata-v2/Tier2/HadISST/OBS_HadISST_reanaly_1_Amon_ts_187001-201712.nc`

**Comment by bouweandela** [comment]
It would be best to report this with iris. When I run this code with iris 3.4,
```python
>>> import iris
>>> cubes = iris.load("/work/bd0854/DATA/ESMValTool2/OBS/Tier2/HadISST/OBS_HadISST_reanaly_1_Amon_ts_187001-201712.nc")
```
the following traceback is shown
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/work/bd0854/b381141/mambaforge/envs/esmvaltool-v2.8.0-dev/lib/python3.10/site-packages/iris/__init__.py", line 318, in load
    return _load_collection(uris, constraints, callback).merged().cubes()
  File "/work/bd0854/b381141/mambaforge/envs/esmvaltool-v2.8.0-dev/lib/python3.10/site-packages/iris/__init__.py", line 284, in _load_collection
    result = _CubeFilterCollection.from_cubes(cubes, constraints)
  File "/work/bd0854/b381141/mambaforge/envs/esmvaltool-v2.8.0-dev/lib/python3.10/site-packages/iris/cube.py", line 104, in from_cubes
    for cube in cubes:
  File "/work/bd0854/b381141/mambaforge/envs/esmvaltool-v2.8.0-dev/lib/python3.10/site-packages/iris/__init__.py", line 269, in _generate_cubes
    for cube in iris.io.load_files(part_names, callback, constraints):
  File "/work/bd0854/b381141/mambaforge/envs/esmvaltool-v2.8.0-dev/lib/python3.10/site-packages/iris/io/__init__.py", line 223, in load_files
    for cube in handling_format_spec.handler(
  File "/work/bd0854/b381141/mambaforge/envs/esmvaltool-v2.8.0-dev/lib/python3.10/site-packages/iris/fileformats/netcdf/loader.py", line 574, in load_cubes
    cube = _load_cube(engine, cf, cf_var, filename)
  File "/work/bd0854/b381141/mambaforge/envs/esmvaltool-v2.8.0-dev/lib/python3.10/site-packages/iris/fileformats/netcdf/loader.py", line 287, in _load_cube
    engine.activate()
  File "/work/bd0854/b381141/mambaforge/envs/esmvaltool-v2.8.0-dev/lib/python3.10/site-packages/iris/fileformats/_nc_load_rules/engine.py", line 97, in activate
    run_actions(self)
  File "/work/bd0854/b381141/mambaforge/envs/esmvaltool-v2.8.0-dev/lib/python3.10/site-packages/iris/fileformats/_nc_load_rules/actions.py", line 521, in run_actions
    action_default(engine)  # This should run the default rules.
  File "/work/bd0854/b381141/mambaforge/envs/esmvaltool-v2.8.0-dev/lib/python3.10/site-packages/iris/fileformats/_nc_load_rules/actions.py", line 74, in inner
    rule_name = func(engine, *args, **kwargs)
  File "/work/bd0854/b381141/mambaforge/envs/esmvaltool-v2.8.0-dev/lib/python3.10/site-packages/iris/fileformats/_nc_load_rules/actions.py", line 90, in action_default
    hh.build_cube_metadata(engine)
  File "/work/bd0854/b381141/mambaforge/envs/esmvaltool-v2.8.0-dev/lib/python3.10/site-packages/iris/fileformats/_nc_load_rules/helpers.py", line 216, in build_cube_metadata
    cube.cell_methods = parse_cell_methods(nc_att_cell_methods)
  File "/work/bd0854/b381141/mambaforge/envs/esmvaltool-v2.8.0-dev/lib/python3.10/site-packages/iris/fileformats/netcdf/saver.py", line 283, in parse_cell_methods
    for m in _split_cell_methods(nc_cell_methods):
  File "/work/bd0854/b381141/mambaforge/envs/esmvaltool-v2.8.0-dev/lib/python3.10/site-packages/iris/fileformats/netcdf/saver.py", line 242, in _split_cell_methods
    method_indices.append((name_start_inds[-1], len(nc_cell_methods)))
IndexError: list index out of range
```
It looks like the [cell method](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch07s03.html) is a bit of text if I understand the CF conventions correctly:
```
ncdump -h /work/bd0854/DATA/ESMValTool2/OBS/Tier2/HadISST/OBS_HadISST_reanaly_1_Amon_ts_187001-201712.nc
netcdf OBS_HadISST_reanaly_1_Amon_ts_187001-201712 {
dimensions:
	time = UNLIMITED ; // (1776 currently)
	lat = 180 ;
	lon = 360 ;
	bnds = 2 ;
variables:
	double time(time) ;
		time:bounds = "time_bnds" ;
		time:calendar = "gregorian" ;
		time:long_name = "time" ;
		time:axis = "T" ;
		time:units = "days since 1950-01-01 00:00:00" ;
		time:standard_name = "time" ;
	double time_bnds(time, bnds) ;
	double lat(lat) ;
		lat:bounds = "lat_bnds" ;
		lat:long_name = "latitude" ;
		lat:axis = "Y" ;
		lat:units = "degrees_north" ;
		lat:standard_name = "latitude" ;
	double lat_bnds(lat, bnds) ;
	double lon(lon) ;
		lon:standard_name = "longitude" ;
		lon:units = "degrees_east" ;
		lon:axis = "X" ;
		lon:long_name = "longitude" ;
		lon:bounds = "lon_bnds" ;
	double lon_bnds(lon, bnds) ;
	float ts(time, lat, lon) ;
		ts:standard_name = "surface_temperature" ;
		ts:units = "K" ;
		ts:cell_methods = "time" ;
		ts:cell_measures = "area" ;
		ts:long_name = "Surface Temperature" ;
		ts:comment = "\"\"skin\"\" temperature (i.e., SST for open ocean)" ;
		ts:_FillValue = 1.e+20f ;

// global attributes:
		:title = "HadISST data reformatted for the ESMValTool v2.0" ;
		:tier = 2 ;
		:source = "http://www.metoffice.gov.uk/hadobs/hadisst/data/download.html" ;
		:reference = "Rayner et al., J. Geophys. Res., doi:10.1029/2002JD002670, 2013" ;
		:user = "b309057" ;
		:host = "m11517.hpc.dkrz.de" ;
		:history = "Created on Thu Feb 21 16:26:28 CET 2019" ;
		:conventions = "CF/CMOR" ;
}
```

**Comment by remi-kazeroni** [comment]
Reported to Iris in https://github.com/SciTools/iris/issues/5119

**Comment by bouweandela** [comment]
It looks like the malformed cell method could be a bug in the CMORizer script. The original data looks like this:
```
ncdump -h /work/bd0854/DATA/ESMValTool2/RAWOBS/Tier2/HadISST/HadISST_sst.nc 
netcdf HadISST_sst {
dimensions:
	time = UNLIMITED ; // (1787 currently)
	latitude = 180 ;
	longitude = 360 ;
	nv = 2 ;
variables:
	float time(time) ;
		time:units = "days since 1870-1-1 0:0:0" ;
		time:calendar = "gregorian" ;
		time:long_name = "Time" ;
		time:standard_name = "time" ;
	float time_bnds(time, nv) ;
	float latitude(latitude) ;
		latitude:units = "degrees_north" ;
		latitude:long_name = "Latitude" ;
		latitude:standard_name = "latitude" ;
	float longitude(longitude) ;
		longitude:units = "degrees_east" ;
		longitude:long_name = "Longitude" ;
		longitude:standard_name = "longitude" ;
	float sst(time, latitude, longitude) ;
		sst:_FillValue = -1.e+30f ;
		sst:standard_name = "sea_surface_temperature" ;
		sst:long_name = "sst" ;
		sst:units = "C" ;
		sst:cell_methods = "time: lat: lon: mean" ;
		sst:missing_value = -1.e+30f ;

// global attributes:
		:Title = "Monthly version of HadISST sea surface temperature component" ;
		:description = "HadISST 1.1 monthly average sea surface temperature" ;
		:institution = "Met Office Hadley Centre" ;
		:source = "HadISST" ;
		:reference = "Rayner, N. A., Parker, D. E., Horton, E. B., Folland, C. K., Alexander, L. V., Rowell, D. P., Kent, E. C., Kaplan, A.  Global analyses of sea surface temperature, sea ice, and night marine air temperature since the late nineteenth century J. Geophys. Res.Vol. 108, No. D14, 4407 10.1029/2002JD002670" ;
		:Conventions = "CF-1.0" ;
		:history = "14/1/2019 converted to netcdf from pp format" ;
		:supplementary_information = "Updates and supplementary information will be available from http://www.metoffice.gov.uk/hadobs/hadisst" ;
		:comment = "Data restrictions: for academic research use only. Data are Crown copyright see (http://www.opsi.gov.uk/advice/crown-copyright/copyright-guidance/index.htm)" ;
}
```
and that loads fine with iris.
