### ISSUE TITLE
Checking if data were previously downloaded before searching on ESGF

### ISSUE THREAD

**Issue by remi-kazeroni** [ESMValGroup/ESMValCore#1889]
**Is your feature request related to a problem? Please describe.**
If I use in my DKRZ config_file:
```
rootpath:
  CMIP5: [/work/bd0854/DATA/ESMValTool2/CMIP5_DKRZ, ~/download_dir/cmip5/output1]
drs:
  CMIP5: DKRZ
```  
the Tool will first search for data at DKRZ but ignore the download directory which has a different `drs` (`ESGF`, instead of `DKRZ`). If datasets are missing at DKRZ, the Tool then search for these data on ESGF before checking if the data were previously downloaded into the `download_dir`. When running "large" recipes (IPCC) this can result in a lot of ESGF searches because lots of CMIP5 data are missing at DKRZ even though all necessary data were downloaded during a previous recipe run. This could increase the risk of recipe failures if ESGF nodes are down even if no data download would have been needed.

Question: would it be possible and desirable to check if the data were previously downloaded before triggering a search on ESGF? @bouweandela, I understand my question might not be relevant once your work on dataset versioning would be merged. Or would that still happen?

Here is a minimal example where the ESGF search is done before using previously downloaded data
[main_log_debug.txt](https://github.com/ESMValGroup/ESMValCore/files/10401131/main_log_debug.txt)
[recipe_test.yml.txt](https://github.com/ESMValGroup/ESMValCore/files/10401132/recipe_test.yml.txt)

**Comment by bouweandela** [comment]
Could this be solved by #129?

An alternative is to change your configuration file: you can increase the ESGF search cache validity duration so the search doesn't actually connect to ESGF. This can be done by setting `expire_after` to a large value as described here: https://docs.esmvaltool.org/projects/esmvalcore/en/latest/quickstart/configure.html#configuration-file
