### ISSUE TITLE
Overview ESMValCore/ESMValTool documentation

### ISSUE THREAD

**Issue by mattiarighi** [ESMValGroup/ESMValCore#193]
This is to summarize the current status of the documentation and list the sections which are finished/wip/tobedone. It replaces the original issue [#1125](https://github.com/ESMValGroup/ESMValTool/issues/1125) by matching the actual structure of the sections on readthedocs for more clarity.

Please check :heavy_check_mark:  each item only when merged in the respective development branches (either ESMValCore or ESMValTool). Mark the work in progress by adding the link to the PR in brackets or tag the assignee).

**PRIORITY 1: add text to empty sections in the current structure**

**Preface**
- [x] Introduction
- [x] Objectives and approach
- [x] License
- [x] Architecture
- [ ] The ESMValTool core development team (subsection "Pull Requests" missing)

**Gallery**
OK

**Getting started**
- [ ] Installing ESMValTool (subsection on Docker missing, instructions must be checked for consistency with CONTRIBUTING.md)
- [x] User configuration file
- [ ] Input data (subsection on Models missing, requires also information on where to find the CMIP data and a link to [this page](http://clipc-services.ceda.ac.uk/dreq/index/var.html) as suggested by Lee)
- [x] Running ESMValTool
- [x] Output

**Recipes**
OK

**Core**
- [ ] Configuration files (section on logging missing)
- [x] Finding data
- [x] Recipe
- [ ] Preprocessor (section on CMOR missing)
- [x] Fixing data

**Guidelines for diagnostic developers**
- [x] Contributing a new diagnostic or recipe
- [ ] How to prepare and run your first diagnostic (subsection on config dictionary missing, required?)
- [x] Porting a namelist (recipe) or diagnostic to ESMValTool v2.0
- [ ] Developer configuration file (already explained in Section Core, I would remove)
- [x] Contributing a CMORizing script for an observational dataset
- [x] GitHub Workflow

**Core API Reference**
- [x] CMOR functions
- [ ] Preprocessor functions (looks complete, but I am not sure)

**ESMValTool Code API Documentation**
OK

**PRIORITY 2: add additional sections**
- [ ] Frequently Asked Questions (FAQs)
- [ ] Documentation on the shared tools in `diag_scripts/shared.py`
- [ ] Common pitfalls page for errors that we regularly encounter when writing a new recipe

**PRIORITY 3: finalize and clean**
- [ ] Homogenize writing style
- [ ] Check url links
- [ ] Check (and add) section refs
- [ ] Check figure refs
- [ ] Check table refs
- [ ] Check code snippets
- [ ] Use sphinx syntax for notes and warnings

**Comment by valeriupredoi** [comment]
related #302

**Comment by ledm** [comment]
Like I said in [ESMValTool #1574](https://github.com/ESMValGroup/ESMValTool/issues/1574#issuecomment-597099507), I'm happy to help with writing documentation.

**Comment by mattiarighi** [comment]
Replaced by #1574.
