### ISSUE TITLE
Combine `offline` and `always_search_esgf` into a single option `search_esgf`

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#1931]
The @ESMValGroup/technical-lead-development-team would like to combine the config-user.yml options `always_search_esgf` and `offline` into a new option `search_esgf` with possible values `never` (corresponds to the current `offline: true`), `default` (corresponds to the current `offline: false`), and `always` (corresponds with the current `offline: false` and `always_search_esgf: true`) and then retire the `offline` option at some point in the future.

_Originally posted by @bouweandela in https://github.com/ESMValGroup/ESMValCore/issues/1609#issuecomment-1424153588_

**Comment by valeriupredoi** [comment]
cheers @bouweandela :beer: Me happy to review and test!

**Comment by schlunma** [comment]
As discussed with @bouweandela I will open a PR for this soon :+1:
