### ISSUE TITLE
Test `test_extract_location` from the regrid testing suite fails very frequently with HTTP Request timed out (after several tries)

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#1982]
Connection errors when temporary internet issues induce the location extraction go boom, since it depends on the internets, see [failed test](https://github.com/ESMValGroup/ESMValCore/actions/runs/4485102863/jobs/7886304487) - this may bite when you most need it not to (eg during a package build). I am of the opinion to mark such failures as xfailed, rather than fails - but what do our Tech A-Team thin @ESMValGroup/technical-lead-development-team

**Comment by valeriupredoi** [comment]
I like that idea @bouweandela - let me do that then - how do we know which tests need the internets btw? Run them all while we've turned off our router? :laughing:  - btw that blithering test failed right on the cusp of 2.8 release, see [fail](https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore/8771/workflows/73a1a102-4ac6-44ff-b725-0f221727ee05/jobs/39005/steps)

**Comment by zklaus** [comment]
Are we sure this is due to connection failure? I see the following error
```
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Salamanca%2CCastilla+y+Le%C3%B3n%2CSpain&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
```

i.e. a usage limitation.

**Comment by bouweandela** [comment]
We probably hit the issue limitation due to too many tests using the service from the same computer.

**Comment by valeriupredoi** [comment]
that looks like a HTTP request happened too many retries - either internet down from the distribution node of the site, or the site down or the site got too many requests (like the EGU site :laughing: ) - at any rate, the root of the exception is HTTP-related, so we can make us a special marker that skips all HTTP-related exceptions - that way we avoid the esgf stuff too, and there was another category I forgot about

**Comment by valeriupredoi** [comment]
this blithering test failed every day for the nightly GA tests since the Easter break began, only to pass again last night - am just about to get a PR done with a pytest marker specific for this one, then we can talk about extending it to other HTTP-requesting tests, have had enough of this guy's unreliability. How can a server go on Easter break? :rofl:

**Comment by valeriupredoi** [comment]
these tests are now failing on an ndustrial scale - pretty much all our test sessions fail because of this, I opened an issue at geopy BTW https://github.com/geopy/geopy/issues/545

**Comment by zklaus** [comment]
@valeriupredoi, if the error messages don't convince you, perhaps [the usage policy](https://operations.osmfoundation.org/policies/nominatim/) will? The servers work as intended, we are abusing them. We should not call the servers from CI, maybe not have any calls in the tests at all?

**Comment by valeriupredoi** [comment]
happy to see someone is still reading usage policies :grin: - beats me if I see a ban on CIs though in there, albeit they do mention one should use it in a rather restricted manner - I find it a bit silly if we have to deactivate those tests TBF - I would argue we should just have them on and get this in to catch the stuff that Nominatim spits out when not happy - also, what puzzles me is why did they start dying with such high frequency only since a month or so ago, we'd had that test module for a while now, and there were no problems

**Comment by valeriupredoi** [comment]
OK - we have #2002 that takes care of skipping in case of HTTP barfs, we have the option to skip it altogether with an indiscriminate `pytest.skip`, we can remove it altogether, or we can `mock` it like Bouwe, Manu and Klaus say - which one to choose? I don't give two hoots about it as long as the damn thing stops failing, and taking forever while doing it :grin:

**Comment by schlunma** [comment]
I'll open a PR with the mocking approach, gimme a sec.

**Comment by schlunma** [comment]
See https://github.com/ESMValGroup/ESMValCore/pull/2005

**Comment by valeriupredoi** [comment]
yes, I had opened https://github.com/ESMValGroup/ESMValTool/issues/3157 for that - a bit tricksy since that test actually runs the recipe - maybe we can just not run the location extraction preprocessor. Also - have we decided to mock or to skip? I like Manu's mocking PR so am in favour of that, but there may be times when we actually want to run the actual test, and not just the mocker
