### ISSUE TITLE
Drop support for Python 3.8?

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#1995]
[NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) recommends that we drop support for Python 3.8 on Apr 14, 2023, so that would mean the v2.9.0 release.

**Comment by valeriupredoi** [comment]
the problem is that support for Python 3.11 is...complicated, see #1832

**Comment by bouweandela** [comment]
Iris will also drop support for Python 3.8 in the upcoming 3.6 release https://github.com/SciTools/iris/pull/5269.

**Comment by valeriupredoi** [comment]
We are literally yards away from getting in support for py311, so let's do the un-py38 then too 👍

**Comment by valeriupredoi** [comment]
Well, provided Tool doesn't complain about py311, that is...
