### ISSUE TITLE
Add Zenodo integration

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#2]
For reproducibility and to make the it easier to cite the ESMValTool Core package, we should add Zenodo integration, this will automatically upload a copy of the source code to Zenodo and generate a DOI for it every time we make a release on github. See [here](https://guide.esciencecenter.nl/citable_software/making_software_citable.html) for instructions.

**Comment by nielsdrost** [comment]
We also need this to "officially" hand in ESMValTool for the MAGIC project.

Note that we should enable this _before_ the next release, as Zenodo will only pick up new releases done after it has been enabled.
