### ISSUE TITLE
Docs can not be built on Readthedocs anymore when moving to new esmpy>=8.4 (and support for Python 3.11)

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#2001]
Readthedocs has the very annoying behaviour that:

- it does almost all its conda env building operations under the hood with close to no input from the user
- it does not `conda activate` an env that it has just built to build the docs

As such, from esmpy>=8.4, one needs to have a valid env variable called `$ESMFMKFILE` that points to a physical file, eg in my env it is `/home/valeriu/miniconda3/envs/py11/lib/esmf.mk` and it contains all the gubbins needed by esmpy to initialize the build libraries. I have tried to set that var in multiple ways in https://github.com/ESMValGroup/ESMValCore/pull/1832 but to no avail, without a proper conda activation (and initialization of all the CONDA vars by doing so) I hit rock bottom. @ESMValGroup/technical-lead-development-team any of you guys know a way to get this variable through the RTD machinery? Ultimately I can open an issue at RTD but let's exhaust all possible slutions before I do that :beer:

**Comment by valeriupredoi** [comment]
@zklaus proposed the nifty solution to use the `--stack` option in https://github.com/conda-forge/esmf-feedstock/issues/91 but alas, that's unusable on RTD because one can not access the conda operations via `.readthedocs.yaml` :moyai:

**Comment by bouweandela** [comment]
You could mock out esmpy when building the documentation, does that work?

**Comment by valeriupredoi** [comment]
> You could mock out esmpy when building the documentation, does that work?

can you be a bit more verbose about this pls, bud?

**Comment by valeriupredoi** [comment]
> > You could mock out esmpy when building the documentation, does that work?
> 
> can you be a bit more verbose about this pls, bud?

actually - this gave me an idea - how about we install esmpy after pip installing all the show, I reckon that'd take care of the env var - let me try

**Comment by zklaus** [comment]
I think the pip install we have in there is a bit wrong, since with the environment not activated, we are also not likely to get the right pip. I am looking into this now.

**Comment by valeriupredoi** [comment]
BTW good to have you back, gents :beers:

**Comment by valeriupredoi** [comment]
yeah, my idea didn't work out https://readthedocs.org/projects/esmvalcore/builds/20103755/ - you would think, that installing a package would result in the correct finding of its conda stuff and setting of the env vars - proves out no for the weird RTD environment; also, their conda is ancient and really needs updating :man_facepalming:

**Comment by bouweandela** [comment]
>> You could mock out esmpy when building the documentation, does that work?
>
>can you be a bit more verbose about this pls, bud?

https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_mock_imports

**Comment by zklaus** [comment]
This has been addressed in #2003, which will find its way into `main` with #1832. Unless we want that fixed independently/before Python 3.11 support, no further action is needed; this issue will be closed by #1832.

**Comment by valeriupredoi** [comment]
seems it didn't close it, so am doing it now
