### ISSUE TITLE
Wildcards are not being substituted in preproc filenames

### ISSUE THREAD

**Issue by sloosvel** [ESMValGroup/ESMValCore#2006]
**Describe the bug**
When creating a recipe that uses wildcards, the preprocessed filenames created from that recipe contain apostrophes and the wildcards are not being substituted. This can lead to overwritting of the files, and also makes navigating the preprocessed output more difficult.

**Comment by valeriupredoi** [comment]
@sloosvel could you pls provide a minimal example recipe so we can use that for testing? :beer:

**Comment by sloosvel** [comment]
Nevermind, it looks like my branch was missing a few pulls :sweat_smile:
