### ISSUE TITLE
The `extract_location` preprocessor doesn't work at the Met Office :(

### ISSUE THREAD

**Issue by ehogan** [ESMValGroup/ESMValCore#2012]
**Describe the bug**

A new ESMValTool user at the Met Office was following the [quick start guide](https://esmvalgroup.github.io/ESMValTool_Tutorial/01-quickstart/index.html) and using our new ESMValTool v2.8.0 environment, but the recipe raised the exception:
```
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443):
Max retries exceeded with url: /search?q=Amsterdam&format=json&limit=1 
(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: 
self-signed certificate in certificate chain (_ssl.c:997)')))
```
The recipe works fine with our ESMValTool v2.7.0 environment.

I have been investigating this for a while; here are the key points:

+ I did not see any problems when running this recipe on JASMIN.
+ In ESMValTool v2.8.0, the [esmvaltool/recipes/examples/recipe_python.yml](https://github.com/ESMValGroup/ESMValTool/compare/v2.7.0...v2.8.0#diff-9ede07c7320e4272382fe41064146c3f8583e358e1cd14e5aaa67a7884c8047d) recipe was updated to use the `extract_location` preprocessor.
+ The `extract_location` preprocessor is (as far as I can tell) the only function in the entire code base that uses `geopy`.
+ I can reproduce the problem by running the code [within the `extract_location` function](https://github.com/ESMValGroup/ESMValCore/blob/9406b7eb7828a8d1a1328697158e4e7805b0a3c6/esmvalcore/preprocessor/_regrid.py#L363) in an interactive Python session:
```
% python
Python 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from geopy.geocoders import Nominatim
>>> geolocator = Nominatim(user_agent="test_emma")
>>> geolocation = geolocator.geocode("Amsterdam")
Traceback (most recent call last):
  [...]
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443):
Max retries exceeded with url: /search?q=Amsterdam&format=json&limit=1
(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:
self-signed certificate in certificate chain (_ssl.c:997)')))
```
+ The problem ultimately is the fault of `geopy`, since  [`requests.Session().trust_env` is hard-coded in `geopy` to be equal to `False`](https://github.com/geopy/geopy/blob/2.3.0/geopy/adapters.py#L397), which prevents our SSL certificates from being used (see [Requests Documentation: trust_env](https://docs.python-requests.org/en/latest/api/#requests.Session.trust_env) for slightly more information). 
+ This can be overridden as follows:
```
% python
Python 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from geopy.geocoders import Nominatim
>>> import ssl
>>> ssl_context = ssl.create_default_context()
>>> geolocator = Nominatim(user_agent="test_emma", ssl_context=ssl_context)
>>> geolocation = geolocator.geocode("Amsterdam")
>>> print(geolocation)
Amsterdam, Noord-Holland, Nederland
>>> 
```
Would it be possible to implement this in ESMValCore, please? I'm not sure whether [ssl.create_default_context()](https://docs.python.org/3/library/ssl.html#ssl.create_default_context) would cause issues for others (I can't think of a reason why it would?), but I would be happy to create a PR for testing purposes?

**Comment by bouweandela** [comment]
> The problem ultimately is the fault of geopy

Maybe you could try raising the issue with `geopy` before implementing this in ESMValCore? In the end, that would make the entire `geopy` package useable from the Met Office instead of just the ESMValCore package, so it is solved there the impact will be larger.

**Comment by ehogan** [comment]
I did consider raising the issue with GeoPy before submitting this issue, but since the `ssl_context` is already configurable (see [GeoPy Documentation: geopy.geocoders.Nominatim](https://geopy.readthedocs.io/en/stable/index.html#geopy.geocoders.Nominatim.__init__)) I decided it wouldn't be worth proposing changes to the GeoPy code.

However, after reading GeoPy's [contributing policy](https://github.com/geopy/geopy/blob/master/CONTRIBUTING.md), I checked https://stackoverflow.com/questions/tagged/geopy and discovered a number of users reporting the same issue: https://stackoverflow.com/search?q=%5Bgeopy%5D+%22self+signed+certificate+in+certificate+chain%22. `KostyaEsmukov` (the person who performed the last GeoPy release) suggested on one of these posts that configuring GeoPy via `default_ssl_context` would solve the problem, which is what I have done above, and gives me confidence that this would be the solution GeoPy would suggest.

I do agree that the above suggestion should be added to the GeoPy documentation, so I have proposed that, see https://github.com/geopy/geopy/issues/546 😊

**Comment by bouweandela** [comment]
> if there is a concern about using the code I suggested above directly in ESMValCore, perhaps it could be configured via the user configuration file

If it works for everyone, I would prefer to include the code in ESMValCore instead of bothering our users with it, as this topic is way too technical for most of them. I just think it's a bit odd that geopy 1) configures this at all and 2) does it in a way that doesn't work for everyone. Why aren't they using the (working) default?

**Comment by valeriupredoi** [comment]
I think @ehogan has found nice solution here (that woks for me, I just tested it) - and I also see that creating a default ssl context is common practice when wants to ship the object over to multiple threads etc. I see no reason why we shouldn't include it in the geoextractor code we have, especially if that enables sites with peculiar settings to use the extractor. However, looking at the actual [SSL wrapper docs](https://docs.python.org/3/library/ssl.html#ssl.create_default_context) it looks like this call may result in fairly numerous exceptions, so maybe encase it in a try/except clause so we can catch the exception and maybe not raise it if it can be stepped over. I wonder if geopy are modifying the ssl settings to heighten the security levels - maybe disable key logging and other such potential vulnerabilities - dunno, might be talking out of my arse here

**Comment by ehogan** [comment]
Should I add anything to https://docs.esmvaltool.org/projects/ESMValCore/en/latest/recipe/preprocessor.html#extract-location?

**Comment by bouweandela** [comment]
No, that would be too much technical detail for our users.
