### ISSUE TITLE
Typo in Timerange documentation examples

### ISSUE THREAD

**Issue by rebeccaherman1** [ESMValGroup/ESMValCore#2017]
In https://docs.esmvaltool.org/projects/ESMValCore/en/latest/recipe/overview.html#time-ranges, I think there is a typo in the examples for Time ranges. In the first line of the table, it says that the range '1980/198**2**' spans from 01/01/1980 to 31/12/198**0**. Shouldn't it span from 01/01/1980 to 31/12/198**2**?

**Comment by schlunma** [comment]
Thanks for reporting this @rebeccaherman1! Would you be willing to fix this in a pull request? The corresponding file that needs to be changed is https://github.com/ESMValGroup/ESMValCore/blob/main/doc/recipe/overview.rst. That would be fantastic! :+1:

You can find our contributing guidelines [here](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#). Let me know if you need any help!
