### ISSUE TITLE
Dynamic HTML output for monitoring

### ISSUE THREAD

**Issue by bsolino** [ESMValGroup/ESMValCore#2059]
The ESMValTool HTML output file, together with monitoring recipes, is being used to monitor model runs. However, the way data is presented makes this use case cumbersome, so we would like to make some improvements.

#### Tab selection of diagnostics
Now it's possible to to view only one diagnostic at a time. The selection is done as tab on the top of the screen, for ease of accessibility.

<details><summary>Screenshots</summary>
<p>

![image](https://github.com/ESMValGroup/ESMValCore/assets/20075170/a675ea7f-c442-4769-bcb0-f2090f4385eb)
![image](https://github.com/ESMValGroup/ESMValCore/assets/20075170/9f8da324-cb4b-45b8-90b8-2bf0061d08f3)

</p>
</details> 

#### Hiding by default "Data Files" section
The "Data Files" section provides links to the sources used to generate the plot. As this information is not necessary when examining the plots, it is now hidden by default. It can be shown again by pressing a button.

<details><summary>Screenshots</summary>
<p>

![image](https://github.com/ESMValGroup/ESMValCore/assets/20075170/a4c24ed5-e4f9-409a-9d7c-e4d56e84b39b)

![image](https://github.com/ESMValGroup/ESMValCore/assets/20075170/5e480c60-f561-4423-906f-fd915c86c757)

</p>
</details> 

#### Plot filtering
It is possible to show only a subset of plots, based on different properties. These properties have to be available on the provenance record. The current supported provenance keys are:
* plot_type, plot_types
* long_names: Long names of variables used
* realms

<details><summary>Screenshots</summary>
<p>
![image](https://github.com/ESMValGroup/ESMValCore/assets/20075170/eadd89fd-7f80-4861-8e0b-3690604b473d)
![image](https://github.com/ESMValGroup/ESMValCore/assets/20075170/999cf6ef-5547-41f8-a784-080da1b0ee9b)

</p>
</details> 

Furthermore, it is possible to hide diagnostics when all their plots are hidden. This behavior can be disabled with a checkmark.

### Live demo
* recipe_monitor.yml:
  * [new version](https://swift.dkrz.de/v1/dkrz_489a8873-df8c-4bed-a8a9-4c14304df6cf/esmvaltool_html_output/new_v2.0/recipe_monitor/index.html)
  * [current look](https://swift.dkrz.de/v1/dkrz_489a8873-df8c-4bed-a8a9-4c14304df6cf/esmvaltool_html_output/current/recipe_monitor/index.html)
* recipe_monitor_with_refs.yml
  * [new version](https://swift.dkrz.de/v1/dkrz_489a8873-df8c-4bed-a8a9-4c14304df6cf/esmvaltool_html_output/new_v2.0/recipe_monitor_with_refs/index.html)
  * [current look](https://swift.dkrz.de/v1/dkrz_489a8873-df8c-4bed-a8a9-4c14304df6cf/esmvaltool_html_output/current/recipe_monitor_with_refs/index.html)

### Open questions
As the HTML file was created for a different purpose we don't know if it could be modified. That issue could be avoided by making this new HTML format an option that could be selected on the recipe.

I have a few questions for the community:
1. Could it be possible to modify the current HTML output file, or should we make that an option?
  a. If we make it an option, where should it go in the recipe? I assume it should go in the "documentation" section, but that section is currently used only for metadata and adding a configuration option there seems a bit out of place.
2. A common request is to be able to open the website directly from the run. For example, the output could include a link that works with port forwarding, or upload the results to a service like DKRZ's [Swift Object Store](https://docs.dkrz.de/doc/datastorage/swift/index.html). However, both these options require additional configuration, and the latter is also site-exclusive. Is there an easier way to achieve this?

**Comment by bouweandela** [comment]
Improving the current HTML output would be great because it's not looking that great.

Regarding the implementation: I would recommend looking into using a framework, e.g. [bootstrap](https://getbootstrap.com/) instead of writing your own CSS and Javascript, because building and maintaining a good-looking website that works on all browsers is much more work than we have time for as a community.

**Comment by bouweandela** [comment]
See here for an example of how to use that: https://github.com/ESMValGroup/ESMValTool/blob/e17d1c8f6ea536d29c81a6230c1ff0ccd41faf18/esmvaltool/utils/testing/regression/summarize.py#L284-L287

**Comment by bsolino** [comment]
> Regarding the implementation: I would recommend looking into using a framework, e.g. [bootstrap](https://getbootstrap.com/) instead of writing your own CSS and Javascript, because building and maintaining a good-looking website that works on all browsers is much more work than we have time for as a community.

Thank you for the suggestion! I tried to keep it basic and avoided including external dependencies out of fear of bloating the output folder with files or requiring an internet connection. As these are output files that could be generated offline, my reasoning was that they should work on their own. However, now that the features are defined and I was going to focus on polishing and implementing feedback, I can look into migrating it to a framework.

**Comment by bsolino** [comment]
I will detail below the new features with some screenshots, but if you want to check out the new output I have prepared a live demo for the recipes:
* [recipe_monitor.yml](https://swift.dkrz.de/v1/dkrz_489a8873-df8c-4bed-a8a9-4c14304df6cf/esmvaltool_html_output/new/recipe_monitor/index.html)
* [recipe_monitor_with_refs.yml](https://swift.dkrz.de/v1/dkrz_489a8873-df8c-4bed-a8a9-4c14304df6cf/esmvaltool_html_output/new/recipe_monitor_with_refs/index.html)
For comparison, this is how they currently look:

* [recipe_monitor.yml](https://swift.dkrz.de/v1/dkrz_489a8873-df8c-4bed-a8a9-4c14304df6cf/esmvaltool_html_output/current/recipe_monitor/index.html)
* [recipe_monitor_with_refs.yml](https://swift.dkrz.de/v1/dkrz_489a8873-df8c-4bed-a8a9-4c14304df6cf/esmvaltool_html_output/current/recipe_monitor_with_refs/index.html)

**Comment by bouweandela** [comment]
> I tried to keep it basic and avoided including external dependencies out of fear of bloating the output folder with files or requiring an internet connection.

They could still be generated offline, you only need an internet connection for the webpage to look nice. Note that you'll be missing some of the citation information too if you do offline processing. In any case, since Mistral has been decommissioned, I don't think there are many people left who actually do offline processing.

**Comment by bsolino** [comment]
There is a new version of the website, I have updated the screenshots and live demo : )
