### ISSUE TITLE
`climate_statistics` with period `hourly`

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#2063]
It would be great if `climate_statistics` supported the period `hourly`. This would be very useful to create diurnal cycle plots.

**Comment by valeriupredoi** [comment]
wouldn't we need as much RAM as it can fit in an ocean liner? Even with Dask and Bouwe magic?

**Comment by valeriupredoi** [comment]
OK not the whole piControl then :rofl:
