### ISSUE TITLE
ESMValTool Python API error when loading config from file

### ISSUE THREAD

**Issue by rbeucher** [ESMValGroup/ESMValCore#2084]
Hi All,

I find out about the Python API using the notebook examples [here](https://github.com/ESMValGroup/ESMValTool-JupyterLab/tree/main/example_notebooks)
I am interested in helping support that workflow approach.

Now I found an issue while trying to run the notebooks:

I can't seem to be able to load the configuration from a file:

```python
import esmvalcore.experimental as esmvaltool
esmvaltool.CFG.load_from_file("my/path/to/config-user.yml")
```

Returns:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 esmvaltool.CFG.load_from_file("/g/data/kj13/admin/ESMValTool/.esmvaltool/config-user.yml")

File /g/data/xp65/public/apps/med_conda/envs/access-med-0.1/lib/python3.10/site-packages/esmvalcore/experimental/config/_config_object.py:92, in Config.load_from_file(self, filename)
     88     else:
     89         raise FileNotFoundError(f'Cannot find: `{filename}`'
     90                                 f'locally or in `{try_path}`')
---> 92 self.clear()
     93 self.update(Config._load_user_config(path))

File /g/data/xp65/public/apps/med_conda/envs/access-med-0.1/lib/python3.10/site-packages/esmvalcore/experimental/config/_validated_config.py:92, in ValidatedConfig.clear(self)
     90 def clear(self):
     91     """Clear Config."""
---> 92     self._mapping.clear(self)

TypeError: dict.clear() takes no arguments (1 given)
```

I am pretty sure it worked a few days ago so I suspect a recent update.

R

**Comment by bouweandela** [comment]
Indeed, the `esmvalcore.experimental.CFG` object has been moved to `esmvalcore.config.CFG` in recent versions of the tool.

To solve your issue, you can use
```python
from esmvalcore.config import CFG
CFG.load_from_file("my/path/to/config-user.yml")
```

You can find the up to date description of the API [here](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/api/esmvalcore.html) and some more example notebooks [here](https://github.com/ESMValGroup/ESMValCore/tree/main/notebooks).

**Comment by rbeucher** [comment]
Thanks @bouweandela . This is great!
