### ISSUE TITLE
Glob expansion fails for fx variables because time range is checked on them

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#2091]
### Discussed in https://github.com/ESMValGroup/ESMValTool/discussions/3218

<div type='discussions-op-text'>

<sup>Originally posted by **rebeccaherman1** June 12, 2023</sup>
ESMValTool appears to be able to expand `timerange: '*'` and `timerange: '*/*'` for variables that vary over time, but not for fx variables like areacella and areacello. 
If I try to use an area statistic, areacella or -o is required, and it is brought in as a supplementary variable whether I do it explicitly or not. But when I've used wildcard expansion for the main variable, it ends up giving me the following:
`ignoring supplementary variable 'areacello', unable to expand wildcards 'time_range'.`
My only idea is to overwrite "timerange" for the supplementary variables, but I have no idea what to replace it with for fx variables. 
Please help!

(I am somewhat perplexed that the algorithm is complaining about "time_range", with "_", rather than "timerange", which is the name of the facet that works...)</div>

**Comment by rebeccaherman1** [comment]
Apologies for the delay in my reply. Unfortunately I fear I was not careful and may have modified the original recipe and deleted the original log that would have helped better trace this error. The next day it started working while I was experimenting, and I have not been able to recreate the error. At the time when I was struggling with this error, the ESGF server search function was not working, and it started working again the same day the error went away. I wonder if they are related.

**Comment by bouweandela** [comment]
Please re-open if the issue is still relevant.
