### ISSUE TITLE
Preprocess datasets in fixed order

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#2102]
It would be nice if the preprocessor would run over the datasets in a single task in a fixed order. This will make it easier to see how far you got and if you have now fixed a particular data issue when running a recipe with multiple datasets with multiple data issues.

**Comment by valeriupredoi** [comment]
alphabetical perhaps?

**Comment by bouweandela** [comment]
Alphabetically is a bit tricky, because what order do you use for the facets? Therefore I implemented the order in which they're listed in the recipe, see the linked pull request.
