### ISSUE TITLE
Version selection does not work if some files are not available for a particular version

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#2104]
Run this script

```python
import logging
from esmvalcore.esgf import find_files

logging.getLogger().setLevel(logging.DEBUG)

if __name__ == '__main__':
    files = find_files(
        dataset='EC-Earth3-Veg',
        project='CMIP6',
        mip='Omon',
        short_name='tos',
        exp='ssp585',
        ensemble='r1i1p1f1',
        grid='gn',
        timerange='2100/2100',
        version='v20200225',
    )
    print("\n".join(str(f) for f in files))
```
results in this stack trace (full output [here](https://github.com/ESMValGroup/ESMValCore/files/11798447/result.txt)):

```
Traceback (most recent call last):
  File "/home/bandela/src/esmvalgroup/esmvalcore/esgf_test.py", line 7, in <module>
    files = find_files(
  File "/home/bandela/src/esmvalgroup/esmvalcore/esmvalcore/esgf/_search.py", line 346, in find_files
    return cached_search(**facets)
  File "/home/bandela/src/esmvalgroup/esmvalcore/esmvalcore/esgf/_search.py", line 360, in cached_search
    files = select_latest_versions(files, facets.get('version'))
  File "/home/bandela/src/esmvalgroup/esmvalcore/esmvalcore/esgf/_search.py", line 67, in select_latest_versions
    raise FileNotFoundError(
FileNotFoundError: Requested versions v20200225 of file not found. Available files: [ESGFFile:CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3-Veg/ssp585/r1i1p1f1/Omon/tos/gn/v20221112/tos_Omon_EC-Earth3-Veg_ssp585_r1i1p1f1_gn_210101-210112.nc on hosts ['esg-dn1.nsc.liu.se']]
```
The best solution would probably be to not raise an exception but simply skip the files if they are not available for the requested version.

**Comment by valeriupredoi** [comment]
that's not what I'd do, man - that's silent fail under the hood, which is always nasty for users - what if they really really want to use that version (for some odd reasons, but heyho). Maybe, and am sure you gonna kill me for this, add a new configuration parameter eg `strict_versioning` etc so that the user has the option to let it look for other versions too, if they're not totally keen on a specific version?

**Comment by bouweandela** [comment]
If you really want specific version (s), you can specify that in the recipe using the `version` facet. If you don't specify it, you'll get the latest version.

**Comment by valeriupredoi** [comment]
oki doki, sounds safe enough then :blowfish:
