### ISSUE TITLE
[Github Actions] old conda and mamba versions

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#2138]
As they come shipped with the setup-miniconda@v2 and immune to a conda update -n base conda, they are fairly old, and we could start seeing issues (we already saw that in the case of conda-lock). The solution is to force update mamba that'll in turn update conda. I'll try work on this, also pinging the action devs needs be done.

**Comment by valeriupredoi** [comment]
opened at upstream https://github.com/conda-incubator/setup-miniconda/issues/288

**Comment by valeriupredoi** [comment]
looks like there isn't much appetite upstream for a solution just yet - gonna try tackle it locally to us then, won't hust anyway even when upstream sorts it out :+1:

**Comment by valeriupredoi** [comment]
OK this needed a bit more poking around - the problem is with Miniforge - since we are getting all our stuff through it, Miniforge is lagging behind the latest conda (at the moment 23.5+) at some 23.3 (latest rlease) - it's not the actions themselves but rather, the grab of the latest Miniforge

**Comment by valeriupredoi** [comment]
@bouweandela you mentioned that the use of Mambaforge is now discouraged - we are setting up all our GA tests with Miniforge miniforge-variant: Mambaforge - and on top of all that the Miniforge latest is lagging considerable behind latest conda https://github.com/conda-forge/miniforge/releases - do we want to go back to a pure conda-mamba environment creation in our GA tests? That'd mean changing the install instructions too (and possible change the workflow in CircleCI tests too)

**Comment by bouweandela** [comment]
We only want packages from conda-forge because some of us would need to buy a licence to use the software from the default channel, that's why we're using miniforge. If there is some other commonly used way to achieve that, that would also be fine.

**Comment by valeriupredoi** [comment]
this has been resolved via upstream (they updated their setup)
