### ISSUE TITLE
convert_units causing strange behavior

### ISSUE THREAD

**Issue by rebeccaherman1** [ESMValGroup/ESMValCore#2147]
I have prepared a cube that results in the following plot:
![Screenshot from 2023-07-25 16-04-15](https://github.com/ESMValGroup/ESMValCore/assets/12139022/91cfbccd-4cb3-42ac-9ae6-d7bd00e0f833)
The `Pa` values are annoyingly large, so I wish to convert the units to `hPa`. I attempt to do that using the following code:
```
Cube = convert_units(Cube, units='hPa')
```
but this gives me the following terribly strange result:
![Screenshot from 2023-07-25 16-07-05](https://github.com/ESMValGroup/ESMValCore/assets/12139022/efe2f866-826b-4741-a64a-9338ba076706)
Am I using this function incorrectly, or is it malfunctioning?

https://github.com/ESMValGroup/ESMValCore/blob/f00b6c6190a114ffe12aea007bd31b066d2cb8d9/esmvalcore/preprocessor/_units.py#L66

**Comment by valeriupredoi** [comment]
looks to me like something I have seen when the user was running with `numpy=1.24.3` - what numpy do you have in your environment?

**Comment by rebeccaherman1** [comment]
Indeed -- that was the numpy version

**Comment by valeriupredoi** [comment]
ah - that's been causing multiple WTF issues just like this :laughing: It's a serious bug with masking, now we're pinning strictly on `!= 1.24.3` so that makes me think you should probably update your ESMValCore version since we've pinning on it since April :+1:

**Comment by rebeccaherman1** [comment]
I'm using ESMValTool on DKRZ. I can try to ask them to update. In the meantime I am trying to change my numpy version. Thank you for helping me find the problem!

**Comment by valeriupredoi** [comment]
my pleasure! Could you pls give me your install params ie the output for `which esmvaltool` and `esmvaltool version` from the install you use on DKRZ? @remi-kazeroni has pushed them to install it (uite a bit) and it looks to me like they've completely left it to the elements by the sound of it. Cheers!

**Comment by rebeccaherman1** [comment]
`/sw/spack-levante/mambaforge-23.1.0-1-Linux-x86_64-4jdbc6/bin/esmvaltool`
```
ESMValCore: 2.8.0
ESMValTool: 2.8.0
```

**Comment by valeriupredoi** [comment]
getcha, thanks! It's old - but not **that** old - I'll ping around ask them to update it to 2.9 :beer:

**Comment by rebeccaherman1** [comment]
They did update it back when I started using it and was confused because it appeared inconsistent with the documentation! I suppose they probably haven't updated it since then.

**Comment by remi-kazeroni** [comment]
I already sent a request to get a module for ESMValTool v2.9. on Levante but I'm afraid this usually takes time. There is not much I can do about that, neither about the problematic numpy version, ...

The last module available for ESMValTool (v.2.8) is known to lead to such issues so not very recommended to use. I would recommend instead to create your own installation, for example from conda-forge, see [here](https://docs.esmvaltool.org/en/latest/quickstart/installation.html#esmvaltool-installation-on-linux).

**Comment by schlunma** [comment]
The module is available on Levante now.

```
> module avail esmvaltool                                                                                                                                                                                                                                      23848ms
---------------------------------------------------------------------------------------------------------------------- /sw/spack-levante/spack/modules -----------------------------------------------------------------------------------------------------------------------
esmvaltool/2.5.0  esmvaltool/2.6.0  esmvaltool/2.7.0  esmvaltool/2.8.0  esmvaltool/2.9.0
```
