### ISSUE TITLE
CMOR checks are done twice or even more often

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#2154]
#### Fix data

During loading a dataset, the steps `fix_data` and `cmor_check_data` are performed right after each other:

https://github.com/ESMValGroup/ESMValCore/blob/f00b6c6190a114ffe12aea007bd31b066d2cb8d9/esmvalcore/dataset.py#L756-L767

However, `fix_data` already includes a CMOR check:

https://github.com/ESMValGroup/ESMValCore/blob/f00b6c6190a114ffe12aea007bd31b066d2cb8d9/esmvalcore/cmor/fix.py#L270-L277

This is basically identical to what is done in `cmor_check_data`:

https://github.com/ESMValGroup/ESMValCore/blob/f00b6c6190a114ffe12aea007bd31b066d2cb8d9/esmvalcore/cmor/check.py#L1167-L1173

Note that the `fail_on_error=False` flag is kind of misleading, as it simply means ["collect all messages before reporting/failing"](https://github.com/ESMValGroup/ESMValCore/blob/f00b6c6190a114ffe12aea007bd31b066d2cb8d9/esmvalcore/cmor/check.py#L98-L100) instead of reporting them immediately. If there is an error, an exception will be raised regardless of the value of the flag.

#### Fix metadata

The situation for `fix_metadata` is quite similar. The only difference is that there is an [additional `concatenate` step ](https://github.com/ESMValGroup/ESMValCore/blob/f00b6c6190a114ffe12aea007bd31b066d2cb8d9/esmvalcore/dataset.py#L739-L751)in between `fix_metadata` and `cmor_check_metadata`.

#### What to do?

Doing the exact same CMOR check twice (or even more often, as `fix_metadata` does the check for each input file prior to concatenation, which can be hundreds or thousands of files **(!)**) is not really efficient.

My suggestion would be:

1. Make the CMOR check in `fix_metadata` and `fix_data` optional (to maintain backwards-compatibility). If not used, add the corresponding automatic fixes to these functions. This is especially necessary for `fix_metadata`, since the subsequent concatenation might fail without the automatic fixes. In addition, it is conceptually sensible to add the fixes to the actual fix preprocessors.
2. Disable the CMOR check in `fix_metadata` and `fix_data` in [`Dataset._load`](https://github.com/ESMValGroup/ESMValCore/blob/f00b6c6190a114ffe12aea007bd31b066d2cb8d9/esmvalcore/dataset.py#L707).
3. Add an optional flag to `cmor_check_data` and `cmor_check_metadata` for `fail_on_error` and use it in [`Dataset._load`](https://github.com/ESMValGroup/ESMValCore/blob/f00b6c6190a114ffe12aea007bd31b066d2cb8d9/esmvalcore/dataset.py#L707).

This would result in one CMOR check (data and metadata) per dataset instead of one metadata check per input file (which, as mentioned, can be thousands) and be fully backwards compatible. For models like ICON (which stores one file per time step), this should be MUCH faster when analyzing sub-daily data.

@ESMValGroup/technical-lead-development-team any opinions on this? Did I miss any reasons which would require us doing these CMOR checks multiple times?

**Comment by valeriupredoi** [comment]
as far as I understand (from distant memories, me actually working with this bit of code - ah when I was young and happy :grin: ) these are necessary since different preprocessing steps may introduce CMOR deviations - but, as you mention, all our preprocessing operations should adhere to CMOR and one check+fix should be enough - but, I am 0.01% dubious about the possibility of a preprocessor conking up CMOR abidance :beer:

**Comment by schlunma** [comment]
The thing is, even if preprocessing steps introduced deviations, we wouldn't know that!

- `cmor_check_data` is performed right after `fix_data`, no preprocessor in between.
- `cmor_check_metadata` is performed after `concatenate`, which in turn is done right after `fix_metadata`. Thus, we would also not detect any CMOR deviations apart from `concatenate`.

Entire loading chain:

```mermaid
graph TD
  fix_file --> load --> fix_metadata --> concatenate -->
  cmor_check_metadata --> clip_timerange --> fix_data --> cmor_check_data
```

**Comment by valeriupredoi** [comment]
concatenate *is* a preprocessor - I'd love to see that very neat workflow chart if you toss in two or three preprocessing steps :+1:

**Comment by schlunma** [comment]
This order is fixed and cannot be changed by the user in any way. All other preprocessors come after `cmor_check_data`. Thus, we have NO CMOR check after that (which is necessary, since data is technically made non-CMOR-compliant by operations like `area_statistics` which removes dimensions).

**Comment by valeriupredoi** [comment]
gotcha! In this case - godspeed :checkered_flag:

**Comment by schlunma** [comment]
I made a suggestion for this in https://github.com/ESMValGroup/ESMValCore/pull/2157.

Contrary to my initial idea, I chose to move the automatic fixes to the CMOR check functions and disable them in the `fix_data` and `fix_metadata` functions. The simple reason is that the automatic fixes are implemented really deep into the CMOR checker code, and separating them from this would lead to A LOT of code changes.

One disadvantage of this approach is that the automatic fixes are now performed after concatenation (previously: before). I discuss this in detail in the PR description. Please let me know there if you think this might lead to any problems.

**Comment by valeriupredoi** [comment]
thanks, Manu! I'll make my way to that PR then :beer:

**Comment by bouweandela** [comment]
The reason for running the checks twice is indeed that they include the option to automatically fix things. Conceptually, fixing and checking are two different operations and to me, it has always seemed an awkward design choice to mix them. How can you have confidence in your data if you're modifying it while checking and then do not check the result of that modification?

**Comment by schlunma** [comment]
Conceptually I fully agree that fixing and checking should be two independent steps, and it's rather weird that both are done by a class called `CMORCheck`.

The problem is that fixing the data also checks the data, which leads to this massive duplicated effort if you have multiple input files per dataset. It would be really nice to disentangle them, but since `CMORCheck` is part of the [public API](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/api/esmvalcore.cmor.html#esmvalcore.cmor.check.CMORCheck) I fear that this becomes really messy if you want to do it in a backwards-compatible way.

Regarding modifying without checking the result: I think this is not a big deal, since all automatic fixes boil down to easy yes/no questions that are straightforward to fix (e.g., is the `standard_name` correct?, is the `long_name` correct?, does the coordinate have bounds?). We should have enough confidence in our code that these problems are fixed properly.

**Comment by schlunma** [comment]
I gave this some more thought, will try to come up with a solution that separates (automatic) fixes and checks. I guess it makes sense to deprecate the `automatic_fixes` keyword of `CMORCheck` in this context, as we all seem to agree that fixes and checks should be clearly separated.
