### ISSUE TITLE
running mean / filter preprocessor

### ISSUE THREAD

**Issue by mathause** [ESMValGroup/ESMValCore#219]
Is there a preprocessor that can calculate running means (or a more general filter preprocessor)? I would need it to work over the time dimension but other dimensions may be helpful as well.

**Would you be able to help out?**
Probably not as I don't usually work with iris.

**Comment by valeriupredoi** [comment]
I'll have a crack at this in the very near future :beer:

**Comment by zklaus** [comment]
Using [`cube.rolling_window`](https://scitools.org.uk/iris/docs/latest/examples/General/SOI_filtering.html?highlight=running%20mean) this will be a one-liner. Good luck :beers:

**Comment by valeriupredoi** [comment]
whoa this one slipped through the cracks big time :grin:

**Comment by valeriupredoi** [comment]
'tis 'ere https://github.com/ESMValGroup/ESMValCore/pull/335
