### ISSUE TITLE
Urgent: Docker Hub billing plan

### ISSUE THREAD

**Issue by axel-lauer** [ESMValGroup/ESMValCore#2190]
@ESMValGroup/technical-lead-development-team 

A while ago, Docker Hub changed their billing plans. The free plan that we had over the last years no longer allows up to 7 team members but is now limited to 3. I am not sure whether also other limitations of the free plan are relevant to us:

![docker_plans](https://github.com/ESMValGroup/ESMValCore/assets/25367775/f5a76a13-c698-47f4-bf52-82f97a2ce4b3)

Since we have no funding to pay $516 per year, we can either remove some team members or discontinue using Docker Hub. I already removed @remi-kazeroni and @nielsdrost (which I hope was fine), so 2 more team members would need to be removed:

![docker_team_members](https://github.com/ESMValGroup/ESMValCore/assets/25367775/60f702e6-5054-4737-9f5b-ef1a84c5e7c8)

Since a few days, I get emails from Docker requesting to update our payment options to pay the first bill. If we do not react within the next 8 days, we will be downgraded automatically. Not sure what this implies, though.

Please provide your ideas and wishes asap.

**Comment by zklaus** [comment]
Several of us have received these emails and @bouweandela is in contact with Docker about this. We did discuss this on the technical lead mailing list, but were not aware that you, @axel-lauer (and maybe others?) also received the emails. Sorry for that oversight! I'll loop you into the email discussion.

**Comment by valeriupredoi** [comment]
I've stopped getting those daily (and massively annoying) emails, I assume this either got sorted out or we've lost all access to Docker?

**Comment by bouweandela** [comment]
Our membership renewal has been approved
