### ISSUE TITLE
Time preprocessor: Climatology

### ISSUE THREAD

**Issue by ledm** [ESMValGroup/ESMValCore#221]
A climatology function was requested today at the NCEO tutorial, and I was surprised it wasn't there already!

It would have to be able to deal with monthly, weekly and daily input. I guess that this will have to wait until after @jvegasbsc's time preprocessor update PR has completed (assuming that a climatology function isn't in PR #87 already!)

**Comment by jvegasbsc** [comment]
It is already there: `climate_statistics`. It is not called climatology because it not only computes the mean: also max, min, median and the usual suspects. It can compute daily, monthly and seasonal climatologies

**Comment by jvegasbsc** [comment]
#87 also have the sibling function `anomalies`

**Comment by ledm** [comment]
It's probably worth putting the word "climatology" somewhere in the function, either in the documentation or comment, as people may wind up searching the documents or the code for this term!

**Comment by jvegasbsc** [comment]
It is already there, with an example on how to calculate the monthly climatology:

https://github.com/ESMValGroup/ESMValCore/blob/dev_season_max/doc/esmvalcore/preprocessor.rst

**Comment by bouweandela** [comment]
@ledm Is issue solved?

**Comment by ledm** [comment]
I have yet to test it, but @jvegasbsc said the requested functionality already exists. That's enough for me!
