### ISSUE TITLE
Preprocessor cuts of first month of monthly data

### ISSUE THREAD

**Issue by bascrezee** [ESMValGroup/ESMValCore#222]
While working on ESMValGroup/ESMValTool#1277 , I found out that the preprocessor cuts off the first month of the data when running `recipe_check_obs.yml`.

My input data is monthly data for which I derive the time_bnds in this function:
https://github.com/ESMValGroup/ESMValTool/blob/63cbe4bc1a8e484bceaa7b32967a47280cd17c69/esmvaltool/cmorizers/obs/cmorize_obs_cds_era5_monthly.py#L35-L55

The time calendar of the CMORized file (hours since ...)  differs from the one in the preprocessor output file (days since ...). However, the recipe_check_obs does not complain about this. Is there a preferred calendar to use?

**Comment by valeriupredoi** [comment]
we are using `days since 1950-01-01` pretty much all over the shop (1850 is good too). Can you not guess bounds via `iris.guess_bounds`?

**Comment by bascrezee** [comment]
> we are using `days since 1950-01-01` pretty much all over the shop (1850 is good too).
Cool, will converting to that. 

> Can you not guess bounds via `iris.guess_bounds`?
No, in this case not, the time on the file always corresponds to 12 UTC on the first day of each month. Guessing the bounds would lead to bounds from e.g. mid-Jan to mid-Feb.

**Comment by bascrezee** [comment]
```
# on the cmorized file: 
ncdump -v time /net/exo/landclim/PROJECTS/C3S/datadir/obsdir/Tier3/cds-era5-monthly/OBS_cds-era5-monthly_reanaly_1_Lmon_sm_197901-197912.nc 
```
`time = 10592, 10623`

10592  = [1 Jan 1979 ](https://www.wolframalpha.com/input/?i=10592+days+after+1+jan+1950)


```
# On the file that is written out by the preprocessor
ncdump -v time /net/exo/landclim/PROJECTS/C3S/datadir/esmval2output/recipe_check_obs_new_20190905_123421/preproc/test/sm/OBS_cds-era5-monthly_reanaly_1_Lmon_sm_1979-1979.nc
```


`time = 47147, 47175 [...]`

47147 = [1 Feb 1979](https://www.wolframalpha.com/input/?i=47147+days+after+1+jan+1850)

**Comment by mattiarighi** [comment]
It is advisable to set the time coordinate to 15th of the month when cmorizing to avoid such issues.

**Comment by bascrezee** [comment]
Yes, that fixes the issue.
