### ISSUE TITLE
extract_region forces the region to be represented from 0-360 longitude

### ISSUE THREAD

**Issue by rebeccaherman1** [ESMValGroup/ESMValCore#2229]
`extract_region` uses an iris cube `intersection`, and then applies another so that the cube is represented from 0-360 longitude. If the extracted region crosses 360 degrees, this forces the bounds to be discontiguous, and prevents future regrid-ing. I see that, in the default preprocessing order, regrid-ing is done before extracting a region. However I can see no obvious benefit to forcing the cube to be stored from 0-360 degrees, and it complicates analysis down the line outside of the preprocessor. I propose that this line be removed.

**Comment by valeriupredoi** [comment]
@rebeccaherman1 the reason why the extracted region cube needs to be intersected on a 0-360 mesh is that the output needs to be on a 0-360 grid to adhere to CMOR standards; taking out that line in your PR #2230 will allow grids that go from eg -180 to 180 to proceed through the preprocessing chain and the task will invariably fail at a CMOR check step that is performed between steps or at the end; could you please tell me how your extracted region crosses 360 degrees? We should put in a check for that and either rotate the data or set some other condition to make bounds continuous

**Comment by valeriupredoi** [comment]
@ESMValGroup/technical-lead-development-team this is starting to creep up in other places, and be reported by other users too (see https://github.com/ESMValGroup/ESMValTool/issues/3387) - my take would be to have upstream iris handle it, what do you think?

**Comment by rebeccaherman1** [comment]
@valeriupredoi I'm not sure there is anything for iris to do here... 
the issue is coming from the fact that `extract_region` uses iris's `intersect` twice in order to satisfy CMOR standards, as you said.

I suppose the only thing iris could do is implement automatic rotation for non-contiguous coordinates that could be contiguous if rotated, for all functions that require that. But since their `extract_region` would have created a contiguous region, I don't see why that would be a natural thing for them to do.

**Comment by zklaus** [comment]
> @rebeccaherman1 the reason why the extracted region cube needs to be intersected on a 0-360 mesh is that the output needs to be on a 0-360 grid to adhere to CMOR standards;

This is not exactly true. In principal, this comes from [the CMIP6 output metadata requirements section on coordinate variables](https://docs.google.com/document/d/1os9rZ11U0ajY7F8FWtgU4B49KcB59aFlBVGfLC4ahXs/edit#bookmark=id.3t64x7z1je8t), specifically point 3.
Even that section applies only to "spherical coordinate grids", which means "cartesian grids defined by longitudes and latitudes and with poles located at the Earth’s north and south poles" (see footnote 2 on that same page).

So for any other grid, there is immediately no such requirement.

Furthermore, there is also point 4, which requires that "Coordinate values must be stored monotonically increasing or decreasing", which conflicts with point 3 in the case of regions that straddle the zero meridian but don't cover all latitudes.

Every use that I know of simply uses negative longitudes for this, which I think we should too.

**Comment by zklaus** [comment]
It's not just a problem of guessing bounds, I'm afraid. When dealing with extracted regions, this makes things more difficult for no good reason. And with increased CORDEX support we'll be dealing with regions a lot more.

**Comment by schlunma** [comment]
> @rebeccaherman1 the reason why the extracted region cube needs to be intersected on a 0-360 mesh is that the output needs to be on a 0-360 grid to adhere to CMOR standards; taking out that line in your PR #2230 will allow grids that go from eg -180 to 180 to proceed through the preprocessing chain and the task will invariably fail at a CMOR check step that is performed between steps or at the end; could you please tell me how your extracted region crosses 360 degrees?

Maybe one more thing to add here: the CMOR checks are performed right after reading input files and (potentially) fixing them. There are **no** CMOR checks after the user-defined preprocessing operations (e.g., `extract_region`). The simple reason for that is that most of our preprocessors cause the CMOR checks to fail (e.g., unit conversion, area statistics, climate stastistics, etc.).

The line that actually makes sure that longitude of input data is in [0, 360] is in the generic fix that is run for every input dataset:

https://github.com/ESMValGroup/ESMValCore/blob/7a70d5b274869052e45d753ef3012a5f3b486696/esmvalcore/cmor/_fixes/fix.py#L668

Thus, removing the corresponding line in the `extract_region` preprocessor would **not** cause the CMOR checks to fail. In my opinion we could definitily try to remove that line; however, there is a possibility that some diagnostics or even other preprocessors downstream would fail if we did that. This needs to be tested with some recipes and potentially fixed in these downstream functions.

**Comment by valeriupredoi** [comment]
I like it! My erroneous comment above (apologies, I haven't run the tool myself in quite a while) triggered both a comment with very useful references, and a confirmation of the current behaviour - this is why GitHub issues are useful - cheers, guys! Let's have a round of testing then, maybe a few recipes that use `extract_region` then merge Rebecca's PR? :beer:

**Comment by rebeccaherman1** [comment]
So! How do I make progress toward understanding what's failing in the automatic tests?

**Comment by bouweandela** [comment]
Running the failing test on your own computer usually makes it easier to find out what happens. Instructions on how to do this are available here: https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests

**Comment by rebeccaherman1** [comment]
Thanks @bouweandela -- that helped me figure it out!
