### ISSUE TITLE
Sorting of ensemble members (#2095) breaks with mix of facet value types

### ISSUE THREAD

**Issue by zklaus** [ESMValGroup/ESMValCore#2237]
**Describe the bug**
In #2095, we introduced sorting of datasets during the recipe filling process.
This breaks currently when the dataset specifiers in the input recipe contain lists, for example for experiments, which is relatively commonly used to combine historical and future simulations into a single timeseries.

Recipes that fail with this include:
- recipe_impact.yml
- ipccwg1ar6ch3/recipe_ipccwg1ar6ch3_atmosphere.yml
- recipe_climwip_test_basic.yml
- recipe_climwip_test_performance_sigma.yml

**Comment by zklaus** [comment]
Sure. I tried to attach it here, but it was too big. I'll send you the path via dm.

**Comment by bouweandela** [comment]
I'll try to run the full recipe_impact.yml then to see if I can find the issue

**Comment by bouweandela** [comment]
I suspect the issue is caused by having a mix of different types for the facet values due to some datasets having multiple versions (different version for historical and future experiment) and some only a single version.

**Comment by zklaus** [comment]
Oh, it's interesting that you bring up versions. There is a second issue that I did not realize might be connected, which is that ESMValTool has become worse at distinguishing versions. For example, using `main`, some `obs4MIPs` datasets bring in different versions and even though the recipe specifies explicitly the later version, e.g. `v2.3`, the preprocessor *also* gets the older version `v2.2` and then can not concatenate the resulting dataset. This is a problem always when different versions cover the same time period both with obs4MIPs (which also doesn't have `version` in its directory/filename template), and some CMIP5 datasets, which is the problem behind the recipes that are not marked as successful in the release tracking discussion.
