### ISSUE TITLE
Pin `python <3.12` for 2.10 release

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#2250]
see eg [all manners of failed flake8 tests](https://github.com/ESMValGroup/ESMValCore/actions/runs/6701959439/job/18227108569) - python=3.12 seems to be bringing in massive PITAs - and, more importantly, conda-lock found a solution for the environment to build which means two things:

- I must revisit our attempt to support python=3.12 in #2228 
- it looks like it's still not 100% ready for python=3.12 support, but an env solution sneaked through, so we should probably pin to `< 3.12` in the release and package build on feedstock -> @zklaus

**Comment by valeriupredoi** [comment]
indeed python 3.12 environment now builds without any incantations https://github.com/ESMValGroup/ESMValCore/actions/runs/6708774145/job/18230325803?pr=2228 but we are running into these flake8 distaters, I think we need to pin < 3.12 asap

**Comment by bouweandela** [comment]
It looks like it's just a few code formatting issues, those should be easy enough to fix and as far as I can see they will not affect the proper functioning of the tool.

**Comment by valeriupredoi** [comment]
indeed! I too am for allowing Python 3.12 to trick-or-treat us, but there may be other issues that'll pop up - that's why I am leaving this to the RM and RMXO to decide - @zklaus and you 😁 (RMXO - release manager executive officer)

**Comment by valeriupredoi** [comment]
saw this was enforced by Flake8 as something valid, folks, it's on their list of no-no's (my way of calling it since I forgot the actual standard's code). I am thinking, if we allow 3.12 in Core, we'll prob have some issues in Tool - do we want to do that and fix anything that may go belly-up in Tool, while we're doing the release? If so, I can work on this today, see if anything's broken in Tool with 3.12-Core

**Comment by zklaus** [comment]
Could you point us to where they say that?

**Comment by valeriupredoi** [comment]
shall dig it out in a jiffy, bud

**Comment by valeriupredoi** [comment]
here is the [E231](https://www.flake8rules.com/rules/E231.html) gents - it does, however, look like a fairly old rule, and I don't know why it's decided to wake up only now for 3.12

**Comment by valeriupredoi** [comment]
there is also `E713 test for membership should be 'not in'` which I agree with, but again, decided to wake up only now, and a couple more different ones - I reckon we can just turn off `flake8` temporarily and wait see how they handle all this, for now; and still get 3.12 in - opinions?
