### ISSUE TITLE
Retire support for Python=3.9

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#2253]
Python 3.9 accepts only security updates, as this nice [plot tells us](https://devguide.python.org/versions/) - in fairness, there's a lengthy time until it reaches EOL, but I reckon, with merging #2227 by which we get support for 3.12 in, we may think of retiring support for 3.9 for the next release? Opinions welcome :beer: 

PS I know some users depend on Python 3.10 environments eg @rebeccaherman1 - so we should think twice, in the not so distant future, about 3.10

**Comment by bouweandela** [comment]
As you know, we follow [NEP-29](https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule) and will support Python 3.9 until April 5, 2024.

**Comment by valeriupredoi** [comment]
which date falls between (our) releases, that's why this issue - do we support it past 2.11 and retire it with 2.12?

**Comment by bouweandela** [comment]
2.12

**Comment by valeriupredoi** [comment]
tres bien, mon capitain 🍺
