### ISSUE TITLE
Version number is hardcoded in conda badge

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#2259]
It looks like the version number is hardcoded in the conda badge:
https://github.com/ESMValGroup/ESMValCore/blob/6e61590e3f58bf9e66ba7f6716e8fca8fbb1e168/README.md?plain=1#L10

Is it possible to avoid this @valeriupredoi?

@zklaus It would be good to update this before the release..

**Comment by bouweandela** [comment]
It looks like the same issue affects ESMValTool: https://github.com/ESMValGroup/ESMValTool/blob/4cce8928e384699dbc63ff6f3c0811726d8b9599/README.md?plain=1#L11

**Comment by valeriupredoi** [comment]
I am aware of this, and it's not ideal - but it seems to be the norm for the new 'shield' type of badge. I'll look around for an alternative 👍

**Comment by bouweandela** [comment]
I'm not sure if having a nicer looking badge is worth this much trouble, but anyway, if we stick with this I would suggest we start using a tool like [bump-my-version](https://pypi.org/project/bump-my-version/).

**Comment by valeriupredoi** [comment]
proves out I was a total doofus and should have read their docs more carefully - one can just create these shields on a whim, however they want to, even colours can change by changing the colour name in the shield name
