### ISSUE TITLE
If custom location for custom CMOR tables is used, default location is ignored

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#2278]
**Describe the bug**
If a custom location for custom CMOR tables is used via `custom: cmor_path: ...` in `config-developer`, the default location `esmvalcore/cmor/tables/custom` is ignored. To avoid copying all existing tables to a custom location, this should be fixed.

I will open a PR for this shortly.

@FranziskaWinterstein

**Comment by valeriupredoi** [comment]
this whole thing about custom location for CMOR tables is making me uneasy. I know I'm a little late and a dollar short, but custom tables in custom locations means we have no control over them, and replication goes out the window if the users don't know what they're doing

**Comment by schlunma** [comment]
I agree with you that this should definitely used for published recipes, but this feature can be really handy for analyzing native model output. It allows users to easily have a look at variables of their models that are not part of CMOR.

By the way, we have similar features that could in theory bypass reproducibility: users can specify their own extra facets files or use a custom config-developer file. Both can lead to failing recipes for other users that do not have those custom files.

In my opinion features like this make it much easier for first-time users to get in touch with ESMValTool. Having to tell people they cannot plot a simple line plot of their favorite model variable without messing with ESMValCore is really not a good feeling 😬

**Comment by valeriupredoi** [comment]
ah I completely agree, and have been a liberal config promoter myself. Still, making me uneasy - like, allowing your cat to roam the neighborhood freely kind of uneasy :grin: :cat:
