### ISSUE TITLE
Derivation of variables that need fx variables should be done with fx VARIABLES not fx files

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#229]
#170 implements the handling of fx variables as regular variables. The derivation of derived variables that need fx data should now be done by treating the fx variables as any regular derivation variables eg: for `nbp_grid.py`:

```
class DerivedVariable(DerivedVariableBase):
    """Derivation of variable `nbp_grid`."""

    # Required variables
    required = [{
        'short_name': 'nbp',
        'fx_files': ['sftlf'],
    }]
```
should change to
```
class DerivedVariable(DerivedVariableBase):
    """Derivation of variable `nbp_grid`."""

    # Required variables
    required = [{
        'short_name': 'nbp'},
        {'short_name': 'sftlf'}]
```

This will insure the correct CMOR checks and variable treatment are applied to the fx data.
I will implement this after #170 is merged.

**Comment by zklaus** [comment]
Great!

Don't forget `__init__.py` and `_shared.py` (not sure much needs to be changed though).

**Comment by schlunma** [comment]
Started working on this now. At the moment the derivation of the affected variables is not possible with CMIP6 data, so it would be nice to merge this during the workshop!
