### ISSUE TITLE
sign the python3statement

### ISSUE THREAD

**Issue by bjlittle** [ESMValGroup/ESMValCore#23]
We've just added `iris` to https://python3statement.org/, also with a timeline of when it will be Python3 only.

You guys are Python3 only already (whoop!), but it would be pretty awesome to see the logo and timeline of ESMValTool there as well - it's all about project public relations, and the python3statement is giving a really nice platform for projects to advertise not only their commitment to Python3, but also that their project exists!

It's pretty easy to do via a PR to https://github.com/python3statement/python3statement.github.io/pulls. Happy to help out if needed :smile:

**Comment by valeriupredoi** [comment]
@bjlittle https://github.com/python3statement/python3statement.github.io/pull/259 cheers for telling me about it :beer: -> although am fairly sure @mattiarighi should have done it since he is the PI but meh, if you tell the guys at @python3statement you OK with that all should be fine :tada:

**Comment by valeriupredoi** [comment]
and look what a nice new package is sitting now beside `iris` https://python3statement.org/ :beer:
