### ISSUE TITLE
Allow calculate_volume read areas from cell_area if available

### ISSUE THREAD

**Issue by enekomartinmartinez** [ESMValGroup/ESMValCore#2310]
**Is your feature request related to a problem? Please describe.**

The current implementation of [calculate_volume](https://github.com/ESMValGroup/ESMValCore/blob/989839f596a6b4433731c0efcb6b5cb4f3ca7045/esmvalcore/preprocessor/_volume.py#L100) tries to directly calculate the area before checking if there is `cell_area` available in the cube.

https://github.com/ESMValGroup/ESMValCore/blob/989839f596a6b4433731c0efcb6b5cb4f3ca7045/esmvalcore/preprocessor/_volume.py#L129-L138

This results in an error raised in the case of irregular grids, although `cell_area` is available.

We were trying to call the `volume_statistics` preprocessor with some datasets where `volcello` is not available, which was falling back on this function. However, we have `areacello` available for all the datasets. Therefore, we suggest checking if `cell_area` is available before trying to compute the area.

<br>

**Would you be able to help out?**

We could try to help with the PR, although it will be our first time contributing to the Core, and we may need some guidance.
We have two possible solutions to suggest.
1. Keeping the current implementation but checking if  `cell_area` is available:
```python
    if cube.cell_measures('cell_area'):
        # Get grid cell area from the cube
        area = cube.cell_measure('cell_area').lazy_data()
    else:
        # Try to calculate grid cell area
        try:
            area = da.array(compute_area_weights(cube))
        except CoordinateMultiDimError:
            logger.error(
                "Supplementary variables are needed to calculate grid cell "
                "areas for irregular grid of cube %s",
                cube.summary(shorten=True),
            )
            raise
```

2. Using [_try_adding_calculated_cell_area](https://github.com/ESMValGroup/ESMValCore/blob/989839f596a6b4433731c0efcb6b5cb4f3ca7045/esmvalcore/preprocessor/_area.py#L286C5-L286C6) function, which will try to compute the area if not available and has also support for `rotated_pole_grid`:
```python
    has_cell_measure = bool(cube.cell_measures('cell_area'))
    _try_adding_calculated_cell_area(cube)
    area = cube.cell_measure('cell_area').lazy_data()
    # Make sure input cube has not been modified
    if not has_cell_measure:
        cube.remove_cell_measure('cell_area')
```

Let us know what you think about it.
Thanks in advance!

**Comment by valeriupredoi** [comment]
hi @enekomartinmartinez and welcome to ESMValCor! Cheers for the issue, and possible solutions, mate. I am afraid I don't fully grasp the problem at hand ie the current implementation is trying to compute the area weights, and then spills out an exception for irregular grids (that need a few more things to get those area weights computed). Your proposal makes use of `cell_area` as a direct quantity for area weights (if the measure exists in or attached to the cube) but AFAIK `cell_area` is not a one to one representation of the area **weights**, rather, those weights need be computed via `iris.analysis.cartography.area_weights(cube)` - @schlunma would know better than me though - Manu, you got a bit of time loook into this, pls, bud? :beer: 

As for a PR - please go ahead with it, not a worry at all, we usually discuss the motivation behind the implementation in the GH issue (here) then we go about reviewing it in the PR - we'll help with pointers to best practice, tests etc at the PR :+1:

**Comment by schlunma** [comment]
Hi @enekomartinmartinez, thanks for opening this issue!

I think your proposal makes sense, and it's probably best to reuse the [`_try_adding_calculated_cell_area`](https://github.com/ESMValGroup/ESMValCore/blob/989839f596a6b4433731c0efcb6b5cb4f3ca7045/esmvalcore/preprocessor/_area.py#L286C5-L286C6) function :+1: Please go ahead and open a PR. You can also add me as a reviewer. Cheers!
