### ISSUE TITLE
symlink to latest output dir

### ISSUE THREAD

**Issue by mathause** [ESMValGroup/ESMValCore#232]
Would it make sense to create a symlink to the latest instance of a recipe that was run? Such that the folder structure of the `output_dir` would look

```
recipe_example_20190905_163431
recipe_example_20190905_163519
recipe_example_LATEST -> recipe_example_20190905_163519
```
Then I would not always need to figure out which folder is the newest. Of course this does not work in windows.

**Would you be able to help out?**
probably

**Comment by bouweandela** [comment]
I'm not sure this is a good idea in general, because what will happen if you're running more than one recipe at a time?

However, you can easily do this yourself, by using a command like the following to run esmvaltool:
```bash
esmvaltool -c ~/config-user.yml recipe_zmnam.yml; ln -sfT $(ls -1d ~/esmvaltool_output/recipe_zmnam_* | tail -1) latest
```

Maybe we could add that as advice somewhere in the documentation?

**Comment by bouweandela** [comment]
@valeriupredoi Did you add the advice to the documentation?

**Comment by valeriupredoi** [comment]
I don't think this is something a regular user will use habitually, it looks like an advanced option for an advanced user -> do we have a section with tips for advanced users?

**Comment by valeriupredoi** [comment]
also `ls -la -d *recioe_blah_* will order the contents of your dir based on time :grin:

**Comment by bouweandela** [comment]
It's a feature that several users have asked me about already. I think it would be good to create a tips and tricks section in the documentation and add this kind of thing there. Similar to: how do I jump into ipython from my diagnostic script.

**Comment by valeriupredoi** [comment]
good call, am onto it right now

**Comment by valeriupredoi** [comment]
closed via https://github.com/ESMValGroup/ESMValTool/pull/1317
