### ISSUE TITLE
Use iris' regridder caching for faster regridding?

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#2341]
Some regridding schemes of iris allow reusing the regridding weights (see [here ](https://scitools-iris.readthedocs.io/en/latest/further_topics/which_regridder_to_use.html)for an overview of them), which might significantly speed up our `regrid` preprocessor if multiple variables of the same dataset are regridded. This is described [here](https://scitools-iris.readthedocs.io/en/latest/userguide/interpolation_and_regridding.html#caching-a-regridder) and basically boils down to using the following pattern

```py
regridder = iris.analysis.Nearest().regridder(source_cube, target_cube)
for cube in list_of_cubes_on_source_grid:
    result = regridder(cube)
```

instead of

```py
for cube in list_of_cubes_on_source_grid:
    result = cube.regrid(target_cube, iris.analysis.Nearest())
```

This should be fairly easy to implement with a `dict` cache that uses the source and target latitude and longitude dimensions as keys (we cannot use `lru_cache` since the `hash` of a coordinate is simply its `id`, therefore this would never use cached results for different cubes).

One drawback here is that we have an additional comparison of the coordinates for each `regrid` call, which makes it slightly slower if just a single variable for many data sets is analyzed.

@ESMValGroup/esmvaltool-coreteam is this something we want? I can open a draft PR so that the discussion is easier.

**Comment by bouweandela** [comment]
I'd recommend using a profiler, eg py-spy, first to profile a run of a typical recipe using regrid and then see where most time is spent. Of it turns out that it is indeed regridding, then we could consider this.

**Comment by bouweandela** [comment]
Maybe you could also try if it still saves time when running with #2316, as it looks like that's where we we're headed. How much memory do the weights take up?

**Comment by schlunma** [comment]
The weights are 2D arrays whose size scales with the number of source/target points. For example, for a 1000x1000 grid (which is much larger than commonly used for CMIP6 models), this sums up to ~8MiB assuming float64. Of course, for very very high resolution grids you might end up with ~1GiB, but I don't think that this matters on machines where you want to evaluate that kind of data.

Also, the improvement shown here is only a lower bound for that use case, as it's data with a very low resolution. For higher resolutions, calculating the regridding weights will even take more time. For other use cases (like one variable, many models), this should not change anything regarding runtime. 

Why would you think that #2316 changes something here?

**Comment by bouweandela** [comment]
The result of investigating the issue with #2316 was that the FileLock that prevents downloading the grid multiple times is blocking the computation (fairly easy to solve) and `esmpy` crashes if used from multiple threads (I reported this to the esmpy developers and hope they will be willing to do something about it) -> some more work to do before #2316 is usable.

**Comment by schlunma** [comment]
Thanks for investigating! I still think it's worth to include this PR. What do you think?

**Comment by valeriupredoi** [comment]
> and esmpy crashes if used from multiple threads

surely having to do with HDF5's thread unsafetyness!

Well, I reviewed and approved Manu's PR which I think it's a good idea - caching is always a nice alternative to on the fly, if it's not a bulky, mem-hogging cache, that is :beer:
