### ISSUE TITLE
[CI/GA] Tests fail with new issue (1 test)

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#2349]
See [repeated fail since Feb 24](https://github.com/ESMValGroup/ESMValCore/actions/runs/8026933669) - I'll investigate tomorrow :+1:

**Comment by schlunma** [comment]
That's the same pandas bug as reported here: https://github.com/ESMValGroup/ESMValCore/pull/2305

They released a new version without the bugfix. We need to extend our pin to `pandas !=2.2.0,!=2.2.1`

**Comment by valeriupredoi** [comment]
good man @bouweandela - was just about to start looking into it, you just made my job 85% easier :grin:

**Comment by valeriupredoi** [comment]
lemme put up a PR with the pin
