### ISSUE TITLE
Potential memory leak in local solar time preprocessor

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#2355]
The iris team warned us that Dask appears to be keeping functions it uses in memory even after it is done with them, see https://github.com/SciTools/iris/pull/5767. Wrapping large arguments, such as numpy arrays in a `functools.partial` is an example of how functions can be created that will make this into a sizeable memory leak. I found one example in our codebase where this seems to happen:
https://github.com/ESMValGroup/ESMValCore/blob/2be264db778c5be86600ff5134d28b3b1d8d1e0c/esmvalcore/preprocessor/_time.py#L1508-L1516

@schlunma, could you have a look?

**Comment by schlunma** [comment]
A fix is available here: https://github.com/ESMValGroup/ESMValCore/pull/2356

I also adapted code in a PR here: https://github.com/ESMValGroup/ESMValCore/pull/2299/commits/b825426908661343aa98da955707d703648272af
