### ISSUE TITLE
[CI/CD/GA] Tests failing with one test fail

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#2357]
See [fail](https://github.com/ESMValGroup/ESMValCore/actions/runs/8104817928/job/22152114274) - unfotunately it is 5min before Friday pub o'clock, so I'll look into it on Monday morning :beers:

**Comment by schlunma** [comment]
I am pretty sure this is related to the new release of iris ([3.8.1](https://github.com/SciTools/iris/releases/tag/v3.8.1))

**Comment by valeriupredoi** [comment]
you are absolutely correct @schlunma - see https://github.com/SciTools/iris/issues/5806

**Comment by valeriupredoi** [comment]
OK that xfailed test we xfail in #2363 needs be un-xfailed, and we need to fix the data instead, see https://github.com/SciTools/iris/issues/5806#issuecomment-2077658271

**Comment by valeriupredoi** [comment]
closed via Manu's https://github.com/ESMValGroup/ESMValCore/pull/2403 - Manu, remember that invoking "proper fix" don't close an issue :grin:
