### ISSUE TITLE
Drop support for Python 3.9

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#2406]
Drop support for Python 3.9 as per [NEP-29](https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule).

**Comment by valeriupredoi** [comment]
yes, as soon as we have support for 3.12 (yesterday, ideally) - I think we have a similar issue down the stack, bud

**Comment by valeriupredoi** [comment]
shall we kickstart this one then? Since now we shoehorned 3.12 in :grin:

**Comment by valeriupredoi** [comment]
another reason we should drop 3.9 asap https://github.com/ESMValGroup/ESMValCore/pull/2445

I reckon this:
- we make the 2.11 release the last one supporting 3.9 (so not including that PR in the release, whose pins break the env solving for Linux and OSX 3.9)
- as soon as the release is out, I will get us rid of 3.9 support
