### ISSUE TITLE
Update Iris pin to avoid using versions with memory issues

### ISSUE THREAD

**Issue by ehogan** [ESMValGroup/ESMValCore#2407]
**Is your feature request related to a problem? Please describe.**
Iris v3.7.0 and v3.8.0 contains a regridding memory leak.

Therefore, Iris v3.7.1, v3.8.1 or >= v3.9 must be used to avoid the regridding memory leak.

The [current pin](https://github.com/ESMValGroup/ESMValCore/blob/main/setup.py#L61) is `>=3.8.0`, so I propose updating the pin to `>3.8.0`. This is equivalent to including `!=3.7.0,!=3.8.0`, which @valeriupredoi proposed in the TLT meeting just now 👍 

Instructions to update dependencies are available at [ESMValCore documentation: Dependencies](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies).

**Would you be able to help out?**
@chrisbillowsMO, would it be possible for you to do this, please? 😁

**Comment by valeriupredoi** [comment]
indeed! i was looking at a slightly older `environment.yml` - a `iris >3.8.0` pin sounds good to me, cheers @ehogan :beer:

**Comment by chrisbillowsMO** [comment]
Docs for ESMValCore dependencies [here](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies)

Only two files to update which chimes with:

* #2285 

Change made in:

> - [X] `environment.yml` contains dependencies that cannot be installed from [PyPI](https://pypi.org/)/[Julia package registry](https://github.com/JuliaRegistries/General)

> - [X] `setup.py` contains all Python dependencies, regardless of their installation source

`setup.py` contains this a comment linking to this issue comment: https://github.com/ESMValGroup/ESMValTool/issues/3239#issuecomment-1613298587

I'm wondering if this comment is now resolved by pinning `>3.8.0` and should be removed? @bouweandela @valeriupredoi @ehogan

**Comment by ehogan** [comment]
@chrisbillowsMO I will propose updating the comment to now point to this issue instead 👍

**Comment by ehogan** [comment]
> Docs for ESMValCore dependencies [here](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies)

Apologies for linking to the incorrect documentation! I'll update this in the first comment 👍
