### ISSUE TITLE
Add draft release notes for v2.11.0rc1

### ISSUE THREAD

**Issue by chrisbillowsMO** [ESMValGroup/ESMValCore#2413]
In preparation for the release we are creating the draft release notes as per the instructions we've broken down into steps in this https://github.com/ESMValGroup/ESMValCore/discussions/2389#discussioncomment-9356771.

We've opened the discussion to request PR highlights [here](https://github.com/ESMValGroup/ESMValCore/discussions/2412).  

We're thinking the thing to do is leave the final TODOs for Highlights and Backwards incompatible changes for another issue (i.e. "Add  final release notes for v2.11.0").  Is that how we should do it?  @valeriupredoi @bouweandela

**Comment by bouweandela** [comment]
It's up to you
