### ISSUE TITLE
Diagnostic failure for `recipe_pcrglobwb.yml` on `v2.11.0rc1`

### ISSUE THREAD

**Issue by chrisbillowsMO** [ESMValGroup/ESMValCore#2425]
**Describe the bug**

This recipe is failing as noted in:

* #2421

**Please attach**
  - The recipe that you are trying to run, you can find a copy in the `run` directory in the output directory
  - The `main_log_debug.txt` file, this can also be found in the `run` directory in the output directory

**Comment by valeriupredoi** [comment]
```
iris.exceptions.ConcatenateError: failed to concatenate into a single cube.
  Cube metadata differs for phenomenon: precipitation_flux
```

Very possible this is a manifestation of the same issue with new iris' Attributes as @schlunma pointed out in the other issue
