### ISSUE TITLE
Recipe test results for ESMValCore v2.11.0rc2

### ISSUE THREAD

**Issue by ehogan** [ESMValGroup/ESMValCore#2468]
#### `mamba` version
```
levante5> mamba --version
mamba 1.5.8
conda 24.5.0
```
#### ESMValTool version
```
levante5> esmvaltool version
ESMValCore: 2.11.0rc2
ESMValTool: 2.11.0.dev100+ga176bfca2.d20240627
```

### Recipes that ran successfully (138 out of 161)
<details>
<summary>Click to expand</summary>

- recipe_albedolandcover.yml
- recipe_anav13jclim.yml
- recipe_arctic_ocean.yml
- recipe_autoassess_landsurface_permafrost.yml
- recipe_autoassess_landsurface_soilmoisture.yml
- recipe_autoassess_landsurface_surfrad.yml
- recipe_autoassess_stratosphere.yml
- recipe_bock20jgr_fig_1-4.yml
- recipe_bock20jgr_fig_6-7.yml
- recipe_bock20jgr_fig_8-10.yml
- recipe_capacity_factor.yml
- recipe_check_obs.yml
- recipe_climate_change_hotspot.yml
- recipe_climate_patterns.yml
- recipe_climwip_brunner20esd.yml
- recipe_climwip_test_basic.yml
- recipe_climwip_test_performance_sigma.yml
- recipe_clouds_bias.yml
- recipe_clouds_ipcc.yml
- recipe_cmug_h2o.yml
- recipe_combined_indices.yml
- recipe_concatenate_exps.yml
- recipe_consecdrydays.yml
- recipe_correlation.yml
- recipe_cvdp.yml
- recipe_daily_era5.yml
- recipe_deangelis15nat.yml
- recipe_deangelis15nat_fig1_fast.yml
- recipe_decadal.yml
- recipe_diurnal_temperature_index.yml
- recipe_eady_growth_rate.yml
- recipe_ecs.yml
- recipe_ecs_scatter.yml
- recipe_ensclus.yml
- recipe_era5-land.yml
- recipe_esacci_lst.yml
- recipe_esacci_oc.yml
- recipe_extract_shape.yml
- recipe_extreme_events.yml
- recipe_extreme_index.yml
- recipe_eyring06jgr.yml
- recipe_flato13ipcc_figure_914.yml
- recipe_flato13ipcc_figure_924.yml
- recipe_flato13ipcc_figure_942.yml
- recipe_flato13ipcc_figure_945a.yml
- recipe_flato13ipcc_figure_96.yml
- recipe_flato13ipcc_figure_98.yml
- recipe_flato13ipcc_figures_926_927.yml
- recipe_flato13ipcc_figures_92_95.yml
- recipe_flato13ipcc_figures_938_941_cmip3.yml
- recipe_flato13ipcc_figures_938_941_cmip6.yml
- recipe_galytska23jgr.yml
- recipe_gier2020bg.yml
- recipe_globwat.yml
- recipe_heatwaves_coldwaves.yml
- recipe_hydro_forcing.yml
- recipe_hyint.yml
- recipe_hyint_extreme_events.yml
- recipe_hype.yml
- recipe_iht_toa.yml
- recipe_impact.yml
- recipe_ipccwg1ar6ch3_fig_3_42_b.yml
- recipe_ipccwg1ar6ch3_fig_3_43.yml
- recipe_ipccwg1ar6ch3_fig_3_9.yml
- recipe_julia.yml
- recipe_kcs.yml
- recipe_landcover.yml
- recipe_lauer13jclim.yml
- recipe_lauer22jclim_fig1_clim.yml
- recipe_lauer22jclim_fig1_clim_amip.yml
- recipe_lauer22jclim_fig2_taylor.yml
- recipe_lauer22jclim_fig2_taylor_amip.yml
- recipe_lauer22jclim_fig6_interannual.yml
- recipe_lauer22jclim_fig7_seas.yml
- recipe_lauer22jclim_fig8_dyn.yml
- recipe_lauer22jclim_fig9-11c_pdf.yml
- recipe_li17natcc.yml
- recipe_lisflood.yml
- recipe_marrmot.yml
- recipe_martin18grl.yml
- recipe_meehl20sciadv.yml
- recipe_model_evaluation_basics.yml
- recipe_model_evaluation_clouds_clim.yml
- recipe_model_evaluation_clouds_cycles.yml
- recipe_model_evaluation_precip_zonal.yml
- recipe_modes_of_variability.yml
- recipe_monitor.yml
- recipe_monitor_with_refs.yml
- recipe_mpqb_xch4.yml
- recipe_multimodel_products.yml
- recipe_my_personal_diagnostic.yml
- recipe_ncl.yml
- recipe_ocean_Landschuetzer2016.yml
- recipe_ocean_bgc.yml
- recipe_ocean_example.yml
- recipe_ocean_ice_extent.yml
- recipe_ocean_multimap.yml
- recipe_ocean_quadmap.yml
- recipe_ocean_scalar_fields.yml
- recipe_pcrglobwb.yml
- recipe_perfmetrics_CMIP5.yml
- recipe_perfmetrics_CMIP5_4cds.yml
- recipe_perfmetrics_land_CMIP5.yml
- recipe_preprocessor_test.yml
- recipe_psyplot.yml
- recipe_pv_capacity_factor.yml
- recipe_python.yml
- recipe_python_for_CI.yml
- recipe_quantilebias.yml
- recipe_r.yml
- recipe_radiation_budget.yml
- recipe_rainfarm.yml
- recipe_runoff_et.yml
- recipe_schlund20jgr_gpp_abs_rcp85.yml
- recipe_schlund20jgr_gpp_change_1pct.yml
- recipe_schlund20jgr_gpp_change_rcp85.yml
- recipe_sea_surface_salinity.yml
- recipe_seaborn.yml
- recipe_seaice.yml
- recipe_seaice_drift.yml
- recipe_seaice_feedback.yml
- recipe_shapeselect.yml
- recipe_smpi.yml
- recipe_smpi_4cds.yml
- recipe_snowalbedo.yml
- recipe_spei.yml
- recipe_tcr.yml
- recipe_thermodyn_diagtool.yml
- recipe_toymodel.yml
- recipe_validation.yml
- recipe_validation_CMIP6.yml
- recipe_variable_groups.yml
- recipe_weigel21gmd_figures_13_16.yml
- recipe_wenzel16jclim.yml
- recipe_wenzel16nat.yml
- recipe_wflow.yml
- recipe_williams09climdyn_CREM.yml
- recipe_zmnam.yml
</details>

### Recipes that failed because the diagnostic script failed (3 out of 161)
- recipe_cox18nature.yml (see https://github.com/ESMValGroup/ESMValTool/issues/3701)
- recipe_ecs_constraints.yml (see https://github.com/ESMValGroup/ESMValTool/issues/3701)
- recipe_schlund20esd.yml (see https://github.com/ESMValGroup/ESMValTool/issues/3701)

### Recipes that failed because of missing data (4 out of 161)
- recipe_aod_aeronet_assess.yml (see https://github.com/ESMValGroup/ESMValTool/issues/3690)
- recipe_ocean_amoc.yml (see https://github.com/ESMValGroup/ESMValTool/issues/3693)
- recipe_russell18jgr.yml (see https://github.com/ESMValGroup/ESMValTool/issues/3693)
- recipe_wenzel14jgr.yml (see https://github.com/ESMValGroup/ESMValTool/issues/3693)

### Recipes that failed because the run took too long (8 out of 161)
- recipe_carvalhais14nat.yml
- recipe_eyring13jgr_12.yml
- recipe_ipccwg1ar6ch3_fig_3_19.yml
- recipe_lauer22jclim_fig5_lifrac.yml
- recipe_lauer22jclim_fig9-11ab_scatter.yml
- recipe_miles_block.yml
- recipe_miles_eof.yml
- recipe_miles_regimes.yml

### Recipes that failed because they used too much memory (2 out of 161)
- recipe_ipccwg1ar6ch3_fig_3_42_a.yml
- recipe_lauer22jclim_fig3-4_zonal.yml

### Recipes that failed of other reasons or are still running (6 out of 161)
- recipe_climwip_brunner2019_med.yml (see https://github.com/ESMValGroup/ESMValTool/issues/3694)
- recipe_collins13ipcc.yml (see https://github.com/ESMValGroup/ESMValTool/issues/3702)
- recipe_easy_ipcc.yml (see https://github.com/ESMValGroup/ESMValTool/issues/3703)
- recipe_ipccwg1ar6ch3_atmosphere.yml (see https://github.com/ESMValGroup/ESMValTool/issues/3702)
- recipe_preprocessor_derive_test.yml (see https://github.com/ESMValGroup/ESMValTool/issues/3702)
- recipe_tebaldi21esd.yml (see https://github.com/ESMValGroup/ESMValTool/issues/3702)

**Comment by ehogan** [comment]
My intension is to push to get the PRs for #3690 and #3701 merged asap (hopefully today), then add all other recipes to list of broken recipes, see https://github.com/ESMValGroup/ESMValTool/issues/3662, so I can complete the release today / tomorrow.

@ESMValGroup/technical-lead-development-team, any objections to this? 🤔

**Comment by ehogan** [comment]
ESMValCore v2.11.0 has been released, and all outstanding issues are detailed in their own issues, so closing this issue 👍

**Comment by valeriupredoi** [comment]
tiptop work Emma and the Release Boys :beer:
