### ISSUE TITLE
Bug in activity_id determination for some cmip6 experiments

### ISSUE THREAD

**Issue by zklaus** [ESMValGroup/ESMValCore#248]
In PR #107 (addressing issue #37), we introduced the automatic determination of `activity_id` from `experiment_id`. This works nicely in most cases, but a few experiments have more than one activity associated with them. In that case, all activities are listed in the CV field separated by spaces, but following [the official DRS standard (bottom of page 17)](http://goo.gl/v1drZl), only the first one is used in the path.

As a fix, the field coming from the CV should be `split` on `" "` and only the first entry be taken. This should also work in the normal case of only one activity.

The list of afflicted experiments is
- dcppC-forecast-addPinatubo
- esm-1pct-brch-1000PgC
- esm-1pct-brch-2000PgC
- esm-1pct-brch-750PgC
- esm-1pctCO2
- esm-bell-1000PgC
- esm-bell-2000PgC
- esm-bell-750PgC
- land-hist
- piClim-aer
- piClim-control
- ssp370

**Comment by sloosvel** [comment]
Ok then, totally missed this case.
