### ISSUE TITLE
Preprocessor uses wrong start and end year when leading 0 are given

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#25]
I want to report a rather strange issue:

In a recipe, I load the following data (CMIP6):

```yaml
- {dataset: GFDL-CM4, exp: piControl, ensemble: r1i1p1f1, grid: gr1, start_year: 0151, end_year: 0300}
```

Somehow, the `start_year` and `end_year` are randomly changed to `105`-`192`. This already happens when the recipe is parsed: Printing `raw_recipe` here

https://github.com/ESMValGroup/ESMValTool/blob/91fcb3b533b336e24fa6f607e2ad7a53f4346673/esmvaltool/_recipe.py#L56-L60

yields

```
{...{'end_year': 192, ..., 'start_year': 105}, ...}
```

So this is a problem of `yaml.safe_load()`.

This can be easily fixed by removing the leading `0`, e.g.

```yaml
- {dataset: GFDL-CM4, exp: piControl, ensemble: r1i1p1f1, grid: gr1, start_year: 151, end_year: 300}
```

I just wanted to report this for future users. It took me over 2h to figure out where the problem was since there is obviously no error or warning message. Is there anything we can do about that? Or is this a "feature" of `yaml`?

**Comment by valeriupredoi** [comment]
did you add this to the documentation @schlunma ? So we can close...

**Comment by schlunma** [comment]
No, I totally forgot about that :grimacing:
