### ISSUE TITLE
Fixes appear not to be applied to variables with uppercase letters in the name

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#251]
As reported here: https://github.com/ESMValGroup/ESMValTool/issues/1292#issuecomment-528855877

**Comment by jvegasbsc** [comment]
I can not understand how I forgot about `sfcWind`. It should not be to difficult to fix

**Comment by jvegasbsc** [comment]
The only assumption will now be that there will be no variables with short names that will look the same after the `lower` call.

**Comment by bouweandela** [comment]
We were already assuming that, because we have a unit test that checks that we have no files with names that only differ in case, because this does not work well with certain filesystems/OSs.
