### ISSUE TITLE
Broken link to CF standard name table

### ISSUE THREAD

**Issue by jchriskaiser** [ESMValGroup/ESMValCore#2510]
In [find_data.rst](https://github.com/ESMValGroup/ESMValCore/blob/main/doc/quickstart/find_data.rst), "http://cfconventions.org/standard-names.html" should be replaced by "https://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html".

**Comment by bouweandela** [comment]
Thanks for reporting!
