### ISSUE TITLE
preprocessor mask_landseaice not working anymore

### ISSUE THREAD

**Issue by ruthlorenz** [ESMValGroup/ESMValCore#252]
When using the mask_landseaice preprocessor I get
ValueError: Landsea-ice mask could not be found. Stopping.

The last time I tried and used it is a while ago, and my recipe (recipe_collins13ipcc.yml) might be the only one using this. So far the recipe is only in ESMValTool-private, but it should go into public and AR6 (asap of course ;-)).

Anyone able to help?

**Comment by valeriupredoi** [comment]
https://github.com/ESMValGroup/ESMValTool/pull/1310 got merged so this issue is redundant :beer:
