### ISSUE TITLE
Dataset problem: regrid AERmonZ CMIP type

### ISSUE THREAD

**Issue by MartineMichou** [ESMValGroup/ESMValCore#2605]
I  would like to plot zonal means of data dealing in the same recipe
with both data on a plev,lat,lon grid and data on a plev, lat, grid
(AERmonZ CMIP6 files). This recipe uses the multi_dataset.py script.

I guess I have to regrid both kind of files to the same horizonal grid first.

When I try to do with; 
    regrid:
      target_grid: 2x2
      scheme: linear

that I get a error message.

ERROR   esmvalcore.preprocessor:348 Failed to run preprocessor function 'regrid' on the data
[<iris 'Cube' of mole_fraction_of_methane_in_air / (mol mol-1) (time:
24; air_pressure: 39; latitude: 128)>]

What would be the way to put the AERmonZ file and the Amon file, for
instance, on the same horizontal grid?

Thank you.
Regards,
Martine Michou

**Comment by valeriupredoi** [comment]
hi @MartineMichou if you try to regrid on a "2x2" grid (lat x lon) a cube that has only one linear horizontal dimension (only latitude, no longitude) then the regridder will fail, AFAIK we don't have a regridding option along a single horizontal dimension, but @schlunma can correct me

**Comment by MartineMichou** [comment]
Thank you for your responses Manuel and Valeriu. I will go for regridding on the AERmonZ grid. Cheers,
Martine
