### ISSUE TITLE
Fix CircleCI for external repositories

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#261]
At the moment, some CircleCI tests fail for external repo's, because coverage cannot be uploaded, see e.g. https://circleci.com/gh/ESMValGroup/ESMValCore/3531?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

The CircleCI test script should be modified so it only tries to upload coverage from the ESMValGroup/ESMValCore repo.

**Comment by valeriupredoi** [comment]
same happens with forked repos https://github.com/ESMValGroup/ESMValCore/pull/272
