### ISSUE TITLE
Read in CMIP3 datasets

### ISSUE THREAD

**Issue by LisaBock** [ESMValGroup/ESMValCore#27]
I need to read in **CMIP3** datasets in the ESMValTool. I started to implement this feature in the code but it was not successful as I did something wrong or missed something for sure.
Is there anyone who could support me?

What I did:
I modified `cmor/table.py` and `config-developer.yml` and added the CMOR table file `cmor/tables/cmip3/Tables/CMIP3_A1` (see branch `version2_development_cmip3`).
And I tried it with adding this dataset lines in the `recipes/recipe_python.yml`:
```
  - {dataset: ukmo_hadcm3,  project: CMIP3,  mip: A1,  exp: 20c3m,  ensemble: run1,  start_year: 1997,  end_year: 1999}
  - {dataset: ukmo_hadgem1,  project: CMIP3,  mip: A1,  exp: 20c3m,  ensemble: run1,  start_year: 1997,  end_year: 1999}
```
On DKRZ the data structure is like this:
`<CMIP3-directory>/20c3m/atm/mo/pr/ukmo_hadgem1/run1/pr_A1.nc`

The error message is:
`esmvaltool._recipe_checks.RecipeError: Unable to load CMOR table 'CMIP3' for variable 'tas' with mip 'A1'`

**Comment by jvegasbsc** [comment]
Now that we are restarting this...

> One idea - can we use the OBS cmorizers to cmorize CMIP3 data in advance of using it?

I would like to try avoiding this. It will be a good test to see if we can manage to read loosely structured datasets
