### ISSUE TITLE
version part of CMIP5 drs on badc

### ISSUE THREAD

**Issue by zklaus** [ESMValGroup/ESMValCore#278]
The drs for CMIP5 on badc/jasmin contains a literal `latest` for the version part. This mostly works because there is always a `latest` link pointing to the most recent version. However, for some datasets there are several versions and the latest only contains a few variables where the bulk of the data comes from earlier versions.

An extreme example is
```
/badc/cmip5/data/cmip5/output1/FIO/FIO-ESM/historical/mon/ocean/Omon/r1i1p1
```
where in the latest version there is *only* `so`, all other variables being available in the earlier version.

Can we replace `latest` with `[latestversion]` as in most of the other drs?

**Comment by valeriupredoi** [comment]
lovely, I guess `so` is the only good *latest* variable and the rest are crap :grin: Good catch @zklaus
