### ISSUE TITLE
Add land/ocean-fraction weighting preprocessor

### ISSUE THREAD

**Issue by ChrisJones-MOHC** [ESMValGroup/ESMValCore#298]
Hi - i'm new to this forum, so hopefully this is the right way to request a new functionality.

It would be great to have a pre-processor which applied a weighting by land-fraction. This is different from simply masking data in/out according to a threshold value. What is required is to multiply the given input field by a fraction from 0-1 to account for the fact that not all grid points are completely land/ocean - some are fractional.

The application is important for most carbon cycle variables, and other land-surface outputs, which are reported in units of "carbon per square-metre". But this actually refers to "per square metre of land" and NOT "per square metre of gridbox". So in order to integrate these globally or regionally one has to both area-weight the quantity but also weight by the land fraction.

It would be great to get a pre-processor which could do this to produce a dataset of carbon stores or fluxes which are "per square metre of gridbox".

so, for example, for the carbon flux called "gpp" I would want to:
gpp(t) = gpp(t) * land-frac
where land_frac is the time-static fractional cover of land in each gridbox

A converse weighting for ocean fluxes is also useful of course. (i.e. scaled by 1-land_frac)

I hope this description makes sense. I'd be happy to try to help test or better define.

thanks!
Chris

**Comment by valeriupredoi** [comment]
welcome to the club @ChrisJones-MOHC :beer: ANd very happy to see a coffee discussion at CRESCENDO GA is now an issue here :grin:

**Comment by ChrisJones-MOHC** [comment]
thanks  @schlunma @valeriupredoi - great support from you guys!

**Comment by schlunma** [comment]
Started working on this now for ESMValGroup/ESMValTool#473.

**Comment by valeriupredoi** [comment]
#331
