### ISSUE TITLE
Older versions of documentation should be deleted or their html addresses should redirect to the latest version

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#302]
`annual_mean` -> `annual_statistics` and such, brought to my attention by @ChrisJones-MOHC

**Comment by bouweandela** [comment]
As discussed offline, up to date documentation is available if you look at the 'latest' version of the documentation, which is shown by default when you go to https://esmvaltool.readthedocs.io.

**Comment by valeriupredoi** [comment]
Aha, but as we talked we need to take the older versions offline or at
least redirect the links to the latest version, so unfortunately am gonna
reopen and rename this issue until that's done :beer:

Dr Valeriu Predoi.
Computational scientist
NCAS-CMS
University of Reading
Department of Meteorology
Reading RG6 6BB
United Kingdom
