### ISSUE TITLE
Make documentation available on docs.esmvaltool.org?

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#315]
It is possible to use your own domain with readthedocs, so we could make the documentation currently available on esmvaltool.readthedocs.org available on docs.esmvaltool.org. This would make our documentation easier to find for new users by reducing the number of possible websites that they need to visit.

See https://docs.readthedocs.io/en/stable/custom_domains.html for instructions.

**Comment by bouweandela** [comment]
@bjoernbroetz Would you be able to do this?

**Comment by axel-lauer** [comment]
I think this is a good idea and I started looking into this. I'll report back soon.

**Comment by axel-lauer** [comment]
The documentation is now available at: http://docs.esmvaltool.org/
Not sure why only "http" works but "https" does not. But maybe this is not a problem for the documentation? If people are happy with this, I would replace the links to the documentation on the esmvaltool website with docs.esmvaltool.org.

**Comment by bouweandela** [comment]
Looks very good! https://docs.esmvaltool.org works fine on my computer too.

**Comment by axel-lauer** [comment]
https now also works for me, maybe it simply took a bit to reissue the ssh certificate. I'll change the links on esmvaltool.org then.

**Comment by axel-lauer** [comment]
Just updated the links to our documentation on esmvaltool.org (changes should be online soon). I guess we could now close this issue?

**Comment by mattiarighi** [comment]
Yes, thank you.

**Comment by bouweandela** [comment]
We also need to change the links everywhere in the ESMValCore and ESMValTool repositories

**Comment by axel-lauer** [comment]
The links have been updated:

https://github.com/ESMValGroup/ESMValCore/pull/675
https://github.com/ESMValGroup/ESMValTool/pull/1679
