### ISSUE TITLE
Use dask whenever possible in preprocessor to keep memory intake low

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#32]
This is a followup from a lot of suggestions and work (mainly done by @bouweandela and @jvegasbsc ). Examples of high memory intake can be seen in various issues like #810 or #922 ; also work is underway in PRs like #1001 or initiated by issues like #949 . There are also the issues related to inherent changes of iris and handling of lazy data eg see #887 So far, actual work is done as follows:

**Active work as PR**
 - [x] ESMValGroup/ESMValTool#1001 on `_area.py`
 - [x] https://github.com/SciTools/iris/pull/3299 for lazy weights on iris aggregators
 - [ ] #51

Let's add pull requests here that address the use of dask in other preprocessor modules and gradually close all the issues and PR's (upon acceptance and good code behavior wrt memory) that are listed above :beer:

**Comment by bjlittle** [comment]
@valeriupredoi and @bouweandela You guys should be aware of https://github.com/SciTools/iris/issues/3357

In a nutshell, if a netCDF variable has an UNLIMITED dimension, then netCDF automatically applies netCDF level chunking to the file, which in most cases will not be detrimental to the performance of dask within iris i.e. the chunking specified by netCDF is really small, almost too small for task, so there is a massive overhead in dask to deal with files that have tiny chunks.

A fix on our side will resolve this... just sayin :wink:

**Comment by bouweandela** [comment]
Created a new overview issue: #674
