### ISSUE TITLE
Alias missing for Multi-model mean

### ISSUE THREAD

**Issue by soufianekar** [ESMValGroup/ESMValCore#324]
When running the recipes with multimodel mean preprocessor, the multimodel mean file does not have an alias attribute. This makes the run fail for diagnostics that expect this key to be available.

**Comment by jvegasbsc** [comment]
Thanks for reporting! I will take a look

**Comment by bouweandela** [comment]
This has been implemented in https://github.com/ESMValGroup/ESMValCore/pull/499.
