### ISSUE TITLE
Errors in landcoverFrac in CESM2 and CESM2-WACCM CMIP6 data

### ISSUE THREAD

**Issue by bascrezee** [ESMValGroup/ESMValCore#328]
While working on https://github.com/ESMValGroup/ESMValTool/pull/1370 I ran into the following `CMORCheckErrors`: 

```
esmvalcore.cmor.check.CMORCheckError: There were errors in variable grassFrac:
typenatgr: does not exist
```

```
esmvalcore.cmor.check.CMORCheckError: There were errors in variable treeFrac:
typetree: does not exist
```

I can confirm that `typenatgr` and `typetree` are not on the files. Why are they expected? How to deal with this discrepancy?

**Comment by valeriupredoi** [comment]
see https://github.com/ESMValGroup/ESMValTool/pull/1272#issuecomment-544873027

**Comment by zklaus** [comment]
It would be really good to have an example of a file that files.
@bascrezee, could you perhaps paste the offending `{dataset:...}` line here?

**Comment by bascrezee** [comment]
> It would be really good to have an example of a file that files.

    - {dataset: CESM2, project: CMIP6, grid: gn, exp: historical, ensemble: r1i1p1f1}

**Comment by zklaus** [comment]
Thanks, @bascrezee !

**Comment by zklaus** [comment]
Ok this actually seems to be simply a bug in the CESM2(-WACCM) data. Could you try with one of the other models that provide the data, ie

* UKESM1-0-LL
* HadGEM3-GC31-LL
* MPI-ESM1-2-HR

?
If that works, we just have to write the fix for CESM2.

**Comment by bascrezee** [comment]
Yes, I can confirm, that it works fine for the following: 

```
    - {dataset: UKESM1-0-LL, project: CMIP6, grid: gn, exp: historical, ensemble: r1i1p1f2}
    - {dataset: HadGEM3-GC31-LL, project: CMIP6, grid: gn, exp: historical, ensemble: r1i1p1f3}
    - {dataset: MPI-ESM1-2-HR, project: CMIP6, grid: gn, exp: historical, ensemble: r10i1p1f1}
```

**Comment by zklaus** [comment]
Great! Could you prepare a PR for the CESM2(-WACCM) fix?
I'd like to see the [`add_scalar_typeland_coord`](https://github.com/ESMValGroup/ESMValCore/blob/0197e1963573d54b012d5581a1dc6a8ff87cc43e/esmvalcore/cmor/_fixes/shared.py#L37) refactored into a `add_scalar_area_type_coord` function that takes both the value and the `long_name`.

Then this can be applied to the model in question with the information from [CMIP6_coordinate.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/c4a8446bae0000ab3ccd0b4871bfdb7241421cc4/Tables/CMIP6_coordinate.json#L3064) and similar blocks in the same file.

**Comment by bascrezee** [comment]
> Great! Could you prepare a PR for the CESM2(-WACCM) fix?
> I'd like to see the [`add_scalar_typeland_coord`](https://github.com/ESMValGroup/ESMValCore/blob/0197e1963573d54b012d5581a1dc6a8ff87cc43e/esmvalcore/cmor/_fixes/shared.py#L37) refactored into a `add_scalar_area_type_coord` function that takes both the value and the `long_name`.
> 
> Then this can be applied to the model in question with the information from [CMIP6_coordinate.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/c4a8446bae0000ab3ccd0b4871bfdb7241421cc4/Tables/CMIP6_coordinate.json#L3064) and similar blocks in the same file.

This does not have a too high priority for me, also I prefer to wait until we have a broader overview of the problem. I would like to push forward the new functionality suggested by @valeriupredoi in https://github.com/ESMValGroup/ESMValCore/pull/307, this would be very helpful for me.

**Comment by zklaus** [comment]
Alright. I guess this issue will hang around for a bit then :man_shrugging:

**Comment by zklaus** [comment]
The CESM problems are now tracked in issue #1066 that supersedes this issue.
