### ISSUE TITLE
CMOR check.py : line duplicated.

### ISSUE THREAD

**Issue by ledm** [ESMValGroup/ESMValCore#357]
Hi,

the line 381 has been duplicated accidentally.

https://github.com/ESMValGroup/ESMValCore/blob/21f3d87afef0de6de5468cb2822d8ba92c3d7c46/esmvalcore/cmor/check.py#L318

This makes the error message more confusing that it should be. Easy fix though.

**Comment by ledm** [comment]
It also needs a space after `{1}`.

**Comment by valeriupredoi** [comment]
maybe just use #334 for this, it's a one-liner, pretty much as the changes in said PR :beer:
