### ISSUE TITLE
start_year and end_year in the filename of preprocessed fx files

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#368]
If you don't specify `start_year` and `end_year` in the recipe for fx variables, the output filename cannot be constructed because it contains these values. This does not make sense.

**Comment by valeriupredoi** [comment]
bleh! this is only for the corner case when you specify your `datasets` or `additional_datasets` as incomplete and populate the variables' attributes with `start/en_year`. Good catch @bouweandela
