### ISSUE TITLE
Mask_landsea unable to find fx files at diagnostic level

### ISSUE THREAD

**Issue by sloosvel** [ESMValGroup/ESMValCore#381]
**Describe the bug**
The mask_landsea routine expects the name of the fx files to start by the `var_name` (sftlf_fx_ ... .nc). This is because of the way the keys are defined in a dictionary inside the routine. 

If the masking is performed at the diagnostic level, it is not able to find the fx files because they get renamed during the preprocessing according to the output_file convention in the config-developer ( project_... .nc). So it always ends up applying the Natural Earth files.

As a reference, in https://github.com/ESMValGroup/ESMValTool/pull/1288/ , I currently have to link the fx files so that the name starts by the var_name in order to be able to apply the mask. But that workaround looks a bit strange. Could the routine be generalised to accept the fx files even after they get renamed?

**Comment by valeriupredoi** [comment]
good catch @sloosvel - I shall attempt at fixing this right now :beer:

**Comment by valeriupredoi** [comment]
#383 have a test pls
