### ISSUE TITLE
Python 3.8 environment for ESMValCore

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#388]
We'll have to lift the pin to `python<3.8` soon so I managed to get us a working environment...minus `numba` but there's good news for that as well. This is it:
```
---
name: esmvaltool
channels:
  - conda-forge

dependencies:
  - esmpy
  - iris>=2.2.1
  - fiona
  - graphviz
  - gcc_linux-64
  - libunwind  # Needed for Python3.7+
  # - numba>=0.47.0
  - python>=3.6
  - python-stratify
```
Note two things: we need `fiona` from conda (because `pip` can not find `gdal` correctly for `fiona`) and we will have `numba=0.47.0` that is built with py38; in fact numba 47 is already available but not yet in the conda json db: https://anaconda.org/numba/numba/files (well, uploaded 9h ago)

**Comment by valeriupredoi** [comment]
and here's me asking the numba guys about their upcoming py3.8 version https://github.com/numba/numba/issues/4936

**Comment by valeriupredoi** [comment]
OK so a numba dev kindly told us they will release numba=0.47 on Dec 19 and that'll work with py3.8. Kudos who gonna test then, I'll be gone for Xmas by then :santa:

**Comment by mattiarighi** [comment]
Still relevant?
