### ISSUE TITLE
Several unit tests involving masked arrays are not implemented correctly ?

### ISSUE THREAD

**Issue by bascrezee** [ESMValGroup/ESMValCore#393]
**Describe the bug**
While working on #392 I found out that the numpy testing function `assert_array_equal` operates on `masked arrays` differently than what one might expect.

Mwe: 
```
import numpy as np
from numpy.testing import assert_array_equal


a = np.ma.masked_array(np.array([1,2]),mask=[True, True])
b = np.ma.masked_array(np.array([1,2]),mask=[True, False])

assert_array_equal(a,b) # doesn't raise !
```

Correct testing should check the mask and the data separately to assert equality.
```
assert_array_equal(a.data, b.data)
assert_array_equal(a.mask, b.mask)
```

Several functions in `test_mask.py` are impacted, e.g.: 
https://github.com/ESMValGroup/ESMValCore/blob/7d682894d872bd00909c040aee435857bbb9768f/tests/unit/preprocessor/_mask/test_mask.py#L94-L98

**Comment by valeriupredoi** [comment]
Very good catch, Bas! cheers, mate, will fix it tomorrow (travelling today)
:beer:

Dr Valeriu Predoi.
Computational scientist
NCAS-CMS
University of Reading
Department of Meteorology
Reading RG6 6BB
United Kingdom

**Comment by valeriupredoi** [comment]
so just to be clear here - the test is performed *only* on the data and not on the mask - so there's no need to expand to `array.data` and simply by stating the comparison on `array` is enough, but it is important to add the extra check on `array.mask` :+1:
