### ISSUE TITLE
Outdated code in _derive/rlnstcs.py

### ISSUE THREAD

**Issue by katjaweigel** [ESMValGroup/ESMValCore#394]
**Describe the bug**
There is outdated code in _derive/rlnstcs.py which causes problems in the preprocessor. It needs to be updated as is has already be done for _derive/rlnst.py
I already made a fix under the new branch rlnstcs_fix.

**Please attach**
  - The recipe that you are trying to run: recipe_deangelis15nat.yml, so far only in the ESMValTool branch deangelis_for_gmdpart4
  - The `main_log_debug.txt` file: [job_18709052.out.log](https://github.com/ESMValGroup/ESMValCore/files/3949411/job_18709052.out.log)

**Comment by valeriupredoi** [comment]
closed via #395
