### ISSUE TITLE
Preprocessor generality

### ISSUE THREAD

**Issue by ledm** [ESMValGroup/ESMValCore#40]
Some preprocessors like `zonal_mean` and `area_average` have recently (#825) been expanded to allow more generic operation beyond just a simple mean. This means that while they're called `mean` or `average`, they can also do medians, standard deviations, variance, etc. 

It would be great to add this functionality to the other spatial and temporal preprocessors: 
- `average_volume`
- `seasonal_mean`
- `time_average`

While we're there, we should also change  `zonal_mean`'s argument from `mean_type` to `operation` to match `average_region`.

We wouldn't even need to change our recipes if we kept the current preprocessors names like `zonal_mean` or `average_volume` as special cases of the more generic functions.

**Comment by jvegasbsc** [comment]
#87 is doing this for time related functions

**Comment by mattiarighi** [comment]
I think this is solved, @ledm ?

**Comment by ledm** [comment]
Yes!
