### ISSUE TITLE
Dataset problem: MCM-UA-1-0 (CMIP6) datasets have wrong coordinate names

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#425]
**Describe the dataset issue**

- ~~Data file has been changed by you in any way (if you answer yes the issue will be void and closed, we are not
supporting custom-made datasets that present problems, it is your resposability to fix those problems)~~
- Project (CMIP5/CMIP6/OBS/obs4mips/etc): CMIP6
- Full dataset decription (fill out as many as you know, please):
  - dataset: MCM-UA-1-0
  - experiment: piControl, 1pctCO2
  - mip: Amon
  - grid: gn
  - type:
  - version: v20190731
  - tier:
  - variable used: `tas`, `ta` (probably all)
  - data_specs_version: 01.00.28
- Problems encountered (please describe what the actual problems are: e.g. wrong standard name, issue with dimensions):
  - For variable `tas`: `height` coordinate is not correctly marked as coordinate, so `iris` does not assign it correctly as `scalar coordinate`
  - `var_name` of `latitude` is `latitude`, not `lat`
  - `var_name` of `longitude` is `longitude`, not `lon`
  - `parent_time_units` has invalid format (ends with `... (noleap)`)
- Pointer to existing copy of data on ESGF node (it would be very useful if you could provide a physical fullpath to the file(s) that are causing the problem, e.g. on CEDA Jasmin or DKRZ): DKRZ: `/mnt/lustre02/work/ik1017/CMIP6/data/CMIP6/CMIP/UA/MCM-UA-1-0/1pctCO2/r1i1p1f1/Amon/tas/gn/v20190731/tas_Amon_MCM-UA-1-0_1pctCO2_r1i1p1f1_gn_000101-010012.nc`
- Other notes and mentions: I will write a fix for it

**Comment by valeriupredoi** [comment]
fixes implemented and merged via https://github.com/ESMValGroup/ESMValCore/pull/426 by @schlunma but we need to alert the MCM-UA folks: @zklaus and/or @valeriupredoi will do that

**Comment by zklaus** [comment]
Reported upstream.

**Comment by valeriupredoi** [comment]
did the upstream reply?

**Comment by zklaus** [comment]
No. As they generally won't :disappointed:
