### ISSUE TITLE
Logger does not print out reference file

### ISSUE THREAD

**Issue by mattiarighi** [ESMValGroup/ESMValCore#434]
While testing other PRs, I noticed that the logger does not print the reference file, although it says so:

```
INFO    [7856] Ending the Earth System Model Evaluation Tool v2.0.0b3 at time: 2020-01-17 08:04:30 UTC
INFO    [7856] Time for running the recipe was: 0:08:26.203280
INFO    [7856] For the required references/acknowledgements of these diagnostics see:

INFO    [7856] Run was successful
```

Actually, we do not have such a file in the output, so we should probably just remove the message. It looks like a remnant from v1.0.

**Comment by bouweandela** [comment]
> we do not have such a file in the output, so we should probably just remove the message. 

Indeed let's remove it. My colleague @SarahAlidoost is working on fixing the citation information in #402.

**Comment by mattiarighi** [comment]
Removed in #435.
