### ISSUE TITLE
Extract odd-shaped (irregular) regions

### ISSUE THREAD

**Issue by LisaBock** [ESMValGroup/ESMValCore#44]
I would like to extract regions in the preprocessor of the ESMValTool which are not rectangular but as they are defined in the IPCC AR5 or AR6. For example to create the panels for a figure like this:

![image](https://user-images.githubusercontent.com/25476740/53959556-38bad400-40e4-11e9-9ccd-501bff7c4295.png)

Is there a possibility to include this in the preprocessor functions? 

At the moment I do not have the specific region definitions but I could share them when I received them.

**Comment by mattiarighi** [comment]
@LisaBock is this solved? If yes, please close.

**Comment by valeriupredoi** [comment]
closing since it looks to be solved, please re-open if need be :beer:
