### ISSUE TITLE
ssp534-over question?

### ISSUE THREAD

**Issue by ledm** [ESMValGroup/ESMValCore#444]
I've encountered a new experiment that I've never encoutered before. The ScenarioMIP experiment, `ssp534-over` branches from the run `ssp585` in 2040. 

If I put this in a recipe like this:
```
exp: [historical, ssp585, ssp534-over]
```
Will ESMValTool be able to figure out that we don't want any data from `ssp585` after 2040?

**Comment by valeriupredoi** [comment]
yes and no, using #280 it will concatenate depending on what and how data starts and ends ie if `ssp534-over` finishes after anything else and it starts at the same time as the others (or before), then it will use only that one; have a look at the concatenation mechanism there

**Comment by mattiarighi** [comment]
Reopen if necessary.
