### ISSUE TITLE
Tiling problem with fx files in `area_statistics`

### ISSUE THREAD

**Issue by ledm** [ESMValGroup/ESMValCore#445]
There are a few issues with `area_statistics`. 
- [ ] The tiling of the areacello/a data was done by numpy, which is too memory heavy. It needs to be replaced by a dask version.
- [ ] There is no option to try to calculate the cell areas. (This is neccesairy for observational datasets, sometimes as FX files are rarely available for these datasets.)
- [ ] There is no way to calculate a weightless mean or a weightless sum. Issue described in more detail in #442

**Comment by ledm** [comment]
PR #446 should address all three issues.

**Comment by valeriupredoi** [comment]
note however that `iris` still doesn't work with dask array weights (`cube.py` line 3277) so them weights need to be numpyfied

**Comment by ledm** [comment]
Really? I thought that if you realise the dask array, it would be fine?

**Comment by valeriupredoi** [comment]
> Really? I thought that if you realise the dask array, it would be fine?

mate: https://github.com/ESMValGroup/ESMValCore/pull/446/files/7ab07fcd14ebd29ffa1b901bf6e2b6a16437d1f6#r371303808

**Comment by bouweandela** [comment]
@ledm Is there anything left to do here? I think these issues have been resolved some time ago.
