### ISSUE TITLE
Outdated CMOR CMIP6 Tables

### ISSUE THREAD

**Issue by tomaslovato** [ESMValGroup/ESMValCore#45]
In the current **version2_development** branch (up to commit d72f6c3915dcc7a55a51b8abae00213a03349659) CMIP6 tables are quite old (about 11 months) and several changes occurred in the data request definition.

I guess it would be good to have a fresh version in the repository and possibly add also a note about the reference Dreq version (likely in cmip6 table README.md).

**Comment by valeriupredoi** [comment]
to be closed via #158
