### ISSUE TITLE
Allow fx cubes as input for preprocessor functions which need fx files

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#451]
As mentioned in #439, it would be nice if all preprocessor functions which use fx files (e.g. `area_statistics`, `volume_statistics`, `landsea_fraction_weighting`, `mask_landsea`, etc.) would also accept `iris.cube.Cube` objects for the fx files, not only file paths, similar to [`regrid`](https://github.com/ESMValGroup/ESMValCore/blob/bc7c117323cd8b6eafcba72f2bcf0ebc1fc5229e/esmvalcore/preprocessor/_regrid.py#L180). That way it would be easier to use them externally, e.g. in derive scripts or in the `esmvaltool` module.

**Comment by bouweandela** [comment]
Related to #436

**Comment by schlunma** [comment]
Since all relevant preprocessors use `iris.cube.Cube.cell_measure`s or `iris.cube.Cube.ancillary_variable`s now, we can close this.
