### ISSUE TITLE
CMIP6 fx files stored in different directories, depending on realm

### ISSUE THREAD

**Issue by DSenftleben** [ESMValGroup/ESMValCore#46]
Not all fx files for CMIP6 models are located in the fx/ directory. For example, 'areacello' is stored under Ofx/, 'sandfrac' under Efx/. See also example below.

Therefore, config-developer.yml needs to be extended to also check the other *fx/ directories when searching for the fx files specified in the recipe.

Example: 
/CNRM-CERFACS/CNRM-CM6-1/historical/r1i1p1f2/fx/
/CNRM-CERFACS/CNRM-CM6-1/historical/r1i1p1f2/Efx/
/CNRM-CERFACS/CNRM-CM6-1/historical/r1i1p1f2/Ofx/

**Comment by valeriupredoi** [comment]
#170 retrieves fx files as any other regular variable so when that gets merged we can close this one too :beer:

**Comment by valeriupredoi** [comment]
also maybe open a new issue with what @bouweandela has suggested to have a list of `mip`'s available for the fx data retriever to look for

**Comment by valeriupredoi** [comment]
hell yeah, cheers for digging this up :beer:
