### ISSUE TITLE
Dataset problem:  GFDL-CM2p1 sit has invalid time bounds

### ISSUE THREAD

**Issue by jvegasbsc** [ESMValGroup/ESMValCore#461]
I have found a sit file for CMIP5 GFDL-CM2p1 that has time bounds of about 1e9  with times of abot 40000. Iris breaks up at the checker, when changing the time units:

```yaml
- {dataset: GFDL-CM2p1, project: CMIP5, exp: historical, ensemble: r1i1p1, start_year: 2001, end_year: 2004}
```

Pull request with the fix is coming soon

**Comment by jvegasbsc** [comment]
[recipe_seaice_feedback.txt](https://github.com/ESMValGroup/ESMValCore/files/4169831/recipe_seaice_feedback.txt)

**Comment by zklaus** [comment]
Just to clarify: I think we won't be reporting CMIP5 problems upstream, only CMIP6. Do you guys agree, @valeriupredoi, @mattiarighi, @bouweandela ?

**Comment by valeriupredoi** [comment]
Indeed, anything that can still be repaired via errata and re-cmorization by the model teams - CMIP5 will not be touched anymore (I got a few blunt replies saying this) :beer:
