### ISSUE TITLE
Do we still need fix_file?

### ISSUE THREAD

**Issue by jvegreg** [ESMValGroup/ESMValCore#463]
This fix was introduced when we were way more strict loading the data with Iris. The fixes we were doing then are now done in the `fix_metadata` step in a more efficient way.

Do we get rid of this fix step or keep it for *possible* future necessity?

@schlunma has implemented some new fixes using this, but I think he may be able to move them to the `fix_metadata` step using https://scitools.org.uk/iris/docs/latest/iris/iris/aux_factory.html. In order to remove it, we need him to confirm if I'm not wrong

@zklaus @bouweandela

**Comment by schlunma** [comment]
> @schlunma has implemented some new fixes using this, but I think he may be able to move them to the `fix_metadata` step using https://scitools.org.uk/iris/docs/latest/iris/iris/aux_factory.html. In order to remove it, we need him to confirm if I'm not wrong

I'll give it a try

**Comment by zklaus** [comment]
This would, however, be moving the fix to the conceptually wrong place, forcing us to duplicate iris code (for parsing the netcdf information and creating the auxfactories, etc.) that is prone to change in future versions of iris and/or CF.

Fixing the attributes before the data is handed over to iris would avoid that.

**Comment by schlunma** [comment]
> This would, however, be moving the fix to the conceptually wrong place, forcing us to duplicate iris code (for parsing the netcdf information and creating the auxfactories, etc.) that is prone to change in future versions of iris and/or CF.
> 
> Fixing the attributes before the data is handed over to iris would avoid that.

Then I won't give it a try? Fixing this with `iris` is probably also less efficient

**Comment by jvegasbsc** [comment]
> Fixing this with iris is probably also less efficient

It is really difficult to be less efficient than `fix_file`, It is reading and writing again the full file before even loading it

**Comment by bouweandela** [comment]
And users complain a lot if you try to do that sort of thing, because it's slow and uses lots of disk space.

**Comment by schlunma** [comment]
> It is really difficult to be less efficient than `fix_file`, It is reading and writing again the full file before even loading it

Right, I forgot that the whole dataset is copied in the first place :man_facepalming:

**Comment by schlunma** [comment]
Okay, I got rid of `fix_data` in my case (was actually a lot simpler than I expected). However, I'm not quite sure if we should `fix_data` completely.

**Comment by schlunma** [comment]
I think we can close this in favor of https://github.com/ESMValGroup/ESMValCore/issues/2129. To remain as flexible as possible in the future, we should not retire `fix_file` altogether. In addition, there are fixes where we definitly need `fix_file` (e.g., [here](https://github.com/ESMValGroup/ESMValCore/blob/a6639a70465dbeca8825a5683cba3ad44302b3cb/esmvalcore/cmor/_fixes/cmip6/cesm2.py#L39)).
