### ISSUE TITLE
Dataset problem: areacello missing for some CMIP5 historical runs

### ISSUE THREAD

**Issue by jvegasbsc** [ESMValGroup/ESMValCore#464]
The following CMIP5 datasets are missing areacello (in Jasmin at least) for the historical experiment 

```yaml
 - {&cmip5 {project: CMIP5, exp: historical, dataset: bcc-csm1-1-m  ensemble: r1i1p1, start_year:        
 - {<<: *cmip5, dataset: CESM1-CAM5-1-FV2}
 - {<<: *cmip5, dataset: FIO-ESM}
 - {<<: *cmip5, dataset: GISS-E2-H-CC}
 - {<<: *cmip5, dataset: GISS-E2-R-CC}
 - {<<: *cmip5, dataset: HadGEM2-AO}
 - {<<: *cmip5, dataset: inmcm4}
```

Detected while working in  ESMValGroup/ESMValTool#1299

**Comment by zklaus** [comment]
Nice way to write the anchor!

The data also isn't available from esgf, so I suggest to simply exclude these models from analysis that relies on `areacello`.

**Comment by jvegasbsc** [comment]
> The data also isn't available from esgf, so I suggest to simply exclude these models from analysis that relies on areacello.

I will do that, leaving a note in the recipe about why we are excluding them.
