### ISSUE TITLE
_stock_cube fails on attempt to use float as integer 

### ISSUE THREAD

**Issue by jhardenberg** [ESMValGroup/ESMValCore#469]
Misteriously my copy of ESMValTool/ESMValCore gives the following error.

After installing a fresh copy of ESMValTool  (a fresh pull, using the master branch, updated environment, new setup etc) and testing any recipe, ESMValTool stops, complaining with

```
 File "/home/jost/miniconda3/envs/esmvaltool/lib/python3.7/site-packages/esmvalcore/preprocessor/_regrid.py", line 133, in _stock_cube
    (_LAT_RANGE / dlat))
  File "<__array_function__ internals>", line 6, in linspace
  File "/home/jost/miniconda3/envs/esmvaltool/lib/python3.7/site-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.
```
In fact lines 130- 142 of _regrid.py are currently
```
    # Construct the latitude coordinate, with bounds.
    if lat_offset:
        latdata = np.linspace(_LAT_MIN + mid_dlat, _LAT_MAX - mid_dlat,
                              _LAT_RANGE / dlat)
    else:
        latdata = np.linspace(_LAT_MIN, _LAT_MAX, _LAT_RANGE / dlat + 1)

    # Construct the longitude coordinat, with bounds.
    if lon_offset:
        londata = np.linspace(_LON_MIN + mid_dlon, _LON_MAX - mid_dlon,
                              _LON_RANGE / dlon)
    else:
        londata = np.linspace(_LON_MIN, _LON_MAX - dlon, _LON_RANGE / dlon)
```

Apparently the last argument (the "num=" argument) should be an integer but is interpreted as a a float. 
Adding an "int()" to the last argument of linspace fixes the issue, for example:

```
        latdata = np.linspace(_LAT_MIN + mid_dlat, _LAT_MAX - mid_dlat,
                              int(_LAT_RANGE / dlat))
```

I have no idea why this is needed for my configuration and apparently nobody else gets it  ....

**Comment by jhardenberg** [comment]
I now see that @bouweandela fixed this 9 days ago. I assume it is not published yet in the conda esmvalcore version ....

**Comment by bouweandela** [comment]
> I have no idea why this is needed for my configuration and apparently nobody else gets it ....

Because you're the first one using numpy 1.18:
> np.linspace parameter num must be an integer. Deprecated in NumPy 1.12. (gh-14620)
from https://numpy.org/devdocs/release/1.18.0-notes.html#expired-deprecations
