### ISSUE TITLE
regrid preprocessor regrids dataset though it has the same grid specification as target grid

### ISSUE THREAD

**Issue by BenMGeo** [ESMValGroup/ESMValCore#485]
The regrid preprocessor currently reacts "dumb" and regrids all datasets, even if a dataset is set as the targetgrid. This takes a serious amount of time, depending on your grid resolution, and has no visible benefits (at least for me).

Same if the horizontal grid is defined the same as the original dataset's.

**Comment by bouweandela** [comment]
I think this would be a good idea, we do have code that does this for vertical regridding, but not for horizontal regridding. See https://github.com/ESMValGroup/ESMValCore/blob/a9312a7d5be4fa3aac55c0b2ef089c6b4e1a61a9/esmvalcore/preprocessor/_regrid.py#L433-L450

**Comment by valeriupredoi** [comment]
this can be done via a quick cube equality check

**Comment by BenMGeo** [comment]
I went one step further to include the option that it is not only the original cube, but also if they are already on the same grid, e.g. a AxB target grid definition.

**Comment by bouweandela** [comment]
Thanks for reporting the problem @tomaslovato! I opened a new issue, because I think that the problem reported here has been solved and you're suggesting a further improvement to that solution, right?
