### ISSUE TITLE
MultiModel statistics data objects missing 'alias' key 

### ISSUE THREAD

**Issue by BenMGeo** [ESMValGroup/ESMValCore#486]
The MultiModel statistics data objects are missing the` "alias"` key. This cannot be set manually (?) and thus is missing if it is called for e.g. labeling. 

The specific dataset name in this case should be good to go, so either you need to pop the `"alias"` in the diagnostic and set the dataset name as the default option OR we just double the dataset name as alias after calculating the statistic.

What is preferred here? Should be a simple fix to include as `"alias"`.

**Comment by bouweandela** [comment]
Yes, you should be able to just add an '`alias'` key e.g. here https://github.com/ESMValGroup/ESMValCore/blob/a9312a7d5be4fa3aac55c0b2ef089c6b4e1a61a9/esmvalcore/_recipe.py#L609

**Comment by BenMGeo** [comment]
Automatic Alias added in #499.

Should we add an optional alias name or leave that to the diagnostic?

**Comment by BenMGeo** [comment]
Closed unless custom aliases should be included.
