### ISSUE TITLE
ESMValCore (and ESMValTool) Python/Jupyter Notebook API

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#498]
For interactive data exploration, it would be great if we could make it possible to use ESMValCore and the diagnostics included in ESMValTool accessible from a Jupyter notebook.

Here is an example of what such a notebook could look like:  [ESMValTool Notebook API example.ipynb](https://gist.github.com/bouweandela/c60fb23ad84bcc1569237d79608e9c02)

And here is a rough mapping from current functionality to the proposed Python API
- `Config` -  `esmvalcore._config.read_config_user_file`/`esmvalcore._config.CFG`
- `Variable` -  `esmvalcore.cmor.table.VariableInfo`
- `Dataset` -  `esmvalcore.preprocessor.PreprocessorFile`
- `Dataset.find_files` - `esmvalcore._data_finder.get_input_filelist`
- `Dataset.filename` - `esmvalcore._data_finder.get_output_file`
- `DatasetList` -  `esmvalcore.preprocessor.PreprocessingTask`
- `Diagnostic` -  `esmvalcore._task.DiagnosticTask`
- `compute` - `esmvalcore._task.run_tasks`
- `load` -  `esmvalcore._recipe.read_recipe_file`

@ESMValGroup/esmvaltool-coreteam Any comments?

**Comment by Peter9192** [comment]
This would also be nice:
`DatasetList.select(model='EC-EARTH', experiment='rcp85')`

**Comment by zklaus** [comment]
This looks very nice!

I wonder how strong the notebook link really is. It looks like a [dataclasses](https://docs.python.org/3/library/dataclasses.html) or [attrs](https://www.attrs.org) inspired interface that could be nice for us to have with or without notebooks, no?

For the notebook part, could you put a pointer on how this connects to any jupyter magic? Say inline dataset printing and plotting like iris cubes or similar?

**Comment by bouweandela** [comment]
Related to #30

**Comment by bouweandela** [comment]
@zklaus Indeed there is nothing specific to a Jupyter notebook in this proposal, you could just as well use the interface from a Python script, I changed the title accordingly. The reason I mentioned the Jupyter notebook is that people typically use this kind of interface from a notebook.

**Comment by stefsmeets** [comment]
@Peter9192 and I just had a long discussion about how to implement this in practice. We think that Dataset and DatasetList should be polymorphic, i.e. you can apply the same preprocessor functions to either and it will return an object of the same type (just like `iris.Cube` and `iris.Cubelist`).

We think it is important to do *one step at a time*. This differs from how it is done currently, where the current `PreprocessorTask` tries to apply all steps at once. This is where we get into issues having to define a future object, without knowing what this object will look like. So we think the mapping above makes more sense if `DatasetList` is defined as a collection of `Dataset`s.

The `Dataset` or `DatasetList` tracks ancestry, step settings and the future state. The `Dataset` represents what is returned when a step is applied to its ancestors. In this way, `Dataset` can be seen as a future object, and `.compute()` acts as the equivalent of `future.get()`.

```python
Dataset.step  # -> current step
Dataset.settings # -> list of step settings
Dataset.apply(step, *args, **kwargs)  # -> returns a new PreprocessorTask with the current one as ancestor
Dataset.ancestor  # -> return previous Dataset
Dataset.compute  # -> recursively call compute on ancestors, appling the specified step
```

We also believe it would be helpful if the apply function returns, rather than updating the object in place. This avoids hidden state, and gives the possibility to chain/fork tasks. This fits well within the idea of making a Jupyter API to allow/stimulate experimentation.

What should happen when `.apply` is called? Ideally, the step defines the preprocessor. We think it would be good if the preprocessor is defined as a class (can be very simple). So when apply is called, the preprocessor will check the settings (`_recipe_checks.py`) and ancestry. It should raise a `RecipeError` if the checks fail.

**Comment by Peter9192** [comment]
Just to elaborate/make it more concrete:

The `Dataset` object is *a future state that is obtained by applying its function to its inputs*. Mathematically:
```
a = 10
b = f(a)
c = g(b)
c = g(f(a)))
```

The esmvaltool equivalent in the envisioned API:
``` python
a = DataSet('pr', ...)
b = a.apply('global_mean')
c1 = b.apply('annual_statistics', operator='mean')
c2 = annual_statistics(global_mean(a), operator='mean')
c1 == c2

```

Example with multi-model (aggregation-type) functions:

```python
a = DataSet('pr', 'esm1_2', ...)
b = DataSet('pr', 'bcc_esm1', ...)

c = a.apply('global_mean')
d = b.apply('global_mean')
e1 = DatasetList(a, b).apply('multi_model_statistics')
e2 = multi_model_statistics([global_mean(a), global_mean(b)])
e1 == e2
```

**Comment by Peter9192** [comment]
> The Dataset does not know what the Preprocessor looks like, but only that it should be applied to its cubes.

Hey @stefsmeets this statement kept nagging at me. What does this mean for mutlimodel/aggregation functions, which convert *m* input products to *n* output products depending on the settings and e.g. the number of groups present in the DatasetList? That means that the initial settings check should update the DatasetList object to inform it about the number and nature of output products. Does that make sense?

**Comment by stefsmeets** [comment]
> 
> 
> > The Dataset does not know what the Preprocessor looks like, but only that it should be applied to its cubes.
> 
> Hey @stefsmeets this statement kept nagging at me. What does this mean for mutlimodel/aggregation functions, which convert _m_ input products to _n_ output products depending on the settings and e.g. the number of groups present in the DatasetList? That means that the initial settings check should update the DatasetList object to inform it about the number and nature of output products. Does that make sense?

Hi @Peter9192 , obviously the DatasetList produced by `apply` should produce a representable list. So it makes sense to purge the number of `Dataset`s as part of the initial settings check (or perhaps some other function).

**Comment by bouweandela** [comment]
> ```
> c1 = b.apply('annual_statistics', operator='mean')
> c2 = annual_statistics(global_mean(a), operator='mean')
> c1 == c2
> ```

It would probably be good to choose one of these options and not implement two ways to do the same thing.

**Comment by stefsmeets** [comment]
Hi all, we have been playing around with some ideas to give this API a bit more shape. We have been working with 2 scenarios that we came up with, one from a more user oriented point of view, and one from a more recipe-developer point-of-view. I put together two notebooks to make it a bit more tangible of what it coud look like.

Here is what we came up with:

**Scenario 1 - user POV:**
- https://gist.github.com/stefsmeets/059f86cae523679f1e955b25c1285f81
- List recipes
- Load ClimWIP recipe
- Show recipe
- Modify recipe
- Save modified recipe
- Run recipe
- Show output

**Scenario 2 - developer POV:** 
- https://gist.github.com/stefsmeets/96ce1df414f586c1c2f8a51a6e5269a2
- Reconstruct ClimWIP recipe from scratch using API calls
- Define datasets/datasetlists
- Apply preprocessor functions
- Call diagnostic script
- Save workflow as recipe

Note that this is absolutely not what it will or should be, but more of a mock-up of what it *could* look like. Your feedback is more than welcome 🍻

**Comment by Peter9192** [comment]
Here is another prototype notebook. This already works on the [DKRZ JupyterHub](https://jupyterhub.dkrz.de/hub/login?next=%2Fhub%2Fhome), but it currently uses calls to the underlying command line interface. We will try to replace those with actual API calls in upcoming PRs. 

https://gist.github.com/Peter9192/5916e8412a344e668f31b9b132bbe87f

**Comment by bouweandela** [comment]
Most of this has been implemented by now.

**Comment by bouweandela** [comment]
You can find a slightly outdated EGU short course here: https://github.com/ESMValGroup/EGU22-short-course

Apart from that, we have example notebooks using just ESMValCore here: https://docs.esmvaltool.org/projects/ESMValCore/en/latest/example-notebooks.html and documentation for running a recipe from a notebook here: https://docs.esmvaltool.org/projects/ESMValCore/en/latest/api/esmvalcore.experimental.html
