### ISSUE TITLE
Dataset peculiarity: UKESM1-0-LL historical daily missing last day 2014-12-31 due to using 360-day calendar

### ISSUE THREAD

**Issue by jhardenberg** [ESMValGroup/ESMValCore#512]
UKESM1-0-LL historical CMIP6 daily data are missing the last date and end on 2014-12-30
I tested zg, pr, tas, ua . Verified also on files downloaded freshly today from ESGF.

This is basically a data error, that is why I report it here for ESMValCore, but there is obviously nothing which can be done about it I guess, apart from reporting it upstream. 
Some diagnostics based on daily data do not like this at all. For example the miles_eof diagnostics checks if the end of the requested time range (20141231 in this case)  is still contained in the provided data and stops as a result. This opens two questions:
1) should diagnostics actually check this or should they be written such that  they allow one or two missing days if possible ? (that’s a question for the ESMValTool github)
2) Shouldn't ESMValCore test for problems like this? I am actually surprised that it doesn’t ….

- Data file has been changed by you in any way : NO
- Project: CMIP6
- Full dataset decription:
  - dataset: UKESM1-0-LL
  - experiment: historical
  - mip: day
  - grid: gn
  - variable used: zg, tas, pr, ua (presumably all are affected)
  - data version: 2019-07-03T14:09:16Z (downloaded today)
- Pointer to existing copy of data on ESGF node: http://esgf-data3.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/MOHC/UKESM1-0-LL/historical/r1i1p1f2/day/tas/gn/v20190627/tas_day_UKESM1-0-LL_historical_r1i1p1f2_gn_19500101-20141230.nc

**Comment by zklaus** [comment]
I'll take the data issue upstream.

Wrt your questions:
1. I think this is heavily diagnostic dependent. A line plot of global average surface temperature will be fine with one day missing. A reference daily climatology obviously not.

2. It depends on what "like that" means, I guess. Historically, ESMValTool is quite focused on monthly data, but with potential changes in the way that time specification is handled (cf #345) and increasingly more fine-grained diagnostics and preprocessors, this specific kind of problem may be checked for in the future.

**Comment by valeriupredoi** [comment]
I think this is an issue with the data in the broad sense, a day missing is, at the end of the day, a missing data point - first let me ask @matthew-mizielinski who is the coordinator of the UKESM data conversions and dissemination (CDDS) what he thinks :beer:

**Comment by valeriupredoi** [comment]
to follow: https://github.com/cedadev/jasmin-cdds/issues/37

**Comment by matthew-mizielinski** [comment]
@jhardenburg, @valeriupredoi 

While it may be unusual within CMIP6, this is not an error in the data. 

The UK models (UKESM1 & HadGEM3) are all configured to run with a 360 day calendar (i.e. 30 days in every month, including February!). This is indicated by the calendar attribute on the time variable in each and every file;
```
netcdf tas_day_UKESM1-0-LL_historical_r1i1p1f2_gn_18500101-19491230 {
dimensions:
        time = UNLIMITED ; // (36000 currently)
        bnds = 2 ;
        lat = 144 ;
        lon = 192 ;
variables:
        double time(time) ;
                time:bounds = "time_bnds" ;
                time:units = "days since 1850-01-01" ;
                time:calendar = "360_day" ;   <------------------ calendar attribute
                time:axis = "T" ;
                time:long_name = "time" ;
                time:standard_name = "time" ;
...
```

There may be certain MIPs that choose to run with a gregorian (DCPP, PAMIP) or 365 day (OMIP), but we haven't attempted to process & publish any data which doesn't use 360 days yet.

As such I'd suggest that this is something that ESMVal will need to adapt to.

**Comment by valeriupredoi** [comment]
perfect, cheers @matthew-mizielinski - I was suspecting it's the 360-cal but didn't want to let the bird out the cage :grinning: 

As Matt says, we should probably get a workaround this then :beer:

**Comment by jhardenberg** [comment]
All clear, thank you very much for the clarification @matthew-mizielinski ! Indeed we will need to adapt our diagnostics to be able deal with this correctly. Thank you.

**Comment by valeriupredoi** [comment]
we should probably add a note on this somewhere somehow, otherwise somebody else will open the same issue again and we'll scratch our heads "hang on, didn't we see this before?"

**Comment by zklaus** [comment]
I disagree. This was an oversight, but all the information is there and correct. We'll just have to deal with these things from time to time.

**Comment by jhardenberg** [comment]
Actually I think that I will open an issue on the ESMValTool github (and develop a PR) to make sure that the diagnostic that was failing for me (miles_eof) works correctly with this dataset .....

**Comment by valeriupredoi** [comment]
> I disagree. This was an oversight, but all the information is there and correct. We'll just have to deal with these things from time to time.

diagnostic developers will not know this first hand and will scratch their heads, in process most probably opening an Issue. I think it's a good idea to note it somewhere - the question is where? Maybe we can create a list of datasets with peculiarities and put it in the documentation? @mattiarighi @bouweandela what say yous? :beer:

**Comment by bouweandela** [comment]
I think the ESMValTool documentation is not the place to document CMIP6 data. I believe this is what ES-DOC is for?

**Comment by valeriupredoi** [comment]
> I think the ESMValTool documentation is not the place to document CMIP6 data. I believe this is what ES-DOC is for?

no of course not, but ES-DOC is huge :grin: Also, if we start adding notes on CMIP6 data in our documentation that may blow up out of proportion and nobody will want to maintain it. So OK, let's just drop itand the next diag developer who's gunna bite the UKESM1 bullet will may want to do a search in our closed issues db
