### ISSUE TITLE
CMOR checker does not check CMIP6 generic levels

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#516]
The CMOR check does not check generic levels, see e.g.
https://github.com/ESMValGroup/ESMValCore/blob/c460ceafde91014df67a67d7f7de8a0867a339ac/esmvalcore/cmor/check.py#L333

However, generic level definitions are available in the CMIP6_coordinates.json file, e.g. (notice line 500)
https://github.com/ESMValGroup/ESMValCore/blob/c460ceafde91014df67a67d7f7de8a0867a339ac/esmvalcore/cmor/tables/cmip6/Tables/CMIP6_coordinate.json#L479-L501

Therefore it would be good if the checker could be improved so it checks these coordinates if a definition is available.

**Comment by sloosvel** [comment]
There are several coordinates sharing the same `generic_level_name` .  So I am not sure how they could be distinguished when loading the table information for each variable in table.py .

Taking `thetao` as an example, the information that is given in the tables regarding its dimensions is:

`"dimensions": "longitude latitude olevel time"`

And in CMIP6_coordinates there are five coordinates that have the generic_level_name set to olevel (depth_coord, ocean_double_sigma, ocean_s, ocean_sigma, ocean_sigma_z). How could you know which one to load?

**Comment by jvegasbsc** [comment]
> How could you know which one to load?

We can not, we must check against the five and raise issues if none of them comply
