### ISSUE TITLE
Dataset problem: ACCESS-CM2 is stored under CSIRO-ARCCSS, not CSIRO-ARCCSS-BoM

### ISSUE THREAD

**Issue by ledm** [ESMValGroup/ESMValCore#517]
The CMIP6 model dataset for the model `ACCESS-CM2` is stored on jasmin under the institude ID:
`CSIRO-ARCCSS`, but recorded as ` CSIRO-ARCCSS-BoM` in ESMValCore in `CMIP6_CV.json`.

ie the paths to this model are:
```
/badc/cmip6/data/CMIP6/CMIP/CSIRO-ARCCSS
```

However, in `esmvalcore/cmor/tables/cmip6/Tables/CMIP6_CV.json`, we record the institude ID for this model to be :
```
        "source_id":{
            "ACCESS-CM2":{
                "activity_participation":[
                    "CMIP",
                    "FAFMIP",
                    "OMIP",
                    "RFMIP",
                    "ScenarioMIP"
                ],
                "cohort":[
                    "Registered"
                ],
                "institution_id":[
                    "CSIRO-ARCCSS-BoM"
                ],
                "source_id":"ACCESS-CM2",
                "source":"ACCESS-CM2 (2018): \naerosol: UKCA-GLOMAP-mode\natmos: MetUM-HadGEM3-GA7.1 (N96; 192 x 144 longitude/latitude; 85 levels; top level 85 km)\natmosChem: none\nland: CABLE2.3.5\nlandIce: none\nocean: ACCESS-OM2 (GFDL-MOM5, tripolar primarily 1deg; 360 x 300 longitude/latitude; 50 levels; top grid cell 0-10 m)\nocnBgchem: none\nseaIce: CICE5.1 (same grid as ocean)"
            },
```
So ESMValTool is looking for this dataset in the non-existant folder:
```
/badc/cmip6/data/CMIP6/CMIP/CSIRO-ARCCSS-BoM/ACCESS-CM2/
``

**Comment by zklaus** [comment]
This was changed 2019-11-15 in the tables. The original change in the CV was on 2019-10-22 and released as 6.2.39.2.

**Comment by valeriupredoi** [comment]
we can probably fix this with a temporary mapping in `config-developer.yml` but really, it's a bad case of old ESGF data structure - I will email @agstephens and Ruth Petrie about it

**Comment by valeriupredoi** [comment]
OK email sent to Ag and Ruth (and you two troublemakers too) :beer:

**Comment by valeriupredoi** [comment]
> OK email sent to Ag and Ruth (and you two troublemakers too) beer

nevermind, I'm being silly - yes, the (new) table is correct and in line with the Jasmin path :beer:

**Comment by bouweandela** [comment]
As a workaround for this issue (until we've updated the CMOR tables again) you can specify the correct institute in the dataset definition in the recipe.

**Comment by bouweandela** [comment]
We are now using the latest release of the CMOR tables (6.9.33),
