### ISSUE TITLE
Incorrect error messages in volume preprocessor function extract_transect

### ISSUE THREAD

**Issue by BrendanMD** [ESMValGroup/ESMValCore#519]
**Describe the bug**
The three Value Error messages in function "extract_transect" (https://github.com/ESMValGroup/ESMValCore/blob/master/esmvalcore/preprocessor/_volume.py) incorrectly refer to the function as "extract_slice" . Lines 384, 389, 394.
**Please attach**

**Comment by valeriupredoi** [comment]
cheers, fixed in https://github.com/ESMValGroup/ESMValCore/pull/526 :beer:
