### ISSUE TITLE
Cubes lose auxiliary coordinates during regridding

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#545]
**Describe the bug**
During our preprocessing step `regrid`, any cube with an `AuxCoord` that includes a horizontal dimension (like e.g. `surface_air_pressure`) loses this. This is caused by [`iris.cube.Cube.regrid`](https://scitools.org.uk/iris/docs/latest/iris/iris/cube.html#iris.cube.Cube.regrid) and probably an intended behavior (@bjlittle is this correct? If not then I will open an issue on the iris GitHub).

I think that at least for coordinates without bounds, the regridding should be possible. I will provide a PR for this. I encountered this problem while dealing with datasets that have a hybrid pressure coordinate and thus a `surface_air_pressure` coordinate.

**Comment by valeriupredoi** [comment]
so given that #548 was closed off, do we want to close the issue too? @schlunma
