### ISSUE TITLE
"_tkinter.TclError: couldn't connect to display" and MPLBACKEND="Agg" missing in re-run command

### ISSUE THREAD

**Issue by katjaweigel** [ESMValGroup/ESMValCore#549]
**Describe the bug**
I'm actually not sure if this is a ESMValCore or an ESMValTool issue: I switched to the latest version of ESMValCore and ESMValTool yesterday and since then I get a error related to the x-server, if I try to run a diagnostic in the queue on Mistral in the log file of the diagnostic:
"self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:40.0""
at the same time I saw, that "MPLBACKEND="Agg"" is missing in the "re-run" command in main_log.txt 
Also including:
`
import matplotlib 
`
`matplotlib.use('Agg')`
in the diagnostic helped to run it in the queue again, but I thought this was not the way we should solve it?
I don't think it is related to the recipe/diagnostic I used, I'll try another soon. If I do the re-run including  "MPLBACKEND="Agg"" it works (possibly also without, I have to try, on mistralpp it has access to the x-server, but not in the queue).
I don't really know where to start searching for the reason of this issue?
[main_log_debug.txt](https://github.com/ESMValGroup/ESMValTool/files/4286401/main_log_debug.txt)

**Please attach**
  - The recipe that you are trying to run, you can find a copy in the `run` directory in the output directory
Github refuses to upload *.yml, see:
https://github.com/ESMValGroup/ESMValTool/tree/linatcc_for_gmdpart4/esmvaltool/recipes/recipe_li17natcc.yml
  - The `main_log_debug.txt` file, this can also be found in the `run` directory in the output directory

**Comment by bouweandela** [comment]
Thank you for reporting. I introduced the bug in #528. It should be fixed by #550.
