### ISSUE TITLE
multi model statistics -- more statistics

### ISSUE THREAD

**Issue by mwjury** [ESMValGroup/ESMValCore#563]
@jvegasbsc How about adding standard deviation, min and max to the pool of available multi model statistics? It would be rather easy to implement. 
It would be nice to also have np.percentile in the mix, though this would require reforming the masked values to nans (numpy.nanpercentile), so idk if that's userful.

**Comment by jvegasbsc** [comment]
Looks interesting, indeed. I will look into it

**Comment by valeriupredoi** [comment]
> It would be nice to also have np.percentile in the mix, though this would require reforming the masked values to nans (numpy.nanpercentile), so idk if that's userful.

an inplace replacement can be done and then a reversal back to 1e20's easily :beer:

**Comment by Peter9192** [comment]
> an inplace replacement can be done and then a reversal back to 1e20's easily

I have a use case for the percentiles function. Is it as simple as this? Can I reopen this issue?
