### ISSUE TITLE
Better integration between synda and data repositories

### ISSUE THREAD

**Issue by jvegasbsc** [ESMValGroup/ESMValCore#57]
There will be two improvements that will make synda downloads really useful:

1.(Optionally) Put synda downloads on the data repository. 

2. Be able to complete the data in the repository with synda downloads. For example, I downloaded 5 years of data for testing and then tried to run a test for 50 years. It will fail because of the missing data even if I put the synda download option

It is not urgent nor I have time for that but wanted to keep this ideas documented

**Comment by bouweandela** [comment]
We're doing synda in favor of esgf-pyclient in #1217
