### ISSUE TITLE
Zonal preprocessor return type float64

### ISSUE THREAD

**Issue by mattiarighi** [ESMValGroup/ESMValCore#577]
**Describe the bug**
The zonal preprocessor returns a cube of type `float64`, instead of `float32` as for other preprocessors.
This is an issue for the NCL diagnostics, which are designed to work with variable of `float32` type (as per CMOR standard).

Hopefully it is easy to fix this.

**Comment by valeriupredoi** [comment]
which zonal - all? looking at it now :beer:

**Comment by mattiarighi** [comment]
For example:
```
zonal_statistics:
  operator: mean
```
would result in a NetCDF file in `preproc` with the variable type `double`, why it should be float.
I kind of rembemer a similar issue with multimodel long time ago.

**Comment by valeriupredoi** [comment]
right! yeah, that was done easily by accessing the data member, now we're all lazy, lemme see if I can find a lazy fix

**Comment by valeriupredoi** [comment]
@schlunma RE here: assigning a different dtype to core data works but that doesn't preserve it to the actual data:

```python
import iris
import numpy as np

c = iris.load_cube("t2.nc")
print(c.core_data().dtype)
c.core_data = c.core_data().astype(np.float16, casting='same_kind')
print(c.has_lazy_data())
print(c.core_data.dtype)
print(c.data.dtype)
iris.save(c, "t3.nc")
d = iris.load_cube("t3.nc")
print(d.data.dtype)
```

@bjlittle do you know how to change the dtype of a cube data member without accessing it and un-lazying the data? :beer:

**Comment by valeriupredoi** [comment]
meh decided to as the iris folk directly: https://github.com/SciTools/iris/issues/3691

**Comment by schlunma** [comment]
Can you try with

```python
c.data = c.core_data().astype(np.float16, casting='same_kind')
```

instead of

```python
c.core_data = c.core_data().astype(np.float16, casting='same_kind')
```

For me that works! Your code only overwrites the function `core_data` with that array.

**Comment by valeriupredoi** [comment]
bingo! that works, good one @schlunma :beer:

**Comment by valeriupredoi** [comment]
quite interesting because it keeps the data lazy even though you are accessing the data member to assign it the new dtype, hmmm

**Comment by schlunma** [comment]
It does not access the `data` member (since we are using `core_data()` to read the data), but only assigns a new dask array to the `data` member.

**Comment by valeriupredoi** [comment]
right coz left hand side is just a pointer to a new variable :man_facepalming:
