### ISSUE TITLE
Can't read models with hybrid sigma pressure coordinate

### ISSUE THREAD

**Issue by LisaBock** [ESMValGroup/ESMValCore#59]
I need to use models with hybrid sigma pressure coordinate:
e.g.: Model: CMIP5 MPI-ESM-LR historical, Variable: cli

Who could extend the preprocessor to recognize these files and convert them to pressure coordinate?

**Comment by RCHG** [comment]
Hi all,

By reading this it seems that the process of climate variables with hybrid sigma pressure vertical coordinates is not implemented yet. I have to process several models with these vertical pressure levels. I would like to know if the idea is to implement a re-grid the dataset to pressure levels, or instead create diagnostics that are able to process both kind of datasets.

Thanks!

**Comment by bouweandela** [comment]
@schlunma Did your recent pull requests solve this issue?

**Comment by schlunma** [comment]
I think so. @LisaBock what do you think? Can you check if the files can be read correctly with the latest version of ESMValCore?

**Comment by LisaBock** [comment]
Yes, it tested the CMIP5 model I mentioned in the beginning of this issue (MPI-ESM-LR historical, Variable: cli) and several CMIP6 models. The ESMValTool could read them all. Thanks @schlunma!
