### ISSUE TITLE
Dataset problem: Fix for missing typesi in GFDL-ESM4 siconc

### ISSUE THREAD

**Issue by npgillett** [ESMValGroup/ESMValCore#590]
GFDL-ESM4 siconc files such as this:
`CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/SImon/siconc/gn/v20190726/siconc_SImon_GFDL-ESM4_historical_r1i1p1f1_gn_185001-194912.nc`
give the following error when running fix_metadata in esmvalcore:

```
  File "/home/rng/miniconda3/envs/esmvaltool2/lib/python3.7/site-packages/esmvalcore/cmor/check.py", line 124, in report_errors
    raise CMORCheckError(msg)
esmvalcore.cmor.check.CMORCheckError: There were errors in variable siconc:
typesi: does not exist
in cube:
```
Here is the log file:
[main_log_debug.txt](https://github.com/ESMValGroup/ESMValCore/files/4394556/main_log_debug.txt)

Here is a fix for this:
[gfdl_esm4.py.txt](https://github.com/ESMValGroup/ESMValCore/files/4394544/gfdl_esm4.py.txt)

**Comment by remi-kazeroni** [comment]
I close this issue since this dataset fix is part of #1104.
