### ISSUE TITLE
Dataset problem: Fix for error with lat/lon bounds when concatenating NorESM2-LM siconc

### ISSUE THREAD

**Issue by npgillett** [ESMValGroup/ESMValCore#591]
When trying to concatenate NorESM2-LM siconc in historical and ssp245 I got the following error:

```
  File "/home/rng/miniconda3/envs/esmvaltool2/lib/python3.7/site-packages/iris/cube.py", line 512, in concatenate_cube
    raise iris.exceptions.ConcatenateError(msgs)
iris.exceptions.ConcatenateError: failed to concatenate into a single cube.
  An unexpected problem prevented concatenation.
  Expected only a single cube, found 2.
```
Similar to issue #576 this turned out to be due to small differences in lat/lon bounds. Rounding the bounds to 4 d.p. fixed the problem. Proposed fix is attached below.
[main_log_debug.txt](https://github.com/ESMValGroup/ESMValCore/files/4394767/main_log_debug.txt)
[noresm2_lm.py.txt](https://github.com/ESMValGroup/ESMValCore/files/4394769/noresm2_lm.py.txt)

**Comment by valeriupredoi** [comment]
fixed in #629 :beer:
