### ISSUE TITLE
CMIP6 data input structure other than "[default]/BADC/DKRZ/ETHZ/" 

### ISSUE THREAD

**Issue by ChunchengGuo** [ESMValGroup/ESMValCore#601]
Dear ESMValTool community,

The CMIP6 data in our local server has a structure of e.g. /exp/dataset/ensemble/filename.nc, which is not one of the "[default]/BADC/DKRZ/ETHZ/" structures as provided by the esmvaltool. I guess one needs to insert an extra entry (with our local structure info) into ESMValCore/esmvalcore/config-developer.yml. 

If I understand it correctly, one workaround could be, instead of using conda install, one could try to install ESMValCore from source, e.g. 1) git clone; 2) customise ESMValCore/esmvalcore/config-developer.yml (adding one extra entry); 3) pip install .

This would require us to install conda by ourselves at the home directory of our local server; this is not ideal for us, as conda is installed and managed by our server support staff, and normal users don't have writing access to. We could ask our support staff, but before that, does anyone have any clue or experience on how to proceed with customising the config-developer.yml file, or any other best practice in handling this issue? 

Many thanks in advance,
Chuncheng

**Comment by bettina-gier** [comment]
I'm not sure why this would require you to install conda by yourself. I'm currently using the pre-installed conda on our server without problems, using both the ESMValTool and ESMValCore repositories cloned from github.
I believe the way you suggested with customising config-developer.yml is the right one in this case! A possible other option off the top of my head if you cannot do this, is to make a symbolic link structure instead. This structure could resemble any one of the implemented data structures, but links to the files in your own data.

**Comment by valeriupredoi** [comment]
> If I understand it correctly, one workaround could be, instead of using conda install, one could try to install ESMValCore from source, e.g. 1) git clone; 2) customise ESMValCore/esmvalcore/config-developer.yml (adding one extra entry); 3) pip install .

That is correct and also @bettina-gier is correct. Since you are doing the `pip install -e .` that means you are installing the package locally, in the same source repository. However, the `egg` needs to be written where `pip` is installed eg in the lib dir `lib/python3.7/site-packages/ESMValCore.egg-link` and if you are using `pip` from the anaconda environment set up on the cluster that will not work; so you will have to have your own `pip` and write to a python `site-packages` directory set up by you eg `$USER/local/lib/python3.7/site-packages` - that applies to the dependencies that `pip` may need to install during the installation process, dependencies that may not be in the main conda environment (due to say, the env is a bit obsolete). Once you've done that make sure you attach the path to your current `$PATH` variable eg `export PATH=/home/$USER/local/lib/python3.7/site-packages:$PATH`

The reason we can not add the specific cluster to `config-developer` is that there are lot of HPC's with different slightly different DRS's, but - is the node you are talking about an official ESGF node? Coz if it is, we can probably add it :beer:

**Comment by valeriupredoi** [comment]
another elegant option would be to allow the user to customize their DRS in `config-user`, what do you think @bouweandela ?

**Comment by schlunma** [comment]
Isn't it possible to specify a `config-developer.yml` file in the `config-user.yml` file?

https://github.com/ESMValGroup/ESMValTool/blob/924c9d376c9746ceb1b85e17eb768ca7bf5df646/config-user-example.yml#L56

**Comment by bettina-gier** [comment]
> > If I understand it correctly, one workaround could be, instead of using conda install, one could try to install ESMValCore from source, e.g. 1) git clone; 2) customise ESMValCore/esmvalcore/config-developer.yml (adding one extra entry); 3) pip install .
> 
> That is correct and also @bettina-gier is correct. Since you are doing the `pip install -e .` that means you are installing the package locally, in the same source repository. However, the `egg` needs to be written where `pip` is installed eg in the lib dir `lib/python3.7/site-packages/ESMValCore.egg-link` and if you are using `pip` from the anaconda environment set up on the cluster that will not work; so you will have to have your own `pip` and write to a python `site-packages` directory set up by you eg `$USER/local/lib/python3.7/site-packages` - that applies to the dependencies that `pip` may need to install during the installation process, dependencies that may not be in the main conda environment (due to say, the env is a bit obsolete). Once you've done that make sure you attach the path to your current `$PATH` variable eg `export PATH=/home/$USER/local/lib/python3.7/site-packages:$PATH`
> 

Hmm the way conda is set up on Mistral at least is that even if you are using the pre-installed anaconda, you can make your own environments, which are then saved to your home directories. pip can install inside these environments no problem. As I said, when I first set up my own esmvaltool I was too lazy to install my own anaconda and am still using the pre-installed one. ESMValTool is recommended to be used within a custom environment anyways so I don't see a problem here?

**Comment by valeriupredoi** [comment]
@schlunma yes that is correct! I just checked `_config.py` and that option is indeed fully implemented - well done whoever put it!
@bettina-gier yes you are right, you can install conda environments separately in user's home dirs, but am not 100% sure if that doesn't need a modification of the conda configuration from the IT guys on @ChunchengGuo 's side - better use the developer config-developer set in the user conf, sorted nicely :grin:

**Comment by ChunchengGuo** [comment]
Thanks all for the great tips! 

I've tried to specify a config-developer.yml file in the config-user.yml file, and it worked nicely :) 
(that line for specifying a config-developer.yml file is somehow commented out by default so I've totally overlooked it)
