### ISSUE TITLE
Apply cmor checks (and fixes) to fx-files

### ISSUE THREAD

**Issue by mattiarighi** [ESMValGroup/ESMValCore#61]
Going through the fx data in CMIP5, I've noticed that there are several issues with the mask variables `sftlf` and `sftof` which needs to be fixed (wrong units, wrong coordinates, wrong fillvalues, etc.), but this is currently not implemented, although some fixes are available (see for example [here](https://github.com/ESMValGroup/ESMValTool/blob/fc376aded0d2092b05e3d1f74132592f0a1dc2a6/esmvaltool/cmor/_fixes/CMIP5/EC_EARTH.py#L29)). 

This affects both, the use of fx variables in the diagnostics (via `fx-files` key in the variable dict) and the use of fx variables for the masking (via `mask_landsea` key in the preprocessor dict).

In principle, whenever a fx-variable is needed, it should be read, cmor-checked, (fixed) and saved in the `work_dir` / `preproc_dir`, as for any other variable. The corresponding path should be then made available to the diagnostics if the `fx-files` key is specified in the recipe (as it happens now with the original input fx-file).

**Comment by zklaus** [comment]
So @valeriupredoi... does it work now? Can we build fixes for fx files?

**Comment by valeriupredoi** [comment]
it do, if you ask for an fx variable just like any other variable in #170

**Comment by zklaus** [comment]
I need it for a derived variable (#192), namely the fx variable volcello. Can I do that somehow?

**Comment by valeriupredoi** [comment]
fixed by #170 and #230
