### ISSUE TITLE
Empty cubes after volume_statistics for certain datasets

### ISSUE THREAD

**Issue by sloosvel** [ESMValGroup/ESMValCore#611]
**Describe the bug**
CMIP6 EC-Earth ocean 3D data has the whole bottom depth layer set to masked values. Both the variables and the volcello. The volume_statistics preproc computes the weighted mean per layer just fine, and for the bottom layer the results are masked as well. But when it comes to computing the weighted mean over the water volume, the presence of masked values sets the results to NaNs and the data comes out of the preprocessing empty:

`result.append(np.average(column, weights=depth_volume))`

It looks like the function `np.average` is not handling well the presence of layers with only masked values. Would it be correct check and remove this sort of layers before calling `np.average` ?

**Please attach**
I'm working with EC-Earth local data and can't seem to find Ecearth data with volcello on /badc, sorry.

**Comment by valeriupredoi** [comment]
this is more of a scientific question (well, statistical) - @ledm I believe is the person to ask - I would definitely replace it with [numpy masked mean](https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.ma.mean.html) though :beer:

**Comment by ledm** [comment]
Replacing
```
result.append(np.average(column, weights=depth_volume))
``` 
with 
```
result.append(np.ma.average(column, weights=depth_volume))
``` 
should fix this ([Numpy.ma.average](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ma.average.html) ). I don't believe that there's an option to add weights to [numpy masked mean](https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.ma.mean.html).

Although there might be another error if the volume includes masked values. I don't know whether numpy.ma.average is able to receive a masked array in the weights argument. Worth checking, it's not explicitly mentioned in the documentation.

**Comment by valeriupredoi** [comment]
will you PR that @ledm ? :beer:

**Comment by valeriupredoi** [comment]
#618 guys :beer:
