### ISSUE TITLE
updated derivation of ctotal for CMIP6 models

### ISSUE THREAD

**Issue by koir-su** [ESMValGroup/ESMValCore#617]
**Describe the bug**
The ctotal is derived as the sum of cVeg and cSoil. But, there are differences in definition of these variables in CMIP5 and CMIP6. In order for recipe_carvalhais2014nat.yml to work for CMIP6 models, the derivation needs to be updated.

**Comment by valeriupredoi** [comment]
@jvegasbsc I can do this, but if you have some spare time and decide to do it, I will not be too angry, not a bit :grin:
