### ISSUE TITLE
Dataset problem: Fixes for CMIP6 monthly model output

### ISSUE THREAD

**Issue by npgillett** [ESMValGroup/ESMValCore#628]
This issue accompanies a pull request for several CMIP6 dataset fixes. It adds fixes for the following:
Fixes issue with different `bounds_dtype` and lat and lon bounds in CESM2 and NorESM2-LM:
https://github.com/ESMValGroup/ESMValCore/issues/576
Fixes missing latitude and longitude bounds in `tos` and `siconc` in FGOALS-g3:
https://github.com/ESMValGroup/ESMValCore/issues/614
Fixes high latitude and longitude values causing code to hang in FGOALS-g3:
https://github.com/ESMValGroup/ESMValCore/issues/627
Applies this fix developed for` tos`  to `siconc` in BCC-CSM2-MR:
https://github.com/ESMValGroup/ESMValCore/pull/560
Adds missing `typesi` for `siconc` in GFDL-ESM4 and CESM2:
https://github.com/ESMValGroup/ESMValCore/issues/590
https://github.com/ESMValGroup/ESMValCore/issues/576

I am submitting a pull request for these fixes so I can publish esmvaltool recipes which run with these data, and so others don't get stuck on these files.. I'm relatively new to python and esmvalcore development, so please go ahead and suggest changes to the code as needed.
Thanks!

**Comment by bouweandela** [comment]
@valeriupredoi @zklaus Were these issues also reported to the data producers?

**Comment by valeriupredoi** [comment]
@zklaus is da man wrt that, I believe yes, and we got replies from very few modelers :beer:

**Comment by bouweandela** [comment]
Let's close the issue then, at least you tried! :partying_face:
