### ISSUE TITLE
Make some functions in multimodel public

### ISSUE THREAD

**Issue by sloosvel** [ESMValGroup/ESMValCore#630]
The multimodel_statistics function can't be called inside diagnostic scripts because it does not accept cubes, but rather products.

However functions _get_overlap, _assemble_overlap_data and _assemble_full_data do accept cubes and they are what computes the statistics anyway. Could they be made public and add in the documentation how to call them? Maybe it would be better to generalise the multimodel_statistics preproc to accept both products and cubes, but it would probably be more time consuming to implement.

**Comment by valeriupredoi** [comment]
good initiative, I fully support it! we do need to make the users aware of them being high-memory functions though, if they don't break the computer during the preprocessor/multimodel step, they may break it while using them in the diagnostic :beer:

**Comment by bouweandela** [comment]
> Maybe it would be better to generalise the multimodel_statistics preproc to accept both products and cubes, but it would probably be more time consuming to implement.

This would probably be the most user friendly and not too difficult to implement, maybe just rename the first argument from `products` to `products_or_cubes` and make some changes so the function is able to deal with both types of input (but not a mix).
