### ISSUE TITLE
Dealing with startdates in filenames

### ISSUE THREAD

**Issue by sloosvel** [ESMValGroup/ESMValCore#632]
**Is your feature request related to a problem? Please describe.**
Some experiments (DCPP, etc) contain startdates in the filenames and this is currently not supported.

**Would you be able to help out?**
Started working in branch dev_dccp_startdates, in which startdates are dealt with the same way as ensemble members by getting expanded. 
The requirement for start_year and end_year is relaxed if the startdate is provided, because in this way the number of chunks per startdate can be flexible. I am not sure if there would be a way to determine how many chunks per startdate will there with parameters from the metadata?

**Comment by bouweandela** [comment]
Could you give some examples of these filenames?

**Comment by sloosvel** [comment]
Yes it's experiments like dcppA-hindcast:

`tas_Amon_EC-Earth3_dcppA-hindcast_s2017-r1i1p1f1_gr_201711-201810.nc`
`tas_Amon_EC-Earth3_dcppA-hindcast_s2017-r1i1p1f1_gr_201811-201910.nc`
`tas_Amon_EC-Earth3_dcppA-hindcast_s2017-r1i1p1f1_gr_201911-202010.nc`
`tas_Amon_EC-Earth3_dcppA-hindcast_s2017-r1i1p1f1_gr_202011-202110.nc`
`tas_Amon_EC-Earth3_dcppA-hindcast_s2017-r1i1p1f1_gr_202111-202210.nc`
`tas_Amon_EC-Earth3_dcppA-hindcast_s2017-r1i1p1f1_gr_202211-202310.nc`
`tas_Amon_EC-Earth3_dcppA-hindcast_s2017-r1i1p1f1_gr_202311-202410.nc`
`tas_Amon_EC-Earth3_dcppA-hindcast_s2017-r1i1p1f1_gr_202411-202510.nc`
`tas_Amon_EC-Earth3_dcppA-hindcast_s2017-r1i1p1f1_gr_202511-202610.nc`
`tas_Amon_EC-Earth3_dcppA-hindcast_s2017-r1i1p1f1_gr_202611-202710.nc`
`tas_Amon_EC-Earth3_dcppA-hindcast_s2017-r1i1p1f1_gr_202711-202810.nc`
`tas_Amon_EC-Earth3_dcppA-hindcast_s2018-r1i1p1f1_gr_201811-201910.nc`
`tas_Amon_EC-Earth3_dcppA-hindcast_s2018-r1i1p1f1_gr_201911-202010.nc`
`tas_Amon_EC-Earth3_dcppA-hindcast_s2018-r1i1p1f1_gr_202011-202110.nc`
`tas_Amon_EC-Earth3_dcppA-hindcast_s2018-r1i1p1f1_gr_202111-202210.nc`
`tas_Amon_EC-Earth3_dcppA-hindcast_s2018-r1i1p1f1_gr_202211-202310.nc`
`tas_Amon_EC-Earth3_dcppA-hindcast_s2018-r1i1p1f1_gr_202311-202410.nc`
`tas_Amon_EC-Earth3_dcppA-hindcast_s2018-r1i1p1f1_gr_202411-202510.nc`
`tas_Amon_EC-Earth3_dcppA-hindcast_s2018-r1i1p1f1_gr_202511-202610.nc`
`tas_Amon_EC-Earth3_dcppA-hindcast_s2018-r1i1p1f1_gr_202611-202710.nc`
`tas_Amon_EC-Earth3_dcppA-hindcast_s2018-r1i1p1f1_gr_202711-202810.nc`
`tas_Amon_EC-Earth3_dcppA-hindcast_s2018-r1i1p1f1_gr_202811-202910.nc`

Or in badc under: `/badc/cmip6/data/CMIP6/DCPP/MOHC/HadGEM3-GC31-MM/dcppA-hindcast/`

`

**Comment by bouweandela** [comment]
It looks like the start date is part of the ensemble name, e.g. `s2017-r1i1p1f1`, right? It does not look like it is a separate facet. Why doesn't this work with the current functionality?

**Comment by sloosvel** [comment]
Because for example, startdate s2017 has files going from years 2017 to 2028 but s2018 has files going from years 2018 to 2029. So you cannot call the experiment in the recipe once setting the ensemble as `s(2017:2018)-r(1:3)i1p1f1` with a common start_year and end_year  without getting a `No input available for years ...` error.


With the current functionality, the recipe would need to call the experiment as many times as there are startdates, to match the start_year and end_year correctly. And if a single experiment has 50 startdates and then you want to work with multiple datasets, the recipe would become endless.
