### ISSUE TITLE
Make preprocessor function volume_statistics lazy

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#647]
Related to #51

**Comment by valeriupredoi** [comment]
I'll fix this once #618 gets merged :beer:

**Comment by bouweandela** [comment]
From looking at the code, this preprocessor seems lazy when the iris statistic is lazy and the required cell measures are available. Lazy area weights are needed to make this completely lazy https://github.com/SciTools/iris/issues/5611.
