### ISSUE TITLE
Use sys.executable to find python interpreter to run diagnostic

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#653]
At the moment, we use the command `python` to run a diagnostic script. It would be more reliable to try to use the same interpreter (using ` sys.executable`) as the `esmvaltool` command. This would then also work even when the conda environment in which esmvaltool is installed is not activated.

**Comment by valeriupredoi** [comment]
this is dangerous because modules could fail to import; if the `$PATH` is not set correctly that'll happen, it needs to point to `anaconda/bin` (which does when the env is not activated) and `anaconda/envs/esmvaltool/bin` (which doesn't when the env is not activated)

**Comment by bouweandela** [comment]
Would you be able to explain that with an example?
