### ISSUE TITLE
Add tests for recipe.py and task.py

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#67]
Once most functionality is supported.

**Comment by valeriupredoi** [comment]
`_recipe.py` is currently 90+% tested, `_task.py` is pretty bad at 45% - I can go ahead and write some more tests for task

**Comment by bouweandela** [comment]
Coverage is [84% for _task.py](https://app.codacy.com/manual/ESMValGroup/ESMValCore/file/42508058162/coverage?bid=13044842&fileBranchId=13044842) too.

I think the issue can be closed.
