### ISSUE TITLE
Make preprocessor dictionary available to the diagnostic script

### ISSUE THREAD

**Issue by mattiarighi** [ESMValGroup/ESMValCore#70]
The preprocessor settings (`levels`, `target_grid`, etc.) used by a given diagnostic shall be made available to the diagnostic script itself via the temporary file (`ncl.interface` for NCL diagnostics).

**Comment by valeriupredoi** [comment]
done in #174 - it adds the preprocessor profile in `metadata.yml`

**Comment by mattiarighi** [comment]
Closing since not required anymore.
