### ISSUE TITLE
Global total air sea flux of CO2 removed

### ISSUE THREAD

**Issue by ledm** [ESMValGroup/ESMValCore#708]
The derived variable  Global total air sera flux of CO2,  `gtfgco2`, is a CRUCIAL measurement of the earth system, and was mistakenly removed in PR #418 during the Christmas break. The changes in pr #418 were pushed without testing their actual functionality. 

This functionality is now missing and can't be reproduced using the previously suggested `area_statistics` and `convert_units` preprocessors. This is because `area_statistics` miscalculates the units, and iris's `convert_units` can't be used to change units with different dimensions. 

This field is also included in the second v2 paper, so this problem really needs to be fixed. 

**Describe the bug**
A clear and concise description of what the bug is. If you are developing a new diagnostic script, please provide a link to the code/branch on GitHub that you are working in.

**Please attach**
  - The recipe that you are trying to run, you can find a copy in the `run` directory in the output directory
  - The `main_log_debug.txt` file, this can also be found in the `run` directory in the output directory

**Comment by bouweandela** [comment]
Just for reference, the proposed way to compute this was to use a preprocessor
```
preprocessors:
  global_total:
    area_statistics:
      operator: sum
      fx_variables: [areacello]
```
on input variable `fgco2`.

> This is because area_statistics miscalculates the units

Does this mean that there is a bug in the `area_statistics` function?

Here is an earlier comment by you:
> The `area_statistics` sum operation calculates the area-weighted sum. This means that it multiplies the value, either a concentration [per cubic meter] or a flux [per square meter] by the area [square meters]. This changes the units, which isn't reflected by the preprocessor at the moment.
>
> This means that every preprocessor that uses the `area_statistics` sum operation with fx files is scientifically incorrect.

Is this the problem you are referring to? Would multiplying the cube units by the weight units, e.g. here:
https://github.com/ESMValGroup/ESMValCore/blob/64911ebf20dcca711b66c82298fc922597840af1/esmvalcore/preprocessor/_area.py#L285-L286
solve that?
