### ISSUE TITLE
Synda download improvements

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#71]
`esmvaltool` can automatically download data using synda (if it is installed and configured with a user account) by specifying the `--synda-download` flag. The currently implemented functionality is sufficient for getting some data if you're a new developer on the project and want to be able to run the tool, but various improvements can be made. The following improvements have been suggested by @valeriupredoi 

- a check for the synda executable should be performed (this is needed e.g in case the code will be run in parallel and we don't want the thing to break);
- whereas sufficiently robust as it's now, there are corner cases that should be accounted for: files may exist locally that partially span the data request, and synda will find these plus a few more that complete the data request but in a partial manner and not FULLY -- in that case I believe the best practice is NOT to download anything IF the diagnostic can not be run on partial data sets;
- I would switch from synda get to synda install, the latter is performing a number of checks that get doesn't -- versioning and file integrity checks; in this case the install is done inside the synda DRS (I don't think we can tell synda to install in a custom path);
- careful with checks of file existence and writing to paths -- files may exist on data archives (BADC, DKRZ) but writing to disk is forbidden there;
- Have a look at the cache file creator tool I wrote and works pretty well for what I reckon are all the corner cases -- it's a large code but you can mix and match quite a few things that are already there and put them in _download.py :)

https://github.com/valeriupredoi/cmip5datafinder/blob/master/cmip5datafinder_v2.py

**Comment by valeriupredoi** [comment]
one thing to comment here: part of the ISENES3 project `synda` will get a massive overhaul. I think we should either use only the most basic functionality of it for now (the basic command) or not use it at all until the IPSL guys finish the rehaul.

**Comment by bouweandela** [comment]
We're dropping synda in favor of esgf-pyclient in #1217
