### ISSUE TITLE
Update yamale to v3

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#717]
A new version of Yamele has been released (v3), but our schemas are not compatible with it.

**Comment by zklaus** [comment]
It seems the main thing that is holding us back is that they changed the default for strictness (allowing additional, unmentioned elements) from `False` to `True`. I have confirmed on the command-line that all recipes validate against the current `recipe_schema.yml` with `--no-strict`.

Are there any other schemas? If not, I think the update is as simple as adding `strict=False` to the call to `yamale.validate`.

**Comment by bouweandela** [comment]
> Are there any other schemas?

No, I was planning to add more (e.g. #124, #68, #125, and maybe for config-developer.yml), but never got round to doing it.

**Comment by bouweandela** [comment]
It looks like the yamale package has been available on conda-forge since a year now too. I've just labeled the package as `deprecated`.

**Comment by zklaus** [comment]
Oh yeah, I assumed the problem with that was that it is too new, but now I saw that there is even a couple of 2.x versions on conda-forge.

Anyway, we should update our code to work with version 3. This is accomplished by #1059.
