### ISSUE TITLE
Failing unit tests with Python 3.6, =<3.7.3

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#719]
These tests are failing on CircleCI with Python 3.7.3:
```
FAILED tests/integration/cmor/_fixes/cmip6/test_cesm2.py::test_cl_fix_file - TypeError: 'NonCallableMagicMock' object is not callable
FAILED tests/integration/cmor/_fixes/cmip6/test_cesm2_waccm.py::test_cl_fix_file - TypeError: 'NonCallableMagicMock' object is not callable
```

The is probably caused by this bug: https://bugs.python.org/issue23078

**Comment by valeriupredoi** [comment]
this happens both on Linux/Python3.6 and OSX/Python3.6 and 3.7 as well, Bouwe, see https://github.com/ESMValGroup/ESMValCore/pull/700 (note that 3.8 for OSX is in fact 3.7, they haven't upgraded the machine's OSX Python yet, 3.8.5 is a week old)

**Comment by bouweandela** [comment]
Updating the docker container that we use for running our unit tests on CircleCI fixed this.
