### ISSUE TITLE
Installation and testing of esmvalcore package

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#731]
#732  and its Github Actions give us insight into the portability of `esmvalcore` as package:

**Installation**:
- installation from PyPi works fine for both Linux (Python>=3.6, <=3.8) and OSX (Python>=3.6, <=3.7)
- installation from conda:
  - works fine via miniconda on Linux (Python>=3.6, <=3.8)
  - works fine via anaconda on Linux (Python>=3.6, <=3.8) **only** if inside an empty virtual env (`conda create -n esmvalcore`), otherwise, it fails with unsolvable environment
  - works fine via miniconda on OSX (Python=3.6 only) **only** if inside an empty virtual env (`conda create -n esmvalcore`), otherwise, it fails with unsolvable environment, also fails for Python<=3.7 in any case
- installation from source works well via miniconda for both Linux and OSX

**Testing**:
testing is easier:
- it works for all bar a couple failed tests for Python<3.8 (https://github.com/ESMValGroup/ESMValCore/issues/719)

We should definitely add the instruction for users to create an empty conda env if their installation fails; we should also look into maybe pinning some deps for the conda env, I am going to remove `libunwind` since I know for sure it's not needed no more, see what that does.

EDIT: spoke too soon, we still need `libunwind` bah

**Comment by valeriupredoi** [comment]
**UPDATE** on testing: oddly enough both Circle and Github Actions CI's fail all Python tests with the system-specific `INTERNALERROR> AttributeError: 'tuple' object has no attribute 'rsplit'` but I am not seeing this on my local machine

**Comment by valeriupredoi** [comment]
> **UPDATE** on testing: oddly enough both Circle and Github Actions CI's fail all Python tests with the system-specific `INTERNALERROR> AttributeError: 'tuple' object has no attribute 'rsplit'` but I am not seeing this on my local machine

solved by merging `master`

**Comment by valeriupredoi** [comment]
OK @bouweandela last PR https://github.com/ESMValGroup/ESMValCore/pull/735 addresses the instructions specifically encouraging the use of miniconda and telling users to create an empty env if the env cannot be solved in `(base)`. There still are a few outstanding issues though:

Changed the PR to https://github.com/ESMValGroup/ESMValCore/pull/732 and reporting this from there:

- tests for Python 3.6.x (x=11 for Linux and x=7 for OSX) and 3.7.3 (Linux and OSX) still crash with the `TypeError: 'NonCallableMagicMock' object is not callable` bug; note that Python 3.7.8 and 3.8 don't display this and tests work so Python>=3.7.8 is all fine!
- conda installation on OSX+Python 3.8.5 is not working - blaming this on the fact that 3.8.5 was released for OSX only 10 days ago so we should probably expect package conflicts for a while now.

@bouweandela do you already have a solution for the test fails or you would want me to have a closer look? :beer:

**Comment by valeriupredoi** [comment]
@bouweandela you closed #719 but tests are still failing, see https://github.com/ESMValGroup/ESMValCore/pull/732

**Comment by valeriupredoi** [comment]
@bouweandela when you do stuff that affect the tests and/or installation can you also post a ping here too please mate :beer:

**Comment by bouweandela** [comment]
> do you already have a solution for the test fails or you would want me to have a closer look?

Yes, use a newer version of Python, i.e. Python 3.7.4 or later or Python 3.8 (the bugfix will not be included in Python 3.6, because that's too old).

**Comment by valeriupredoi** [comment]
so we're not officially supporting Python<3.7.3 then? :beer:

**Comment by bouweandela** [comment]
Maybe we can drop support for Python 3.6 once 3.9 is released? That will be this autumn.

About using Python 3.7.3, that was released in March 2019 and a number of bug and security fixes have been published since, so if you run into one of those, as is the case here, your only option is to upgrade. The list of Python releases and their release dates can be found here: https://www.python.org/downloads/. I don't think we can test or support all of these Python (or any other software package) releases, because the number of testing scenarios would be huge, e.g. there have been 12 Python 3.6 releases since it was first released, 9 Python 3.7 releases and 6 Python 3.8 releases...

**Comment by valeriupredoi** [comment]
good jub @bouweandela - we now have nightly testing with the merge of #732 and are in a very good position wrt portability :beer: There are the issues with OSX but we have an issue for that and I am going to try get access to a Mac very soon see what I can on it :apple:
