### ISSUE TITLE
Adding area weighted RMS to area_statistics 

### ISSUE THREAD

**Issue by pcosbsc** [ESMValGroup/ESMValCore#739]
Would it be possible to add the iris analysis operator Root Mean Square (with area weighting) to the `area_statistics` function?
My guess is that just adding it to the`operators` array in the `get_iris_analysis_operation` function should solve it.

**Comment by bouweandela** [comment]
> Would it be possible to add the iris analysis operator Root Mean Square (with area weighting) to the area_statistics function?

Yes, I think so. Would you be able and willing to implement this and make a pull request? Let me know if you need help.

**Comment by pcosbsc** [comment]
Yes, thanks @bouweandela! I'll create the pertinent pull request.

**Comment by pcosbsc** [comment]
The enhancement is ready to be pushed to a new branch but I don't have permission to ESMValGroup/ESMValCore.git. Would you be able to grant me access?

Thanks

**Comment by bouweandela** [comment]
> The enhancement is ready to be pushed

Great!

> Would you be able to grant me access?

I believe everyone who is able to do that is on holiday at the moment. Maybe it would be easiest if you could fork the repository and make the pull request from there. Would you be able to do that?
