### ISSUE TITLE
Wrong units after derivation of variable

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValCore#750]
After the derivation script of a variable is executed, the units of the resulting cube are set to the ones given by the CMOR table without converting the data / checking if the units are correct:

https://github.com/ESMValGroup/ESMValCore/blob/594cb65498f92e6c08586e86d05933538be09de1/esmvalcore/preprocessor/_derive/__init__.py#L106

This is particularly problematic if the units after the derivation of the variable depend on the project (e.g. CMIP5 vs. CMIP6) and is really hard to debug, since it does **not** result in an exception.

**Solution**

I will add a check if the units are correct, and if not convert the units.

@hb326

**Comment by bouweandela** [comment]
> This is particularly problematic if the units after the derivation of the variable depend on the project 

Are there other cases where this would be problematic? The functionality was implemented before CMIP6 was data was available, so I was not aware that the units would be different for the same variable at the time I wrote this.

**Comment by schlunma** [comment]
We found this problem while working with CMIP5 and CMIP6 data simultaneously. I do not know of any other cases, but I think the way it is implemented right now is prone to errors that are not easy to debug, since we expect the derivation script to output the correct units without cross-checking this.
