### ISSUE TITLE
Preprocessor feature request: Add a way to specify Dataset start_month and end_month

### ISSUE THREAD

**Issue by ledm** [ESMValGroup/ESMValCore#76]
Hi,

I'm attempting to look at the South Hemisphere Summer seasonal mean, (DJF), so I've used the `extract_season` preprocessor. If I run the analysis from January to December, then the first seasonal_year includes only January and February, and the final seasonal_year only includes December. These data are not comparable, and shows a huge bias at the first and last points:
![diag_cmip5_hadgem2-cc_oimon_historical_r1i1p1_to2m_sic_timeseries_shs_ice_extent_diag_ice_shs_1989_2004_ortho_map_south_djf_0](https://user-images.githubusercontent.com/4180685/45675571-90aa5200-bb27-11e8-99ca-949ff7474c95.png)

. To remove the erroneous months from the analysis, I've added the `start_month` and  `end_month` fields to the `dataset` dictionary. 

I'm using the following dataset:
  - {dataset: HadGEM2-CC, project: CMIP5, exp: historical, ensemble: r1i1p1, start_year: 1989, end_year: 2004, start_month: 3, end_month: 10}

However, the `start_month` and `end_month` fields are not taken into account by the preprocessor, and the preprocessed data runs from January 1889 to December 2004. 

Is this a bug? Can someone reproduce it? what is the problem? Cheers!

**Comment by bouweandela** [comment]
This has been implemented some time ago, it can be done using [`timerange`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/recipe/overview.html#recipe-section-datasets).
