### ISSUE TITLE
Switch from vmprof to vprof as supported diagnostic profiler?

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#765]
We currently support profiling diagnostic with [vmprof](https://github.com/vmprof/vmprof-python) when the `profile_diagnostic` option is set to `true` in config-user.yml. I tried to use the output, but was not successful in getting it to display. The project does not look very active on GitHub either and we regularly have installation issues with it, see e.g. [here](https://app.circleci.com/pipelines/github/ESMValGroup/ESMValTool/3065/workflows/247fde2e-e729-4ee6-b60d-ca1a7ba66827/jobs/35980).

We could switch to [vprof](https://github.com/nvdv/vprof), which looks slightly more maintained, is easier to install, and produces json output (instead of custom file format) as well as a kind of working local website.

@jvegasbsc since you first implemented this feature, do you have an opinion on this?

Or does anyone have a suggestion for a more user friendly profiler?

**Comment by jvegasbsc** [comment]
> @jvegasbsc since you first implemented this feature, do you have an opinion on this?

I do not have a strong opinion on that, but if the new one produces human readable output it is a good improvement. Please, go ahead

**Comment by valeriupredoi** [comment]
I'll test this in light of getting rid of `libunwind` which currently causes issues with OSX installations :+1:

**Comment by valeriupredoi** [comment]
OK it works nicely https://github.com/ESMValGroup/ESMValCore/actions - I'll make a PR - note that actual correct testing with Python 3.8 on OSX has now unearthed a different issue, but nothing to do with vmprof/vprof - good idea, @bouweandela :beer:
