### ISSUE TITLE
Conflicting import formatting between yapf and isort

### ISSUE THREAD

**Issue by stefsmeets** [ESMValGroup/ESMValCore#777]
**Describe the bug**
I just noticed that both yapf and isort will format the imports, which is undesirable. This does not really affect if you run isort/yapf manually, but for `pre-commit` this turns into an infinite loop of both fixing each others changes.

The culprit is probably was probably introduced here: https://github.com/ESMValGroup/ESMValCore/blob/6594471a0128dca05b56a7e5317525ddb16b8567/setup.cfg#L32

Either we
1. Ensure the formatting between isort and yapf is the same
2. We use an import sorter that does not do formatting
3. Yapf should not touch the imports

**Comment by stefsmeets** [comment]
The PR fixes most cases, but there is still an issue with this.
I just came accross this conflict in `tests/unit/preprocessor/_multimodel/test_multimodel.py`

isort likes:
```python
from esmvalcore.preprocessor._multimodel import (_assemble_data,
                                                 _compute_statistic,
                                                 _get_time_slice, _plev_fix,
                                                 _put_in_cube,
                                                 _unify_time_coordinates,
                                                 multicube_statistics,
                                                 multicube_statistics_iris)
```

yapf likes:
```python
from esmvalcore.preprocessor._multimodel import (
    _assemble_data, _compute_statistic, _get_time_slice, _plev_fix,
    _put_in_cube, _unify_time_coordinates, multicube_statistics,
    multicube_statistics_iris)
```

**Comment by stefsmeets** [comment]
It seems that `yapf` tries to determine whether to go for the `isort` style above or move the imports over to the next line based on some algorithm. The choice for this formatting in isort is static and defined via a config file.

The alternative is to go for a different style of import formatting as also stated in the [isort documentation](https://pycqa.github.io/isort/docs/configuration/profiles/). This will give something like:
```python
from esmvalcore.preprocessor._multimodel import _assemble_data
from esmvalcore.preprocessor._multimodel import _compute_statistic
from esmvalcore.preprocessor._multimodel import _get_time_slice
from esmvalcore.preprocessor._multimodel import _plev_fix
from esmvalcore.preprocessor._multimodel import _put_in_cube
from esmvalcore.preprocessor._multimodel import _unify_time_coordinates
from esmvalcore.preprocessor._multimodel import multicube_statistics
from esmvalcore.preprocessor._multimodel import multicube_statistics_iris
```

This will also play nice with `yapf`, and is (in my opinion) the better way to format imports anyway. The advantage is that it reduces merge conflicts. By having a single import per line, contributors can add/remove imports while keeping a clean history.

**Comment by stefsmeets** [comment]
I also found an alternative tool [here](https://github.com/asottile/reorder_python_imports) to do import reordering, which seems to be less fussy than `isort`, but gives the same ordering as in https://github.com/ESMValGroup/ESMValCore/issues/777#issuecomment-692096721. Might be a good alternative.

**Comment by bouweandela** [comment]
I think you need to use
```
[isort]
multi_line_output = 3
include_trailing_comma = true
```
because `yapf` will respect the multi line format if there is a trailing comma.

**Comment by stefsmeets** [comment]
Okay, I wasn't aware of this. This indeed works, I just tested it and the trailing comma makes the difference! 

The output is again slightly different:

```python
from esmvalcore.preprocessor._multimodel import (
    _assemble_full_data,
    _assemble_overlap_data,
    _compute_statistic,
    _datetime_to_int_days,
    _get_overlap,
    _get_time_offset,
    _plev_fix,
    _put_in_cube,
    _slice_cube,
)
```

**Comment by stefsmeets** [comment]
Just to make sure I tested this on all files in the repo, and there are no more conflicts 🎉

**Comment by alproskip** [comment]
It seems that the issue still persists, specifically for single imports that exceed the character limit. Here's the difference in behavior:

- yapf: Places the import on a new line with a trailing comma and parentheses.
```from long_module_name import (
    SomeVeryLongClassName, )
)
```
- isort: Moves the closing parentheses to a new line.
```from long_module_name import (
    SomeVeryLongClassName,
```

**Comment by Liquidmasl** [comment]
> It seems that the issue still persists, specifically for single imports that exceed the character limit. Here's the difference in behavior:
> 
> * yapf: Places the import on a new line with a trailing comma and parentheses.
> 
> ```
> from long_module_name import (
>     SomeVeryLongClassName, )
> )
> ```
> 
> * isort: Moves the closing parentheses to a new line.
> 
> ```
> from long_module_name import (
>     SomeVeryLongClassName,
> )
> ```

still having this issue, any solution to that?

**Comment by alexandreczg** [comment]
Yah, this is till happening, same as @Liquidmasl .

**Comment by hrushikeshm-g** [comment]
Its not resolve , why this is close....
