### ISSUE TITLE
Download subcommand for downloading of tutorial data

### ISSUE THREAD

**Issue by nielsdrost** [ESMValGroup/ESMValCore#788]
It would be nice to be able to ask ESMValTool to download some "getting started" data for you for the tutorial. This could for instance be in the form of a download subcommand.

```esmvaltool download example-data```

Eventually we can also add the capability to download data for a specified recipe to this new subcommand (via Synda or otherwise).

Thoughts?

**Comment by valeriupredoi** [comment]
we could put some data on a server and use that as example data and make it accessible to anyone who's got the tool via `wget`? Not an ESGF server, but some cloud storage unit - I am not sure which one would be suited for that though

**Comment by bouweandela** [comment]
It would be good to check with @jvegasbsc how much is already done in esmvalgroup/esmvaltool#1657 before getting started on this.

**Comment by jvegasbsc** [comment]
A bunch of observational data is available, CMIP data is not

**Comment by valeriupredoi** [comment]
wait - am confused - CMIP5 data is fully available and free for redistribution (apart from MIROC, but who gives a hoots) - why don't we just grab a few models and put them in a cloud store?

**Comment by jvegasbsc** [comment]
> wait - am confused - CMIP5 data is fully available and free for redistribution (apart from MIROC, but who gives a hoots) - why don't we just grab a few models and put them in a cloud store?

I was referring to the automatic download and installation of data in ESMValTool. Assuming Synda is available is too ambitious at the moment

**Comment by valeriupredoi** [comment]
ah right! Synda is still hacky (just had a conversation with Ruth Petrie about it, they have an installation on Jasmin that was a bit of a pain to get it done) and we need to make sure 100% data doesn't change for accurate testing; anyways, I am open to suggestions and am willing to help with whatever we decide :+1:

**Comment by bouweandela** [comment]
It would probably be a good idea to switch to [esgf-python](https://esgf-pyclient.readthedocs.io/en/latest/notebooks/examples/download.html) for downloading while running the recipe.

It would be nice to also have an option to generate a [synda selection file](http://prodiguer.github.io/synda/sdt/selection_file.html) from a recipe, in case you want to use the data not just once, but install it with synda for re-use.
