### ISSUE TITLE
Check if command line arguments are valid

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#797]
At the moment the `esmvaltool` command does not check if any invalid arguments are provided, e.g. a command like this
```
esmvaltool run --config-flie config-user.yml examples/recipe_python.yml
```
will happily run and try to use the configuration file in default location `~/.esmvaltool/config-user.yml` instead of the one provided on the command line. This is very confusing if that file contains an error and you do not spot the typo in the command.

**Comment by valeriupredoi** [comment]
by all means, if yous have a simple and qwik fix for this, fire up (literally :grin: ) - I am starting to get very frustrated with me being a muppet and misspelling command args and the thing doing its stuff without alerting me at runtime point :beer:

**Comment by valeriupredoi** [comment]
friendly ping to myself since I've been meaning to look into fixing this

**Comment by stefsmeets** [comment]
I implemented validators for all the CLI parameters in the experimental API. https://docs.esmvaltool.org/projects/esmvalcore/en/latest/api/esmvalcore.api.config.html

**Comment by schlunma** [comment]
The validation is now implemented:

```
> esmvaltool run --config-file ~/config-user.yml --wrong 1 ~/tmp/recipes/recipe_cox18nature.yml
...
esmvalcore.experimental.config._validated_config.InvalidConfigParameter: `wrong` is not a valid config parameter.
```

However, this fails when there is a typo in ``--config-file`` and the default config file does not exist:

```
> esmvaltool run --config-usa ~/config-user.yml ~/tmp/recipes/recipe_cox18nature.yml
...
FileNotFoundError: [Errno 2] No such file or directory: '~/.esmvaltool/config-user.yml'
```

Apart from a more detailed error message I see no easy way to handle this last case, since the validation can only happen after the configuration file is read; and this is too late.

Any opinions on this? I propose to close this.

**Comment by zklaus** [comment]
Hmmm. Why isn't the output
```
`config-usa` is not a valid config parameter.
```
?

**Comment by schlunma** [comment]
It is when `~/.esmvaltool/config-user.yml` exists, otherwise the error above appears. We would need some kind of spell-checking for this to work, otherwise I don't see a solution for this. Or maybe expand the error message to something like

```
FileNotFoundError: [Errno 2] No such file or directory: '~/.esmvaltool/config-user.yml', make sure that ``--config-file`` is spelled correctly...
```

**Comment by zklaus** [comment]
My point is that there should be an error about the wrong parameter, no matter what happens with the config file.

**Comment by schlunma** [comment]
The check for the parameters only happens after reading the configuration file (as many of the options are added by this), we would need another validation step specifically for the command line arguments for this before the config file is read.

**Comment by schlunma** [comment]
Okay there's actually a very easy fix for this. I thought the creation of the experimental config objects checks for missing options, but actually it doesn't.

So this a we can actually add a simple validation like this

```py
from .experimental.config._validated_config import ValidatedConfig
ValidatedConfig(kwargs)
```

to the [top of `ESMValTool.run()`](https://github.com/ESMValGroup/ESMValCore/blob/e9daad3b648d4872bfd67320b68d578faa1faee5/esmvalcore/_main.py#L323). Makes sense?

**Comment by zklaus** [comment]
Sounds good. @Peter9192 or @stefsmeets, could you comment briefly?

**Comment by stefsmeets** [comment]
> Sounds good. @Peter9192 or @stefsmeets, could you comment briefly?

Yeah, tricky issue. The question is whether: 

1. You do a pre-parsing of the CLI parameters and retrieve the `--config-user` flag. This will not protect you from miss-spelling the paramater, and this is what happens now I think.
2. Or do you first validate the config, and then read/overwrite the config, and then validate again. I think this is what @schlunma is suggesting.

The core of the problem that I ran into when developing this is that ESMValTool treats CLI paramaters and config parameters as one. You put config paramers in the CLI and vice-versa. 

This could do with better separation, the parameters could eventually go into the same dict and be validated. 

It also does not help that `fire` does not seem to be very strict about spelling either. `argparse` from the standard library does this much better imo (but less flexible).

I proposed using an environment variable to specify the config file location to get around this, but there was no support for it.

**Comment by schlunma** [comment]
>     2. Or do you first validate the config, and then read/overwrite the config, and then validate again. I think this is what @schlunma is suggesting.

Yes, that's exactly what #1435 does.

> The core of the problem that I ran into when developing this is that ESMValTool treats CLI paramaters and config parameters as one. You can put config parameters in the CLI and vice-versa.

Yes!
