### ISSUE TITLE
Cube coord bounds make cube intersection misbehave

### ISSUE THREAD

**Issue by lukasbrunner** [ESMValGroup/ESMValCore#799]
**Issue in a nutshell**

- operation: `_area.py/extract_region()`
- task at hand: func needs to perfrom cube intersection on 0-360 lons
- comment: `extract_region` works well when run on a cube with negative longitude points and run as a stand alone preprocessor step, see [comment](https://github.com/ESMValGroup/ESMValCore/issues/799#issuecomment-701301097) but the intersection operation misbehaves when a `regrid` step has been run before, see [comment](https://github.com/ESMValGroup/ESMValCore/issues/799#issuecomment-701313532)

**Original Post**

Hi all!

I am currently testing the new recipe ClimWIP, which, among other things, calls the pre-processor to extract the following region:
https://github.com/ESMValGroup/ESMValTool/blob/414d7d2e84a62a777dfada79297c0ed400b6bbd3/esmvaltool/recipes/recipe_climwip.yml#L52-L56

For me the resulting longitude values look like this:
` lon = -1.25, 1.25, 3.75, 6.25, 8.75, 11.25, 13.75, 16.25, 18.75, 21.25, 
    23.75, 26.25, 28.75, 31.25, 33.75, 36.25, 38.75, 351.25, 353.75, 356.25 ;
`

Can anyone recreate this behaviour? Is it even expected? To me this looks wrong. My understanding is that the longitude should either be in [-180, 180) OR in [0, 360) but neither case is true here. 

Many thanks,
Lukas

[main_log_debug.txt](https://github.com/ESMValGroup/ESMValTool/files/5292272/main_log_debug.txt)

**Comment by Peter9192** [comment]
Good! At least we get the same results now, that helps.

**Comment by valeriupredoi** [comment]
it's the `bounds` that fool `intersection`, here's a minimal example:
```python
import iris
import numpy as np

lon_points = np.array([-8.75, -6.25, -3.75, -1.25,  1.25,  3.75,  6.25,  8.75, 11.25,
                       13.75, 16.25, 18.75, 21.25, 23.75, 26.25, 28.75, 31.25, 33.75,
                       36.25, 38.75])
lon_bounds = np.array([
    [ -2.5,   0. ],
    [  0. ,   2.5],
    [  2.5,   5. ],
    [  5. ,   7.5],
    [  7.5,  10. ],
    [ 10. ,  12.5],
    [ 12.5,  15. ],
    [ 15. ,  17.5],
    [ 17.5,  20. ],
    [ 20. ,  22.5],
    [ 22.5,  25. ],
    [ 25. ,  27.5],
    [ 27.5,  30. ],
    [ 30. ,  32.5],
    [ 32.5,  35. ],
    [ 35. ,  37.5],
    [ 37.5,  40. ],
    [350. , 352.5],
    [352.5, 355. ],
    [355. , 357.5]])
lons = iris.coords.DimCoord(lon_points, standard_name='longitude', bounds=lon_bounds,
                            units='degrees_east')
cube = iris.cube.Cube(np.zeros((20,)), dim_coords_and_dims=[(lons, 0)])
isect_with_bounds = cube.intersection(longitude=(0, 360))
print(isect_with_bounds.coord("longitude"))
cube.coord("longitude").bounds = None
isect_without_bounds = cube.intersection(longitude=(0, 360))
print(isect_without_bounds.coord("longitude"))
```

**Comment by Peter9192** [comment]
Seems to be this issue then: https://github.com/SciTools/iris/issues/3391

**Comment by valeriupredoi** [comment]
Indeed, good find @Peter9192 - I posted the minimal code so the iris folk can see the behavior :+1:

**Comment by Peter9192** [comment]
Okay let's wait for their reply then. It would be better to solve this in iris then for us to hack around it.

**Comment by valeriupredoi** [comment]
too late - I already created a temporary fix for us :grin:
