### ISSUE TITLE
Send message to development team

### ISSUE THREAD

**Issue by mattiarighi** [ESMValGroup/ESMValCore#8]
Once the repositories split is complete, an email should be sent to the whole development team to inform them about the changes and with detailed instruction on:
- how to install / reinstall the tool
- how to move PRs from ESMValTool to ESMValCore
- where to open issues / submit PRs in the future

**Comment by valeriupredoi** [comment]
this has been done no?

**Comment by mattiarighi** [comment]
Long ago.
