### ISSUE TITLE
Update list of contributors

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#801]
Before we make the release, we need check the list of contributors in .zenodo.json file and update it if needed.

**Comment by valeriupredoi** [comment]
how do I do this @bouweandela :grin:

**Comment by bouweandela** [comment]
```bash
git ls-files | xargs -n 1 git blame | cut -d'(' -f2 | cut -d'2' -f1 | sed 's/ *$//g' | sort -u
```

**Comment by valeriupredoi** [comment]
If data archaeologists will discover your message in two thousand years they'll think we were all machines :grinning: Cheers, dude :beer:

**Comment by valeriupredoi** [comment]
OK so by miracle this thing spat a list of names - now all I haz to do is make sure each of those names is in the zenodo file?

**Comment by bouweandela** [comment]
Yes, I would think so. Or do you think we should ask people first if they would like to be listed as author @ESMValGroup/esmvaltool-coreteam?

**Comment by valeriupredoi** [comment]
yah I think it's best we ask first - plus, there are some I new ones I saw that I don't have any information on (employer etc) so it'd be cool to ask them to provide contact details if they agree to be added as contributors :+1:

**Comment by bouweandela** [comment]
I suspect you can find a lot of the info in https://github.com/ESMValGroup/ESMValTool/blob/master/esmvaltool/config-references.yml

**Comment by valeriupredoi** [comment]
yah good point! :beer:

**Comment by stefsmeets** [comment]
For sure my name is not on the list yet 😅

```yaml
{
  "affiliation": "NLeSC, Netherlands",
  "name": "Smeets, Stef",
  "orcid": "0000-0002-5413-9038"
},
```

**Comment by valeriupredoi** [comment]
@bulli92 @bascrezee @BenMGeo @bettina-gier @evertrol @egalytska @ipelupessy @JaroCamphuijsen @jhardenberg @katjaweigel @mwjury @mathause @npgillett @pcosbsc @Peter9192 @SarahAlidoost @ssmithClimate @koir-su @tillku @tobstac @tomaslovato  - you guys have contributed to ESMValCore and are not currently listed in the [zenodo](https://github.com/ESMValGroup/ESMValCore/blob/master/.zenodo.json) contributors' file. We'd like to thank you very much for contribution to the code and invite you to be added to the contributors list! Should you choose to accept, can I please ask you to post here the entry for your you just as @stefsmeets has just posted in this [comment](https://github.com/ESMValGroup/ESMValCore/issues/801#issuecomment-702681828) - no worries if you don't have an ORCID id, but if you have one it'd be good to include it. Cheers muchly for your efforts :beer: PS: as contributor to ESMValCore, you will be added to the list but there is no expectation that you continue to contribute, we're adding your name to the list as a result of your contributions to date, although we'd be very happy if you stuck around for a wee more :grin:

**Comment by JaroCamphuijsen** [comment]
Sure! Thanks for adding!

```
{
  "affiliation": "NLeSC, Netherlands",
  "name": "Camphuijsen, Jaro",
  "orcid": "0000-0002-8928-7831"
},
```

**Comment by bettina-gier** [comment]
Oh yeah I actually made an orcid too, I'll have to update the tool developer list next time I put a pull request I guess
{
  "affiliation": "University of Bremen, Germany",
  "name": "Gier, Bettina K.",
  "orcid": "0000-0002-2928-8664"
},

**Comment by katjaweigel** [comment]
Thanks for checking!
{
  "affiliation": "University of Bremen, Germany",
  "name": "Weigel, Katja",
  "orcid": "0000-0001-6133-7801"
},

**Comment by mathause** [comment]
Thanks, happy to be included.
{
"affiliation": "Institute for Atmospheric and Climate Science, ETH Zurich, Zurich, Switzerland",
"name": "Hauser, Mathias",
"orcid": "0000-0002-0057-4878"
},

**Comment by Peter9192** [comment]
```
{
  "affiliation": "Netherlands eScience Center",
  "name": "Kalverla, Peter",
  "orcid": "0000-0002-5025-7862"
},
```

**Comment by egalytska** [comment]
Thanks for including.
```
{
  "affiliation": "University of Bremen, Germany",
  "name": "Galytska, Evgenia",
  "orcid": "0000-0001-6575-1559"
},
```

**Comment by pcosbsc** [comment]
Thanks!

```
{
  "affiliation": "BSC, Spain",
  "name": "Cos-Espuña, Pep"
}, 
```

**Comment by ipelupessy** [comment]
{
  "affiliation": "Netherlands eScience Center",
  "name": "Pelupessy, Inti",
  "orcid": "0000-0002-8024-0412"
},

**Comment by koir-su** [comment]
{
"affiliation": "Max Planck Institute for Biogeochemistry, Germany",
"name": "Koirala, Sujan",
"orcid": "0000-0001-5681-1986"
},

🍺 🍻 and one more 🍺

**Comment by tobstac** [comment]
Thanks a lot!
{
"affiliation": "Helmholtz-Zentrum Geesthacht, Germany ",
"name": "Stacke, Tobias",
"orcid": "0000-0003-4637-5337"
},

**Comment by SarahAlidoost** [comment]
Thanks, here my info:
{
    "affiliation": "Netherlands eScience Center",
    "name": "Alidoost, Sarah",
    "orcid: "0000-0001-8407-6472"
}

**Comment by mwjury** [comment]
@valeriupredoi 5 minutes to late, worth a shot though. Thanks, very much anyways!
{
"affiliation": "Barcelona Supercomputing Center",
"name": "Jury, Martin",
"orcid: "0000-0003-0590-7843"
}

**Comment by valeriupredoi** [comment]
no worries @mwjury - you will get in at the next release via https://github.com/ESMValGroup/ESMValCore/pull/810 :beer:
