### ISSUE TITLE
Better time bounds in regrid_time preprocessor

### ISSUE THREAD

**Issue by Peter9192** [ESMValGroup/ESMValCore#803]
Currently the regrid_time preprocessor sets the center points of the time bounds, e.g. monthly data at the 15th day of each month, 00 UTC. 

I replicated this behaviour for multimodel stats in #685, but @sloosvel noticed in #673 that this creates slightly offset time bounds, e.g. the bounds of the time coordinate are at 12:00 UTC instead of midnight at the start of the new month.

Note that #744 proposes to move all time handling from multimodel to regrid_time, so I think this issue will have to be addressed in the regrid_time preprocessor, not in multimodel.

[@bouweandela propopsed](https://github.com/ESMValGroup/ESMValCore/pull/673#issuecomment-702575580) the following approach: 
> set the lower bound to the start of the month, the upper bound to the start of the next month and then set the points by computing 0.5 * (lower_bound + upper_bound).

**Comment by sloosvel** [comment]
I think this can be linked to #802 as well. If we check for presence of time bounds and for some reason they are not there, they could be guessed following the same approach.
