### ISSUE TITLE
Concatenation fails due to different bounds for different experiments but same model

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#806]
In #576 amongst other already resolved data issues, both @mwjury and @rswamina have run into issues related to iris cube concatenation failing due to very slightly different bounds values for different experiments but same model (see this [comment](https://github.com/ESMValGroup/ESMValCore/issues/576#issuecomment-639293655) and this [comment](https://github.com/ESMValGroup/ESMValCore/issues/576#issuecomment-702657244) - and may be more). This is a nasty problem but it is easily fixable by harmonizing the bounds values across experiments. I propose we introduce a dedicated builtin CMOR-like check for bounds before concatenation - this will, of course, alter original metadata but the metadata is wrong anyway. What do you think? :beer:

**Comment by rswamina** [comment]
@valeriupredoi  - In as much as we can say this is a problem only for concatenation then yes. I do not know if this can be a problem elsewhere. Also I do not know if altering the metadata will have implications. If there are none then should this just be a fix for this particular dataset?

**Comment by valeriupredoi** [comment]
@rswamina 

> If there are none then should this just be a fix for this particular dataset?

No, the original bounds are not `None` , they are different from one experiment to the other, and on top of that, the lowermost bound is negative for one experiment dataset (can you get negative lower bound for an always positive coordinate @zklaus ?)

A dataset fix is tricky unless you completely remove the bounds from each exp dataset and guess them with `iris` - `guess_bounds()` always returns consistent bounds, but the problem is that you are getting rid of a fair amount of metadata by doing this :beer:

**Comment by rswamina** [comment]
@valeriupredoi : By None I mean no other problems with altering the metadata.  As in should we make this change for this dataset regardless of concatenation or may be not based on what you say about using guess bounds?
> No, the original bounds are not `None` , they are different from one experiment to the other, and on top of that, the lowermost bound is negative for one experiment dataset (can you get negative lower bound for an always positive coordinate @zklaus ?)

**Comment by valeriupredoi** [comment]
ah got you, Ranjini! OK - I'd be very interested in what @jvegasbsc and @zklaus think about this :+1:

**Comment by bouweandela** [comment]
> cube concatenation failing due to very slightly different bounds values for different experiments but same model

Guessing the bounds sounds a bit drastic for solving this. In most cases we solve this by rounding the problematic coordinate value to one digit less, e.g. in the worst case to 6 digits if the modellers used a 32 bit float to store the data.

> A dataset fix is tricky 
Why is it not possible to write a fix for the specific models that have this problem?

**Comment by jvegasbsc** [comment]
If the bounds are not the same by an appreciable margin (i.e more than 0.01º), one of the experiments have an issue, as they are supposed to be run with exactly the same model version and grid. We should fix that experiment, not the other. In fact, if bounds have changed there is a chance that they detected an error in the older experiment, fixed it in the new and "forgot" to fix the older one.

If differences are smaller than that, it is usually just a rounding issue that we already solve in other models by rounding to a reasonable accuracy

**Comment by valeriupredoi** [comment]
it's not the model but the experiment: eg `historical` is fine and `ssp126` is fine too (if negative bounds are allowed for positive coord values) but they differ, here:
```
hist first and last lon bounds:  [0.   1.25] [356.25 360.  ]
ssp126 first and last lon bounds:  [-1.25  1.25] [356.25 358.75]
```
How can this be fixed?

**Comment by valeriupredoi** [comment]
> If the bounds are not the same by an appreciable margin (i.e more than 0.01º), one of the experiments have an issue, as they are supposed to be run with exactly the same model version and grid. We should fix that experiment, not the other. In fact, if bounds have changed there is a chance that they detected an error in the older experiment, fixed it in the new and "forgot" to fix the older one.
> 
> If differences are smaller than that, it is usually just a rounding issue that we already solve in other models by rounding to a reasonable accuracy

Most interesting, Javi, didn't know that! So how would you approach the fix based on the values above?

**Comment by jvegasbsc** [comment]
I would guess that the `hist` bounds are not correct. The fix should just be something like:

```python
# Assuming ocean grids are irregular and all grids with regular longitude have the same grid
if lon.ndim == 1 and lon.bounds[0,0] == 0.:
    lon.bounds[0,0]  = -1.25
    lon.bounds[-1,-1] = 358.75
```

**Comment by valeriupredoi** [comment]
cheers muchly @jvegasbsc - sounds good to me - @rswamina or @mwjury would you guys be okay to write the fix pls? :beer:

**Comment by mwjury** [comment]
@valeriupredoi see #816.

**Comment by valeriupredoi** [comment]
@mwjury fixed this via dataset fixes in #816 - cheers! CESM2 might need fixing for the same reasons but we'll bridge that bridge when we get there. Only thing left to do now is to ascertain this is indeed a model data issue and raise it with the model developers but seeing that they fixed something but didn't fix other stuff as @jvegasbsc points out in [comment](https://github.com/ESMValGroup/ESMValCore/issues/806#issuecomment-703521316) slim chances they will do it - @zklaus what do you think?

**Comment by mwjury** [comment]
@valeriupredoi I didn't have problems with CESM2 lately. Seems the already implemented boundary guessing for TAS did the trick.

**Comment by valeriupredoi** [comment]
cheers for the heads up @mwjury - and cheers for the fixes :beer: I reckon we can close this for now and do it English way - hope for the best :grin: @zklaus do we want to communicate the data issues to the modellers after all?
