### ISSUE TITLE
Upload packages to esmvalgroup conda channel and PyPI using GitHub actions

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#814]
Here is an action for deploying to PyPI: https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

Here is an action to upload a conda package to a custom conda channel: https://github.com/marketplace/actions/anaconda-action by my colleague @fdiblen

EDIT: The action above is not quite ready, best to copy/paste/modify the actions defined in https://github.com/matchms/matchms/tree/master/.github/workflows for now. They do build the Conda package, deploy to Conda channel and test the deployed packages as well.

**Comment by valeriupredoi** [comment]
good finds @bouweandela - will have a look at these later on today, currently installing ESMValTool centrally on Jasmin :partying_face: (won't be available until it gets linked in a module by the CEDA folk but this is the first step)
