### ISSUE TITLE
Adding variable cl to the era5 cmorizer

### ISSUE THREAD

**Issue by hb326** [ESMValGroup/ESMValCore#823]
I would like to get the variable "fraction of cloud cover" (cl) added to the era5 cmorizer.

I have added a cl class already to the file "era5.py" (see branch "adding_cl_to_era5_cmorizer"), but there is still a problem with the vertical coordinate (pressure). It seems like the cmip6 table provides the dimensions "longitude latitude alevel time", and "alevel" is not recognizes as a vertical coordinate in the cmorizer yet.

**Comment by schlunma** [comment]
This has been added here: https://github.com/ESMValGroup/ESMValCore/pull/1850
