### ISSUE TITLE
Dataset problem: Hybrid sigma pressure coordinate points in CESM models

### ISSUE THREAD

**Issue by sloosvel** [ESMValGroup/ESMValCore#840]
**Describe the dataset issue**
Due to #598 , the CMOR checker will be able to detect issues in the hybrid sigma pressure coordinate for models that so far were passing the checks. 

Some fixes are already implemented for CESM2 models, but with the new checks it turns out that the level coordinate has wrong negative values as well as wrong units ('hPa' instead of '1') and the already implemented fixes are not enough:

``` 
netcdf cl_Amon_CESM2_historical_r1i1p1f1_gn_185001-201412 {

...

lev = -3.64346569404006, -7.59481964632869, -14.3566322512925,
    -24.6122200042009, -35.9232500195503, -43.1937500834465,
    -51.6774989664555, -61.5204982459545, -73.7509578466415,
    -87.8212302923203, -103.317126631737, -121.547240763903,
    -142.994038760662, -168.225079774857, -197.908086702228,
    -232.828618958592, -273.910816758871, -322.241902351379,
    -379.100903868675, -445.992574095726, -524.687174707651,
    -609.778694808483, -691.389430314302, -763.404481112957,
    -820.858368650079, -859.53476652503, -887.020248919725,
    -912.644546944648, -936.198398470879, -957.485479535535,
    -976.325407391414, -992.556095123291 ; 
}
```
According to [cfconventions](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.0/build/apd.html):
`The hybrid sigma-pressure coordinate for level k is defined as a(k)+b(k) or ap(k)/p0+b(k), as appropriate.`

I guess the points should be recalculated using one of those formulas? I do not have much experience with these types of coordinates though. 

- Project (CMIP5/CMIP6/OBS/obs4mips/etc): CMIP6
- Full dataset description (fill out as many as you know, please):
  - dataset: CESM2
  - experiment: historical
  - mip: Amon
  - grid: gn
  - version: v20190308
  - variable used: cl
- Problems encountered (please describe what the actual problems are: e.g. wrong standard name, issue with dimensions): Explained above
- Pointer to existing copy of data on ESGF node (it would be very useful if you could provide a physical
fullpath to the file(s) that are causing the problem, e.g. on CEDA Jasmin or DKRZ): /badc/cmip6/data/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/Amon/cl/gn/latest/cl_Amon_CESM2_historical_r1i1p1f1_gn_185001-201412.nc

**Comment by bouweandela** [comment]
It looks like this was fixed by #882
