### ISSUE TITLE
ERA5-Land cmorizer/fixes

### ISSUE THREAD

**Issue by katjaweigel** [ESMValGroup/ESMValCore#855]
**Is your feature request related to a problem? Please describe.**
At the moment, there is an "on the flight" cmorizer for ERA5 data. In principle it also works for ERA5-Land, but there are some issues:
1) For ESMValCore: The fixes already existing for ERA5 are to a large extend also needed for ERA5-Land, I tested this for the variable pr (monthly) by simply copying
esmvalcore/cmor/_fixes/native6/era5.py 
to
esmvalcore/cmor/_fixes/native6/era5_land.py
and it works, but there might be differences for other variables.
2) For the ESMValTool: Would it make sense, to include an ERA5-Land example to esmvaltool/recipes/cmorizers/recipe_era5.yml or make an own esmvaltool/recipes/cmorizers/recipe_era5-land.yml?

**Would you be able to help out?**
Partly

**Comment by valeriupredoi** [comment]
@katjaweigel probably best to include the land bit in the existng `recipe_era5.yml` unles there are solid reasons why it should be separate; are the fixes needed for **all** the ERA5 variables? If so, we can use the `All` functionality for all vars :+1:

**Comment by katjaweigel** [comment]
I'm afraid the fixes are different, for different variables, for ERA5 there are already fixes for several variables in esmvalcore/cmor/_fixes/native6/era5.py, for ERA5-Land at least the fix there for pr is the same as for ERA5, but  I'm not sure if this is true for the other variables.

**Comment by bouweandela** [comment]
> copying esmvalcore/cmor/_fixes/native6/era5.py to esmvalcore/cmor/_fixes/native6/era5_land.py and it works

Rather than copying the file, I would recommend `import`ing the required classes from it

> but there might be differences for other variables.

Yes, the main part of the work would probably be to carefully read the ERA5(land) documentation and see what is needed

> For the ESMValTool: Would it make sense, to include an ERA5-Land example to esmvaltool/recipes/cmorizers/recipe_era5.yml or make an own esmvaltool/recipes/cmorizers/recipe_era5-land.yml?

I think both options are fine.
