### ISSUE TITLE
iris 2.4.0 needing 5x filesize in memory to save it

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#861]
I have created these files, each of them from data cmorization and the resulting cubes to be saved all had lazy data:
```bash
(esmvaltool-21) [valeriu@sci2 esmvaltool_var_test]$ du -h LST/cmorize_obs_20201110_180659/Tier2/ESACCI-LST/OBS_ESACCI-LST_sat_1.00_Amon_ts_200401-200412.nc 
1.2G	LST/cmorize_obs_20201110_180659/Tier2/ESACCI-LST/OBS_ESACCI-LST_sat_1.00_Amon_ts_200401-200412.nc
(esmvaltool-21) [valeriu@sci2 esmvaltool_var_test]$ du -h LST/cmorize_obs_20201110_180659/Tier2/ESACCI-LST/OBS_ESACCI-LST_sat_1.00_Amon_ts_200501-200512.nc 
1.2G	LST/cmorize_obs_20201110_180659/Tier2/ESACCI-LST/OBS_ESACCI-LST_sat_1.00_Amon_ts_200501-200512.nc
(esmvaltool-21) [valeriu@sci2 esmvaltool_var_test]$ du -h LST/cmorize_obs_20201110_180659/Tier2/ESACCI-LST/OBS_ESACCI-LST_sat_1.00_Amon_ts_200601-200612.nc 
1.2G	LST/cmorize_obs_20201110_180659/Tier2/ESACCI-LST/OBS_ESACCI-LST_sat_1.00_Amon_ts_200601-200612.nc
```
for each of this files the `iris.save()` call consumed anywhere between 5-7GB of RES memory (on Jasmin, where there is a **risk** that the RES memory is blown up); has anyone else noticed large memory being needed by iris save lately? @bouweandela @bjlittle @zklaus

**Comment by valeriupredoi** [comment]
BTW I have just asked this to the Jasmin folks: hey guys, I have a question related to the sci nodes memory: I have a number of processes that if I run them on sci2 they take anywhere inbetween 5-7GB of RES max memory each as measured via top, and if I run them on sci3 the max memory goes to 11-13GB for the same processes; I am using exactly the same software environment and these are not random number gen/regen processes that may have computational variability - it's basically saving **fixed** iris cubes with **fixed** lazy data arrays to disk - why is there such a massive difference in memory consumption? Is the RES memory reported correctly on each node? Cheers :beer:

**Comment by bouweandela** [comment]
Maybe it would be better to open this issue in the iris repo?

**Comment by valeriupredoi** [comment]
maybe, I was wondering if I can pick up some momentum here with people saying "yeah I've noticed this too" and start a discussion :+1:

**Comment by zklaus** [comment]
Something you could perhaps try is to realize the data immediately before saving, ie throw a `result.data` in there (or a `result.lazy_data().compute()`. Reason is that last I checked, saving needed going to the serial scheduler and if many calculations are still outstanding it is possible that more things are done serially than needed. Just an idea though.

**Comment by valeriupredoi** [comment]
good call, Klaus! I had done that (I forgot to post here) and the mem profile is the same; one thing I learned from the folk at Jasmin is that the more available memory the node has the more the stack will ask for, so if we run this on different nodes then the max mem will differ depending on the node; this explains the variation I see across nodes but still doesn't explain why iris is asking for so much memory to start with - might have to plop this one to the SciTools GitHub as Bouwe recommends :+1:

**Comment by zklaus** [comment]
I suppose the other question is: What's the problem? If the memory is available and things can be done faster using more memory, should iris/dask not go for it? If your answer is "No!", you can always put a limit on the memory that dask uses.

**Comment by valeriupredoi** [comment]
yeah the "is it swapping yet" is a solid answer, I guess I just wanted to understand the mechanism behind it, but prob best to forget about it - not an actual issue no more now that I am starting to see there is no actual bug in the code :+1:
