### ISSUE TITLE
Github Actions failing due to obsolete miniconda setup action

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#867]
[Fail list](https://github.com/ESMValGroup/ESMValCore/actions/runs/373416098) due to `goanpeca/setup-miniconda@v1` using obsolete syntax; the solution is here https://github.com/conda-incubator/setup-miniconda/issues/101 - we just need to switch from `goanpeca/setup-miniconda@v1` hook to `conda-incubator/setup-miniconda@v2` - I'll do it in a few minutes :+1:

**Comment by nielsdrost** [comment]
@valeriupredoi changes look good to me. I guess we will only know the result when we merge, right?

**Comment by bouweandela** [comment]
Has this been fixed now?

**Comment by valeriupredoi** [comment]
yip, but my latency at closing issues hasn't yet :grin:
