### ISSUE TITLE
Numba causing installation issues with python=3.9

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#869]
conda=4.9.2 env builds well but installing doesn't:
```
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /home/valeriu/miniconda3/envs/esmvalcore-492/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-elou0qm8/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-elou0qm8/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-woct46sr/install-record.txt --single-version-externally-managed --compile --install-headers /home/valeriu/miniconda3/envs/esmvalcore-492/include/python3.9/llvmlite
         cwd: /tmp/pip-install-elou0qm8/llvmlite/
    Complete output (29 lines):
    running install
    running build
    got version from file /tmp/pip-install-elou0qm8/llvmlite/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    /home/valeriu/miniconda3/envs/esmvalcore-492/bin/python3.9 /tmp/pip-install-elou0qm8/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-install-elou0qm8/llvmlite/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/home/valeriu/miniconda3/envs/esmvalcore-492/lib/python3.9/subprocess.py", line 420, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/home/valeriu/miniconda3/envs/esmvalcore-492/lib/python3.9/subprocess.py", line 501, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/home/valeriu/miniconda3/envs/esmvalcore-492/lib/python3.9/subprocess.py", line 947, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/home/valeriu/miniconda3/envs/esmvalcore-492/lib/python3.9/subprocess.py", line 1819, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-elou0qm8/llvmlite/ffi/build.py", line 191, in <module>
        main()
      File "/tmp/pip-install-elou0qm8/llvmlite/ffi/build.py", line 181, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-elou0qm8/llvmlite/ffi/build.py", line 107, in main_posix
        raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/home/valeriu/miniconda3/envs/esmvalcore-492/bin/python3.9' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/valeriu/miniconda3/envs/esmvalcore-492/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-elou0qm8/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-elou0qm8/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-woct46sr/install-record.txt --single-version-externally-managed --compile --install-headers /home/valeriu/miniconda3/envs/esmvalcore-492/include/python3.9/llvmlite Check the logs for full command output.
```

**Comment by valeriupredoi** [comment]
OK the cause is again `numba` (we should really think about removing it from our deps list - the performance improvements we get by using it are marginal, do you agree @jvegasbsc ?) see https://github.com/numba/numba/issues/6345 - they say they will release a compatible version by the end of the year!

**Comment by jvegasbsc** [comment]
Currently we are using it only for the derivation of `toz`, which was done by @schlunma. He says in a comment that is 10x faster, but I think we can live without it for the time being, as it only affects a very specific part of the code.

**Comment by schlunma** [comment]
I did not write the actual derivation of `toz`, I only changed the interface of derived variables some time ago (that's why it shows me as author) 😄

However, I think that this factor of 10 can make quite a difference. If I remember correctly this part of the code is really slow, so the difference of let's say 10 min to 100 min is quite significant. I can have look at this, I wanted to work on #783 which uses this part of the code anyway. Maybe it's possible to optimize the code without using `numba`.

**Comment by bouweandela** [comment]
That code is ancient, it was already part of the project before I joined, maybe @nielsdrost remembers who wrote it? It would be really good If you could have a look at it and add some unit tests too @schlunma.

**Comment by valeriupredoi** [comment]
so `numba` actually slows down that function by a heck of a lot:
- with the jit decorator: 0.399s for 10 runs of the function
- without it: 0.001s for the same number of runs

It could be that as is the case with `numba` there are large deltas for not many runs, so for 100 runs I get: 0.0094s without jit and 0.401s with it. This is for the standard `plev19` array, here's the code if you don't trust me. So numba is going down! :+1: 

```python
import cf_units
import iris
import numba
import numpy as np
from scipy import constants

import time as tr

@numba.jit()  # ~10x faster
def _p_level_widths(array):
    """Create pressure level widths.

    The array with pressure levels is assumed to be monotonic and the
    values are decreasing.

    The first element is the lower boundary (surface pressure), the last
    value is the upper boundary. Thicknesses are only calculated for the
    values between these boundaries, the returned array, therefore,
    contains two elements less.

    >>> _p_level_widths(np.array([1020, 1000, 700, 500, 5]))
    array([170., 250., 595.], dtype=float32)

    >>> _p_level_widths(np.array([990, np.NaN, 700, 500, 5]))
    array([  0., 390., 595.], dtype=float32)
    """
    surface_pressure = array[0]
    top_limit = array[-1]
    array = array[1:-1]

    p_level_widths = np.full(array.shape, np.NAN, dtype=np.float32)

    last_pressure_level = len(array) - 1
    for i, val in enumerate(array):
        # numba would otherwise initialize it to 0 and
        # hide bugs that would occur in raw Python
        bounds_width = np.NAN
        if np.isnan(val):
            bounds_width = 0
        else:
            # Distance to lower bound
            if i == 0 or np.isnan(array[i - 1]):
                # First pressure level with value

                dist_to_lower_bound = surface_pressure - val
            else:
                dist_to_lower_bound = 0.5 * (array[i - 1] - val)

            # Distance to upper bound
            if i == last_pressure_level:  # last pressure level
                dist_to_upper_bound = val - top_limit
            else:
                dist_to_upper_bound = 0.5 * (val - array[i + 1])

            # Check monotonicity - all distances must be >= 0
            if dist_to_lower_bound < 0.0 or dist_to_upper_bound < 0.0:
                raise ValueError("Pressure level value increased with "
                                 "height.")

            bounds_width = dist_to_lower_bound + dist_to_upper_bound

        p_level_widths[i] = bounds_width
    return p_level_widths

arl =  ["100000.",
        "92500.",
        "85000.",
        "70000.",
        "60000.",
        "50000.",
        "40000.",
        "30000.",
        "25000.",
        "20000.",
        "15000.",
        "10000.",
        "7000.",
        "5000.",
        "3000.",
        "2000.",
        "1000.",
        "500.",
        "100."
]
ar = np.array([float(p) for p in arl])
t1 = tr.time()
for i in range(100):
    f = _p_level_widths(ar)
print(tr.time() - t1)
```

**Comment by schlunma** [comment]
Cool, thanks for the analysis V.! I will refactor the code, add some tests and remove `numba` in #783!

**Comment by valeriupredoi** [comment]
awesomepossum :hedgehog:

**Comment by nielsdrost** [comment]
> That code is ancient, it was already part of the project before I joined, maybe @nielsdrost remembers who wrote [it](https://github.com/ESMValGroup/ESMValCore/blob/master/esmvalcore/preprocessor/_derive/toz.py)? It would be really good If you could have a look at it and add some unit tests too @schlunma. It should also be made lazy.

Sorry, not sure. Perhaps @bjlittle or @jvegasbsc have some idea? :-)

Agree to drop numba!

**Comment by jvegasbsc** [comment]
> 
> 
> so `numba` actually slows down that function by a heck of a lot:
> 
>     * with the jit decorator: 0.399s for 10 runs of the function
> 
>     * without it: 0.001s for the same number of runs
> 
> 
> It could be that as is the case with `numba` there are large deltas for not many runs, so for 100 runs I get: 0.0094s without jit and 0.401s with it. This is for the standard `plev19` array, here's the code if you don't trust me. So numba is going down! 👍
> 
> ```python
> import cf_units
> import iris
> import numba
> import numpy as np
> from scipy import constants
> 
> import time as tr
> 
> @numba.jit()  # ~10x faster
> def _p_level_widths(array):
>     """Create pressure level widths.
> 
>     The array with pressure levels is assumed to be monotonic and the
>     values are decreasing.
> 
>     The first element is the lower boundary (surface pressure), the last
>     value is the upper boundary. Thicknesses are only calculated for the
>     values between these boundaries, the returned array, therefore,
>     contains two elements less.
> 
>     >>> _p_level_widths(np.array([1020, 1000, 700, 500, 5]))
>     array([170., 250., 595.], dtype=float32)
> 
>     >>> _p_level_widths(np.array([990, np.NaN, 700, 500, 5]))
>     array([  0., 390., 595.], dtype=float32)
>     """
>     surface_pressure = array[0]
>     top_limit = array[-1]
>     array = array[1:-1]
> 
>     p_level_widths = np.full(array.shape, np.NAN, dtype=np.float32)
> 
>     last_pressure_level = len(array) - 1
>     for i, val in enumerate(array):
>         # numba would otherwise initialize it to 0 and
>         # hide bugs that would occur in raw Python
>         bounds_width = np.NAN
>         if np.isnan(val):
>             bounds_width = 0
>         else:
>             # Distance to lower bound
>             if i == 0 or np.isnan(array[i - 1]):
>                 # First pressure level with value
> 
>                 dist_to_lower_bound = surface_pressure - val
>             else:
>                 dist_to_lower_bound = 0.5 * (array[i - 1] - val)
> 
>             # Distance to upper bound
>             if i == last_pressure_level:  # last pressure level
>                 dist_to_upper_bound = val - top_limit
>             else:
>                 dist_to_upper_bound = 0.5 * (val - array[i + 1])
> 
>             # Check monotonicity - all distances must be >= 0
>             if dist_to_lower_bound < 0.0 or dist_to_upper_bound < 0.0:
>                 raise ValueError("Pressure level value increased with "
>                                  "height.")
> 
>             bounds_width = dist_to_lower_bound + dist_to_upper_bound
> 
>         p_level_widths[i] = bounds_width
>     return p_level_widths
> 
> arl =  ["100000.",
>         "92500.",
>         "85000.",
>         "70000.",
>         "60000.",
>         "50000.",
>         "40000.",
>         "30000.",
>         "25000.",
>         "20000.",
>         "15000.",
>         "10000.",
>         "7000.",
>         "5000.",
>         "3000.",
>         "2000.",
>         "1000.",
>         "500.",
>         "100."
> ]
> ar = np.array([float(p) for p in arl])
> t1 = tr.time()
> for i in range(100):
>     f = _p_level_widths(ar)
> print(tr.time() - t1)
> ```

V, that is expected for 10, as numba has to compile but I think this function is called thousands of times in the real scenario

**Comment by valeriupredoi** [comment]
correct, Javi! That's why I ran it 1000 times as well, I just reran it for 10000 times and indeed with numba it takes 0.6s and without 1.2s so numba indeed improves it but hey - we can spare 0.6s :grin: - 1e5 times the run we can see the benefit of numba: 12s without, 0.6 with - but 10s is a good tradeoff for a package that is often broken :+1:

**Comment by jvegasbsc** [comment]
Tested for 1e6 executions:

```
Numba:            1.452 s
Without numba:   82.244 s
```

**Comment by valeriupredoi** [comment]
yeah, as my [comment](https://github.com/ESMValGroup/ESMValCore/issues/869#issuecomment-732957678) - we can spare a few tens of seconds, it's not that the bottleneck for ESMValTool, I'd trade that for getting rid of a package that causes headaches quite often :beer:

**Comment by jvegasbsc** [comment]
Go ahead, then!

**Comment by valeriupredoi** [comment]
boss! @schlunma she's all yours, say bye to `numba` for me :beer:

**Comment by schlunma** [comment]
Bad news, I tested this with an actual dataset (IPSL-CM6A-LR, 100 years of monthly mean data).

With `numba`, it finished after 6 min, without `numba` it's still running (for >75 min now). I think this increase in time is unacceptable, especially wenn analyzing more than one dataset. I try to refactor the code to speed it up without `numba`, but not sure if that's feasible.

**Comment by schlunma** [comment]
Okay, good news: brought the time down to 57s (from 6 min) without `numba` :muscle: Will push the changes tomorrow! (BTW the old version was still running after 175min, so `numba` DID make a difference there :smile:)

**Comment by valeriupredoi** [comment]
you da man!! I was stinking there should be a way to rewrite the function - it's a blithering array only as input, but then I got distracted, well done @schlunma :beer:
