### ISSUE TITLE
CircleCI: don't use old image for test, rather re-create environment then test when deps are added/removed in a PR

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#875]
I nearly lost my ...ahem...posture when I kept getting a dependency error in https://github.com/ESMValGroup/ESMValTool/pull/1707 from CI: test - then I realized this is using a cached image - @bouweandela man, this is not something I like, can we change the CI so it dynamically builds the environment each time before testing when there is a change in the environment (ie a dependency is added or removed)? It's not much more than what it already does since the CI machine is slow like a slow train anyway, but stuff like env hiccups can be found this way - since nobody apart from you and me checks the GA tests :grin:

**Comment by valeriupredoi** [comment]
@bouweandela what you think about this - we can talk about it, if you wish :+1:

**Comment by bouweandela** [comment]
Sure, we can talk about it, but I'm a bit puzzled about the error message in that pull request, because I can see that `pip install .[test]` says it's already installed in [this build](https://app.circleci.com/pipelines/github/ESMValGroup/ESMValTool/3612/workflows/2b199711-f5f2-4ec3-b6c3-92a821640700/jobs/38926):
```
Requirement already satisfied: ruamel.yaml in /opt/conda/lib/python3.7/site-packages (from ESMValTool==2.1.0) (0.15.87)
```
but then when trying to run `esmvaltool install Julia` it crashes with the error message:
```
ERROR:esmvalcore._main:Program terminated abnormally, see stack trace below for more information
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/esmvalcore/_main.py", line 430, in run
    fire.Fire(ESMValTool())
  File "/opt/conda/lib/python3.7/site-packages/esmvalcore/_main.py", line 290, in __init__
    self.__setattr__(entry_point.name, entry_point.load()())
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ruamel.yaml' distribution was not found and is required by the application
```

**Comment by valeriupredoi** [comment]
it's very puzzling since I can't reproduce the problem locally. There is something to do with a chached installation that was installing `ruamel` from conda rather from PyPi, am pretty sure of that

**Comment by bouweandela** [comment]
I guess `ruamel.yaml` is already a dependency of one of our dependencies and therefore it is already installed from conda.
