### ISSUE TITLE
cftime>=1.3.0 completes years<1000 with zeros instead of spaces

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#876]
as the title says, now we have zeros, see below:

run this script:

```python
import cftime
from cf_units import Unit, date2num, num2date
d = cftime.DatetimeGregorian(40, 1, 16, 12, 0, 0, 0)
print([d.strftime('%Y%m%d%H%M')])
```

with `cftime<1.3.0` the result is `['  4001161200']` whereas with `cftime=1.3.0` the result is `['004001161200']`

As a consequence, we have two failed tests, see [here](https://github.com/ESMValGroup/ESMValCore/runs/1431151389?check_suite_focus=true)

I propose we either place a check on version in the test or we pin the package, either or - what do you think Javi and Bouwe?

**Comment by bouweandela** [comment]
Pin cftime to the most recent version and fix the tests

**Comment by valeriupredoi** [comment]
aye, just aboot to do that, capt'n :ship:
