### ISSUE TITLE
Failing tests on CircleCI

### ISSUE THREAD

**Issue by stefsmeets** [ESMValGroup/ESMValCore#893]
**Describe the bug**
Hi all,
There are a bunch of tests that keep failing on CircleCI with arbitrary reasons (segmentation fault or memory errors). Usually re-running the tests works. With this Issue I want to inventorize which tests keep failing to see if there is a pattern.

```
tests/integration/cmor/_fixes/cmip6/test_gfdl_cm4.py::test_cl_fix_metadata
tests/integration/cmor/_fixes/test_common.py::test_cl_hybrid_pressure_coord_fix_metadata_with_a
...
```

**Comment by valeriupredoi** [comment]
this is #644 - we have yet to understand the reason behind these failures, it looks to be system-related, by my investigations these happen at different rates depending on what platform the tests are run on, but as to the cause, it's still a mystery :ghost:

**Comment by stefsmeets** [comment]
I wonder where I had seen this before... I will close this 👍
