### ISSUE TITLE
Add extras to documentation: quick user giude, site-local info, known issues and future developments

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#90]
![Quick_User_Guide](https://user-images.githubusercontent.com/28983971/59515855-fc9fc800-8eb7-11e9-8f0b-7e9e41f3899c.png)
 
I am suggesting new sections to the documentation:
- quick user giude as pdf (so it's portable and easily detechabale from the main documentation page); I have started working on it (see attached png);
- information on local sites: data paths for Jasmin/DKRZ, available environments on sites, OBS data locations, how to apply for memberships for various group workspaces etc;
- a list of known issues that *are NOT* listed on gitHub (rather long-term issues or caveats);
- intended future developments;
- a link to the governance document (when we have it);

**Comment by mattiarighi** [comment]
Closing.
Please add this to the to-do list in https://github.com/ESMValGroup/ESMValTool/issues/1574.
