### ISSUE TITLE
Pull request template in .github is wonky

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#929]
the .md template is wonky - stuff like

```yaml
## Checklist

-   \[ \] PR has a descriptive
```

returns a graphical box that can not be checked with a :ballot_box_with_check:

**Comment by stefsmeets** [comment]
We went for that because Codacy complained about it. Agree that it should be reverted back and maybe a reminder to make the markdown checker less strict (Codacy in the ESMValTool repo does not complain).

- [ ] working box
- \[ \] wonky box
