### ISSUE TITLE
Multi-model statistics produces wrong/misleading results for daily data

### ISSUE THREAD

**Issue by Peter9192** [ESMValGroup/ESMValCore#937]
**Describe the bug**
The current implementation of the multimodel statistics preprocessor was not designed to work for daily data, but it doesn't raise an error either. This leads to misleading results, because prior to the statistics calculations, all time points are reset to the first of the month: https://github.com/ESMValGroup/ESMValCore/blob/4d52e4ac50483a98e946353a630427831da44f3a/esmvalcore/preprocessor/_multimodel.py#L216

This error has propagated into the [reference datasets](https://github.com/ESMValGroup/ESMValCore/blob/master/tests/sample_data/multimodel_statistics/) for the multimodel-statistics regression tests. While the sample data have 62 time points (days), the reference statistics cubes only have 2 (the first days of the 2 months).

This issue will be solved in #685, but until then, daily multimodel-statistics output should not be trusted.

**Comment by bouweandela** [comment]
@Peter9192 Can this issue be closed, now that #685 was merged?

**Comment by Peter9192** [comment]
Yes, thanks! I wanted to add automation but I forgot...
