### ISSUE TITLE
extract_region preprocessor no longer works on irregular grids

### ISSUE THREAD

**Issue by ledm** [ESMValGroup/ESMValCore#94]
Hi,

we recently changed the irregular grid section of the `extract_region` preprocessor in `preprocessor/_area.py` from this:

```
    # irregular grids
    lats = cube.coord('latitude').points
    lons = cube.coord('longitude').points
    mask = np.ma.array(cube.data).mask
    mask += np.ma.masked_where(lats < start_latitude, lats).mask
    mask += np.ma.masked_where(lats > end_latitude, lats).mask
    mask += np.ma.masked_where(lons > start_longitude, lons).mask
    mask += np.ma.masked_where(lons > end_longitude, lons).mask
    cube.data = np.ma.masked_where(mask, cube.data)
    return cube
```

to this:
```
    # irregular grids
    lats = cube.coord('latitude').points
    lons = cube.coord('longitude').points
    select_lats = start_latitude < lats < end_latitude
    select_lons = start_longitude < lons < end_longitude
    selection = select_lats & select_lons
    data = da.ma.masked_where(~selection, cube.core_data())
    return cube.copy(data)
```

The new code doesn't work for irregular grids. It produces the error message:
```
  File "/users/modellers/ledm/workspace/ESMValToolTest/ESMValTool/esmvalcore/preprocessor/_area.py", line 82, in extract_region
    select_lats = start_latitude < lats < end_latitude
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```
Any suggestions on how to fix it and keep it lazy? For now, I've reverted my local code back to the previous version. (but I'm not going to push it!)

The reason that we didn't catch the problem at the time is because the ocean recipes that use this were designed to demonstrate the diagnostics, not test the preprocessor. I'm changing recipe_ocean_example.yml to include an irregular grid CMIP5 model for future testing.

**Comment by bouweandela** [comment]
Hi Lee,

Maybe we can solve this issue together in the following way:
1) you create a new branch and draft pull request in which you implement a unit test that demonstrates that it is broken
2) I fix the function so it passes the unit test
Do you think that could work?

**Comment by ledm** [comment]
I should be okay to write most of a test - once I get the new split code installed! 

To write this test, I'll need to create an iris cube with an irregular grid - I've never had to do this before. Is there an example somewhere of how you create an irregular gridded cube in iris, @bouweandela 
 or @bjlittle?

**Comment by ledm** [comment]
I should be okay to write most of a test - once I get the new split code installed! 

To write this test, I'll need to create an iris cube with an irregular grid - I've never had to do this before. Is there an example somewhere of how you create an irregular gridded cube in iris, @bouweandela 
 or @bjlittle?

**Comment by bouweandela** [comment]
I think you can just load some CMIP variable that is on an irregular grid and see what the coordinates and data look like. I would recommend slicing the cube so you only a small part. You can then copy paste that into code and put in your own values.

**Comment by ledm** [comment]
The `area_statistics,` `volume_statistics`, `zonal_statistics` & `meridional_statistics` preprocessors all assume that the `fx_files` received as an argument is a dictionary containing: `{key: 'fx file path}`. This is how it worked in the `mask_landsea` function so I used that method.

We can't write a test that passes fx_files as a cube. The cube would need to be a saved fx_file somewhere in the repository and passed to the preprocessor function as a path. Is that possible @bouweandela?

**Comment by bouweandela** [comment]
Yes, just write the cube to a temporary file. For the path to the temporary file, I recommend using the pytest [`tmp_path`](https://docs.pytest.org/en/latest/tmpdir.html#the-tmp-path-fixture) fixture.

**Comment by bouweandela** [comment]
The irregular grid code should probably look something like:
```python
    # irregular grids
    lats = cube.coord('latitude').points
    lons = cube.coord('longitude').points
    select_lats = (start_latitude < lats) & (lats < end_latitude)
    select_lons = (start_longitude < lons) & (lons < end_longitude)
    selection = select_lats & select_lons
    selection = da.broadcast_to(selection, cube.shape)
    cube.data = da.ma.masked_where(~selection, cube.core_data())
    return cube
```
