### ISSUE TITLE
Ambiguous cache retrieval in regrid preprocessor

### ISSUE THREAD

**Issue by stefsmeets** [ESMValGroup/ESMValCore#953]
**Describe the bug**

In #907 I came across the following test failure:

```
self = <tests.unit.preprocessor._regrid.test_regrid.Test testMethod=test_regrid__cell_specification>

    def test_regrid__cell_specification(self):
        specs = ['1x1', '2x2', '3x3', '4x4', '5x5']
        scheme = 'linear'
        for spec in specs:
            result = regrid(self.src_cube, spec, scheme)
            self.assertEqual(result, self.regridded_cube)
>           self._check(spec, scheme, spec=True)

tests/unit/preprocessor/_regrid/test_regrid.py:107: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/unit/preprocessor/_regrid/test_regrid.py:23: in _check
    self.assertEqual(_CACHE[spec], self.tgt_grid)
E   AssertionError: <iris 'Cube' of unknown / (unknown) (latitude: 180; longitude: 360)> != <Mock spec='Cube' id='140424322565072'>
```

I could not reproduce the error on my machine, and it occasionally passed on CircleCI. I tracked it down to being related to the `_CACHE`:

https://github.com/ESMValGroup/ESMValCore/blob/de112e449c2aa8fb1d132816c8c5cd7a3186b821/esmvalcore/preprocessor/_regrid.py#L42

The cache stores the results of the regridding as a simpley key, `1x1`, `2x2`, etc. The problem is that the key assignment is ambiguous. This means after multiple calls, there _will_ be a name collision, so that the wrong cached value is retrieved. This may lead to data corruption, and in my case, random test failures. 

For #907, I believe that the outcome of the test depends on whether the regridder goes first (pass) or last (second). I happened to catch this, because I implement additional tests which also call the regridder at some point.

I have worked around the issue the issue by clearing `_CACHE` in #907 , but a less naive implementation of the cache is necessary.

**Comment by stefsmeets** [comment]
@bouweandela do you want to have a look at this?

**Comment by valeriupredoi** [comment]
the keys that the `CACHE` dict elements get accessed by are the grid specs `1x1` etc, they are unique - I fail to see how the multiple runs affect the test results?

**Comment by stefsmeets** [comment]
> the keys that the `CACHE` dict elements get accessed by are the grid specs `1x1` etc, they are unique - I fail to see how the multiple runs affect the test results?

Ah, now I understand it better. Maybe it is a testing thing then. In the regrid tests, the CACHE gets filled with mocked cubes. Whereas in the code I'm developing I'm also calling the regridder with real cubes. Which are then also added to the CACHE.

 In regrid tests, the specs are directly compared here: 

https://github.com/ESMValGroup/ESMValCore/blob/de112e449c2aa8fb1d132816c8c5cd7a3186b821/tests/unit/preprocessor/_regrid/test_regrid.py#L23

So it fails if it finds a real cube instead of a mocked cube.

**Comment by stefsmeets** [comment]
I have added another clear after the test in #907 just to be sure that the cache will not linger around with mocked cubes. I think that resolves the issue.
