### ISSUE TITLE
Add a coverage reporting service to increase test coverage

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#961]
To make us all more aware of how well we are testing new code, it would be good to add a coverage reporting service that comments on a pull request and shows how well we are doing. An example of such a service is https://about.codecov.io/product/features/

**Comment by valeriupredoi** [comment]
good idea! I'll self assign meself to this :+1: We need to make this easy to understand since we'd want to be used not only by geeks like us but rather any of our developers
