### ISSUE TITLE
Unclear default preprocessor order for time related preprocessor functions

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValCore#971]
It looks like there has been a mistake when fixing a merge conflict in #696 and now the default order in which the preprocessor functions are applied is no longer clear because several preprocessor functions are mentioned twice in the list that defines the order:
https://github.com/ESMValGroup/ESMValCore/blob/1c9885bb9796c88f3a14e21ef4148968fe9475b4/esmvalcore/preprocessor/__init__.py#L90-L104

I think that all time related preprocessor functions would need to be moved after `cmor_check_data`, but can you please check @schlunma and @jvegasbsc?

**Comment by schlunma** [comment]
Yes, all non-default preprocessors that can be specified by the user in the recipe should be moved after `cmor_check_data` so that `custom_order: true` works with them (see #762). Thus, the order should be:

```py
    ...
    # Concatenate all cubes in one
    'concatenate',
    'cmor_check_metadata',
    # Extract years given by dataset keys (start_year and end_year)
    'clip_start_end_year',
    # Data reformatting/CMORization
    'fix_data',
    'cmor_check_data',
    # Time extraction (as defined in the preprocessor section)
    'extract_time',
    'extract_season',
    'extract_month',
    'resample_hours',
    'resample_time',
    # Level extraction
    'extract_levels',
    # Weighting
    'weighting_landsea_fraction',
    ...
```
