### ISSUE TITLE
Release v2.2.0 things to include after the Feb. 1st, 2021 freeze

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#982]
Things to include on a "heck yeah, we really need this" basis:

**General faff**
- should do (even if DKRZ is missing at the mo) https://github.com/ESMValGroup/ESMValCore/pull/841
- should do (nice user-friendly) https://github.com/ESMValGroup/ESMValCore/pull/848
~~- possibly https://github.com/ESMValGroup/ESMValCore/pull/865~~
- must do #947 (IPCC relevant)
- must do https://github.com/ESMValGroup/ESMValCore/pull/978
- must do https://github.com/ESMValGroup/ESMValCore/pull/979
- must do https://github.com/ESMValGroup/ESMValCore/pull/981
- possibly #984 if merged/wanted in this release by Javi
 - must do (release dox) https://github.com/ESMValGroup/ESMValCore/pull/985
- must do (bug!) https://github.com/ESMValGroup/ESMValCore/pull/986
- must do #987 - `fiona` needs some caressing 
- must do (re-add fiona to setup.py) https://github.com/ESMValGroup/ESMValCore/pull/990

**Dataset Fixes**

- https://github.com/ESMValGroup/ESMValCore/pull/904
- if Javi says "Si, segnor" https://github.com/ESMValGroup/ESMValCore/pull/911
-

**Comment by valeriupredoi** [comment]
@jvegasbsc I am torn if we would want to include more dataset fixes or not - some are ready, some are ready(ish) too - what do you think? I'd say do them in for the next release (apart from the ones that are really needed - like the IPCC one above)

**Comment by jvegasbsc** [comment]
Data fixes are quite safe: they should not be a problem as they are usually very focused. PRobably we are safe to add anything that does not include an `AllVars`

**Comment by valeriupredoi** [comment]
@jvegasbsc successfully released, this goes to bin :+1:
